### PR TITLE
Use npm 7.x package-lock.json

### PR DESCRIPTION
**Pull request by kjeremy**
Supposedly backwards compatible

### CODE REVIEW

**Comment by lnicola** [comment]
Hmm, didn't already try this a while ago?

**Comment by lnicola** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/6538

**Comment by kjeremy** [comment]
I do have a memory of some `npm` change where I had to update to a new major version but I didn't think it was the lock file version. Maybe? I did change the scripts to use `npm ci` to avoid changing the lockfile on install.

**Comment by lnicola** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/6538#issuecomment-726701175

How did I know that? 😕 I'm not even sure what Node has to do with the lockfile format, isn't that a nom thing?

**Comment by lnicola** [comment]
Well, what's the worst that could happen?

bors r+

**Pull request merged**
