### PR TITLE
Deduplicate method candidates

### PR DESCRIPTION
**Pull request by flodiebold**
With trait method completion + autoderef, we were getting a lot of duplicates, which was really annoying...

### CODE REVIEW

**Comment by CptFox** [comment]
Sorry this doesn't have much to do with anything, but do you know of a place I can learn about what this `<|>` thing does? I feel like I've seen it before, but can't find a source nor figure out what it does

**Comment by CptFox** [comment]
> Sorry this doesn't have much to do with anything, but do you know of a place I can learn about what this `<|>` thing does? I feel like I've seen it before, but can't find a source nor figure out what it does

Oh wait, I think I just realised because this is a text: is that simply an escape sequence for the cursor?

**Comment by matklad** [comment]
>is that simply an escape sequence for the cursor?

Yes, exactly!

**Comment by matklad** [comment]
Makes sense to do in general!

bors r+

**Pull request merged**
