### PR TITLE
add option to disable notify

### PR DESCRIPTION
**Pull request by matklad**
This should help if notify uses 100% of CPU. Put

```
{
    "rust-analyzer.useClientWatching": true,
}
```

into `.vscode/settings.json` (or appropriate config of your editor) to use editor's file watching capabilites instead of notify

### CODE REVIEW

**Comment by max-frai** [comment]
What functionality will we loose if disabling this feature?

**Comment by matklad** [comment]
You'll lose all file watching if the editor does not support watching part of the protocol. Additionally, files outside of the workspace won't be watched. And there might be a different set of bugs related to the differences between various watcher implementations.

**Pull request merged**
