### PR TITLE
Fix two more “a”/“an” typos (this time the other way)

### PR DESCRIPTION
**Pull request by steffahn**
Follow-up to #9987

you guys are still merging these fast :sweat_smile:

_this time I thought – for sure – that I’d get this commit into #9987 before it’s merged…_

### CODE REVIEW

**Comment by lnicola** [comment]
You can mark PRs as draftl 😛.

**Comment by steffahn** [comment]
Well, each PR by itself is not leaving the source in an unfinished / intermediate state, so I guess it’s not a draft.

**Comment by Veykril** [comment]
Feel free to merge this when you think you are done then 😄
bors d+

**Comment by steffahn** [comment]
I really am done for now, as far as I’m aware xD

**Pull request merged**
