### PR TITLE
internal: don't pull tracing via chalk

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by lnicola** [comment]
Don't we use that? https://github.com/rust-analyzer/rust-analyzer/pull/8963#discussion_r638090360

**Comment by flodiebold** [comment]
(We pull in tracing anyway though. IMO we should probably just switch to it.)

**Comment by matklad** [comment]
I believe this is the correct change: https://github.com/rust-analyzer/rust-analyzer/pull/8963#discussion_r651150554

and yeah, we shoud switch from `log` to tracing everywhere.

**Comment by flodiebold** [comment]
Yeah, I think we disable a few features on tracing-subscriber so this is still a small reduction in dependencies.

**Pull request merged**
