### PR TITLE
Make SemanticsScope non-generic

### PR DESCRIPTION
**Pull request by lnicola**
This slightly reduces the build times:

image

(compare to https://github.com/rust-analyzer/rust-analyzer/issues/1987#issuecomment-652202248)

### CODE REVIEW

**Comment by matklad** [comment]
Right, you are spot on @lnicola! I originally tried making Semantics non-generic, but didn't. I don't exactly remember why, it might be that either:

* there's some annoying `dyn` limitation
* I decided that `sema.db` being a concrete type would be useful

If it's the latter, we can have generic `Semantics` and concrete `SemanticsImpl`. I'll look into this if no one beats me to it.

**Comment by lnicola** [comment]
I'm not sure if `Semantics` can be non-generic, it's a bit of an annoying change.

**Comment by matklad** [comment]
>I'm not sure if Semantics can be non-generic,

The following setup should work without breaking the API:

```rust
pub struct Semantics<'db, DB>{
  db: &'db DB
  imp: SemanticsImpl<'a>
}

struct SemanticsImpl<'a> {
  db: &'db dyn HirDatabase
  s2d_cache: RefCell<SourceToDefCache>,
  cache: RefCell<FxHashMap<SyntaxNode, HirFileId>>,
}
```

**Comment by lnicola** [comment]
What about the change in this PR? Do you think it's not a good idea?

**Comment by matklad** [comment]
Argh, I assumed this is an issue and not a PR. Gotta go make some pu erh I guess...

**Comment by matklad** [comment]
bors r+

This totally makes sense, but we need to do the rest as well!

**Comment by lnicola** [comment]
One issue is that some places seem to require `SourceDatabase` instead of `HirDatabase`, so we might need to add more `Upcast` impls?

**Comment by matklad** [comment]
Adding upcasts should be fine!

**Comment by lnicola** [comment]
Ugh, after a while, `ra_hir_def` is back to 176s for me, so maybe this PR didn't do anything :confused:.

**Pull request merged**
