### PR TITLE
feat: improve CPU usage

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by bjorn3** [comment]
I think you mentioned the wrong issue in the last commit.

**Comment by matklad** [comment]
Seems to work!

It even has this fun effect that, after typing, the indexing restarts at the crate it was finished at -- that's because the coalescing code just rushes thorough already analyzed crates. 

I wonder if we can add "is this fresh?" query to salsa, so that we can actually implement this, instead of relying on timing? 

bors r+

cc @jonas-schievink

**Comment by matklad** [comment]
Oups, how could I, that was almost #9292!

bors r+

**Comment by matklad** [comment]
I've just realized that bors implements exactly the same concurrency control as we do -- pushes to a branch cancel pending runs, and my `git push --force-with-lease && gh pr comment --body 'bors r+'` is exactly `if cancelled { self.prime_caches_queue.request_op(); }` :rofl:

**Pull request merged**
