### PR TITLE
cargo update

### PR DESCRIPTION
**Pull request by CAD97**
Closes #3644 as well.

Would setting up [dependabot](https://dependabot.com/) make sense for this repository?

### CODE REVIEW

**Comment by kjeremy** [comment]
Wait what happened here? Most of these changes are also in #3616

**Comment by CAD97** [comment]
hmm did I do this on an outdated master...

**Comment by CAD97** [comment]
I hate that git tells you that you're up to date with upstream/master when you aren't because you haven't done a `fetch`.

**Comment by CAD97** [comment]
Now this should properly be against master.

**Comment by matklad** [comment]
> dependabot 

Probably not, I feel like I’ll spend more time on it than if I just bump deps myself occasionally.

bors r+

**Comment by kjeremy** [comment]
@CAD97 since `thin-dst` is deprecated should we move to `slide-dst`?

**Comment by CAD97** [comment]
> @CAD97 since thin-dst is deprecated should we move to slice-dst?

Eventually, definitely. It's still perfectly workable for what it does, though. I think the work to rejig rowan's current API to use slice-dst and erasable rather than thin-dst is probably more work than it's worth right now, though, especially with my work towards a newly rewritten version of rowan that actually takes full advantage of slice-dst and the rest of pointer-utils. (I'd still be happy to review/mentor if someone wanted to do it, though. I considered rewriting thin-dst to use slice-dst under the covers, but I don't know if it's worth it (and having two separate impls does have some value).)

**Pull request merged**
