### PR TITLE
vscode: updated rollup typescript so it typechecks the bundle

### PR DESCRIPTION
**Pull request by Veetaha**
See [this happy update](https://github.com/rollup/plugins/blob/master/packages/typescript/CHANGELOG.md#v300) from `@rollup/typescript-plugin` changelog)

I also added a utility script to view the latest dependencies versions (`dry-run` variant) and update them in batch. Beware, that it bumps versions even if the major version of them has changed (for updating only within one major version there is a cli option, but I didn't want add a whole bunch of scripts)
Some of the dependencies major versions are out of date:
```
~/my/projects/rust-analyzer/editors/code (feature/refactoring-vscode-ext) $ npm run bump-deps:dry-run

> rust-analyzer@0.1.0 bump-deps:dry-run /home/veetaha/my/projects/rust-analyzer/editors/code
> npm-check-updates

Checking /home/veetaha/my/projects/rust-analyzer/editors/code/package.json
[====================] 16/16 100%

 jsonc-parser                    ^2.1.0  →   ^2.2.0 
 @rollup/plugin-commonjs        ^11.0.1  →  ^11.0.2 
 @rollup/plugin-node-resolve     ^6.1.0  →   ^7.1.0 
 @types/node                  ^12.12.25  →  ^13.7.0 
 rollup                         ^1.30.1  →  ^1.31.0 
 tslint                         ^5.20.1  →   ^6.0.0 
 vsce                           ^1.71.0  →  ^1.72.0 
```

### CODE REVIEW

**Comment by matklad** [comment]
I feel like `npm-check-updates` does not worth +2k lines in package.json.lock :)

Other than that, looks good to me

**Comment by Veetaha** [comment]
Ooops, yeah, kinda 2K) If you don't want that script, I'll remove!

**Comment by matklad** [comment]
Yeah, let's remove it.

bors d+

**Comment by matklad** [comment]
yup, much less scary now :)

bors r+

**Comment by matklad** [comment]
Could you also make an intetnional type error in type script to verify that CI actually fails?

**Comment by Veetaha** [comment]
Ok, lets try!

**Comment by Veetaha** [comment]
Hmm, it bails out on the first type error

**Comment by matklad** [comment]
bors try

**Comment by Veetaha** [comment]
Whilst `npx tsc --noEmit` reports all errors thruout the project

**Comment by Veetaha** [comment]
Should I revert that commit or rebase and remove it?

**Comment by matklad** [comment]
I don't care a lot about git history, but, withing "not caring a lot", I much prefer the rebase approach.

**Comment by Veetaha** [comment]
Done, bos r+

**Pull request merged**
