### PR TITLE
Hide argument name hint regardless of case

### PR DESCRIPTION
**Pull request by jhpratt**

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
One small nit: could you try and use `make_ascii_lowercase` instead of its `to_` counterpart?
The recent trend is to avoid unnecessary allocations and this case sounds like a place worth to try: we run this `filter_map` for every parameter hint in the whole document open, which can be big.

**Comment by jhpratt** [comment]
For the parameter name at least, it's not currently taken as mutable. By using `make_ascii_lowercase`, it would affect every usage of the variable. I can do this if desired, but I presume it would cascade and may have unintended consequences.

**Comment by SomeoneToIgnore** [comment]
Yes, should have elaborated a bit more: don't bother with `parameter_name`, it's `&str` anyway, but the `repr` could be processed as

```
Some(mut repr) => {
    let param_name = param_name.to_ascii_lowercase();
    let argument_string = {
        repr.make_ascii_lowercase();
        repr.trim_start_matches('_')
    };
    argument_string.starts_with(&param_name) || argument_string.ends_with(&param_name)
}
```

or simiar way, but the point is that it's a `String` so no need to reallocate it more.

**Comment by jhpratt** [comment]
Ah, gotcha. Of course I was just playing around wondering why it wasn't working, and didn't even think to reorder the `make_ascii_lowercase` and `trim_start_matches`. I wasn't sure the extent you meant because you seemed to have wanted me to break other things :stuck_out_tongue: 

Regardless, I've just pushed up an updated commit without compile errors and including a trivial test case.

**Comment by SomeoneToIgnore** [comment]
> you seemed to have wanted me to break other things

That would be to unfair ot lure you into a small PR and ask for big breakings in other places, so no.
Thanks again!

bors r+

**Comment by jhpratt** [comment]
Admittedly I wouldn't have minded, just wanted to be clear on what you wanted haha

Thanks for the quick feedback and guidance!

**Pull request merged**
