### PR TITLE
Merge imports when auto importing

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**

### CODE REVIEW

**Comment by flodiebold** [comment]
Instead of joining the `ModPath`s to strings and them later splitting them again, why not construct the `Vec`s directly?

**Comment by SomeoneToIgnore** [comment]
I've considered that even for 20 imports with 10 segments that would be pretty cheap and done with a few linnes.
You way will need to add another method to `ModPath`, adjust the `Display` impl for that and require more tests.

But sure, I can do that either a bit later.

**Comment by flodiebold** [comment]
I'm not worried about performance, it just seems like a roundabout way to achieve this... I guess ideally `auto_import_text_edit` would take a `ModPath` directly :thinking: 

But we can also merge this for now.
bors d+

**Comment by SomeoneToIgnore** [comment]
> I guess ideally auto_import_text_edit would take a ModPath directly 🤔

That would be great indeed, the whole `target: &[SmolStr]` parameter there is odd IMO.

I just don't want to touch the `auto_import_text_edit` method yet, since I think the whole functionality needs to be refactored and moved away and that will be a separate big change.

But I'll try to compe up with something simple and, if fail, will merge this change, thanks!

**Comment by SomeoneToIgnore** [comment]
How about now?

I had to add `Ord` to `ModPath` to ensure the import order, add a bunch of `known` items and expose the `known` module (that exposure I don't like, I think the whole `ImportResolver` should be replaced with the `ImportsLocator`), but now 

> I guess ideally auto_import_text_edit would take a ModPath directly 🤔

is implemented.

**Comment by flodiebold** [comment]
I think it's fine temporarily, but maybe you could move the known names you added to a separate section so that we can easily remove them again later?

Also, btw, there's a `name` macro which makes writing known names a bit nicer (just `name![std]`).

**Comment by SomeoneToIgnore** [comment]
Done.

> can easily remove them again later

Just curious: what's the point of that and what criteria do you use to distinguish one from another?
Say, why `IntoIterator` is known and `Iterator` is not and should be removed later?

**Comment by SomeoneToIgnore** [comment]
> Also, btw, there's a name macro which makes writing known names a bit nicer (just name![std]).

That's even better, no `known` module exposure now, thanks.

**Comment by flodiebold** [comment]
> Say, why `IntoIterator` is known and `Iterator` is not and should be removed later?

`IntoIterator` is known because `for` loops get desugared to code involving it. I.e. rustc 'knows' about it in the same way. In other ways, the only criterion is whether we need it somewhere, but `IntoIterator` is likely to stay and `Iterator` is not.

**Comment by SomeoneToIgnore** [comment]
Thanks for the explanations and the very valuable code adjustment proposals.
I have nothing to add or remove here, should we merge it now?

**Comment by flodiebold** [comment]
Sure!

bors r+

**Pull request merged**
