### PR TITLE
Do not propose to auto import fully qualified method paths

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This PR solves an issue when an auto import was proposed for the paths like `ast::SourceFile::cast` (as in https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_assists/src/handlers/auto_import.rs#L46)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
This PR solves an issue when an auto import was proposed for the paths like `ast::SourceFile::cast` (as in https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_assists/src/handlers/auto_import.rs#L46)

Unfortunately, we still propose auto imports for the paths that end with the method that does not exist: `ast::SourceFile::nonexistent_nonsence`
Maybe there is a better approach that covers this case also?

**Comment by SomeoneToIgnore** [comment]
Now this PR in a bit of a weird state: after the last commit here, I don't really need the first two ones. 

Yet, I've left them more for the sake of a discussion: is it the right way to try to detect methods as I do that in the first two commits?
I want to use that for the "auto import trait for the method" functionality later, so those are still valuable IMO.
Also note that the resolution does not work properly for cases like
```
use foo::bar::baz

fn call_baz_method() {
  baz_method<|>(5) // this gets wrongly resolved to a struct
}
```

**Comment by matklad** [comment]
I guess the first two tests should be  changed from `whatever::Trait::consume` to just `consume`?

Also, this might be a case where a `mark` might be useful, to makes sure we don't propose auto-import for the right reason

**Comment by SomeoneToIgnore** [comment]
I think this PR needs a split into two, because it tries to solve 2 different issues and does not do it fully:
* do not propose auto imports for methods and fully qualified methods: currently the PR does not provide a fix for the former
* do not propose auto imports for fully qualified paths when the first segment is already in scope: currently the PR fixes that, but importing the first segment glitches sometimes

I'll close this PR and come up with 2 separate later, one for every issue.
But good that the https://github.com/rust-analyzer/rust-analyzer/pull/3061/files#diff-af32458a9c9edad8a17c19b48e2145e7R317 approach did not cause questions per se, I'll use it when fixing the first issue

**Pull request closed without merging**
