### PR TITLE
Add installation notes for Arch Linux users

### PR DESCRIPTION
**Pull request by murlakatamenka**
Note: 2 of the AUR packages mentioned are maintained by me and are updated rather promptly.

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

Thanks! And thanks for packaging in the first place :)

**Comment by lnicola** [comment]
Thanks for packaging it. It might be worth enabling `jemalloc`, see #3459 and #3531.

**Comment by murlakatamenka** [comment]
@lnicola shouldn't it be unnecessary? Currently binary is built with just `cargo build --release --locked` and thus uses default toolchain and system's allocator. I assume people use `stable/nightly-x86_64-unknown-linux-gnu` by default and use `musl` target just to compile a generic *nix binary that would fit everyone.

**Comment by lnicola** [comment]
> Currently binary is built with just cargo build --release --locked and thus uses default toolchain and system's allocator. I assume people use stable/nightly-x86_64-unknown-linux-gnu by default

Yes, but enabling `jemalloc` (nb. that's a package feature, not a toolchain) makes it marginally faster (8.7% in my test) and enables memory usage reporting via a custom LSP / Code command. I don't know if that's worth the effort and build time hit, though. We don't try to ship the fastest binary anyway -- that would imply adding `codegen-units = 1` and `lto = on`.

**Comment by murlakatamenka** [comment]
I meant that using `jemalloc` is more beneficial for `musl` target (with slower allocator) and questionable for default `unkown-linux-gnu` one that will be used for building on users' Arch machines (with faster `glibc` allocator). But now I learned that it may still make sense to use `jemalloc` for non-`musl` targets.

Thanks, I'll test the tradeoff of longer compile time / faster binary and see whether using this feature is worth it.

**Comment by matklad** [comment]
I personally run rust-analyzer compiled from source with system allocator
(that's on NixOS, so glibc)

**Pull request merged**
