### PR TITLE
Increace tracing-tree version from 0.1.3 to 0.1.4

### PR DESCRIPTION
**Pull request by vandenheuvel**

### CODE REVIEW

**Comment by lnicola** [comment]
Is there something wrong with 0.1.3? We were already using 0.1.4, and most of the time we don't bump the version numbers in `Cargo.toml` for patch updates.

**Comment by davidbarsky** [comment]
0.1.3 was pulling in Quanta, which caused rust-analyzer to fail to compile on 32-bit platforms. If 0.1.4 is already being resolved, shrugs.

**Comment by vandenheuvel** [comment]
@Inicola I'm trying to increase the chalk version to `0.19.0` (coming out tomorrow), e.g. chalk-solve uses tracing-tree `0.1.4`

**Pull request merged**
