### PR TITLE
couple clippy::complexity fixes

### PR DESCRIPTION
**Pull request by matthiaskrgr**
avoid redundant `.into()` calls to convert T into identical T (`let x: String = String::from("hello").into();`)
use `if let Some(x)` instead of `.is_some()` + `.unwrap()`
don't clone Copy types
remove redundant wrapped ?s:  `Some(Some(3)?)` can just be `Some(3)`
use `.map(|x| y)` instead of `and_then(|x| Some(y)` on `Option`s

### CODE REVIEW

**Review by matklad — COMMENTED** [review]
bors r+

redundant clones and intos should probably be lifted into the compiler proper from clippy. Do we have a tracking issue for those?

**Comment by lnicola** [comment]
changelog skip

**Comment by matthiaskrgr** [comment]
I could not find anything.

Note that we have two different lints, one for [redundant clones](https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone) and one for [clone on copy types](https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy).

The redundant_clone one works in most common cases but also has a couple of false positives here and there

About the [useless conversion lint](https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion) I have not seen any FPs myself but we have a report about a libc code FP.

**Comment by matklad** [comment]
Systems-engineering wise, I'd probably try to start the conversation about moving these lints (starting with redundant clone perhaps) into `rustc`, as allowed-by-default, if I had leadership capacity for that (i don't :P). In principle, they could be implemented without false positives I think, and they make the code strictly simpler. They also trigger a lot, so there seems to be a lot of value add in having them build-in.

**Pull request merged**
