### PR TITLE
Diagnose files that aren't in the module tree

### PR DESCRIPTION
**Pull request by jonas-schievink**
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6377

I'm not sure if this is the best way to do this. It will cause false positives for all `include!`d files (though I'm not sure how much IDE functionality we have for these).

### CODE REVIEW

**Comment by matklad** [comment]
Probably needs at least a smoke test and a conditional compilaton tests (`cfg(a) mod a; cfg(b) mod b;`). I think false positives are OK here, although the question of what `sema` should do with included files is interesting...

**Comment by lnicola** [comment]
changelog feature add diagnostic for files missing from the module tree:

**Comment by fruffy** [comment]
Hello,
is there a way to disable this diagnostic? I updated `rust-analyzer` recently and now I am getting false positives all over my projects. 
Can also can create a dedicated issue for this.

**Comment by jonas-schievink** [comment]
Please open an issue for any false positives you encounter. The manual documents how to disable diagnostics here: https://rust-analyzer.github.io/manual.html#diagnostics

**Comment by fruffy** [comment]
Thanks! Just found #8188 so no new issue is necessary.

**Pull request merged**
