### PR TITLE
Support LSP 3.15

### PR DESCRIPTION
**Pull request by kjeremy**
This merely upgrades our protocol support. It does not add any of the new features.

### CODE REVIEW

**Comment by matklad** [comment]
Hm, looks like this causes rust-analyze to die horrible early during
initalization

**Comment by kjeremy** [comment]
Ugh sorry. Back it out and I'll investigate.

**Comment by matklad** [comment]
That's totally OK! There were no resonable way to notice this, such things
just happen from time to time :)

**Comment by matklad** [comment]
I think I have a fix

**Comment by matklad** [comment]
https://github.com/gluon-lang/lsp-types/pull/122

**Pull request merged**
