### PR TITLE
Retry rust audit as well

### PR DESCRIPTION
**Pull request by matklad**
https://github.com/rust-analyzer/rust-analyzer/runs/511553989?check_suite_focus=true#step:3:6

bors r+
🤖

### CODE REVIEW

**Comment by matklad** [comment]
@Veetaha why `cargo install audit` works? Where do we get the cargo from? Is it just some potentially old version, preinstalled on ubuntu?

**Comment by bjorn3** [comment]
> Is it just some potentially old version, preinstalled on ubuntu?

Yes

**Comment by Veetaha** [comment]
I am not sure what suddenly happened. And I don't fully understand the question, why wouldn't `cargo audit install` work whatsoever?

**Comment by Veetaha** [comment]
Oh I see, we didn't install it on ci, did we?

**Pull request merged**
