### PR TITLE
Bump rustc_lexer, cfg-if to 1.0 and add new license to check

### PR DESCRIPTION
**Pull request by kjeremy**

### CODE REVIEW

**Comment by lnicola** [comment]
We only use `cfg_if` once, I wonder if it's worth having it (other crates bring in the older version).

**Comment by kjeremy** [comment]
I'm not sure. Since it's a bump to 1.0 I'm hoping that our other dependencies update quickly (PRs welcome!).

**Comment by kjeremy** [comment]
Interesting test failure on bors:

> test tests::test_derive_proc_macro_list ... ok
> thread panicked while panicking. aborting.
> error: test failed, to rerun pass '-p proc_macro_srv --lib'
> 
> Caused by:
>   process didn't exit successfully: `/home/runner/work/rust-analyzer/rust-analyzer/target/debug/deps/proc_macro_srv-32fc1aa629146b4f` (signal: 4, SIGILL: illegal instruction)

I wonder if this is because rust 1.47 was just released.

**Pull request merged**
