### PR TITLE
Remove dead code in handle_rename

### PR DESCRIPTION
**Pull request by stanciuadrian**
On rename, VSCode sends a `textDocument/prepareRename` request. Then it displays the text box requesting the new name. 
It seems VSCode sends the subsequent `textDocument/rename` request only if the new name is not empty.

The proposed change removes the always-`false` condition and its body.

Checked it with the debugger, but I'm wondering if it can be triggered some other way.

_Edit: grammar_

### CODE REVIEW

**Comment by lnicola** [comment]
It's probably worth keeping this check, other LSP clients might not do such a careful validation as Code does.

**Comment by lnicola** [comment]
The spec seems to put the onus of validation upon the server:

```typescript
interface RenameParams extends TextDocumentPositionParams, WorkDoneProgressParams {
	/**
	 * The new name of the symbol. If the given name is not valid the
	 * request must return a [ResponseError](#ResponseError) with an
	 * appropriate message set.
	 */
	newName
}
```

**Comment by kjeremy** [comment]
From the spec:

> result: Range | { range: Range, placeholder: string } | { defaultBehavior: boolean } | null describing the range of the string to rename and optionally a placeholder text of the string content to be renamed. If { defaultBehavior: boolean } is returned (since 3.16) the rename position is valid and the client should use its default behavior to compute the rename range. If null is returned then it is deemed that a ‘textDocument/rename’ request is not valid at the given position.
error: code and message set in case the element can’t be renamed. Clients should show the information in their user interface.

**Comment by lnicola** [comment]
@kjeremy that's on the `prepareRename` side, while the validation removed in the PR checks for an empty new name.

**Comment by kjeremy** [comment]
Ah right! I think I put that check into `handle_rename` because that was before we handled prepare (which a lot of clients still do not support).

**Comment by lnicola** [comment]
It can only be handled in rename, prepareRename doesn't know the new name, so it can't validate it.

**Comment by matklad** [comment]
Yeah, I think a useful design guideline is that a request cannot assume anything except what is specified in the request itself, so I am inclined to close.

**Comment by stanciuadrian** [comment]
You're right, I only looked at VSCode as client and the spec is clear.
I wonder if a comment would be useful there. For the next lost soul wandering around.

**Comment by matklad** [comment]
Yeah, a comment would help!

**Comment by matklad** [comment]
Closing, but feel free to submit PR with comment clarification!

**Pull request closed without merging**
