### PR TITLE
fix: Limit depth to 1 when searching for `Cargo.toml`

### LINKED ISSUE #7268: [code] rust-analyzer failed to discover workspace
I just discovered that rust extensions seems activated accidently in my cpp project, it shows this:

image

### PR DESCRIPTION
**Pull request by lnicola**
...and add `rust-project.json`.

More or less fixes #7268

### CODE REVIEW

**Comment by matklad** [comment]
I'd say shold only one level deep, to match our auto-discovery logic: https://github.com/matklad/rust-analyzer/blob/15c4b3fa7f9d97029d64a7e13a12aa1ee42316d7/crates/project_model/src/lib.rs#L122

**Comment by lnicola** [comment]
That makes sense, updated. For some reason, `*/Cargo.toml` works for both `Cargo.toml` in the project root and in a subdirectory (but not two levels deep).

**Comment by matklad** [comment]
bors r+

Excellent find by the way!

**Comment by lnicola** [comment]
bors r=matklad

**Comment by lnicola** [comment]
@CalebEverett I suppose it depends. Can you use a Code workspace, or even open separate windows for the Rust and non-Rust parts of your project?

**Comment by CalebEverett** [comment]
> @CalebEverett I suppose it depends. Can you use a Code workspace, or even open separate windows for the Rust and non-Rust parts of your project?

Hi, thanks. Adding a Cargo.toml to the top level with just the workspaces key in with entries for the other crates worked.

```toml
workspace]
members = [
    "src/cli-rust",
    "src/program-rust",
]
```

**Comment by akutruff** [comment]
So I just hit this, and it's not an option to move Cargo.toml to the top of my directory structure.  Is there a setting?  I don't understand why this is so rigid.

**Comment by matklad** [comment]
`rust-analyzer.linkedProjects `(default: [])
Disable project auto-discovery in favor of explicitly specified set of projects.

Elements must be paths pointing to Cargo.toml, rust-project.json, or JSON objects in rust-project.json format.

**Pull request merged**
