### PR TITLE
Finish weird exprs

### LINKED ISSUE #290: ra_syntax: can't parse weird-exprs.rs correctly
rust-analyzer reports lots of syntax errors on [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7cf3546d8416fc76e5828481576fe6f9) (extracted [from the compiler](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/weird-exprs.rs) + added ktulhu).

### PR DESCRIPTION
**Pull request by DJMcNab**
Fix #290.

Note that I'm not certain my use of `p.nth(1) == Ident` is entirely consistent with `libsyntax` - in the original, [`is_union_item`](https://github.com/rust-lang/rust/blob/9622f9dc4745eb59fd229477f453ae83e8044db9/src/libsyntax/parse/parser.rs#L4593-L4596) uses `t.is_ident() && !t.is_reserved_ident()`, whereas we effectively only do `is_ident`. However, I cannot find the definition of `is_reserved_ident` (even searching the rust repository only gives uses, no definitions), so this will have to do unless someone else can find it :|.

### CODE REVIEW

**Comment by matklad** [comment]
>However, I cannot find the definition of is_reserved_ident

A good use-case for workspace symbols!

image

**Comment by DJMcNab** [comment]
Well indeed - I just didn't have Rust already cloned so was github searching

**Comment by matklad** [comment]
>: Do you want use to handle the keywords gracefully? Is there a good way to do it that?

I think that the current approach is good!

r=me with comment about the origin of the test file added

bors delegate+

**Pull request merged**
