### PR TITLE
Tweak message shown for query fallback

### PR DESCRIPTION
**Pull request by killercup**
Small tweak for #518

### CODE REVIEW

**Comment by killercup** [comment]
Originally noticed this because of:

bildschirmfoto 2019-01-13 um 13 27 27

It now only shows the second line of there are ~~methods~~ items to show.

- - -

I assume that `Arc` doesn't resolve in this snippet is a known bug:

```rust
use std::sync::{Arc, Mutex};

/// Structure holding your output targets
#[derive(Default, Clone)]
pub struct Output {
    inner: Arc<Mutex<InnerOutput>>,
}
```

but I can quickly open an issue if necessary

**Comment by DJMcNab** [comment]
bors r+

Thanks! That's definitely a better user experience.

**Comment by flodiebold** [comment]
Hm. About `Arc`, `std::sync` gets properly resolved, but it reexports `Arc` from `alloc_crate`, which is an extern crate rename: `extern crate alloc as alloc_crate`. I guess that's the problem.

**Comment by killercup** [comment]
Thanks for the quick merge! @flodiebold alright, I'll open an issue with a reproducible test case

**Pull request merged**
