### PR TITLE
Cargo Update run

### PR DESCRIPTION
**Pull request by kjeremy**
Bump relative-path to 0.4.0
Failure 0.1.3 to fix leak with downcast

Updated everything else too

### CODE REVIEW

**Comment by matklad** [comment]
Could you run `cargo outdated` (extern subcommand) as well?

bors r=+

**Comment by matklad** [comment]
argh, I am aweful with bors command today :( 

bors delegate+

**Comment by kjeremy** [comment]
Yep, I did that before submitting :)

**Pull request merged**
