### PR TITLE
feat: make sure nightly regressions don't break users

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
r? @lnicola 

Thinking more about it, looks like "just push to the release branch" is an OK patch release workflow for now, we don't necessary need to get fancier here. Makes more sense to concentrate on prevention of the problem.

**Comment by lnicola** [comment]
Writing the changelog after a patch release is really hard. I need to at least add a way to do it before Monday.

bors r+

**Comment by matklad** [comment]
@lnicola one possible wayt to do that would be to add `--prev-release commit-hash` arg to the xtask.

**Comment by lnicola** [comment]
Yeah, that was my plan (well, an env variable, but..)

**Pull request merged**
