### PR TITLE
Enable thread-local coverage marks

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by lnicola** [comment]
changelog internal enable thread-local coverage mark support

**Comment by JoshMcguigan** [comment]
I was going to suggest moving the `cov_mark::hit!` rather than deleting it, but that particular test is just demonstrating that we don't currently have the behavior we will eventually want, so I don't think there is any good place to put that mark.

LGTM!

bors r+

**Comment by matklad** [comment]
commit-message police: the commit message here doesn't fare to well on the "why, not what" scale :0)

**Comment by lnicola** [comment]
For the record: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/test.20marks.20flakey.3F/near/230346699

**Pull request merged**
