### PR TITLE
Support unnamed arguments in function pointers

### LINKED ISSUE #3089: Unnamed argument in type alias parsed incorrectly
The following type alias with an unnamed argument (`_`)
```rust
pub type test = unsafe extern "C" fn(_: *const gchar) -> ();
```
gives some errors when parsed by rust-analyzer (commit 29f5e7eebf606c1929d5a77ad66624cd4f3fcf49):
```
 test.rs     1  39 error           rust-analyzer: Syntax Error: expected type (lsp-ui)
 test.rs     1  39 error           rust-analyzer: Syntax Error: expected COMMA (lsp-ui)
 test.rs     1  40 error           rust-analyzer: Syntax Error: expected COMMA (lsp-ui)
```
When the variable is named or the unnamed variable is in a function declaration no syntax errors are generated:
```rust
pub type test = unsafe extern "C" fn(test: *const gchar) -> ();
unsafe extern "C" fn test(_: *const gchar) -> ();
```

### PR DESCRIPTION
**Pull request by hanmertens**
Fixes #3089

### CODE REVIEW

**Comment by kiljacken** [comment]
Would you mind adding a test to the comment just above your change?

**Comment by hanmertens** [comment]
I'm not entirely sure how the tests work but I assume this should do the trick.

**Comment by edwin0cheng** [comment]
CI falied, @hanmertens Would you mind to run `cargo xtask codegen` and commit the generated test case too. ?

**Comment by hanmertens** [comment]
I've run `cargo xtask codegen`, and `cargo test` in the `ra_syntax` crate, I hope that fixes it.

**Comment by edwin0cheng** [comment]
Thanks.
bors r+

**Pull request merged**
