### PR TITLE
Better handle illformed node id from metadata

### PR DESCRIPTION
**Pull request by edwin0cheng**
In some rare cases, deps node-id from cargo-metadata do not match its version-id, which cause a panic in `cargo-workspace.rs`. This PR try to ignore these ill-formed node id from `cargo-metadata`. An alternative is return  `Err` in these cases but I think make it resilience is a better choice here.

Related #2767

### CODE REVIEW

**Comment by matklad** [comment]
Hm, what would be the minimal reproducible example? It looks like it is a bug in cargo/cargo metadata, we probably should not paper over it, but rather fix the root cause

**Comment by matklad** [comment]
Aha, there's a repro in the issue: https://github.com/ChaseElectr/analyzer-panic

It's definitely true that `cargo metadata` output for that lockfile looks invalid. I have not compared lockfile and metadata yet.

**Comment by edwin0cheng** [comment]
Yeah that demo is artificial one, and I did checked that will show some warning in `cargo check` :
```
warning: dependency (diesel) specification is ambiguous. Only one of `branch`, `tag` or `rev` is allowed. This will be considered an error in future versions
warning: dependency (diesel_derives) specification is ambiguous. Only one of `branch`, `tag` or `rev` is allowed. This will be considered an error in future versions
```

From the thread of that issue, my wild guess it is related to [this cargo settings](https://github.com/rust-analyzer/rust-analyzer/issues/2767#issuecomment-573682954). But I tried to setup a similar case but can't reproduce it.

**Comment by matklad** [comment]
Opened upstream issue here: https://github.com/rust-lang/cargo/issues/7841

**Comment by matklad** [comment]
Ok, looks like more than one person suffers from this, so let's merge and revert once cargo bug is fixed :D 

bors r+

**Pull request merged**
