### PR TITLE
feat: add tab stops for keyword completions

### PR DESCRIPTION
**Pull request by eduardocanellas**
Add tab stops for all the keywords that I judged fit. I also introduced some line breaks and spaces, following the pattern I saw in the `postfix` module.

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

Let’s see how this works out in practice.


I am personally not a fan of multi-tabstop snippets — they are unpredictable to users for non-trivial cases. I think that always available tab-stops, a-la https://github.com/rust-analyzer/rust-analyzer/issues/7280, would be a better experience.


But we don’t have now, and we don’t know how this works out in practice, so it makes sense to try!

**Comment by matklad** [comment]
Hm, I am having second thoughts here. Turns out, VS Code forcefully disables completion for all the tab stops except the first one. They do this because there's a conflict between "`tab` moves to the next tabstop" and "`tab` accepts completion":

https://github.com/microsoft/vscode/issues/87607

https://user-images.githubusercontent.com/1711539/122680345-51891e00-d1f7-11eb-8460-c5a75938498e.mp4

The end result is quite suboptimal -- after expanding, eg, `match`, you don't get completion for the head expression. I wonder what we should do here, to get the best UX given editor's constraints... @eduardocanellas curious, which editor do you use? How it behaves with such snippets?

**Comment by eduardocanellas** [comment]
@matklad I use vs code too and I noticed this problem :/ I don't know about other editors, though.

Earlier you suggested #7280 as an alternative to this PR. Do you think it could face the same problem?

**Comment by matklad** [comment]
#7280 would probably have a diffferent set of problems: there’s no build-in tab navigation in vscode, we’ll have to hack it ourselves, and that obv will have (yet unknown) drawbacks.

**Pull request merged**
