### PR TITLE
Expose the range of the decl's name

### LINKED ISSUE #230: Local var renaming strips `mut` away
Before:

```rust
fn test() {
    let mut x = 42;
    let y = x;
}
```

After (rename x to foo):

```rust
fn test() {
    let foo = 42;
    let y = foo;
}
```

### PR DESCRIPTION
**Pull request by kjeremy**
Fixes #230

### CODE REVIEW

**Comment by kjeremy** [comment]
Hm. Do we have tests for LSP handlers?

**Comment by matklad** [comment]
No, but I think we should test it on the analysis layer, not on the LSP layer. That is, we can move the bulk of `handle_rename` into `ra_analysis`, and then write a test for it there.

**Comment by DJMcNab** [comment]
@kjeremy do you want someone to make this change, or are you willing to update it yourself?

**Comment by DJMcNab** [comment]
#375 supersedes this - I think we can close.

**Pull request closed without merging**
