### PR TITLE
Normalize line endings to Unix flavor on IO bounraries

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
cc @kjeremy: this risk breaking windows (but it shouldn't, we have a test for this), so if something weird happens, this PR might be to blame

**Comment by kjeremy** [comment]
> cc @kjeremy: this risk breaking windows (but it shouldn't, we have a test for this), so if something weird happens, this PR might be to blame

A quick smoke test of `cargo test` and some light editing in vscode passes on my machine.

**Pull request merged**
