### PR TITLE
vscode: fix bundling by switching to es2015 target modules system

### PR DESCRIPTION
**Pull request by Veetaha**
Quick fix

### CODE REVIEW

**Comment by matklad** [comment]
Actually I think this is more *correct* right? There's no need to use commonjs polifill, if we can use standard es2015 modules, right?

bors r+

**Comment by Veetaha** [comment]
Actually, yes, I'd say this is more correct, because bundlers are used to work with new es2015 modules syntax. Anyway, the commonjs version was supposed to "work" too...

**Comment by lnicola** [comment]
Is there a reason why we can't go for something even newer?

**Comment by Veetaha** [comment]
@lnicola es2015 is the newest module syntax, though may read a bit misleading

**Pull request merged**
