### PR TITLE
Add Note to loadOutDirsFromCheck Setting

### PR DESCRIPTION
**Pull request by zicklag**
Adds a note to the setting description saying that the setting may need
to be enabled for autocomplete for certain crates.

### CODE REVIEW

**Comment by lnicola** [comment]
I think the preferences are defined in `crates/rust-analyzer/src/config.rs` and you need to run.. `rust-analyzer --print-config-schema` and replace its output in `package.json`.

Renaming that preference would also be a good idea.

r? @edwin0cheng

**Comment by matklad** [comment]
The source of truth for this is here: https://github.com/rust-analyzer/rust-analyzer/blob/f301da3c3d1c73dd9d438cb0736e23430287dba7/crates/rust-analyzer/src/config.rs#L46-L48

**Comment by lnicola** [comment]
Also, there's no help for `--print-config-schema`.

**Comment by edwin0cheng** [comment]
I do not have preference for this pr, but I am working on #7328, and hope that will solve this problem permanently.

**Comment by zicklag** [comment]
OK, I tried that out, but now it's failing some tests. I'll come back to this later 'cause I don't have time to fix it now, but I was wondering whether or not it seemed right that a lot of settings in the settings schema were deleted when I did the `--print-config-schema` and did a diff on the JSON with the changes.

**Comment by matklad** [comment]
#7450 should automate package.json syncing

**Comment by matklad** [comment]
we updated the docs, and https://github.com/rust-analyzer/rust-analyzer/pull/7914 makes this enabled by default, so I feel we can close this

**Pull request closed without merging**
