### PR TITLE
Merge ra_vfs_glob and ra_lsp_server

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by lnicola** [comment]
Can `ra_cli` be a binary in `ra_lsp_server` instead?

**Comment by matklad** [comment]
we can, but having a single binary (to be renamed `rust-analyzer` by the next relesae) is a part of a motivation here. I *think* this will be useful for folks to minimize and reproduce bugs.

**Pull request merged**
