### PR TITLE
vscode: migrate to tripple equals

### PR DESCRIPTION
**Pull request by Veetaha**

### CODE REVIEW

**Comment by Veetaha** [comment]
Merging it will require time consumption, so nah...

**Comment by matklad** [comment]
I would rather do https://github.com/rust-analyzer/rust-analyzer/issues/3041 first

**Comment by Veetaha** [comment]
I'd like to postpone this for an indefinite amount of time... I know one of my coworkers tried to migrate some codebase to eslint and after 3 months of moving this task from sprint to sprint she actually gave up... Eslint doesn't currently support all rules that require type information and this was the main problem. This particular rule won't make any harm anyway...

**Comment by matklad** [comment]
Status: this needs to add eqeqeq [rulse](https://eslint.org/docs/rules/eqeqeq) to our .eslint config

**Comment by Veetaha** [comment]
@matklad thank you for messing with eslint ;)

**Pull request merged**
