### PR TITLE
rust-analyzer.files.excludeDirs

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors d=@jyn514 

Does this help with your use-case?

**Comment by jyn514** [comment]
@matklad I won't have a chance to test this out in the near future. Feel free to merge without me, or you can replicate the extra memory usage by doing a full build with docs.rs, there are instructions in the readme (search for `regex`).

**Comment by matklad** [comment]
bors r+

)

**Comment by jyn514** [comment]
Unfortunately this didn't seem to help. I added `.rustwide` and `.rustwide-docker` to `rust-analyzer.files.excludeDirs` and reloaded VSCode, but RA is still using over 2 GB (when most other people were only seeing about 1.3 GB used).

**Comment by jyn514** [comment]
If there's a way to see exactly what files are being loaded, that would be very helpful.

**Pull request merged**
