### PR TITLE
goto in macro calls

### PR DESCRIPTION
**Pull request by matklad**
goto

This builds on the awesome infrastructure created by @edwin0cheng

### CODE REVIEW

**Comment by Matelasse** [comment]
@matklad Is this also a stepping stone to https://github.com/rust-analyzer/rust-analyzer/issues/2158 ?

**Comment by cynecx** [comment]
Honestly, hitting on an emoji would be probably enough. But I just would like to express, how really **awesome** this is. Thank you guys for doing amazing work!

**Comment by kjeremy** [comment]
A similar issue exists with hover.

**Comment by matklad** [comment]
@Matelasse yeah, but completion would be harder: we will have to either translate ranges in the edit back, or switch to relative edits.

**Comment by matklad** [comment]
@kjeremy in general, every feature of rust-analyzer needs to be explicitelly adapted to macros. #2279 makes macro expansino machinery indempendet of go to def, which should be enough for hover. That is, hover code should be adapted to work with `Source<TextUnit>` instead of `FIlePosition`, ad then it shoudl call `descend_into_macros` to go from `FilePosition` to `Source<TextUnit>`.

**Pull request merged**
