### PR TITLE
Specify desirable namespace when calling resolve

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
The overall goal here is to remove various `unreachable!()` cases from the name resolution, by using maxiamlly specific types for the results of name resolution. 

@flodiebold what do you feel about this overall direction?

**Comment by flodiebold** [comment]
Yeah, that's basically what I thought we should do as well. I don't remember exactly why I didn't just do it, but I don't think it was any fundamental reason.

**Comment by matklad** [comment]
This is getting pretty big, so let's merge this. I feel like this is already an improvement. 

bors r+

**Pull request merged**
