### PR TITLE
Add a rudimentary json regex to get at information like `endLine`

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

Seems useful!

Is there a specific case where one is forced to use JSON?

**Comment by oli-obk** [comment]
> Is there a specific case where one is forced to use JSON?

I found the squiggly lines to be fairly confusing with the standard matchers. Especially around unused imports I kept getting the `std` of `use std::something::Else;` highlighted, which looked rather odd.

**Comment by matklad** [comment]
Just for the context, the long-term plan here is to move this from frontend (VS Code), to the language server proper (but still using an external command to get the errors). In this future setup, we should just parse JSON properly.

**Comment by oli-obk** [comment]
Yea I'm totally aware this is just papering over the issue. Great to hear there's a plan for it.

**Pull request merged**
