### PR TITLE
Revive cache cleaning


### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by Veetaha** [comment]
@matklad 

> The idea here is that, on CI, we only want to cache crates.io
dependencies, and not local crates. This keeps the size of the cache
low, and also improves performance, as network and moving files on
disk (on Windows) can be slow.

But the cache is downloaded from the network, isn't it? Btw, I have doubts that caching `CARGO_HOME` subdirs gives any ci performance wins, because these are the files downloaded by cargo and taking into account that cache is also restored from network there shouldn't be big difference in using it, since either way we use network?

**Comment by matklad** [comment]
>But the cache is downloaded from the network, isn't it? 

It's faster to download 100MB of cache than 200MB of cache. 

> I have doubts that caching CARGO_HOME subdirs gives any ci performance wins, because these are the files downloaded by cargo and taking into account that cache is also restored from network there shouldn't be big difference in using it, since either way we use network?

I think this is roughly correct, but I'd still expect caching to be a win even in this case:

* downloading one big thing should be faster than downloading many small things
* I expect cache is closer to workers than crates.io

But its worth experimenting here

**Pull request merged**
