### PR TITLE
Rebuild rust-analyzer when launching in VS Code

### PR DESCRIPTION
**Pull request by jonas-schievink**
This is usually the right thing, and previously would launch a stale r-a server.

### CODE REVIEW

**Comment by matklad** [comment]
Shouldn’t we run both tasks on build?

**Comment by jonas-schievink** [comment]
Probably, yeah. I'd have to make an extra task then, since you can only specify one in the launch configuration.

**Comment by jonas-schievink** [comment]
It seems that you can't make a launch configuration depend on a background task (it will wait indefinitely for the task to finish)

**Comment by jonas-schievink** [comment]
Okay this seems to work, but I have no clue about npm or TypeScript

**Comment by matklad** [comment]
bors r+

I *feel* like this can be in theory trimmed down a bit, as it seems like we shouldn't have that many different compbinations. but I also don't have any specific suggestions here, as I don't use tasks at all :)

**Comment by felix91gr** [comment]
I'm sorry to bother you guys, but what does this do exactly? Are you rebuilding r-a? 

But r-a is (more or less) a compiler. 
Wouldn't rebuilding it take way too long? Therefore, I'm assuming I got it wrong and it's something else that's being rebuilt.
Unless it's being rebuilt incrementally?

**Comment by flodiebold** [comment]
@felix91gr As far as I know, these are tasks for use while developing rust-analyzer in VSCode. And yeah, an incremental build of rust-analyzer doesn't take that long.

**Pull request merged**
