### PR TITLE
Don't assume DidChangeTextDocument paths exist

### LINKED ISSUE #5933: panic: called `Option::unwrap()` on a `None` value
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/rust-analyzer/src/main_loop.rs:449:31
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::panicking::panic
             at src/libcore/panicking.rs:56
  14: core::ops::function::FnOnce::call_once
  15: rust_analyzer::dispatch::NotificationDispatcher::on
  16: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
  17: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
  18: rust_analyzer::main_loop::main_loop
  19: rust_analyzer::main
  20: std::rt::lang_start::{{closure}}
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  23: std::panicking::try
             at src/libstd/panicking.rs:274
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: main
  27: __libc_start_main
  28: _start
```

Not sure exactly which version (probably last week's), but md5 was `b28aafc021827342f526d27972e475c1`. This was on the https://github.com/MaterializeInc/materialize/ codebase. It usually runs fine but crashed unexpectedly. Using http://github.com/mjibson/acre as the client.

### PR DESCRIPTION
**Pull request by mjibson**
Fixes #5933

### CODE REVIEW

**Comment by mjibson** [comment]
My (probably buggy?) [acme client](https://github.com/mjibson/acre) causes rust-anayzer to crash a few times per day on this. While clients should do a good job, it is currently trivial to panic rust-analyzer if you send it a ChangeText notification on some random path.

**Comment by SomeoneToIgnore** [comment]
Thank you!

bors r+

**Comment by kjeremy** [comment]
Is this correct behavior? Why doesn't he tpath exist? The client needs to gain ownership of the fire first by sending DidOpen which should have a valid URI.

**Comment by mjibson** [comment]
I agree the client should do that. I thought I programmed mine to always send an open first, but apparently it has a bug. However, it should never just panic rust-analyzer.

**Comment by matklad** [comment]
> However, it should never just panic rust-analyzer.

For some historical context, we used to deliberately panic in such cases (to force the us/clients fix all the bugs), but we've changed our stance on this. 

That said, I think we need to abstract this away into some kind of `log_protocol_violation` error, such that we can show an error message to the client or something like that. But that, to be done nicely, requires re-engineering of our event loop I think....

**Pull request merged**
