### PR TITLE
Use first match branch in case of type mismatch, not last

### LINKED ISSUE #4304: Autocompletion on Match arms has Inversed
Hello!

I believe autocompletion in Match statements has inverted. I'll explain:

image

Here, we have some Match with some Enum being returned on the first Arm. Rustc has therefore decided that each arm is of type `Repo`, and that therefore, my other arms are in a failure state, as they do not have such a return type. If this is true, and with no other code present, then RA should agree with `x` now being of the type `Repo`, but it's still typed as `()`. 

Now, if I do this...
image

The RA now says that X is of type `Repo`, when Rustc actually thinks this Match should return a  `()`!

I realize this is only an error case, and filling these arms up with `todo` or `unreachable` essentially makes them be in agreement, but going bottom up is a little counter intuitive. Personally, it interrupts how I program, since I frequently make match arms at the top, fill in one branch, and then live with the errors but with the type checking until I'm ready to go back.

Side note: this has nothing to do with the `_` match. the follow demonstrates that:

image

I also feel like this wasn't the case before the update this morning? But not positively sure.

Thanks for all the great work all!

### PR DESCRIPTION
**Pull request by flodiebold**
The comment says this was intentional, but I do agree with #4304 that it makes
more sense the other way around (for if/else as well).

Fixes #4304.

### CODE REVIEW

**Comment by kjeremy** [comment]
LGTM!

**Comment by flodiebold** [comment]
bors retry

**Comment by flodiebold** [comment]
bors retry

**Pull request merged**
