### PR TITLE
Extension debug

### PR DESCRIPTION
**Pull request by andrew-w-ross**
I was having trouble getting started with contributing to `rust-analyzer`.

This PR adds debugging for both the vscode extension and the rls server and instructions on how to get setup.

### CODE REVIEW

**Comment by matklad** [comment]
Awesome :heart_eyes: ! 

Could you use [this](https://github.com/rust-analyzer/rust-analyzer/issues/567#issuecomment-455513742) instead of adding the gif directly to the repository?

**Comment by andrew-w-ross** [comment]
@matklad There you go.

**Comment by andrew-w-ross** [comment]
@kjeremy Let me see if I can't get `CodeLLDB` working on windows. `Native Debug` hasn't seen an update since March 2018 so it might be abandonware.

**Comment by DJMcNab** [comment]
Just as note, adding that gif directly into the repository means it has to be downloaded on every clone, even though it should never been seen. Unfortunately, I'm not sure there's anything that can be done now, unless we rewrite history, which seems bad.

However, if we want to do so, now is our best chance whilst it is still fresh.

**Comment by matklad** [comment]
Ouch, of course you are correct, thank you so much for spotting this!

Will rewrite the history now!

**Comment by matklad** [comment]
Blast it! I've tagged this change for the guide as well TT

**Pull request merged**
