### PR TITLE
Make sure normal dependencies always have version

### PR DESCRIPTION
**Pull request by pksunkara**
How do I prevent this happening in the future by doing something in the CI? IIRC this is the second time.

### CODE REVIEW

**Comment by lnicola** [comment]
There's one more in `crates/rust-analyzer`, maybe we should update that too?

**Comment by pksunkara** [comment]
That is a dev dep though.

**Comment by matklad** [comment]
>How do I prevent this happening in the future by doing something in the CI? IIRC this is the second time.

It should be implemented here: https://github.com/rust-analyzer/rust-analyzer/blob/master/xtask/tests/tidy.rs

Just checking that every line with path also has version should work

**Pull request merged**
