### PR TITLE
Proper handle inner recursive macro rules cases

### LINKED ISSUE #7645: Could not resolve macro when macro is defined in recursive macro expansion
```rust
macro_rules! import_helper_macros {
    () => {
        import_helper_macros!($)
    };

    ($x:tt) => {
        #[allow(unused_macros)]
        macro_rules! blub { () => {  }; }
        
    };
}


fn main() {
    import_helper_macros!();
    blub!(); // <- error here
}
```

rust-analyzer shows `could not resolve macro 'blub'`, but rustc will compile just fine.
Error goes away if `import_helper_macros!($)` is used in the main.

### PR DESCRIPTION
**Pull request by edwin0cheng**
Fixes #7645

cc @jonas-schievink 

bors r+

### CODE REVIEW

**Comment by edwin0cheng** [comment]
bors cancel

**Comment by lnicola** [comment]
changelog fix

**Pull request merged**
