### PR TITLE
Use proptest as a dev-dependency in ra_text_edit

### LINKED ISSUE #1925: Some crates are built twice
This looks like mismatched features, but I'm not sure where:

```
$ cargo run --bin ra_cli --release -- analysis-stats .
  Downloaded once_cell v1.2.0
   Compiling once_cell v1.2.0
   Compiling ra_parser v0.1.0 (crates/ra_parser)
   Compiling ra_prof v0.1.0 (crates/ra_prof)
   Compiling ra_syntax v0.1.0 (crates/ra_syntax)
   Compiling ra_db v0.1.0 (crates/ra_db)
   Compiling ra_mbe v0.1.0 (crates/ra_mbe)
   Compiling ra_fmt v0.1.0 (crates/ra_fmt)
   Compiling ra_project_model v0.1.0 (crates/ra_project_model)
   Compiling ra_hir v0.1.0 (crates/ra_hir)
   Compiling ra_assists v0.1.0 (crates/ra_assists)
   Compiling ra_ide_api v0.1.0 (crates/ra_ide_api)
   Compiling ra_batch v0.1.0 (crates/ra_batch)
   Compiling ra_cli v0.1.0 (crates/ra_cli)
    Finished release [optimized + debuginfo] target(s) in 2m 51s
     Running `target/release/ra_cli analysis-stats .`

$ cargo install-ra                                                     
[snip]

will run: cargo install --path crates/ra_lsp_server --locked --force
  Installing ra_lsp_server v0.1.0 (crates/ra_lsp_server)
    Updating crates.io index
   Compiling matches v0.1.8
   Compiling percent-encoding v2.1.0
   Compiling num-traits v0.2.8
   Compiling rand v0.6.5
   Compiling unicode-normalization v0.1.8
   Compiling threadpool v1.7.1
   Compiling serde_repr v0.1.5
   Compiling lsp-server v0.2.0
   Compiling unicode-bidi v0.3.4
   Compiling proptest v0.9.4
   Compiling num-integer v0.1.41
   Compiling chrono v0.4.9
   Compiling idna v0.2.0
   Compiling flexi_logger v0.14.3
   Compiling url v2.1.0
   Compiling lsp-types v0.61.0
   Compiling ra_text_edit v0.1.0 (crates/ra_text_edit)
   Compiling ra_syntax v0.1.0 (crates/ra_syntax)
   Compiling ra_mbe v0.1.0 (crates/ra_mbe)
   Compiling ra_db v0.1.0 (crates/ra_db)
   Compiling ra_fmt v0.1.0 (crates/ra_fmt)
   Compiling ra_project_model v0.1.0 (crates/ra_project_model)
   Compiling ra_hir v0.1.0 (crates/ra_hir)
   Compiling ra_assists v0.1.0 (crates/ra_assists)
   Compiling ra_ide_api v0.1.0 (crates/ra_ide_api)
   Compiling ra_lsp_server v0.1.0 (crates/ra_lsp_server)
    Finished release [optimized + debuginfo] target(s) in 2m 50s
```

### PR DESCRIPTION
**Pull request by lnicola**
Maybe fixes #1925.

### CODE REVIEW

**Comment by matklad** [comment]
I am pretty sure that this'll break tests in other crates, but let's check

bors try

**Comment by lnicola** [comment]
I take it `cfg(test)` only applies to the current crate, and not to its dependencies?

**Comment by matklad** [comment]
>I take it cfg(test) only applies to the current crate, and not to its dependencies?

Yeah, `cargo test --lib` compiles the library with `--cfg=test`, while all the deps are compiled as usual.

**Comment by lnicola** [comment]
Can we move `ra_text_edit/src/test_utils.rs` to `ra_ide_api`? :cry:

**Comment by matklad** [comment]
No, because coherence. Really, we should just axe proptest :)

**Comment by lnicola** [comment]
The issue isn't only that `proptest` is slow to build, but it being used in `ra_text_edit` causes every following crate to be rebuilt.

**Pull request closed without merging**
