### PR TITLE
Build release binaries on Ubuntu 18.04

### LINKED ISSUE #11558: "Bootstrap Error" rust-analyzer requires glibc >= 2.28 in latest build.
rust-analyzer no longer will run on Ubuntu 18.04( which bundles [glibc 2.27](https://launchpad.net/ubuntu/+source/glibc/2.27-3ubuntu1)), and other distros which have a glibc older than 2.27.

this issue manifests as a "Bootstrap Error" notably, the extension output will log something along the lines of:

```
ERROR [2/28/2022, 8:46:56 AM]: Bootstrap error [Error: Failed to execute /home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer --version
```

when running the binary, we get the following error: 

```
/home/jake/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.3.953/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /home/jake/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.3.953/server/rust-analyzer)
/home/jake/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.3.953/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/jake/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.3.953/server/rust-analyzer)
```

current workarounds are mentioned in this comment: https://github.com/rust-analyzer/rust-analyzer/issues/11558#issuecomment-1054802255

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #11558

### CODE REVIEW

**Comment by lnicola** [comment]
I don't know whether we really want to merge this. On one hand we generally don't work around old software versions, on the other hand it's a small change and seems to affect a good number of people.

r? @rust-analyzer/review

**Comment by SomeoneToIgnore** [comment]
Maybe add a comment/issue with some LTS expiration date to revisit and bump it later?

**Comment by lnicola** [comment]
We'll have to bump at the latest when GitHub discontinues those builders, so probably no need for that.

**Comment by lnicola** [comment]
I'll merge this tonight if there's no disagreement.

**Comment by matklad** [comment]
>I don't know whether we really want to merge this. On one hand we generally don't work around old software versions, on the other hand it's a small change and seems to affect a good number of people.

My personal heuristic here would be:

* Do support old stuff on best-effort basis if that's not to hard
* But be very explicit about this being just "best effort"

That is, the only problem here is that in the future, someone might ask for a more onerous change. Responding to that becomes much easier if you have a "precedent" PR which articulates the policy.

**Comment by lnicola** [comment]
Exactly, a similar thing came up in https://github.com/rust-analyzer/rust-analyzer/pull/10457#issuecomment-1031201857.

**Comment by jonhoo** [comment]
Out of curiosity, will [the rust-lang org adoption](https://blog.rust-lang.org/2022/02/21/rust-analyzer-joins-rust-org.html) mean that rust-analyzer will be built and distributed entirely using the main Rust build infrastructure one day (maybe that's already what the nightly preview component does)? If so, that should help this a lot since we won't be at the mercy of when GitHub decides to drop support for old runners.

**Comment by matklad** [comment]
@jonhoo that's an open question at the moment! Using Rust distribution infra obviously brings a ton of benefits! But it comes with a sizable drawback -- a switch from 1 week release cycle to 6 weeks with additional 6 week lag.

**Comment by jonhoo** [comment]
All the more incentive for developers to use `beta` in the developer environments :p

**Comment by lnicola** [comment]
That still means losing the nightly versions of RA. We can't realistically upgrade merge the changes every day (it's a submodule update, not a "pull this repository, build it, then publish to the two marketplaces").

And our nightlies have been very useful in finding regressions.

**Comment by jonhoo** [comment]
True, though nothing precludes those builds from continuing to exist. The main Rust build would just provide a more stable release for those who are okay with not being on the bleeding edge if it gives them more dependable artifacts.

**Comment by lnicola** [comment]
> maybe that's already what the nightly preview component does

That component has the latest stable (weekly) RA release, with a lag of a couple of days or so. There was a release yesterday, and I just filed a PR to update the submodule (https://github.com/rust-lang/rust/pull/95424), which will probably get merged today or tomorrow.

We could update the submodule on Monday. I tend to wait a day just in case we find some critical regression, but that's probably not necessary.

So the `rustup` component basically "just" needs to be renamed and included in `stable` at some point.

**Pull request merged**
