### PR TITLE
Use todo!() as placeholder body for generated match arms

### PR DESCRIPTION
**Pull request by jDomantas**
`todo!()` seems to be a better fit for this than `{}`. Seeing that this assist predates stabilization of `todo` my guess is that simply no one bothered to change it yet.

Also fixed the issue where if the last arm was not block-like, rust-analyzer would not add a comma after it and would generate invalid code.

### CODE REVIEW

**Comment by matklad** [comment]
Using `{}` was intentional -- most of the time you want to just replace this code, and deleting `{}` is fewer keystrokes than deleting `{}`. No idea if that's good motivation though.

I guess, unless anyone objects, lets' merge this and see if people complain(/

**Comment by jDomantas** [comment]
My personal gripe with generating `{}` was that it usually gives you non-compiling code. My usual process is that I fill in the arm bodies one by one and I want to check if my code compiles when I finish an arm. To be able to do that I immediately replace `{}` with `todo!()` so that I would be able to have compiling code until I finish the whole match.

**Comment by matklad** [comment]
Sounds convincing!

bors d+

(seems like there are some test failures?)

**Comment by Veykril** [comment]
I'm a bit split on this, having a block ready to be used is quite helpful at times since you can just insert your statements into it without the need to remove anything at all and if you only use one statement rustfmt formats the block away for you. So I personally prefer having a block be generated here.

**Comment by Veykril** [comment]
Thinking about it a bit more I think the *produces compiling output* is still a better choice to go by after all so I agree 👍

**Comment by flodiebold** [comment]
I kind of want `todo!()` to be a "hole" that can just be easily overwritten...

**Comment by matklad** [comment]
I think that’s https://github.com/rust-analyzer/rust-analyzer/issues/7280

if the “next” position is todo, it should be selected to be easily overwritten

**Comment by pravic** [comment]
I wish this offered an option: to write empty match arms or to write todoed ones.

**Pull request merged**
