### PR TITLE
fix: `fill_match_arms` hangs on a tuple of large enums

### LINKED ISSUE #8835: Hang in match exhaustiveness
image

Get a bunch of "overly long loop: 10s" in this situation

### PR DESCRIPTION
**Pull request by iDawer**
+ Lazy computation of missing arms.
+ Convenience function to test lazy computation: `ide_assists::tests::check_assist_unresolved`.

Fixes #8835

### CODE REVIEW

**Comment by iDawer** [comment]
Do we need a benchmark for this?

**Comment by Veykril** [comment]
I don't think benching single assists is worth it? Unsure.

This PR still calculates all arms eagerly where as we should try to only check whether we find a single missing arm and then actually calculate all arms in the closure instead as outlined by matklad, https://github.com/rust-analyzer/rust-analyzer/issues/8835#issuecomment-841809519

**Comment by iDawer** [comment]
@Veykril I've seen your comment. I think it is worth to add a test with `cov_mark` asserting that it is lazy.

**Comment by Veykril** [comment]
Ye I misunderstood the comment, I wish there was a nicer way to write this but I cant think of one any right now. It would be nice to be able to make sure that it is lazy somehow.

**Comment by iDawer** [comment]
Hmm, I don't see a way to test with `AssistResolveStrategy::None`. Probably it needs a new `check_assist_unresolved(..)`.

> I don't think that's doable with cov_mark.

I just checked 
```rust
fn main() {
    let mut x = vec![1, 2, 3]
        .into_iter()
        .inspect(|item| println!("inspected {}", item));
    x.next();
    drop(x);
}
```
prints a single `inspected 1` so dropping not-runned-out iterator shouldn't be a problem for `cov_mark`

**Comment by matklad** [comment]
Looks good to me, thanks @iDawer !

bors r+

**Pull request merged**
