### PR TITLE
Don't reuse the Chalk solver

### PR DESCRIPTION
**Pull request by flodiebold**
This slows down analysis-stats a bit (~5% in my measurement), but improves
incremental checking a lot because we can reuse trait solve results.

### CODE REVIEW

**Comment by matklad** [comment]
Sigh, this makes #3188 much worse ;-(

**Comment by bkchr** [comment]
I think this solves the recent memory usage problems I had with rust-analyzer: https://github.com/rust-analyzer/rust-analyzer/issues/2945#issuecomment-590914458

Ty! :) 

(Just tested it a little bit by randomly browsing the Substrate source code, but it clearly looks way better than before.)

**Pull request merged**
