### PR TITLE
fix: Code: update the LSP server without asking

### PR DESCRIPTION
**Pull request by lnicola**
Most LSP extensions seem to do the same thing, and this is causing some
confusion for users who don't notice the update prompt before Code hides
it.

### CODE REVIEW

**Comment by matklad** [comment]
I guess that makes sense! The original thinking was that we don't want to call home without explicit opt-in (via nightly channel), but I guess, as we can not not download the binary, the user-experienced is pretty bad. The ideal solution would be for the VS Code marketplace to allow for distribution of binaries, but it doesn't look like it's comming.

Let's update the `Securty` section of the manual though, to mention that we now *do* http by default when downloading the server.

**Comment by matklad** [comment]
Alternative ideal solution -- ship rust-analyzer on stable rustup. Doesn't look any more comminger.

**Comment by lnicola** [comment]
But then you only get an update every six weeks :-).

> Let's update the Security section of the manual though

Yeah, we should probably move the `PRIVACY.md` stuff under there.

**Comment by matklad** [comment]
TIL we have privacy.md! Yeah, makes sense, although we probably should link security section from the readme then

**Review by matklad — COMMENTED** [review]
bors r+

Thanks!

**Comment by tronical** [comment]
> The ideal solution would be for the VS Code marketplace to allow for distribution of binaries, but it doesn't look like it's comming.

Technically this appears to be possible - I know of at least one extension that’s including rust binaries ;). Is there a policy that’s preventing this?

**Comment by lnicola** [comment]
We build binaries for 7 platforms (soon to be 8?), so we can't pack every one of them in the vsix. matklad meant platform-specific vsixes.

**Comment by vi** [comment]
Maybe it should ask, but contain "don't ask again" checkbox?

Users with expensive network connections may download xpi file separately, expect that that's a complete extension and be surprised that it then downloads a large file from internet without asking anything.

**Comment by lnicola** [comment]
There's a preference you can toggle to disable this (look at the change). I suggest disabling Code extension updates too, in order to avoid the situation you mentioned.

**Pull request merged**
