### PR TITLE
Add L_DOLLAR and R_DOLLAR

### PR DESCRIPTION
**Pull request by edwin0cheng**
As discussion in issue https://github.com/rust-analyzer/rust-analyzer/issues/1132 and PR #1125 , this PR add 2 `Syntax::Kind` : `L_DOLLAR` and `R_DOLLAR` for representing `Delimiter::None` in mbe and proc_marco. By design, It should not affect the final syntax tree, and will be discard in `TreeSink`.

My original idea is handling these 2 tokens case by case, but i found that they will appear in every place in the parser (imagine `tt` matcher). So this PR only handle it in `Parser::do_bump` and `Parser::start`, although It will not fix the `expr` matcher executing order problem in original idea.

### CODE REVIEW

**Comment by matklad** [comment]
>My original idea is handling these 2 tokens case by case, but i found that they will appear in every place in the parser (imagine tt matcher). So this PR only handle it in Parser::do_bump and Parser::start, although It will not fix the expr matcher executing order problem in original idea.

Heh, I haven't thought about tt and imagined that case-by-case approach works... yeah, that's nasty.

I guess it's important to add handling of `$sum * 92` problem in this PR, to check if this approach works  at all :D It seems doable: by default, we eat dollars transparently, but we should also add ability to check if we are inside dollars, to handle the expr case.

I guess, `eat_dollars` can set a flag on the parse if a dollar was just eaten. That we could have dedicated `has_ate_l_dollar()`, `has_ate_r_dollar()` methods on parser which we use from parse expr

**Comment by edwin0cheng** [comment]
I cherry-picked https://github.com/rust-analyzer/rust-analyzer/pull/1125 and merge into this PR for testing `expr` matcher, (and added `ty` and `pat` matchers).
The key charges to support `expr` priority order is  [expression.rs](https://github.com/rust-analyzer/rust-analyzer/pull/1138/files#diff-4b77066bc13387916309d7b95d003abaL209), we use a `dollar_lvl` to change the priority order (i.e. `bp`) conditionally. 

The current parser is very well written, i hope this change won't break the beauty of it. :)

**Comment by edwin0cheng** [comment]
And i change `convert_tt` function in `syntax_bridge.rs` such that it will handle `Delimiter::None` correctly, Previously it skips all empty delimiter node. And it should fix https://github.com/rust-analyzer/rust-analyzer/issues/1141, although i didn't test that case.

**Comment by matklad** [comment]
Excellent, thanks!

bors r+

**Pull request merged**
