### PR TITLE
internal: more reasonable grammar for blocks 

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by matklad** [comment]
bors r-

Wait, not yet ready to get this in

**Comment by matklad** [comment]
to be used with https://github.com/rust-analyzer/ungrammar/pull/40

**Comment by matklad** [comment]
bors r+

Let's land this! It's a big change, and one which I am pretty sure we should make. I don't think it'll break anything catastrophically, but there might be minor breakages. As this has potential to conflict with anything, seems better to :shipit: :)

**Comment by bjorn3** [comment]
Maybe wait until the next release to give it a bit more time?

**Pull request merged**
