### PR TITLE
Cleanup project.json deserialization

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by matklad** [comment]
cc @tweksteen, this is what I had in mind for https://github.com/rust-analyzer/rust-analyzer/issues/4816#issuecomment-641593177

**Comment by tweksteen** [comment]
Ack, thanks that looks good. Although, it would be nice to keep some unit test there, just to confirm we are still parsing the same  format (you've removed `test_crate_deserialization`).

**Comment by matklad** [comment]
We have integration test in heavy/main.rs

**Pull request merged**
