### PR TITLE
Add ra_ide_api::expand

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by flodiebold** [comment]
I guess this would help getting the right ranges in `ra_cli` when printing type mismatches? We currently have a large amount of type mismatches that seem to be happening in `format!` related macros, which are kind of hard to investigate because there's no useful range for them...

**Comment by matklad** [comment]
Indeed! Especially once this start to be more correct then it is right now (though the API I think is OK after this PR)

**Comment by matklad** [comment]
Also, format macros are the worst, because the format string is expanded eagerly: `format!(concat!())`;

**Comment by lnicola** [comment]
You can use this as a repro:

```rust
use std::fmt::{ArgumentV1, Arguments, Display};

fn main() {
    Arguments::new_v1(&["", "\n"], &[ArgumentV1::new(&"hello", Display::fmt)]);
}
```

```
Expressions of unknown type: 0 (0%)
Expressions of partially unknown type: 2 (14%)
Type mismatches: 4
```

Changing it to:

```rust
    let pieces = ["", "\n"];
    Arguments::new_v1(&pieces, &[ArgumentV1::new(&"hello", Display::fmt)]);
```

yields:

```
Expressions of unknown type: 0 (0%)
Expressions of partially unknown type: 0 (0%)
Type mismatches: 2
```

**Pull request merged**
