### PR TITLE
Allow pressing | to surround closure arguments in VSCode

### PR DESCRIPTION
**Pull request by Smittyvb**
This makes pressing <kbd>|</kbd> while some text is selected surround that text with pipes. This is useful when writing closures. 

In this demo, I press <kbd>|</kbd> to easily surround some text (`predicate`) with pipe characters to create a closure. Before, this would have replaced `predicate` with just `|`.

(I am getting failures when I do `cargo test` even on `master` locally (due to #8585 I think), but GH Actions is fine with this)

### CODE REVIEW

**Comment by matklad** [comment]
Hm, I guess I am OK with it, but this is papering over a gaping hole in our UX. I think we should:

* forcefully trigger completion when the cursor is in the position of an argument of a closure typer
* suggest `|param1, param2| $0` as a completion variant

**Comment by matklad** [comment]
Alternatively, we can show two completion variants for filter:

```
filter(...)
filter(|x| ...)
```

**Comment by flodiebold** [comment]
IMO completing `|x| $0` when you type `|` would be enough? Making `|` surround wouldn't actually help with that.

**Comment by lnicola** [comment]
changelog feat (first contribution) allow pressing `|` to surround closure arguments in VS Code

**Pull request merged**
