### PR TITLE
LSIF: consolidate references into a single edge where possible.

### PR DESCRIPTION
**Pull request by khuey**

### CODE REVIEW

**Comment by bjorn3** [comment]
You could iterate over the vec the same way it is done before this PR and use a `HashSet` for checking if an edge has already been emitted. This would avoid the need for sorting.

**Comment by khuey** [comment]
In that case it would probably be easiest to just remove the produced values from the HashMap as we go through the Vec the second time rather than maintain a separate HashSet.

**Comment by bjorn3** [comment]
I mean you can avoid the `HashMap` in the first place if you use the original `Vec` + a `HashSet` for deduplication. Something like this I think:

```rust
let mut visited_references = HashSet::new();
for x in token.references {
    if !visited_references.insert(x) {
        continue;
    }
    // ...
}
```

**Comment by khuey** [comment]
`x` is not what's duplicated though. `(x.range.file_id, x.is_definition)` is what is duplicated. And the vertices need to be consolidated into a single edge.

Here's what a diff of the output looks like
```diff
-{"id":1082,"type":"edge","label":"item","document":14,"property":"references","inVs":[17],"outV":1080}
-{"id":1083,"type":"edge","label":"item","document":14,"property":"references","inVs":[23],"outV":1080}
-{"id":1084,"type":"edge","label":"item","document":14,"property":"references","inVs":[34],"outV":1080}
-{"id":1085,"type":"edge","label":"item","document":14,"property":"references","inVs":[42],"outV":1080}
-{"id":1086,"type":"edge","label":"item","document":14,"property":"references","inVs":[50],"outV":1080}
-{"id":1087,"type":"edge","label":"item","document":14,"property":"references","inVs":[55],"outV":1080}
-{"id":1088,"type":"edge","label":"item","document":14,"property":"references","inVs":[66],"outV":1080}
-{"id":1089,"type":"edge","label":"item","document":14,"property":"references","inVs":[74],"outV":1080}
-{"id":1090,"type":"edge","label":"item","document":14,"property":"references","inVs":[82],"outV":1080}
-{"id":1091,"type":"edge","label":"item","document":14,"property":"references","inVs":[96],"outV":1080}
+{"id":1082,"type":"edge","label":"item","document":14,"property":"references","inVs":[17,23,34,42,50,55,66,74,82,96],"outV":1080}
```

**Comment by bjorn3** [comment]
I see.

**Comment by HKalbasi** [comment]
Given that `Item` isn't the only kind of edge that accepts multiple `inV`, maybe it make sense to have a general lsif optimizer pass?

**Comment by khuey** [comment]
It would be difficult to do this as an "optimization pass" because it would require renumbering all the emitted entries.

**Comment by khuey** [comment]
"contains" would benefit from this too but it is a bit harder to do because the edges are not all emitted at the same time. e.g.

```
$ cat test-subjects/rust/target/debug/lsif4.test | grep inVs | grep \"outV\":1373
{"id":1375,"type":"edge","label":"contains","inVs":[1374],"outV":1373}
{"id":2653,"type":"edge","label":"contains","inVs":[2652],"outV":1373}
{"id":2666,"type":"edge","label":"contains","inVs":[2665],"outV":1373}
{"id":2679,"type":"edge","label":"contains","inVs":[2678],"outV":1373}
{"id":2692,"type":"edge","label":"contains","inVs":[2691],"outV":1373}
{"id":2705,"type":"edge","label":"contains","inVs":[2704],"outV":1373}
{"id":2718,"type":"edge","label":"contains","inVs":[2717],"outV":1373}
{"id":2731,"type":"edge","label":"contains","inVs":[2730],"outV":1373}
{"id":2744,"type":"edge","label":"contains","inVs":[2743],"outV":1373}
{"id":2757,"type":"edge","label":"contains","inVs":[2756],"outV":1373}
{"id":2770,"type":"edge","label":"contains","inVs":[2769],"outV":1373}
{"id":2809,"type":"edge","label":"contains","inVs":[2808],"outV":1373}
{"id":2822,"type":"edge","label":"contains","inVs":[2821],"outV":1373}
{"id":2848,"type":"edge","label":"contains","inVs":[2847],"outV":1373}
```

**Comment by HKalbasi** [comment]
> It would be difficult to do this as an "optimization pass" because it would require renumbering all the emitted entries.

Yes, or equivalently, regenerate the whole data. A better abstraction than `self.add_edge` might also do the job (something that gets a `Fn(EdgeDataMultiIn) -> Edge` and `in_id` and `out_id` that internally have that hashmap). And maybe reusing other edges doesn't worth it since they are less common?

Btw, from your github account history, it seems that you are doing some interesting with `rr` and `lsif`. Would you mind to explain your usage of `lsif`?

**Comment by khuey** [comment]
> > It would be difficult to do this as an "optimization pass" because it would require renumbering all the emitted entries.
> 
> Yes, or equivalently, regenerate the whole data. A better abstraction than `self.add_edge` might also do the job (something that gets a `Fn(EdgeDataMultiIn) -> Edge` and `in_id` and `out_id` that internally have that hashmap). And maybe reusing other edges doesn't worth it since they are less common?

I think "contains" could be done by deferring the edge generation from `get_range_id` to something higher up that groups by document. A general optimization pass feels like overkill to me.

**Comment by khuey** [comment]
> > I think "contains" could be done by deferring the edge generation from get_range_id to something higher up that groups by document. A general optimization pass feels like overkill to me.
> 
> Storing the hashmap on `LsifManager` and generating actual edges at the end would also work, no? And in this way `Item` and `Contain` (and other `EdgeDataMultiIn`s) can share some bits of code.

It would, I don't think you could share much code though. `Item` needs to be consolidated on a different key than `Contains`, and there are no other `EdgeDataMultiIns`s. `Contains` actually has two different code paths and the normal one in `add_file` already does this sort of consolidation itself. It's only the fallback path in `get_range_id` (which appears to be used for e.g. libstd files that aren't part of the actual project but are referenced by it) that doesn't consolidate already.

**Comment by khuey** [comment]
The `Items` generated in the branch at 193 can never be consolidated because their outVs are always unique.

**Comment by HKalbasi** [comment]
hmm, correct. There are cases which have multiple definitions (or patterns), but we just use one of them. Other queries (type definition, implementation, ...) will have multiple results, but since they don't exist yet, and `contain` edges are different with them, I think it's fine to don't have a general structure for `EdgeDataMultiIn` and keep this PR as is.

**Comment by khuey** [comment]
Ok, great. Who can merge this PR? :)

**Comment by Veykril** [comment]
I can :)
bors r+

**Comment by khuey** [comment]
Thanks!

**Pull request merged**
