### PR TITLE
Add Lifetime to TyKind::Ref and DynTy

### PR DESCRIPTION
**Pull request by Veykril**
CC #8313

### CODE REVIEW

**Comment by flodiebold** [comment]
It might be nice to extract the static lifetime construction to a central `fn static_lifetime()`, so we can later easily review all the uses?

r=me otherwise

**Comment by Veykril** [comment]
bors r=flodiebold

**Comment by lnicola** [comment]
Another slight bump here:

image

**Comment by matklad** [comment]
I wonder if this can be automated...

**Comment by lnicola** [comment]
Of course it can, but then what do I do?

**Comment by matklad** [comment]
If you can automate the automation process, you are allowed to take a vacation.

**Comment by lnicola** [comment]
changelog internal

**Pull request merged**
