### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by lnicola**
Unfortunately, this brings a bunch of proc macros dep because `cargo-metadata` went full-in on `derive-builder`. I'm not sure what we can do here..

### CODE REVIEW

**Comment by lnicola** [comment]
Filed https://github.com/oli-obk/cargo_metadata/issues/154, just in case.

**Comment by matklad** [comment]
urgh, I think that maybe it's time to just implement our own cargo-metadata? Historically, I've spend quite some time chasing upstream....

**Comment by matklad** [comment]
Might be a good opportunity to investigate `nano-serde`

**Comment by lnicola** [comment]
For now, it looks like oli-obk might revert those changes. The builders themselves aren't really used in `cargo-metadata` yet.

**Comment by matklad** [comment]
let's hold off meta for a week?

**Comment by lnicola** [comment]
Sure. I split off the last commit.

**Pull request merged**
