### PR TITLE
show imported trait on autocompletion of associated items

### PR DESCRIPTION
**Pull request by mahdi-frms**
Fixes: #7456

The thing is however, due to the trait being already imported, the path to the trait is just the name of the trait itself.
I also updated the test concerning the labels.

### CODE REVIEW

**Comment by matklad** [comment]
How do before/after completions look like in VS Code?

**Comment by mahdi-frms** [comment]
this is before the import completion:
Screenshot from 2021-07-04 19-08-42

this is after the import:
Screenshot from 2021-07-04 19-09-03

**Comment by matklad** [comment]
Aha, this looks much better indeed. I have some concerns about the impl (I'd rather avoid `find_use_path`, as we *already* know if we auto-importing or not). As it took me some time to find it, here's the code that sets auto-import label:

https://github.com/matklad/rust-analyzer/blob/f9d84db0e0f8c571de0d4c8b82c3e717c2227129/crates/ide_completion/src/item.rs#L419-L434

**Comment by matklad** [comment]
Yeah, I guess, rather than calling `find_use_path`, let's do the following:

```rust
diff --git a/crates/ide_completion/src/item.rs b/crates/ide_completion/src/item.rs
index ae63d132e..1dfe2dd82 100644
--- a/crates/ide_completion/src/item.rs
+++ b/crates/ide_completion/src/item.rs
@@ -394,6 +394,7 @@ pub(crate) struct Builder {
     source_range: TextRange,
     completion_kind: CompletionKind,
     import_to_add: Option<ImportEdit>,
+    trait_name: Option<String>,
     label: String,
     insert_text: Option<String>,
     insert_text_format: InsertTextFormat,
@@ -430,6 +431,8 @@ impl Builder {
             } else {
                 format_to!(label, " ({})", original_path)
             }
+        } else if let Some(trait_name) = &self.trait_name {
+
         }
 
         let text_edit = match self.text_edit {
```

The problem with `find_use_path` is that it re-derives the "is this an auto-import" fact, but we already know this. Additionally, `find_use_path` is rather slow. 

While we are at it, another thing to add would be to change the text in parens to be `(use std::io::Read)` for auto-import, and `(as Read)` for just using method from a trait.

**Comment by mahdi-frms** [comment]
OK, I'll work on it. what you're saying is that we introduce a new trait_name property to the builder, and set it in the render functions, right?

**Comment by matklad** [comment]
>OK, I'll work on it. what you're saying is that we introduce a new trait_name property to the builder, and set it in the render functions, right?

Right! To be clear, I haven't looked closely at the code here, so there might be better ways to express this, but the overall control flow should look like this:

```rust
if importing {
    add_import_path_to_label()
} else if from_trait {
    add_trait_name_to_label()
}
```

:thinking: , I think I've just discovered a case where `find_use_path` would be outright buggy. If we use `_`-import for a trait, like `use serde::Serialize as _`, we want to see `(as Serialize)`, rather than a full path.

**Comment by matklad** [comment]
Moves in the right direction, but the tests are failing!

**Comment by mahdi-frms** [comment]
Oops! looks like there has been considerable change since I updated my fork.
The code does not even compile.

**Comment by matklad** [comment]
bors r+

thanks!

**Comment by matklad** [comment]
> While we are at it, another thing to add would be to change the text in parens to be (use std::io::Read) for auto-import, and (as Read) for just using method from a trait.

This would be great as a follow up PR! If you do this, consider including a smaller screenshot in the description, so that we can advertise this in the [next changelog](https://rust-analyzer.github.io/thisweek) with a picture!

**Comment by mahdi-frms** [comment]
I had actually added that, but looks like it had been lost during the rebase.
as I'm tired of that branch,I'll open another PR.

**Pull request merged**
