### PR TITLE
Plumbing for local items support

### PR DESCRIPTION
**Pull request by matklad**
bors r+

### CODE REVIEW

**Comment by ice1000** [comment]
🎉🤖🚀❤️💟😍

**Comment by ice1000** [comment]
What's the next step of supporting local imports?

**Comment by flodiebold** [comment]
How do you intend to handle something like
```rust
fn foo() {
    {
        fn bar() {}
    }
}
```
? Should the container just be the function here, even though it's actually a nested scope?

**Comment by matklad** [comment]
@ice1000 local imports will be supported last, as they are the most complex bit.

@flodiebold don't know yet! My current plan is to treat every item as if declared in the outermost block, which will cover 80% of use-cases I hope!

I think though we do want to anchor every item at the def, for identification purposes. That is, the name resolution scopes don't have to correspond 1-to-1 to how we store things internally.

**Pull request merged**
