### PR TITLE
ide: hack to make self not unresolved reference in async trait wrapped impl's

### LINKED ISSUE #10708: `self` is has unresolvedReference semantic token when using async-trait
Given this code:

```rust
#[async_trait::async_trait]
trait Foo {
    async fn foo(&self);
}

struct Bar {
    x: usize,
}

#[async_trait::async_trait]
impl Foo for Bar {
    async fn foo(&self) {
        let y = self.x;
        //      ^^^^ unresolvedReference
    }
}
```

`self` is marked as an `unresolvedReference`

However, type inference does appear to work, and we can see inlay hints display:

image

### PR DESCRIPTION
**Pull request by jhgg**
fixes #10708 

this is a bit hacky, but it "works". 

i'm not sure how to even write a test for this though, but i've confirmed it works via manual testing...

### CODE REVIEW

**Comment by Veykril** [comment]
Can we add a `FIXME` or `HACK` to the comment with a link to the issue this covers up? While fine as a temporary fix we should really look into why this actually fails at some point because the problem here will manifest itself for more things than just an incorrect highlight.

**Comment by jhgg** [comment]
> Can we add a `FIXME` or `HACK` to the comment with a link to the issue this covers up? While fine as a temporary fix we should really look into why this actually fails at some point because the problem here will manifest itself for more things than just an incorrect highlight.

Done! I would love to fix this the proper way but macro expansion is a bit beyond me at this point haha.

**Comment by Veykril** [comment]
> I would love to fix this the proper way but macro expansion is a bit beyond me at this point haha.

Understandably, especially token up/down-mapping can become rather confusing, took me quite a bit to grasp how it currently works in r-a.

The main problem with fixing this is to figure out whats wrong here, which can turn out to be quite annoying since that requires fiddling with r-a and the proc-macro outside of r-a's testing infra.

bors r+

**Comment by jhgg** [comment]
> Understandably, especially token up/down-mapping can become rather confusing, took me quite a bit to grasp how it currently works in r-a.

I'm eagerly awaiting matklad's explain RA video on this topic. Those vidoes so far have been really helpful in groking the project :D

**Pull request merged**
