### PR TITLE
minor: Bump npm deps

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by magjac** [comment]
My guess is that you also need to upgrade [@hpcc-js-wasm](https://github.com/hpcc-systems/hpcc-js-wasm) to version 1.12.8 which is what d3-graphviz 4.1.0 is built for and which supplies [`graphvizVersion()`](https://github.com/hpcc-systems/hpcc-js-wasm#graphvizVersion).

**Comment by lnicola** [comment]
That's already happening, as far as I can tell: https://github.com/rust-analyzer/rust-analyzer/pull/11821/files#diff-5327de443060217a48dced224bfca8b87dc60e5f9b3f8550c4782776295121f0R1061, https://github.com/rust-analyzer/rust-analyzer/pull/11821/files#diff-5327de443060217a48dced224bfca8b87dc60e5f9b3f8550c4782776295121f0R4147.

**Comment by magjac** [comment]
It's not part of that diff, but I see it's in https://github.com/lnicola/rust-analyzer/blame/npm-deps/editors/code/package-lock.json#L53.

Sorry, I can't say what's wrong. I see it's loaded at https://github.com/lnicola/rust-analyzer/blob/npm-deps/editors/code/src/commands.ts#L520. I would try to debug and see what it's actually loading.

Did you run `npm install` before build to get the latest version?

The function is tested in https://github.com/magjac/d3-graphviz/blob/master/test/graphvizVersion-test.js.

**Comment by magjac** [comment]
I *is* a bug in d3-graphviz after all. See https://github.com/magjac/d3-graphviz/issues/224#issuecomment-1082294206 for a workaround.

**Comment by magjac** [comment]
The issue with [d3-graphviz](https://github.com/magjac/d3-graphviz) is fixed in [version 4.1.1](https://github.com/magjac/d3-graphviz/blob/master/CHANGELOG.md#411) if you want to remove the workaround of not using a worker added in https://github.com/rust-analyzer/rust-analyzer/pull/11821/commits/a7e83418d5941b6fbe5bd9c2d390fb03b0428e95, which may have an impact on performance and/or responsiveness.

Sorry for the troubles.

**Comment by lnicola** [comment]
Thank you very much!

**Pull request merged**
