### PR TITLE
internal: prepare to move rename to base_db 

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by lnicola** [comment]
Something something readable commit messages :stuck_out_tongue:.

**Comment by matklad** [comment]
I actually find the commit message rather apropos. When doing refactors, I find it useful to explain the underlying philosophical *why*. Hence it's the general "pull the members up to allow for re-use" rather than "remove IdentifierKind::ToSelf". Although, the commit message misses specific context here -- that I want to put the generic impl into the base db, let me amend that...

**Comment by matklad** [comment]
Should be better now!

bors r+

**Comment by lnicola** [comment]
I don't personally mind it, but the lack of context does make putting together the changelog harder.

**Comment by matklad** [comment]
Yeah, that's hard... For a manually written changelog, I'd actually put all of my today's PRs under the single "internal: extract diagnostics to a separate crate" bullet, but:

* it's hard (and very time consuming) to figure that out during changelog authoring
* it's impossible to figure this out now, as it's unclear what the work ends up being! (naturally, this was the *first* item on my today's todo list, but it rapidly grew a bunch of side-quests, as, turns out, diagnostics need rename, and that is in ide, and uses TryToNav which is very wrong, and has special cases in the guts of supposedly to be correct logic)

**Pull request merged**
