### PR TITLE
Add Discord to the sponsors list

### PR DESCRIPTION
**Pull request by jhgg**
Hey! I figured it might be appropriate to do this, given Discord currently contributes 2,500 EUR/mo to this project! :)

### CODE REVIEW

**Comment by Veykril** [comment]
We are actually about to remove these due to the transition into the rust org 😅

https://github.com/rust-analyzer/rust-analyzer/pull/11641#issuecomment-1069568849:
> We actually should revome mentions of sponsors and branding from the repo, due to transition to rust-lang org. I'll do that when I have time (should have some by the time ! hits stable)

**Comment by jhgg** [comment]
Ah well.

**Comment by Veykril** [comment]
I mean we could probably add it until we moved the repo? I am not sure when that will be happening tbh.

**Comment by jhgg** [comment]
No worries - it doesn't really matter!

**Pull request closed without merging**
