### PR TITLE
Add References CodeLens.

### LINKED ISSUE #5836: Add CodeLens for references
Currently, the only CodeLenses that rust-analyzer shows are `Run` above `fn main()`, `Run Test | Debug` above tests, and `n implementations` above struct, enum, union and trait definitions. A useful addition to this would be a CodeLens of the form `n references` above definitions where this makes sense. When clicked, this CodeLens would show all the references to the symbol the definition defines.

Here’s a list of some possible definitions above which the references CodeLens could be shown:

- structs
- enums
- unions
- traits
- free functions
- functions in impl blocks
- functions in trait definitions

It _might_ be a good idea to show the CodeLens above enum variant definitions as well as struct and union field definitions, but that might be a bit much.

### PR DESCRIPTION
**Pull request by vsrs**
Closes #5836

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

Welcome back, @vsrs!

**Comment by vsrs** [comment]
Thanks :)

**Comment by lnicola** [comment]
references

**Comment by lnicola** [comment]
references

**Comment by ericsampson** [comment]
@vsrs , I was trying to follow up on this by adding a reference CodeLens for enum variants.
I made the naive change to add a `hir::ModuleDef::Variant` match arm 
[here](https://github.com/rust-analyzer/rust-analyzer/blob/93f3c173e15917051cbb57f4057014f8defa76a7/crates/ide/src/annotations.rs#L67), and it compiled fine but didn't make the variant lens annotations show up.

Is that because [visit_file_defs](https://github.com/rust-analyzer/rust-analyzer/blob/009e6ceb1ddcd27a9ced3bcb7d0ef823379185a1/crates/ide_db/src/helpers.rs#L97) isn't returning nodes for enum variants?

Or am I just totally out to lunch lol.

I'd appreciate any pointers :) Thanks!!

**Comment by Veykril** [comment]
I'm pretty sure declarations of a module don't contain variants, so `visit_file_defs` won't iterate over those as well. So you want to match on the ADT, checking if its an enum, fetch its variants and work with that.

**Comment by ericsampson** [comment]
@Veykril thanks a ton, that actually helped get me pointed in the right direction!!
Now I just need to figure out how to write a test for this...

**Comment by Veykril** [comment]
We don't really test protocol boundary parts that much, as seen in this PR there aren't any tests for this either so I'd say its fine to go without them here.

**Pull request merged**
