### PR TITLE
Rename extension config

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by lnicola** [comment]
Finally 😆.

**Comment by edwin0cheng** [comment]
@lnicola Should we post this change in "Anouncements: Client Changes" too ?

**Comment by matklad** [comment]
@edwin0cheng not really -- this is vscode-specific, and we maintain that. That issue is primaraly for maintainers of other clients.

**Comment by Jesse-Bakker** [comment]
There are still references to the old setting in docs/{dev/README.md,user/manual.adoc}

**Pull request merged**
