### PR TITLE
Forbid TODO markers on master branch

### PR DESCRIPTION
**Pull request by matklad**
this makes TODO markers useful for things which you want to fix before sending a PR

### CODE REVIEW

**Comment by flodiebold** [comment]
I tend to use TODO and FIXME exactly the other way around ;)

**Comment by matklad** [comment]
yeah, me to, but rust-lang/rust prefers FIXME, and it makes sense to be consistent with it?

**Comment by mjkillough** [comment]
The merge of #982 will have introduced another `TODO` which will need to be updated to `FIXME` here. :slightly_smiling_face:

**Comment by matklad** [comment]
I don't plant to merge this until #988  is r+ed :)

**Comment by matklad** [comment]
A bit of git archeology revealed this: https://github.com/rust-lang/rust/commit/fe77e962a826ac41354a7b1b4afa08c527e86e8c

Basically, there once was a policy in rust-lang to require issue numbers on FIXME comments, and to do was forbidden as a work-around for that. 

I guess it's a good idea to create issues for FIXMEs on a best-effort bases!

**Pull request merged**
