### PR TITLE
feat: Support `#![recursion_limit]` attribute

### LINKED ISSUE #8640: Configure recursion limit for macro expansion
As a follow up to https://users.rust-lang.org/t/rust-analyzer-increase-recursion-limit/55057/3, it would be very useful if the recursion limit for macro expansion could be configured/changed. Normally in rust files you can add a `#![recursion_limit = "1024"]` to the file but rust-analyzer does not respect this.

I believe the recursion limit was set to a const value in https://github.com/rust-analyzer/rust-analyzer/pull/5320.

I am unsure how one would go about this.

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Peek 2022-01-28 02-33

Resolves #8640

@matklad thanks, for the instructions, they were very helpful :)

### CODE REVIEW

**Comment by lnicola** [comment]
:heart_eyes: does this fix https://github.com/rust-analyzer/rust-analyzer/issues/4243#issuecomment-1013306835 too?

**Comment by lnicola** [comment]
I think you need to rebase upon `master` to fix the formatting error.

**Comment by WaffleLapkin** [comment]
@lnicola `async-std` is still broken, it seems. Not sure what exactly happens to that cursed macro, but yeah, `next` is still unresolved by RA.

**Comment by lnicola** [comment]
// 5 <-- increment this if you've looked at `async_std::extension_trait!` without figuring out why it fails

**Comment by lnicola** [comment]
It actually starts working for me if I increase the limit:

image

But it's sooooooooo slow :cry:.

I didn't test your PR yet.

**Comment by lnicola** [comment]
Yeah, your PR fixes #4243 for me, at least in the `tcp-echo` example.

**Review by lnicola — APPROVED** [review]

**Comment by WaffleLapkin** [comment]
@lnicola wait 🤔 

If RA ignores the limit (without this PR anyway) how can increasing it help? And since `cargo check` works I'd assume that the limit is already high enough...

> Yeah, your PR fixes #4243 for me, at least in the tcp-echo example.

The weird part is that it doesn't for me, lol. I wander what's up with that 🤔

**Comment by lnicola** [comment]
RA used to bail out after 128 expansions, now your PR makes it run to the end.

**Pull request merged**
