### PR TITLE
Update crates

### PR DESCRIPTION
**Pull request by kjeremy**

### CODE REVIEW

**Comment by lnicola** [comment]
CI fails because the `Url` `Debug` implementation has changed and tests need to be updated.

**Comment by kjeremy** [comment]
I really dislike how some tests don't run on windows

**Comment by lnicola** [comment]
I think they run, but you need to set an environment variable.

**Comment by matklad** [comment]
No, those tests are genuinely skipped on windows. 

However, I do dislike that bunch of tests,I wish we'd refactor `cargo check` diagnostic handling to be more obviously correct and smaller.

I wonder, can we change those tests to convert to LSP diagnostics (so that expect data is JSON)? That way, they'll be more robust...

bors r+

**Pull request merged**
