### PR TITLE
Vscode: add comment on possible UnhandledPromise rejection error

### PR DESCRIPTION
**Pull request by Veetaha**

### CODE REVIEW

**Comment by lnicola** [comment]
On phone, but if that function returns a promise and nested promises get flattened as you showed me, I'm not sure whether this has any effect. But I don't know the specifics of error propagation in JS promises.

It might be clearer to be more explicit about handling errors (with `.catch`?).

**Comment by Veetaha** [comment]
@lnicola unwrapping of `Promises` doesn't affect error propagation. If the inner `Promise` is rejected, the unwrapped one will be rejected with the same value. Yes it might be reasonable to put `.catch(unreachable)` here.

But what I also learned today is that vscode doesn't await `Promise`s from event handlers too. So everywhere we subscribe with `onDid<HappenSomething>(handler, thisArg, disposables)` the handler is not awaited and if it returns a rejected Promise you get this printed to dev console:

image

Now I see that according to this PR logic we would need to put `.catch(unreachable)` in each event handler, but that would be too verbose. I think the default behavior of printing unhandled promise rejections to the console is acceptable, so I am inclined to close this PR as it would bring unnecessary complexity where it is not required...

**Comment by lnicola** [comment]
I tend to agree. My point was that I don't think this PR has any effect, even if that method does throw.

**Comment by Veetaha** [comment]
Sure, I got your point

**Pull request closed without merging**
