### PR TITLE
Resolve prelude and crate root names in the root DefMap

### PR DESCRIPTION
**Pull request by jonas-schievink**
Should fix https://github.com/rust-analyzer/rust-analyzer/issues/8418

bors r+

### CODE REVIEW

**Comment by lnicola** [comment]
image

These still don't get resolved though.

**Comment by jonas-schievink** [comment]
Pretty sure that's a different issue, we're still having trouble with local impls at the IDE layer, even though the HIR layer knows how to handle them in `const _`s

**Comment by lnicola** [comment]
changelog fix

**Pull request merged**
