### PR TITLE
Clone for update

### PR DESCRIPTION
**Pull request by matklad**
rowan counterpart https://github.com/rust-analyzer/rowan/pull/93

#6857

### CODE REVIEW

**Comment by matklad** [comment]
I think this is at the stage where we can decide if we want to go with this approach or not. 

The best evaluation of positive impact is this file:

https://github.com/rust-analyzer/rust-analyzer/pull/7498/files#diff-09dc617f489e73535f15e893ffaba3d5feafdc00689a795d607b3fad6b36f73a

Here, I was able to re-write a string-based refactor to just mutate the tree in-place, using some generic infra for tree manipulation. For example, things like `func.get_or_create_where_clause()` become meaningful.

The  primary drawback is that it's not zero-cost for the case where you *do not* mutate syntax trees:



```
# baseline
Database loaded:     362.41ms, 276minstr, 79mb
  crates: 36, mods: 611, decls: 11849, fns: 9300
Item Collection:     5.88s, 61ginstr, 392mb
  exprs: 255464, ??ty: 2455 (0%), ?ty: 2529 (0%), !ty: 1322
Inference:           14.25s, 124ginstr, 677mb
Total:               20.12s, 185ginstr, 1070mb

# clone for update
Database loaded:     348.46ms, 275minstr, 79mb
  crates: 36, mods: 611, decls: 11849, fns: 9300
Item Collection:     6.33s, 68ginstr, -1223mb
  exprs: 255464, ??ty: 2455 (0%), ?ty: 2529 (0%), !ty: 1322
Inference:           14.43s, 128ginstr, 2409mb
Total:               20.77s, 197ginstr, 1185mb
```

The primary costs here are:

* we now do an allocation for syntax tokens during traversal
* syntax node objects are bigger (though I think we can combat this with cursed hackery)
* there a bit more extra branches during traversal

Another big drawback is that the rowan impl is hard. I don't envy future @matklad who would have to maintain it.

**Comment by matklad** [comment]
bors r+

The worst that can happen here is a segfault :D

**Comment by matklad** [comment]
```
Run 3
Database loaded:     355.57ms, 287minstr, 86mb
  crates: 34, mods: 630, decls: 12212, fns: 9614
Item Collection:     6.60s, 75ginstr, 446mb
  exprs: 263019, ??ty: 2386 (0%), ?ty: 1839 (0%), !ty: 1132
Inference:           24.43s, 229ginstr, 793mb
Total:               31.03s, 305ginstr, 1239mb

Run 3
Database loaded:     349.50ms, 287minstr, 86mb
  crates: 34, mods: 630, decls: 12212, fns: 9614
Item Collection:     6.16s, 65ginstr, 376mb
  exprs: 263019, ??ty: 2386 (0%), ?ty: 1839 (0%), !ty: 1132
Inference:           24.55s, 223ginstr, 758mb
Total:               30.70s, 289ginstr, 1134mb
````

**Comment by lnicola** [comment]
Just for posterity, can you label the benchmarks above? "Run 3" is a bit opaque :-).

**Comment by lnicola** [comment]
changelog internal switch to a mutable syntax tree implementation

**Pull request merged**
