### PR TITLE
Refactor to allow for multiple assists 

### PR DESCRIPTION
**Pull request by eulerdisk**
This is necessary to allow assist "providers" (which currently are simple free function) to produce multiple assists. I'm not sure this is the best possible refactoring tough.

### CODE REVIEW

**Comment by DJMcNab** [comment]
Should this be used to make auto_import_assist return all the available options, preferring the 'best'. Also, why do these return an `Option<Vec<_>>` - a `Vec` with 0 capacity doesn't allocate so a 'failure' can be marked by an empty vector.

**Comment by eulerdisk** [comment]
> Should this be used to make auto_import_assist return all the available options, preferring the 'best'. 

Yes, this is in preparation for that.

>Also, why do these return an `Option<Vec<_>>` - a `Vec` with 0 capacity doesn't allocate so a 'failure' can be marked by an empty vector.

Yes, it's a way to do that. I like to use `Option` and enums in general because they are explicit. The problem is I'm not sure returning `Vec` is the best way to do that anyway, maybe @matklad has some other ideas.

**Comment by DJMcNab** [comment]
Maybe it should use an accumulator like the validators do.

**Comment by matklad** [comment]
Agree in general that zero-length vector is better than an `Option`, but in this specific case option is required to make `?` work. 

Allowing assist providers to return several assists seems like a good idea as well. I think the better way to do it though is to move the `Vec` *inside* of the `Assist` type, so that existing code does not have to change, at the expense of the more verbose API when we do need to return multiple assists.

**Comment by eulerdisk** [comment]
@matklad Are you suggesting something like this?
```
#[derive(Debug)]
pub struct AssistLabel {
    /// Short description of the assist, as shown in the UI.
    pub label: String,
}

pub struct AssistAction {
    pub edit: TextEdit,
    pub cursor_position: Option<TextUnit>,
    pub target: Option<TextRange>,
}

pub(crate) enum AssistChoice {
    Unresolved(AssistLabel),
    Resolved(AssistLabel, AssistAction),
}

pub(crate) enum Assist {
    choices: Vec<AssistChoice>,
}
```

**Comment by matklad** [comment]
@eulerdisk almost, I think it should be

```
enum Assist {
    Unresolved(Vec<AssistLabel>),
    Resolved(Vec<(AssistLabel, AssistAction)>),
}
```

`should_compute_edit` is sort-of static configuration, so all assists should be in the same mode.

**Comment by eulerdisk** [comment]
@matklad I implemented your suggestion. Tell me if it's good.

**Comment by matklad** [comment]
yep, lgtm!

bors r+

**Pull request merged**
