### PR TITLE
fix: Listen to clippy

### PR DESCRIPTION
**Pull request by Milo123459**
This PR is here to fix various clippy lints.

### CODE REVIEW

**Comment by Milo123459** [comment]
Bug report as well. Running the rename symbol thing didn't change the occurrence in some places. Doing it manually. Is this a Rust-analyzer bug or VSCode?

**Comment by lnicola** [comment]
We don't fix _all_ clippy lints and I doubt that the casing one will be accepted.

Also, `generated.rs` is generated automatically.

**Comment by Milo123459** [comment]
> We don't fix _all_ clippy lints and I doubt that the casing one will be accepted.
> 
> Also, `generated.rs` is generated automatically.


Is there a command that does that..?

**Comment by Milo123459** [comment]
Also, the purpose of this is to clean up the codebase. I think this is a good idea as it can overwhelm new contributors with the amount of warnings.

**Comment by lnicola** [comment]
We don't have a set of ignored clippy warnings. `generated.rs` is generated by the `tidy` test in `xtask` IIRC.

> I think this is a good idea as it can overwhelm new contributors with the amount of warnings.

Running clippy might look like a good first contribution, but it's not what we do: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/style.md#clippy. It's fine to submit a couple of fixes from time to time, but there are a lot of false positives, even with the lints that shouldn't have them.

**Comment by Veykril** [comment]
I am a bit confused as to why clippy would be linting this in the first place. The generated file with the `SyntaxKind` enum has `#![allow(bad_style, missing_docs, unreachable_pub)]` which should surpress the styling lints triggered by that enum so there shouldn't be any such warnings.

**Comment by lnicola** [comment]
For example, try running `cargo clippy -- -A clippy::all -W clippy::perf`. I see one legit warning, one that's arguable, and the others are false positives.

**Comment by Milo123459** [comment]
I see.

**Comment by lnicola** [comment]
Of course, targeted clippy fixes are still welcome as long as they don't touch `crates/proc_macro_srv/src/proc_macro` -- though matklad will still disagree with some of them.

**Pull request closed without merging**
