### PR TITLE
feat: Speculatively expand attributes in completions

### LINKED ISSUE #9866: Completion does not work in attribute macros
During completion, we use this code to descend from a macro invocation to the expansion:

https://github.com/rust-analyzer/rust-analyzer/blob/1376ece497c2e189c97810e188e25c94f10951a8/crates/ide_completion/src/context.rs#L178-L182

This does not handle attribute macros, so completion doesn't work inside them. The code also makes use of speculative expansion, which is not yet implemented for attribute macros.

### PR DESCRIPTION
**Pull request by Veykril**
j1OjBt5Nca

Fixes #9866

### CODE REVIEW

**Comment by matklad** [comment]
We really need to up our testing game here :-) The fact that the easiest way to test this is to `#[test]` in an ide instead of writing a `#[test]` points at the proc-macro shaped hole in our testing infra. 

My current thinking is that running fully-fledged proc macros inside tests is not a good idea. I think it would be long-term beneficial if "every test runs in a single, static binary" were an invariant of our code-base. 

In the `base_db` layer, procedural macros are already abstracted away as an arbitrary `TokenStream -> TokenStream` transformation. So I think what we want to do is to add a dummy, test impl of this trait with some example macros, and use that to write most of the tests. The actual proc macro loading cound then be delegated to a few `heavy` tests I think.

**Comment by Veykril** [comment]
Ye we should definitely prioritize testing for now.

Regarding `async_trait` not working here, I fear that might be due to the syn parser being used in the attribute failing to parse the item input when typing in there... so the expansion fails, this of course works fine for the simple `#[test]` attribute I used for testing since we just feed back the input item without validating 😬 Now I fear that we probably have to do this some other way as most attributes if not all will fail in this manner as they expect fully correct syntax as input.

**Comment by matklad** [comment]
It doesn't work even for complete syntax `self.pref;`, so I think that's not the issue

**Pull request merged**
