### PR TITLE
Changes Cursor Marker To $0

### PR DESCRIPTION
**Pull request by kevaundray**

### CODE REVIEW

**Comment by matklad** [comment]
@kevaundray could you split additional retactors into a separate PR?

If you could additionally split the first commit into "smart" part which modities the logic of test_utils and "dumb" part which does search-replace, that'd be extra sweet!

**Comment by kevaundray** [comment]
> @kevaundray could you split additional retactors into a separate PR?
> 
> If you could additionally split the first commit into "smart" part which modities the logic of test_utils and "dumb" part which does search-replace, that'd be extra sweet!

done! I think that since I reset the head on my branch, the CI keeps failing. The solution from the CI error message was to reset --soft and batch commit the changes. I've done this now, however the CI error persists. Tomorrow morning, I can re-branch off of master and re-do the commit

**Comment by matklad** [comment]
>I've done this now, however the CI error persist

Did you do `git push --force-with-lease`? Whats the output of `git --log`?

**Comment by matklad** [comment]
Added some diagnostics tips in https://github.com/rust-analyzer/rust-analyzer/pull/7189

**Comment by kevaundray** [comment]
> Added some diagnostics tips in #7189

Thanks a lot for this, it was very helpful in debugging the issue.

**Pull request merged**
