### PR TITLE
Debug macOS CI problems

### PR DESCRIPTION
**Pull request by jonas-schievink**

### CODE REVIEW

**Comment by matklad** [comment]
I wonder if this has to do with `rustc` version. Proc macro ABI changed in 1.47, but CI still uses 1.46.

**Comment by jonas-schievink** [comment]
Locally that just resulted in test failures, I would not expect that to affect building r-a itself

**Comment by lnicola** [comment]
CI updates to 1.47, but those errors are really weird:

```
error[E0463]: can't find crate for `serde_derive` which `serde_json` depends on
```

**Comment by matklad** [comment]
But mac CI **is** using 1.46: https://github.com/rust-analyzer/rust-analyzer/runs/1242732678#step:4:21. Filed #6206 to not be surprised by this.

**Comment by matklad** [comment]
Ah, no, CI updates 1.46 to 1.47...

**Comment by lnicola** [comment]
Yep. The GitHub Actions image has 1.46, but the `toolchain` action updates it.

**Comment by jonas-schievink** [comment]
Turns out this is a bug in BSD tar, which is what macOS uses: https://github.com/rust-lang/cargo/issues/8603

Apart from disabling caching, there doesn't seem to be any way to fix this on our end.

**Comment by jonas-schievink** [comment]
Actually we can just use GNU tar instead...

**Comment by jonas-schievink** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/6208 should fix this

**Pull request closed without merging**
