### PR TITLE
QOL: VSCode status bar icon on click now shows server status

### PR DESCRIPTION
**Pull request by Milo123459**
Now, when you click the little status bar text, it will automatically reload the server. I don't think I've ever seen anyone click it randomly, and, it's there to save you a few clicks.

### CODE REVIEW

**Comment by lnicola** [comment]
Do other servers do the same thing? I did click it randomly, and wouldn't have expected a reload. Maybe it would be more useful to run the "Server Status" command instead?

**Comment by Milo123459** [comment]
Some over LS' I've added this to, most private.

**Comment by flodiebold** [comment]
IMO any situation where the server needs to be restarted manually is a bug (unless you're working on the server), so I would be against making the restart function so prominent. (There are a few such situations remaining, but we should fix them.) Plus it can be accessed pretty fast through the command palette, can't it?

That said, I don't personally use VSCode anyway, so my opinion doesn't count that much :man_shrugging:

**Comment by Milo123459** [comment]
Well, a bug would be when `cargo fix` changes something the errors persist on the same lines without making the LS check. My reasoning for this is that you can click the button to restart it to fix this error.

**Comment by lnicola** [comment]
Doesn't saving the file clear the errors (unless you changed `Cargo.toml` outside of Code)?

**Comment by Milo123459** [comment]
Yes, but it slips through the cracks when a program in the commandline edits the file. This is just a way to help users fix it by clicking a button!

**Comment by lnicola** [comment]
If the errors don't go away after you save a file, it's probably a bug. I know it happens if you use `cargo-edit`, but that's a different thing. Saving the current file (even without any changes) should re-run `cargo check`.

**Comment by Milo123459** [comment]
So is this not going to be merged most likely?

**Comment by Milo123459** [comment]
Also, this just adds functionality to it. There isn't entirely a point to having it there if it does nothing.

**Comment by lnicola** [comment]
My point is that restarting the server is a thing you shouldn't need to do often, and we might want to do something else there. Showing the server info seems more useful to me.

**Comment by lnicola** [comment]
And if you find a case when you need to restart the server, please file an issue.

**Comment by Milo123459** [comment]
But then what other function would it have? This is the best one I could think of.

**Comment by lnicola** [comment]
> But then what other function would it have? This is the best one I could think of.

Maybe "Rust Analyzer: Status"?

**Comment by Milo123459** [comment]
What exactly does that command do?

**Comment by lnicola** [comment]
It shows what the server has been up to:

```
workspaces:
179 packages loaded

analysis:
3586 (38mb) files
0 (0b) index symbols
2551 trees, 128 retained
30588 trees, 128 retained (macros)
681mb total

counts:
all counts are zero

file info:
crate: ide_completion(CrateId(188))
deps: core=CrateId(1), alloc=CrateId(0), std=CrateId(6), base_db=CrateId(47), cov_mark=CrateId(77), either=CrateId(128), expect_test=CrateId(136), hir=CrateId(181), ide_db=CrateId(189), itertools=CrateId(210), log=CrateId(249), once_cell=CrateId(295), profile=CrateId(352), rustc_hash=CrateId(423), stdx=CrateId(490), syntax=CrateId(522), test_utils=CrateId(524), text_edit=CrateId(531)


requests:
  436 textDocument/codeLens               0ms
  437 textDocument/codeLens               0ms
  644 textDocument/codeLens               0ms
  645 textDocument/codeLens               0ms
* 359 textDocument/codeLens               0ms
  360 textDocument/codeLens               0ms
  362 textDocument/codeLens               0ms
  363 textDocument/codeLens               0ms
  427 textDocument/codeLens               0ms
  428 textDocument/codeLens               0ms
```

E.g. if something seemed slow, you can use it to see what request that was. It's not the best way to do profiling, but it's handy.

Or it could trigger the "Memory usage" command:

```
Per-query memory usage:
    89mb FileItemTreeQuery
    43mb CrateDefMapQueryQuery
    39mb FileTextQuery (purge)
    36mb HygieneFrameQuery
    34mb MacroArgTextQuery
    24mb TraitImplsInDepsQuery
    20mb ParseQuery
    16mb InternMacroQuery
    15mb TraitSolveQueryQuery (purge)
    15mb BodyQuery
    11mb MacroDefQuery
    10mb BodyWithSourceMapQuery
[snip]
110mb Remaining

(note: database has been cleared)
```

**Comment by Milo123459** [comment]
That's a better idea. I will add it when I get back home.

**Comment by bjorn3** [comment]
Could you please update the PR title to match the current implementation?

**Comment by matklad** [comment]
bors r+

IIRC, we actually used to reload on click on the status bar. The status indeed seems like a better thing to do here. 

Although, truth be told, our "status" page isn't really friendly or useful :( UX-wise, I think we need something like https://github.com/rust-analyzer/rust-analyzer/issues/4284.

**Pull request merged**
