### PR TITLE
feat: Visualize compiler inserted reborrows via inlay hints

### PR DESCRIPTION
**Pull request by Veykril**
Disabled by default.

image

Closes https://github.com/rust-analyzer/rust-analyzer/issues/11275

### CODE REVIEW

**Comment by flodiebold** [comment]
It would be nice to be able to toggle visualizations like this and the implicit lifetimes, I guess. Probably very few people will want to turn them on permanently, but would sometimes want to see them.

**Comment by Veykril** [comment]
Ye hence why I've disabled them by default. Iirc you can (at least in VSCode) bind configuration toggles to buttons? I'll check that, would probably be good to mention that in the changelog if that is indeed possible.

**Comment by Veykril** [comment]
Ah nvm, we added an extra thing for that https://github.com/rust-analyzer/rust-analyzer/pull/4601

**Comment by Veykril** [comment]
So, I personally don't feel too good about adding a `toggle X` command for all these things that we might have and as it turns out (at least for VSCode) you can do arbitrary config toggles by adding an extension and then adding to your keybindings like written here https://medium.com/hack-visual-studio-code/toggle-any-setting-in-vs-code-using-keyboard-shortcut-arguments-cdb5ddc56955
Which sounds like the better overall solution to me to point people to.

**Comment by lnicola** [comment]
Can we drop #4601 then? :laughing:

**Comment by Veykril** [comment]
I'd say yes :)

**Comment by flodiebold** [comment]
I wouldn't want to add a toggle command for all the things. I do think though that if we want to provide a good user experience for this, we should provide some way of showing it temporarily and not require a hack with another extension. (Is it even possible to toggle the setting without restarting the server?)

**Comment by Veykril** [comment]
Yes changing inlay hint settings retriggers them.

**Pull request merged**
