### PR TITLE
:arrow_up: rowan

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by lnicola** [comment]
Changelog skip

**Comment by lnicola** [comment]
@matklad can you push the `rowan` changes here.

**Comment by matklad** [comment]
@lnicola they are in https://github.com/rust-analyzer/rowan/tree/clone-for-update

**Comment by lnicola** [comment]
But that one is still on `0.13.0-pre.2`.

**Comment by matklad** [comment]
oupps, pushed now. That relase fixes a nasty bug: when iterating a linked list in reverse, I've mixed up `next` and `prev`. Seems like I didn't have enough linked lists interviews )

**Pull request merged**
