### PR TITLE
Add warning when open file outside workspace

### LINKED ISSUE #967: Open a file outside the project throw error
## Steps to reproduce the issue
- Create two projects
```
cd /tmp
cargo new foo
cargo new --lib bar
```
- Open project `foo` with vscode
- In vscode terminal, run ` code ../bar/src/lib.rs`

## Errors
```
[Error - 9:54:55 AM] Request textDocument/codeAction failed.
  Message: unknown file: /tmp/bar/src/lib.rs
stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::h79b7b90ae93b1542 (0x5597f5c2624f)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h905b008d64ea401c (0x5597f5c264df)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
      <failure::backtrace::Backtrace as core::default::Default>::default::h638e863abbd4b22e
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125
   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h7668224d41baa776 (0x5597f57f3834)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
      <failure::error::Error as core::convert::From<F>>::from::h828074654907c31c
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
      failure::error_message::err_msg::h926e532de9a18ff5
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12
      ra_lsp_server::server_world::ServerWorld::uri_to_file_id::{{closure}}::h3e231d697e319737
             at crates/ra_lsp_server/src/server_world.rs:157
      <core::option::Option<T>>::ok_or_else::h4edd928d6b3bf9fb
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/option.rs:528
      ra_lsp_server::server_world::ServerWorld::uri_to_file_id::hab991fdc830ce03e
             at crates/ra_lsp_server/src/server_world.rs:153
   3: <&'a lsp_types::TextDocumentIdentifier as ra_lsp_server::conv::TryConvWith>::try_conv_with::h12ae56b638f55b47 (0x5597f5775a7b)
             at crates/ra_lsp_server/src/conv.rs:240
      ra_lsp_server::main_loop::handlers::handle_code_action::h7b6a0211152ea036
             at crates/ra_lsp_server/src/main_loop/handlers.rs:577
   4: ra_lsp_server::main_loop::PoolDispatcher::on::{{closure}}::h6f33c687f69b3736 (0x5597f5797542)
             at crates/ra_lsp_server/src/main_loop.rs:423
      <F as threadpool::FnBox>::call_box::hffbc2aa1ba2387fb
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:95
   5: threadpool::spawn_in_pool::{{closure}}::h947567af836fdee9 (0x5597f58c3da2)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:767
      std::sys_common::backtrace::__rust_begin_short_backtrace::h2711fac6d1b13c9d
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sys_common/backtrace.rs:136
   6: __rust_maybe_catch_panic (0x5597f5cef169)
             at src/libpanic_unwind/lib.rs:102
   7: std::panicking::try::hc0164bdc83a4fac3 (0x5597f58c16ab)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:289
      std::panic::catch_unwind::ha4c2860674a89e14
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:398
      std::thread::Builder::spawn_unchecked::{{closure}}::h7481bfff8b8c7d2e
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/mod.rs:476
      <F as alloc::boxed::FnBox<A>>::call_box::h94db59dad7e6b442
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:673
   8: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d (0x5597f5ce2d2d)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
      std::sys_common::thread::start_thread::h9605a7df0f911844
             at src/libstd/sys_common/thread.rs:24
      std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
             at src/libstd/sys/unix/thread.rs:90
   9: start_thread (0x7fc6c4c23a9c)
  10: clone (0x7fc6c4b39b22)
  11: <unknown> (0x0)
  Code: -32603 
[Error - 9:54:55 AM] Request textDocument/foldingRange failed.
  Message: unknown file: /tmp/bar/src/lib.rs
stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::h79b7b90ae93b1542 (0x5597f5c2624f)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h905b008d64ea401c (0x5597f5c264df)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
      <failure::backtrace::Backtrace as core::default::Default>::default::h638e863abbd4b22e
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125
   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h7668224d41baa776 (0x5597f57f3834)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
      <failure::error::Error as core::convert::From<F>>::from::h828074654907c31c
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
      failure::error_message::err_msg::h926e532de9a18ff5
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12
      ra_lsp_server::server_world::ServerWorld::uri_to_file_id::{{closure}}::h3e231d697e319737
             at crates/ra_lsp_server/src/server_world.rs:157
      <core::option::Option<T>>::ok_or_else::h4edd928d6b3bf9fb
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/option.rs:528
      ra_lsp_server::server_world::ServerWorld::uri_to_file_id::hab991fdc830ce03e
             at crates/ra_lsp_server/src/server_world.rs:153
   3: <&'a lsp_types::TextDocumentIdentifier as ra_lsp_server::conv::TryConvWith>::try_conv_with::h12ae56b638f55b47 (0x5597f577281e)
             at crates/ra_lsp_server/src/conv.rs:240
      ra_lsp_server::main_loop::handlers::handle_folding_range::h51e42a197c3f3ac4
             at crates/ra_lsp_server/src/main_loop/handlers.rs:370
   4: ra_lsp_server::main_loop::PoolDispatcher::on::{{closure}}::h058701f5e57d33c0 (0x5597f5791321)
             at crates/ra_lsp_server/src/main_loop.rs:423
      <F as threadpool::FnBox>::call_box::h5c73b098d3d421de
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:95
   5: threadpool::spawn_in_pool::{{closure}}::h947567af836fdee9 (0x5597f58c3da2)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:767
      std::sys_common::backtrace::__rust_begin_short_backtrace::h2711fac6d1b13c9d
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sys_common/backtrace.rs:136
   6: __rust_maybe_catch_panic (0x5597f5cef169)
             at src/libpanic_unwind/lib.rs:102
   7: std::panicking::try::hc0164bdc83a4fac3 (0x5597f58c16ab)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:289
      std::panic::catch_unwind::ha4c2860674a89e14
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:398
      std::thread::Builder::spawn_unchecked::{{closure}}::h7481bfff8b8c7d2e
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/mod.rs:476
      <F as alloc::boxed::FnBox<A>>::call_box::h94db59dad7e6b442
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:673
   8: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d (0x5597f5ce2d2d)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
      std::sys_common::thread::start_thread::h9605a7df0f911844
             at src/libstd/sys_common/thread.rs:24
      std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
             at src/libstd/sys/unix/thread.rs:90
   9: start_thread (0x7fc6c4c23a9c)
  10: clone (0x7fc6c4b39b22)
  11: <unknown> (0x0)
  Code: -32603 
[Error - 9:54:56 AM] Request textDocument/codeLens failed.
  Message: unknown file: /tmp/bar/src/lib.rs
stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::h79b7b90ae93b1542 (0x5597f5c2624f)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h905b008d64ea401c (0x5597f5c264df)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
      <failure::backtrace::Backtrace as core::default::Default>::default::h638e863abbd4b22e
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125
   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h7668224d41baa776 (0x5597f57f3834)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
      <failure::error::Error as core::convert::From<F>>::from::h828074654907c31c
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
      failure::error_message::err_msg::h926e532de9a18ff5
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12
      ra_lsp_server::server_world::ServerWorld::uri_to_file_id::{{closure}}::h3e231d697e319737
             at crates/ra_lsp_server/src/server_world.rs:157
      <core::option::Option<T>>::ok_or_else::h4edd928d6b3bf9fb
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/option.rs:528
      ra_lsp_server::server_world::ServerWorld::uri_to_file_id::hab991fdc830ce03e
             at crates/ra_lsp_server/src/server_world.rs:153
   3: <&'a lsp_types::TextDocumentIdentifier as ra_lsp_server::conv::TryConvWith>::try_conv_with::h12ae56b638f55b47 (0x5597f5777e70)
             at crates/ra_lsp_server/src/conv.rs:240
      ra_lsp_server::main_loop::handlers::handle_code_lens::h4a0e1bc06da107ad
             at crates/ra_lsp_server/src/main_loop/handlers.rs:639
   4: ra_lsp_server::main_loop::PoolDispatcher::on::{{closure}}::h6ed642fd26127d0e (0x5597f578dee9)
             at crates/ra_lsp_server/src/main_loop.rs:423
      <F as threadpool::FnBox>::call_box::h24a6722ad2128a26
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:95
   5: threadpool::spawn_in_pool::{{closure}}::h947567af836fdee9 (0x5597f58c3da2)
             at /home/sigoden/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:767
      std::sys_common::backtrace::__rust_begin_short_backtrace::h2711fac6d1b13c9d
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sys_common/backtrace.rs:136
   6: __rust_maybe_catch_panic (0x5597f5cef169)
             at src/libpanic_unwind/lib.rs:102
   7: std::panicking::try::hc0164bdc83a4fac3 (0x5597f58c16ab)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:289
      std::panic::catch_unwind::ha4c2860674a89e14
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:398
      std::thread::Builder::spawn_unchecked::{{closure}}::h7481bfff8b8c7d2e
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/mod.rs:476
      <F as alloc::boxed::FnBox<A>>::call_box::h94db59dad7e6b442
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:673
   8: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d (0x5597f5ce2d2d)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
      std::sys_common::thread::start_thread::h9605a7df0f911844
             at src/libstd/sys_common/thread.rs:24
      std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
             at src/libstd/sys/unix/thread.rs:90
   9: start_thread (0x7fc6c4c23a9c)
  10: clone (0x7fc6c4b39b22)
  11: <unknown> (0x0)
  Code: -32603 
```

Same bug with issue #717?

### PR DESCRIPTION
**Pull request by edwin0cheng**
When file is not found in `ra_vfs` but exist, use `LspError` for warning instead of `error_fmt` to bail out error, 

Temporarily fix #967 .

edit: typo

### CODE REVIEW

**Comment by matklad** [comment]
Excellent idea!

We probably shouldn't be checking specifically if the path exists: VSCode can send us in-memory files. In general, we should interract with fs only via vfs.

**Comment by edwin0cheng** [comment]
Fixed 👍

**Comment by edwin0cheng** [comment]
> We probably shouldn't be checking specifically if the path exists: VSCode can send us in-memory files. In general, we should interract with fs only via vfs.

If we only handle files via vfs, what is the proper way to handle this error ? Currently even we pass this error back to vscode, when the user do other actions, it will send the warnings again and again, and is still  very annoying. Should we add some kind of cached mechanism which suppress the warning (cancel the action) when it happens before ?

On the other hand, could it possible to add a new api which allow us to add a new `Roots` in `ra_vfs` after initialization ? If so, we can check whether file exists ***and*** the file's ancestor directory is a cargo workspace And then we add that directory in the new roots.

**Comment by matklad** [comment]
bors r+

Ideally, this should not be an error at all: we should just add the file to some kind of "default" VFS root. According to the protocol, it is valid for the client to send arbitrary files to the server.


However in practice, if we get a lot of such warnings, that probably means that something is misconfigurated on our side (as opposed to client genuinelly sending us random files)

**Pull request merged**
