### PR TITLE
Use clippy on ci

### PR DESCRIPTION
**Pull request by Veetaha**

### CODE REVIEW

**Comment by Veetaha** [comment]
@matklad what happens with `jemalloc-sys` using C and failing ci? I haven't touched it in any way

**Comment by edwin0cheng** [comment]
Related: https://github.com/rust-analyzer/rust-analyzer/issues/848#issuecomment-464493575

**Comment by matklad** [comment]
We intentionally don't use clippy on CI

**Comment by Veetaha** [comment]
What are the intentions @matklad ?

**Comment by Veetaha** [comment]
Won't you merge at least the clippy fixes?

**Pull request closed without merging**
