### PR TITLE
Handle coercion on binary operator RHS

### LINKED ISSUE #9968: Type mismatch with deref and reseating references
CC #8961

```
fn g(_text: &str) {}
fn f(text: &str) {
    let mut text = text;
    let tmp = String::new();
    text = &tmp; // Expected &str, got &String
    g(text);
}
```

### LINKED ISSUE #9971: Normalization issue with operators or `Deref`
CC #8961

```rust
let s = String::new() + &String::new(); // s is <String as Add<String>>::Output
```

### PR DESCRIPTION
**Pull request by lnicola**
Closes #9968
CC #8961

### CODE REVIEW

**Comment by lnicola** [comment]
Hmm, this doesn't fully fix #9971. We still don't normalize the output type in `String::new() + &String::new()`, but the type error is gone.

**Comment by flodiebold** [comment]
The problem is that we only do the trait resolution at the end, but we need to do it before checking the right-hand side (with a variable in place of the RHS type). For `String`, that will tell us that the RHS type has to be `&str`.

**Pull request merged**
