### PR TITLE
Handle `cargo watch` errors caused by `cargo-watch` itself

### PR DESCRIPTION
**Pull request by oxalica**
Currently, it silently fails when `cargo-watch` is installed but broken.

This PR handles missing cases and prompt the error message when failed.

### CODE REVIEW

**Comment by matklad** [comment]
Let's check exit-code instead of `stderr`: in general, utilities can print diagnostic infos to stderr

**Comment by matklad** [comment]
bors r+

Thanks!

**Comment by oxalica** [comment]
@matklad Fixed

**Comment by lnicola** [comment]
CI failed because of a formatting issue.

**Comment by oxalica** [comment]
Fixed formating

**Pull request merged**
