### PR TITLE
Set opt-level=1 for test profile

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by matklad** [comment]
I *think* that for this to be an overall win, we need to set `dev` to `opt-leve=1` as well. Otherwise, some deps will be compiled twice

**Comment by lnicola** [comment]
Updated. I don't know how the `test` and `dev` profiles interact, but you're probably right.

**Comment by lnicola** [comment]
We could also disable debug info, but it might lead to a poor development experience.

**Comment by matklad** [comment]
>We could also disable debug info, but it might lead to a poor development experience.

Hm, this might actually be a good idea to do on CI, at least to reduce the size of a cache. Do you know if profiles from `.config` are stable? I also wouldn't mind just echoing a special profiling config into Cargo.toml from .travis.yaml :D

**Comment by matklad** [comment]
@lnicola it would be awesome if you could benchmark time and size of /target dir locally, to make sure that this optimization is not accidentaly a pessimization :)

**Comment by lnicola** [comment]
Even in CI, this doesn't seem to be a win.

**Comment by matklad** [comment]
In this particular case we miss all the caches, and need to recompile the world

**Comment by lnicola** [comment]
With cache (`find ./target/debug -maxdepth 1 -type f -delete; rm -fr ./target/debug/{deps,.fingerprint}/{*ra_*,*test*,*gen_lsp*,*thread_worker*}; rm -f  ./target/.rustc_info.json`), looks like this could be a small improvement:

```
opt-level=1

cargo test --no-run  151.35s user 17.88s system 220% cpu 1:16.82 total
cargo test --no-run  159.48s user 18.41s system 218% cpu 1:21.55 total
cargo test --no-run  150.69s user 17.57s system 248% cpu 1:07.66 total

cargo test  135.35s user 0.76s system 475% cpu 28.612 total
cargo test  133.51s user 0.70s system 496% cpu 27.058 total
cargo test  136.05s user 0.71s system 497% cpu 27.474 total

opt-level=0
cargo test --no-run  109.02s user 15.96s system 157% cpu 1:19.46 total
cargo test --no-run  109.74s user 15.82s system 161% cpu 1:17.55 total
cargo test --no-run  109.02s user 16.19s system 168% cpu 1:14.40 total

cargo test  353.92s user 0.91s system 489% cpu 1:12.50 total
cargo test  354.45s user 0.88s system 501% cpu 1:10.87 total
cargo test  354.40s user 0.86s system 494% cpu 1:11.86 total
```

**Comment by matklad** [comment]
heh it looks like a major improvement actually. What is the difference in the size of `./target` directory?

**Comment by lnicola** [comment]
Updated. It might be even worth going to `opt-level=2`, but a full build gets slower. Disabling incremental builds is worse, because we seem to be caching `target/incremental`, but I'm not sure how large that gets and who deletes it.

**Comment by matklad** [comment]
Hm, IIRC incremental is disabled automatically on CI, so we shouldn't cache it?

**Comment by lnicola** [comment]
Ah, right, then my tests are useless :sob:.

**Comment by matklad** [comment]
Only some of them, I didn't realise that `debug = false` is this much lighter!

**Comment by lnicola** [comment]
Yeah, did you notice that `ra_lsp_server` is 388 MB?

**Comment by matklad** [comment]
:fearful: 

Nope! Heh, I wonder if we should remove `debug = true` from our release profile...

**Comment by lnicola** [comment]
```
    Finished release [optimized + debuginfo] target(s) in 5m 17s
    Finished release [optimized] target(s) in 3m 59s
```

It's still a nice win, I guess.

---

I wonder if we could cache `target/incremental`, but remove old outputs?

**Comment by lnicola** [comment]
For completeness:

```
dev opt-level = 2, test opt-level = 0, no debug info, no incremental
cargo test --no-run  911.50s user 11.78s system 633% cpu 2:25.70 total
cargo test  20.14s user 0.72s system 408% cpu 5.105 total

dev opt-level = 1, test opt-level = 0, no debug info, no incremental
cargo test --no-run  668.26s user 13.49s system 549% cpu 2:04.05 total
cargo test  134.19s user 0.71s system 490% cpu 27.495 total

dev opt-level = 0, test opt-level = 0, no debug info, no incremental
cargo test --no-run  254.57s user 11.07s system 456% cpu 58.138 total
cargo test  315.76s user 0.85s system 490% cpu 1:04.58 total
```

**Pull request closed without merging**
