### PR TITLE
Fix `$true` and `$false` as $var name error

### PR DESCRIPTION
**Pull request by edwin0cheng**
This PR fixed a bug which cannot use `$true` and `$false` as `$var` name in mbe.

### CODE REVIEW

**Comment by matklad** [comment]
@vlad20012 says that any keyword can be identifier, not only bools

**Comment by edwin0cheng** [comment]
Hmm... https://github.com/rust-lang-nursery/packed_simd/blob/ba837650b983a71367f68695af99b89174ac7543/src/api/ops/vector_bitwise.rs#L3-L8

**Comment by edwin0cheng** [comment]
Yes, and others keywords are handled in `tt::Ident` already. In the original implementations, bools also are treated as `Ident`, but when i add `lit` matcher, i changed it as `Literal`.

**Pull request merged**
