### PR TITLE
internal: Profile trait solving for all invocations

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Follow-up of https://github.com/rust-analyzer/rust-analyzer/pull/8514#issuecomment-819610492

### CODE REVIEW

**Comment by matklad** [comment]
Curious, what does the profile look now?

**Comment by SomeoneToIgnore** [comment]
Pretty much the same, except for the names:

First query :
```
  255ms - handle_completion
       60ms - SourceBinder::to_module_def
           60ms - crate_def_map:wait
      106ms - descend_into_macros
          106ms - Semantics::analyze_impl
              104ms - infer:wait @ syntax_highlighting_not_quadratic
                  104ms - infer_query
                       98ms - deref
                           98ms - deref_by_trait
                               93ms - trait_solve::wait
                                0ms - crate_lang_items_query (1 calls)
                        0ms - crate_def_map:wait (80 calls)
                        0ms - deref (21 calls)
                        1ms - resolve_obligations_as_possible (15 calls)
                        1ms - trait_solve::wait (15 calls)
                0ms - SourceBinder::to_module_def (1 calls)
                2ms - body_with_source_map_query (1 calls)
                0ms - crate_def_map:wait (2 calls)
                0ms - generic_params_query (1 calls)
        8ms - render_resolution
            8ms - parse_query @ FileId(209)
            0ms - crate_def_map:wait (1 calls)
            0ms - item::Builder::build (1 calls)
        8ms - render_resolution
            8ms - parse_query @ FileId(600)
            0ms - crate_def_map:wait (1 calls)
            0ms - item::Builder::build (1 calls)
       14ms - render_resolution
           13ms - parse_query @ FileId(185)
            0ms - crate_def_map:wait (1 calls)
            0ms - item::Builder::build (1 calls)
        0ms - Semantics::analyze_impl (2 calls)
        0ms - crate_def_map:wait (2 calls)
        0ms - descend_into_macros (1 calls)
        0ms - import_on_the_fly (1 calls)
        0ms - item::Builder::build (23 calls)
       54ms - render_resolution (182 calls)
```

Consequent queries:

```
   37ms - handle_completion
       12ms - SourceBinder::to_module_def
           12ms - crate_def_map:wait
       18ms - descend_into_macros
           18ms - Semantics::analyze_impl
               17ms - infer:wait @ syntax_highlighting_not_quadratic
                   17ms - infer_query
                       16ms - deref
                           16ms - deref_by_trait
                               16ms - trait_solve::wait
                        0ms - crate_def_map:wait (79 calls)
                        0ms - deref (21 calls)
                        0ms - resolve_obligations_as_possible (15 calls)
                        0ms - trait_solve::wait (15 calls)
                0ms - SourceBinder::to_module_def (1 calls)
                0ms - body_with_source_map_query (1 calls)
                0ms - crate_def_map:wait (2 calls)
        0ms - Semantics::analyze_impl (2 calls)
        0ms - crate_def_map:wait (2 calls)
        0ms - descend_into_macros (1 calls)
        0ms - import_on_the_fly (1 calls)
        0ms - item::Builder::build (23 calls)
        4ms - render_resolution (185 calls)
```

**Comment by matklad** [comment]
>16ms - trait_solve::wait

so that's actually interesting. there's wait, but no actual query. So this means that completion is waiting for some other query, intiated by another thread.

I guess we *really* need completion benchmark, where we can run completion without other queries.

**Comment by SomeoneToIgnore** [comment]
Yes, it's time for me to finally compose _something_ in that front.

**Pull request merged**
