### PR TITLE
fix: Disable string highlight injection for macros changing string literals

### LINKED ISSUE #10845: Wonky syntax highlighting for indoc macros
*I know macros are super hard to support well, but I couldn't find an existing bug report about this (open or closed) so I thought I'd open this, even if it might not be actionable (I hope it is!).*

When using `formatdoc!` from the [indoc](https://lib.rs/crates/indoc) crate, rust-analyzer tries to highlight `{}`s but fails to do so in the correct positions:

Screenshot_2021-11-23_135908

rust-analyzer version: 1b938ef1c 2021-11-23 nightly

### PR DESCRIPTION
**Pull request by Veykril**
Fixes #10845
bors r+

### CODE REVIEW

**Comment by jplatte** [comment]
What happened after this? I can't find a related PR after this one, but it just started working on today's Nightly (or maybe yesterday already):

Screenshot_2021-11-26_154226

**Comment by Veykril** [comment]
Oh, that PR title is wrong oops. This changed the behaviour so that we do the format string analysis on the expansion, but do the actual highlighting on the original string.

**Comment by jplatte** [comment]
Awesome! 😊

**Pull request merged**
