### PR TITLE
Update crates

### PR DESCRIPTION
**Pull request by kjeremy**
This brings in a number of new dependencies though.

### CODE REVIEW

**Comment by matklad** [comment]
Which of you have done this?

**Comment by matklad** [comment]
https://github.com/steveklabnik/semver-parser/pull/50

**Comment by matklad** [comment]
new version of semver shold fix this

**Comment by kjeremy** [comment]
bors try

**Comment by kjeremy** [comment]
@matklad are you good with `pest` being added?

**Comment by matklad** [comment]
Well, no, especially for the task of parsing semver, but I think we can stomach that, and there are plans about zero-dep rewrite of semver.

**Pull request merged**
