### PR TITLE
Handle multiple cargo check quick fix spans

### PR DESCRIPTION
**Pull request by brandondong**
Resolves https://github.com/rust-analyzer/rust-analyzer/issues/10705.

**Cause:**
- For a cargo check diagnostic with multiple spans, only a single quick fix action would be created at the location of `spans[0]`. Additionally, the hover window details would only show the location of `spans[0]` next to the message.

**Fix:**
- Allow cargo check quick fix actions to be triggerable from multiple selection ranges. Specifically, if the selection intersects with any of the replacement spans, the quick fix action is shown.
- No change in behavior for the hover window details. It's pretty minor and I think showing multiple locations next to the message may be more confusing anyways.

### CODE REVIEW

**Comment by brandondong** [comment]
Failing test case:
```rust
pub fn foo() -> Vec<i32> {
    let a = (0..10).collect();
    a
}
```
Clippy expression return quick fix currently only works when hovering over the first line and not the second. With the fix, hovering on either produces the quick fix action as expected.

**Comment by Veykril** [comment]
Note this was removed before in https://github.com/rust-analyzer/rust-analyzer/pull/7285 due to fix-it duplication as seen in https://github.com/rust-analyzer/rust-analyzer/issues/6851. So this probably needs some extra stuff to prevent that from happening again? Not sure

**Comment by brandondong** [comment]
Ahh, I hadn't noticed that. In the above test case, if I decide to highlight both lines, then I'll get duplicated quick fixes.

**Comment by brandondong** [comment]
@Veykril I updated the approach and all the aforementioned issues are now fixed. It would be greatly appreciated if you could take another look when you get the time.

**Comment by Veykril** [comment]
Looks good to me! Thanks!
This is a really useful and much apprecitated fix!
bors r+

**Pull request merged**
