### PR TITLE
Cargo Format run

### PR DESCRIPTION
**Pull request by kjeremy**
I'm not sure how appreciated this is but I figured I would run `cargo fmt` and see what came up.

I made sure that `cargo test` still passes.

### CODE REVIEW

**Comment by kjeremy** [comment]
Good catch.

**Comment by matklad** [comment]
bors delegate+

LGTM, but the generated files should be ignored but rustfmt I guess.

I slightly dislike the fact that rustfmt mixes std with all other imports, but I guess we can fix on case-by-case basis by adding blank lines?

**Comment by kjeremy** [comment]
I'll look through the documentation and see if there's an option for that.

**Comment by kjeremy** [comment]
@matklad correct it looks like we can insert new-lines for groupings. I'll make a few adjustments and see what it looks like.

**Pull request merged**
