### PR TITLE
Relax VS Code version requirement

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by kjeremy** [comment]
@types/vscode needs to be downgraded as well.

**Comment by vsrs** [comment]
@matklad vscode v1.45 introduced dynamic `DebugConfigurationProvider`s https://github.com/microsoft/vscode/issues/88230#issuecomment-624066526 and I was going to try this new API to show runnables in a more vscode-natural way.

Not that it matters, I'm not even sure it will work for us. JFYI, if the API turns out to be useful, we might need 1.45.

**Comment by matklad** [comment]
@vsrs would it be hard to conditionally enable the API if we are on 1.45?

**Comment by vsrs** [comment]
@matklad 
> would it be hard to conditionally enable the API if we are on 1.45?

I think it should be easy as the API does not need any package.json modification.

One more thing. From the v1.45 release notes
>In the next milestone, we'll add UI so that an automatic debug configuration can be easily added to the launch.json for further configuration.

So, I want to wait for this UI and try all this all together.

**Pull request merged**
