### PR TITLE
Fix Clippy warnings and replace some `if let`s with `match`

### PR DESCRIPTION
**Pull request by arzg**
I decided to try fixing a bunch of Clippy warnings. I am aware of this project’s opinion of Clippy (I have read both [rust-lang/clippy#5537](https://github.com/rust-lang/rust-clippy/issues/5537) and [rust-analyzer/rowan#57 (comment)](https://github.com/rust-analyzer/rowan/pull/57#discussion_r415676159)), so I totally understand if part of or the entirety of this PR is rejected. In particular, I can see how the semicolons and `if let` vs `match` commits provide comparatively little benefit when compared to the ensuing churn.

I tried to separate each kind of change into its own commit to make it easier to discard certain changes. I also only applied Clippy suggestions where I thought they provided a definite improvement to the code (apart from semicolons, which is IMO more of a formatting/consistency question than a linting question). In the end I accumulated a list of 28 Clippy lints I ignored entirely.

Sidenote: I should really have asked about this on Zulip before going through all 1,555 `if let`s in the codebase to decide which ones definitely look better as `match` :P

### CODE REVIEW

**Review by Veykril — APPROVED** [review]
The changes look good to me.
Though I am personally not a fan of "Replace `if let Some(_) = foo` with `if let foo.is_some()`", I prefer pattern matches.

Will wait for another opinion before merging.

**Comment by arzg** [comment]
To ensure the semicolon changes remain in future, would it be good to add a check just for that lint to CI?

**Comment by arzg** [comment]
Sorry for the force push, just noticed I wrote `if let foo.is_some()` instead of `if foo.is_some()` in the commit message.

**Comment by Veykril** [comment]
> To ensure the semicolon changes remain in future, would it be good to add a check just for that lint to CI?

I feel like that might become very annoying(wish rustfmt would just fix that since it's a change that wouldn't change semantics anyways).

**Comment by arzg** [comment]
Hmm, good point. I too wish rustfmt would handle adding semicolons in these places automatically. Doing this kind of formatting requires type information, so I can definitely see why it hasn’t been implemented. Is there any point in making semicolons consistent now if they’ll just regress over time?

**Comment by Veykril** [comment]
Right that does require type info...

I mean it doesn't hurt making these consistent every now and then if its just running a clippy fix. At least its better than having these accumulate more and more I feel like.

**Comment by arzg** [comment]
Unfortunately fixing semicolons is not something done by `cargo clippy --fix` at the moment. I took a short look through the Clippy source code, but I can’t find anything that specifically implements fixes for certain lints.

**Comment by Veykril** [comment]
Oh that's a shame, sounds like something that could have a simple fix to it.

I'll go ahead and merge this now before this might run into merge conflicts as this applies none of the weird clippy lints.
bors r+

**Pull request merged**
