### PR TITLE
fix: Fix server path on NixOS

### PR DESCRIPTION
**Pull request by lnicola**
See https://github.com/rust-analyzer/rust-analyzer/commit/c0d0ceefb29111732cacf39dbb57fe9f3ce25ee8#commitcomment-62688259.

bors r+

### CODE REVIEW

**Comment by lnicola** [comment]
CC @cab404

**Comment by cab404** [comment]
LGTM; Are there workflows producing vsix, so I can test it?

**Comment by lnicola** [comment]
I kicked off an early nightly build, https://github.com/rust-analyzer/rust-analyzer/actions/runs/1637540572, check https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly in 30 minutes or so.

**Comment by cab404** [comment]
Thank you!

**Comment by cab404** [comment]
Just checked — works fine)

**Pull request merged**
