### PR TITLE
vscode: skip node internals while debugging

### PR DESCRIPTION
**Pull request by Veetaha**
Before:
without-skip-files
After:
with-skip-files

### CODE REVIEW

**Comment by lnicola** [comment]
LGTM

Since you're touching the comments anyway, can you include my proposed change from the other PR? The one mentioning `ptrace_scope` and stuff.

**Comment by Veetaha** [comment]
Sure

**Comment by Veetaha** [comment]
Done, @lnicola, I added a bit more practical hints to you proposals

**Pull request merged**
