### PR TITLE
Special case for empty comments in doc comment kind 

### PR DESCRIPTION
**Pull request by edwin0cheng**
Part of #4103

Fix `ui/empty/empty-comment.rs macros`

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

I wonder though, if we can/need fix something on the macro side as well.. It seems weird that macro non-panicing depends on an impl details of a function elsewhere. Perhaps we can lift some invariants to types or something...

**Comment by edwin0cheng** [comment]
> I wonder though, if we can/need fix something on the macro side as well.. It seems weird that macro non-panicing depends on an impl details of a function elsewhere. Perhaps we can lift some invariants to types or something...

The panic is actually raised by here:

https://github.com/rust-analyzer/rust-analyzer/blob/f654f4943552888c2b8f079cf687970268d81f18/crates/ra_mbe/src/syntax_bridge.rs#L164-L177

It bascially try to convert a comment text to `#[doc(sth)]` , I think we could move this logic to `ast::make` ?

**Comment by edwin0cheng** [comment]
bors retry

**Comment by matklad** [comment]
So, I think semantically what we do here is that we extract contents of the comment. We have `DocCommentsOwner::doc_comment_text` which does a similar job. I probably would expect an `ast::Comment::contents() -> String` method to be used to implement both getting docs (which is stiched form many line comments) and for lowering doc comemnts to attributes.

**Pull request merged**
