### PR TITLE
Upgrade Chalk to 0.36

### PR DESCRIPTION
**Pull request by flodiebold**
Quite a few changes, because Chalk got rid of the `ApplicationTy` nesting.

### CODE REVIEW

**Comment by lnicola** [comment]
LGTM, but take that with a grain of salt.

Unrelated, is the plan still to move to `chalk` types and does anything block that?

**Comment by flodiebold** [comment]
Yeah. My plan is to first finish the "resolved types" IR that I've been working on for a while now; then the current `Ty` should mostly only be used in inference, and can be replaced by Chalk types there. At least that's the idea :smile:

**Comment by flodiebold** [comment]
I'll take the LGTM as a

bors r+

:wink:

**Comment by jackh726** [comment]
@flodiebold do we know if there was a perf diff here?

**Comment by lnicola** [comment]
There's https://rust-analyzer.github.io/metrics/, but I haven't dug up the right commit.

**Comment by jackh726** [comment]
Hmm okay. Was just a bit curious if the reduced substitutions we use in chalk now helped anything.

**Pull request merged**
