### PR TITLE
Do not show default types in function and closure return values

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Avoid things like 
image

### CODE REVIEW

**Comment by GrayJack** [comment]
I actually like that it shows up the default types

**Comment by SomeoneToIgnore** [comment]
Do you know any other cases when they are displayed? I'll gladly remove those too 😄 

I personally don't think we should display the default generics at all, since they bloat the hints significantly with no immediate bonus to the reader.
Additionally, hover can display those already:
image


If you still want to display those in the hints, I think we'd better come up with a separate issue and good design due to the following reasons:
* https://github.com/rust-analyzer/rust-analyzer/issues/1946 — a number of people have an opposite opinion and don't want extra hints displayed
* this particular PR only polishes the work that had started on omitting the default types: https://github.com/rust-analyzer/rust-analyzer/pull/2594, https://github.com/rust-analyzer/rust-analyzer/pull/2894, https://github.com/rust-analyzer/rust-analyzer/pull/2657 and changing it back would require some effort
* ideally, we should discuss other display option: display type aliases or types, shorten iterator types like `Flatten<Chain<Chain<Once<Map<{unknown}, fn to_string<{unknown}>(&{unknown}) -> String>>, {unknown}>, Once<Option<String>>>>` into `impl Iterator<Item = String>` or not, display closure parameters or not, etc., etc., etc.

**Comment by GrayJack** [comment]
> I personally don't think we should display the default generics at all, since they bloat the hints significantly with no immediate bonus to the reader.

Yeah, agree with that, that it should not show them in the inlay hints, the way it was put made me thing not show then at all in any form of hints, hover or inlay

**Pull request merged**
