### PR TITLE
internal: replace AstTransformer with mutable syntax trees

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors try

**Comment by lnicola** [comment]
bors try

**Comment by matklad** [comment]
@flodiebold any thought here? :)

**Comment by flodiebold** [comment]
Seems good. Maybe we could now give it a more specific name than `AstTransform` though?

**Comment by flodiebold** [comment]
I wonder if we could apply this automagically at some point -- just doing `some_ast_node.append(some_other_ast_node)` and `some_other_ast_node` would automatically get qualified for the new scope...

**Comment by lnicola** [comment]
Ugh.

bors retry

**Pull request merged**
