### PR TITLE
don't optimize on CI, it isn't faster

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by lnicola** [comment]
:cry:

Should we also disable `debug` on `release` builds?

**Comment by matklad** [comment]
Hard question. I bet https://github.com/rust-analyzer/rust-analyzer/issues/1541 would be significantly more difficult to debug if we didn't include debug info in release by default

**Comment by matklad** [comment]
did https://github.com/rust-analyzer/rust-analyzer/pull/1577 as a middle ground

**Pull request merged**
