### PR TITLE
Fixture improvements

### PR DESCRIPTION
**Pull request by TimoFreiberg**
As mentioned in [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/resolve_path.20between.20fixture.20files) :)

I think always allowing unindented first lines is friendlier than making the user fix it and I don't see any drawbacks.

### CODE REVIEW

**Comment by matklad** [comment]
arghs, sorry, I've caused a merge conflict here :( Could you rebase?

bors d+

**Comment by TimoFreiberg** [comment]
Gonna do it in the evening after work :)

**Pull request merged**
