### PR TITLE
Switch to dynamic dispatch

### PR DESCRIPTION
**Pull request by matklad**
Benches are in https://github.com/rust-analyzer/rust-analyzer/issues/1987#issuecomment-598807185

TL;DR: 

* 33% faster release build
* slightly worse/same perf
* no changes for debug build
* slightly smaller binary

cc @flodiebold I genuinely don't know if it is a good idea or not.

### CODE REVIEW

**Comment by flodiebold** [comment]
Having to explicitly coerce is kind of annoying. I thought this is supposed to work with implicit coercions :thinking: Other than that, the numbers seem to speak for themselves?

**Comment by matklad** [comment]
In theory, https://github.com/rust-analyzer/rust-analyzer/pull/3584/commits/603d45dc48ff7bc5e0da633f0b628ff40e47ad8b should get rid of manual downcasting, but it fails with a trait error which I don't understand.

**Comment by matklad** [comment]
Yeah, I think it would be possible to push the as ref trait over the finish line, but it actually seems more annoying than call-site upcasting.

**Comment by Veetaha** [comment]
What is the general guideline on using `impl` vs `dyn` now?

**Comment by matklad** [comment]
There isn’t a universal guideline, but it’s important to understand the compile-time and code size implication of monomorphisation. In general, avoid monomorphising large swaths of code.

**Comment by lnicola** [comment]
Are there multiple implementations of `HirDatabase` and friends? Does it come from `salsa`? I'm still not sure why the code needs to be generic and/or what gets compiled twice.

**Comment by matklad** [comment]
I've just realised that compile time performance gains here are larger than I've thought: **total** compile time goes from 300s to 200s, but part of that total are dependencies like syn and regex.

**Comment by matklad** [comment]
>Are there multiple implementations of HirDatabase and friends? 

Yup, there are a couple of `TestDB` crates, but that should not matter that much. However, even with a single `RootDatabase`, we get duplication I think. To put it in other way, every crate that uses `Vec<String>` contains a fresh monomorphisation of Vec's methods.

**Comment by Veetaha** [comment]
I wish we could use that `share generics` nightly flag ...

**Comment by matklad** [comment]
I think I've tried it, and it made everything much slower.

**Comment by lnicola** [comment]
> However, even with a single RootDatabase, we get duplication I think.

But if there's a single implementation, there's no need to make the code generic?

> I wish we could use that share generics nightly flag ...

I tested that in https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/weekly.20sync-up/near/188391137, the run-time impact is too large.

**Comment by matklad** [comment]
Ah, right, it was @lnicola who did the testing, that's why I recall the result, but don't remmeber me actually tring this :D

**Pull request merged**
