### PR TITLE
feat: join lines joins two ifs into `else if`

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

join-if

### CODE REVIEW

**Comment by jhpratt** [comment]
Is there any other place joining lines has behavior other than just joining the lines? This seems quite counterintuitive to me.

**Comment by flodiebold** [comment]
It already removes braces and commas. If you just want to join lines, you can use the editor's built-in functionality; the whole point of this function is to be smarter. And there's really no good reason to join `}` and `if {` into `} if {`, unless you want `} else if {`. I think there are probably a lot of other similar opportunities to DWIM.

**Comment by jhpratt** [comment]
That's just syntactic, not semantic, setting aside macros for obvious reasons. Imo "no other reason you'd do that" is quite dangerous when I join lines. Personally, I _overrode_ the editor's built-in join lines to be r-a _because_ I expect it to be a drop-in replacement.

**Comment by flodiebold** [comment]
Undo is just a keypress away. Still, I don't see any situation where you'd join these lines without intending this change. But I'm sure @matklad would be open to making this configurable ;)

**Comment by jhpratt** [comment]
It's more the unexpectedness factor for me. I don't think that "join lines" should do anything but save for some syntactic cleanup. I have no issue waiting for a response, though 🙂

**Comment by matklad** [comment]
Yeah, adding a config flag should be fine. I guess, I probably should heed my own advice and proactively add flags for other bits of functionality here :)

Couple of more things to do:

* document special cases that join lines has
* consider renaming it to just "join"?

**Comment by rogerdahl** [comment]
At first glance, this looks like an automated refactoring which shouldn't change semantics, but if the two predicates are not mutually exclusive, or if there are side effects, it will. So it seems like it could be a footgun for the unwary... Is there a way to tell if something is an automated refactoring or a code editing shortcut?

**Comment by matklad** [comment]
@rogerdahl explicitly invoked actions are "do what I mean" rather than "do not change semantics". If the user invokes join lines (which is an explicit shortcut) between two ifs, that's a signal for the IDE that they want to join the two lines.

**Comment by matklad** [comment]
Note that this behavior is not configurable: https://github.com/rust-analyzer/rust-analyzer/pull/9503/files#diff-00784dde03b1be151004f435a4ca74754cb674a9e789840e12760d8f3ac1728fR727

**Comment by jhpratt** [comment]
Thank you!

**Pull request merged**
