### PR TITLE
Use applySnippetWorkspaceEdit again for actions, allow it to create files

### LINKED ISSUE #7037: Implement missing members for trait impl and fill match arms adds $0
Steps to reproduce:
1. `impl Iterator for Foo {}` 
2. Try to apply "Implement missing members"

```rust
struct Foo;

impl Iterator for Foo {
    $0type Item;

    fn next(&mut self) -> Option<Self::Item> {
        todo!()
    }
}
```

RA version: 0.3.428-nightly

### PR DESCRIPTION
**Pull request by Veykril**
Fixes #7037

### CODE REVIEW

**Comment by Veykril** [comment]
Well that is quite lovely, this function actually just appends edits. Never trust the docs I guess 😅 
image

**Comment by Veykril** [comment]
Mmh looks like this approach won't work as I just found an implementation bug in `vscode.WorkspaceEdit.set`, https://github.com/microsoft/vscode/issues/113512

I don't really see how this could be fixed otherwise though as the WorkspaceEdits have a very limited api surface.

**Comment by Veykril** [comment]
Alright, this works for me now. Snippets are correctly applied again while module extraction keeps working as well. Nevertheless I'd appreciate a second set of eyes testing whether this really works just in case.

**Comment by matklad** [comment]
bors r+

Thanks!

**Pull request merged**
