### PR TITLE
Avoid checking all ancestors and fix mis-completion

### PR DESCRIPTION
**Pull request by oxalica**
Refactor the logic of `completion_match` to check deterministic number of ancestors instead of `token.ancestors().find_map()`.
This should fix wrong completions (https://github.com/rust-analyzer/rust-analyzer/pull/5976#issuecomment-692332191) and hopefully make completion to be faster (#6004).

More play and test? @jonas-schievink @hammypants 

If this patch works, we can avoid the revert #6005 . :disappointed:

### CODE REVIEW

**Comment by hammypants** [comment]
@oxalica Sure. Instructions: Build from source off your fork's branch and that's it? Haven't had to do this before.

**Comment by jonas-schievink** [comment]
Yeah, just `cargo build --release`, and then set `rust-analyzer.serverPath` in VS Code to point at the executable

**Comment by hammypants** [comment]
Done. Still a noticeable increase before actions and general intellisense comes online, but _much_ faster than nightly, and after that everything is snappy.

I also noticed that the issue wasn't as bad on a full power desktop machine earlier this morning, but it definitely dunked both my laptops.

This definitely brings it back into more than usable! You guys are amazing.

**Pull request merged**
