### PR TITLE
Renaming crates and preparing Cargo.tomls for release

### PR DESCRIPTION
**Pull request by pksunkara**
I have decided to do this as a separate PR so that we can merge faster. Otherwise, rebasing is giving me a lot of pain.

### CODE REVIEW

**Comment by matklad** [comment]
Hm, this gives me a pause...

I do think that we should do the renames, but I'd rather do this myself, to minimize painful rebasing. 

I also want to remove `ra_` prefixes from the dir names. 

And I think I'll go for `0.0.0` as a version of crates, as that makes more sense.

Will this be a step towards publishing?

**Comment by pksunkara** [comment]
Yes. The prefixes need to be removed first.

I was planning to do it small steps prs to minimize rebasing pain.

**Comment by pksunkara** [comment]
I agree with `0.0.0`. Are you planning to do this today?

**Comment by matklad** [comment]
I am planning, yeah, but the probability that I succeed is <50%: just back
from vacation, looking through backlog!

**Comment by pksunkara** [comment]
Great. I will change the versions parts in a separate PR so that you don't
need to care about that.

**Pull request closed without merging**
