### PR TITLE
Rename record_field_pat to record_pat_field

### PR DESCRIPTION
**Pull request by pksunkara**
The token was renamed but not this.

### CODE REVIEW

**Comment by pksunkara** [comment]
@matklad I am not exactly sure how to fix this failure. Could you please help me a bit?

**Comment by lnicola** [comment]
@pksunkara try https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/dev#parser-tests

**Comment by pksunkara** [comment]
It didn't work. But I realised that I updated the name of an inline test and renamed the files. Thanks for pointing in the direction. 😄 

This PR is now ready.

**Comment by jonas-schievink** [comment]
Nice, thanks!

bors r+

**Pull request merged**
