### PR TITLE
Import fixpoint loop for name resolution

### PR DESCRIPTION
**Pull request by flodiebold**
This implements reexports, so only the glob import part of #231 remains.

### CODE REVIEW

**Comment by matklad** [comment]
awesome!

bors r+

**Comment by flodiebold** [comment]
By the way, there's still a lot of imports not being resolved, so I think there's still a bug or two in there. I'm looking into it.

**Comment by matklad** [comment]
Yep. I think we might not resolve imports transitively perhaps? That is, if we see an import we record an empty resolution, and if othe r stuff sees this import, it will get this empty resolution as well, and won't be backfield when we finally resolve it.

**Comment by flodiebold** [comment]
Actually, it's something much simpler :) Will get a fix in soon.

**Pull request merged**
