### PR TITLE
Always put a space after impl in macro pretty-printing

### PR DESCRIPTION
**Pull request by jplatte**
… regardless of whether the next symbol is punctuation or not.

Followup to #11200.

### CODE REVIEW

**Comment by lnicola** [comment]
I wonder if there might not be a better place for the pretty-printing test in #11200.

**Comment by Veykril** [comment]
We could probably have the tests for this live in the same module as the pretty printing and just have the test snippet be wrapped in a macro, invoke that, apply the pretty printing and then `expect!` the output.

**Comment by lnicola** [comment]
Done in https://github.com/rust-analyzer/rust-analyzer/pull/11217.

**Pull request merged**
