### PR TITLE
Further tweak for macro_use on extern crate

### PR DESCRIPTION
**Pull request by uHOOCCOOHu**
Some more tweaks to #1743 to behave more like `rustc`
1. Hoist macros from `#[macro_use] extern crate`, so that they can be used before `extern crate`.
2. Implicit `#[macro_use]` for `prelude` if exists

### CODE REVIEW

**Comment by matklad** [comment]
perfect, thanks!

bors r+

**Comment by lnicola** [comment]
After this, #1688 is still an issue. I don't know if it's new, but "go to definition" is now working on `std::vec!`, but not on `vec!`. The types are still not resolved.

**Comment by matklad** [comment]
Hm, I am seeing a cycle due to this in rust-lang/rust:

```
 0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   8: salsa::runtime::Runtime<DB>::report_unexpected_cycle
             at /home/matklad/projects/rust-analyzer/<::std::macros::panic macros>:4
   9: salsa::QueryTable<DB,Q>::get::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:475
  10: core::result::Result<T,E>::unwrap_or_else
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:766
  11: salsa::QueryTable<DB,Q>::get
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  12: <T as ra_hir::db::DefDatabase>::crate_def_map
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  13: ra_hir::nameres::collector::DefCollector<&DB>::import_all_macros_exported
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:191
  14: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:529
  15: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:491
  16: ra_hir::nameres::collector::DefCollector<&DB>::resolve_macros
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:470
  17: ra_hir::nameres::collector::DefCollector<&DB>::collect
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:114
  18: ra_hir::nameres::collector::collect_defs
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:45
  19: ra_hir::nameres::CrateDefMap::crate_def_map_query
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres.rs:255
  20: <ra_hir::db::CrateDefMapQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  21: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  22: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  23: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  24: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  25: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  26: salsa::QueryTable<DB,Q>::get
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  27: <T as ra_hir::db::DefDatabase>::crate_def_map
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  28: ra_hir::code_model::Crate::root_module
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/code_model.rs:66
  29: ra_hir::nameres::collector::collect_defs
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:24
  30: ra_hir::nameres::CrateDefMap::crate_def_map_query
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres.rs:255
  31: <ra_hir::db::CrateDefMapQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  32: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  33: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  34: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  35: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  36: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  37: salsa::QueryTable<DB,Q>::get
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  38: <T as ra_hir::db::DefDatabase>::crate_def_map
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  39: ra_hir::code_model::Crate::root_module
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/code_model.rs:66
  40: ra_hir::nameres::collector::collect_defs
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:24
  41: ra_hir::nameres::CrateDefMap::crate_def_map_query
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres.rs:255
  42: <ra_hir::db::CrateDefMapQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  43: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  44: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  45: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  46: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  47: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  48: salsa::QueryTable<DB,Q>::get
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  49: <T as ra_hir::db::DefDatabase>::crate_def_map
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  50: ra_hir::code_model::Crate::root_module
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/code_model.rs:66
  51: ra_hir::nameres::collector::collect_defs
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:24
  52: ra_hir::nameres::CrateDefMap::crate_def_map_query
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres.rs:255
  53: <ra_hir::db::CrateDefMapQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  54: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  55: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  56: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  57: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  58: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  59: salsa::QueryTable<DB,Q>::get
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  60: <T as ra_hir::db::DefDatabase>::crate_def_map
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  61: ra_hir::code_model::Crate::root_module
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/code_model.rs:66
  62: ra_hir::nameres::collector::collect_defs
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:24
  63: ra_hir::nameres::CrateDefMap::crate_def_map_query
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres.rs:255
  64: <ra_hir::db::CrateDefMapQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  65: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  66: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  67: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  68: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  69: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  70: salsa::QueryTable<DB,Q>::get
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  71: <T as ra_hir::db::DefDatabase>::crate_def_map
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  72: ra_hir::code_model::Crate::root_module
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/code_model.rs:66
  73: ra_hir::nameres::collector::collect_defs
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:24
  74: ra_hir::nameres::CrateDefMap::crate_def_map_query
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/nameres.rs:255
  75: <ra_hir::db::CrateDefMapQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  76: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  77: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  78: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  79: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  80: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  81: salsa::QueryTable<DB,Q>::get
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  82: <T as ra_hir::db::DefDatabase>::crate_def_map
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:84
  83: ra_hir::source_binder::module_from_source::{{closure}}
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/source_binder.rs:96
  84: core::iter::traits::iterator::Iterator::find_map::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1861
  85: core::iter::traits::iterator::Iterator::try_for_each::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1610
  86: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/adapters/mod.rs:582
  87: <core::slice::Iter<T> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/slice/mod.rs:3164
  88: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/adapters/mod.rs:582
  89: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1610
  90: core::iter::traits::iterator::Iterator::find_map
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1860
  91: ra_hir::source_binder::module_from_source
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/source_binder.rs:94
  92: ra_hir::source_binder::module_from_file_id
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/source_binder.rs:37
  93: ra_ide_api::diagnostics::diagnostics
             at crates/ra_ide_api/src/diagnostics.rs:92
  94: ra_ide_api::Analysis::diagnostics::{{closure}}
             at crates/ra_ide_api/src/lib.rs:525
  95: ra_db::CheckCanceled::catch_canceled::{{closure}}
             at /home/matklad/projects/rust-analyzer/crates/ra_db/src/lib.rs:39
  96: std::panicking::try::do_call
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:296
  97: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  98: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  99: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  100: ra_db::CheckCanceled::catch_canceled
```

**Comment by matklad** [comment]
fixed by https://github.com/rust-analyzer/rust-analyzer/pull/1787

**Pull request merged**
