### PR TITLE
Avoid hard install error if `code` isn't found

### PR DESCRIPTION
**Pull request by mqudsi**
Before doing anything else when installing the client extension, check
if `code` or `code.exe` even exists. If it isn't found, raise a warning
on stderr, but do not fail the install process.

This distinguishes between a failure to install the VS Code extension
when it exists but the installation process failed (e.g. `npm` doesn't
exist or VS Code reports the extension does not exist after it is
installed) from the much more innocuous error when `code` cannot be
found quite possibly because it was never even installed.

Given that `rust-analyzer` has plenty of system-wide use cases that do
not involve VS Code, this seems like it is more appropriate/graceful
handling of this particular case.

### CODE REVIEW

**Comment by lnicola** [comment]
Thank you for the PR, but considering that `cargo xtask --server` already exists, do you think this is useful?

One nit I have is that the Code executable isn't always called `code` (we also try `code-insiders`, `codium` and `code-oss`). I think we already print an inaccurate error message, but this PR introduces an extra one.

**Comment by matklad** [comment]
I think we should close this. To add to what @lnicola said, my personal experience tells me that, from the user experience point of view, it actually is preferable to try and fail, then to fail pre-flight check:

* pre-flight checks tend to get out of sync with the operation they are guarding
* by printing out the steps the thing tries, it becomes possible for the user to debug the problem by trying out the commands manually.

**Comment by mqudsi** [comment]
So I guess this could be chalked up to a question of semantics: as a user unfamiliar with the project but after reading the section of the manual [linked from the readme](https://rust-analyzer.github.io/manual.html#installation) just going with the conventions and standards in open source software, I did the `xtask` equivalent of `make && make install`.

I would expect the default install target for a project’s build system to install the primary binary and to exit with status code 0 of that were accomplished.  I wouldn’t expect a build command that does not contain `install` in its name (eg “server”) to modify or install anything outside of the build directory.

Given that no message is printed when the primary binary is installed and that the last message printed is an error due to the failure to install the extension integration, the end user would be either confused as to whether or not the binary was installed or under the incorrect impression that it wasn’t.

**Comment by mqudsi** [comment]
> pre-flight checks tend to get out of sync with the operation they are guarding

Note that no additional preflight check was added. Rather the command/step that *would* fail is carried out before all others to give it a chance to fail fast and early rather than after partial progress (which doesn’t fail) has been made.

**Comment by lnicola** [comment]
I filed a PR to clear things up a little, but I don't understand this remark:

>  I wouldn’t expect a build command that does not contain install in its name (eg “server”) to modify or install anything outside of the build directory.

The command you ran is `cargo xtask install`, so it does contain `install` in its name. But I agree, it's a bit different from the `./configure && make && make install` that Unix people will be used to. At least, the binaries are installed in per-user locations, not system-wide.

**Comment by mqudsi** [comment]
> The command you ran is `cargo xtask install`, so it does contain `install` in its name

Yes, but `cargo xtask --server` does not have "install" in its name :)

**Comment by lnicola** [comment]
That was a typo :-)

**Comment by mqudsi** [comment]
I previously misread almost the same thing you mistyped; my original reading was that the server alone is installed with `xtask server` and not `xtask install --server`!

**Pull request closed without merging**
