### PR TITLE
Fixed expr meta var after path colons in mbe

### LINKED ISSUE #7207: parser panic in weird macro expansion
```rust
macro_rules! m {
    ($k:expr) => {
        f(K::$k)
    }
}

fn main() {
    m!(C("0"));    
}
```

Panic : 

```
thread '<unnamed>' panicked at 'the parser seems stuck', crates/parser/src/parser.rs:51:9
stack backtrace:
   0: std::panicking::begin_panic
   1: parser::grammar::expressions::atom::atom_expr
   2: parser::grammar::expressions::expr_bp
   3: parser::grammar::expressions::stmt
   4: parser::grammar::fragments::macro_stmts
   5: parser::parse_fragment
   6: mbe::syntax_bridge::token_tree_to_syntax_node
   7: hir_expand::db::parse_macro_with_arg
   8: salsa::runtime::Runtime::execute_query_implementation
   9: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  10: salsa::derived::slot::Slot<Q,MP>::read
  11: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  12: <DB as hir_expand::db::AstDatabase>::parse_macro_expansion::__shim
  13: <DB as hir_expand::db::AstDatabase>::parse_macro_expansion
  14: hir_expand::db::parse_or_expand
  15: <DB as hir_expand::db::AstDatabase>::parse_or_expand
  16: hir_def::body::Expander::enter_expand
  17: hir_def::body::lower::ExprCollector::collect_macro_call
  18: hir_def::body::lower::ExprCollector::collect_stmt
  19: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  20: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  21: hir_def::body::lower::ExprCollector::collect_block
  22: hir_def::body::lower::ExprCollector::collect_expr
  23: hir_def::body::lower::lower
  24: hir_def::body::Body::body_with_source_map_query
  25: salsa::runtime::Runtime::execute_query_implementation
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::read
  28: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  29: <DB as hir_def::db::DefDatabase>::body_with_source_map::__shim
  30: hir::source_analyzer::SourceAnalyzer::new_for_body
  31: hir::semantics::SemanticsImpl::analyze_impl
  32: hir::semantics::SemanticsImpl::scope
  33: ide::inlay_hints::inlay_hints
  34: std::panicking::try
  35: ide::Analysis::inlay_hints
  36: rust_analyzer::handlers::handle_inlay_hints
  37: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by edwin0cheng**
Fixes #7207

Added `L_DOLLAR` in `ITEM_RECOVERY_SET` , but I don't know whether it is a good idea.

r? @matklad

### CODE REVIEW

**Comment by matklad** [comment]
Urgh, the sad thing is that I don't know it the idea is good neither :(

I think, if we do this, we should do that at `Parser::err_recover`, but, iirc, that fails as well.

cc https://github.com/rust-analyzer/rust-analyzer/pull/4680#issuecomment-641346748

**Comment by edwin0cheng** [comment]
I managed to move it inside `Parser::err_recover`, however the design problem you mentioned didn't resolved.

**Comment by edwin0cheng** [comment]
Just check , it seem to fix  #6100 too.

**Comment by matklad** [comment]
Ok, lets merge it. I don't think this is right, but the original code is also wrong, and this reduces the number of observable bugs. 

Long term, I'd love to move the parser to a separeate repo, with cleanly defined input-outpuf intertace. That would be the appropriate time to solve this in a principled way.

**Comment by edwin0cheng** [comment]
bors retry

**Pull request merged**
