### PR TITLE
fix: Don't try to resolve methods on unknown types

### LINKED ISSUE #10454: Unknown types implement all traits
image

### PR DESCRIPTION
**Pull request by flodiebold**
Fixes #10454, and some type mismatches.

### CODE REVIEW

**Comment by lnicola** [comment]
bors, I was just saying good things about you.

bors ping

**Comment by lnicola** [comment]
My finger is itching to click the merge button :sweat_smile:.

**Comment by jonas-schievink** [comment]
https://app.bors.tech/ has been down since today's GH outage about 4 hours ago

**Comment by lnicola** [comment]
CC @notriddle can you please click that "restart" button again? :smile:

**Comment by notriddle** [comment]
bors ping

**Comment by Veykril** [comment]
Thank you!
bors r+

**Comment by lnicola** [comment]
bors retry

**Pull request merged**
