### PR TITLE
Revert #2230

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by matklad** [comment]
cc @kjeremy 

At least, we tricked @killercup to improve error handing by using anyhow and contexts :)

**Comment by killercup** [comment]
Haha, and I haven't even looked what autoconf is even supposed to do

**Comment by kjeremy** [comment]
Haha im all for subterfuge and trickery. Was this causing issues or just incorrect?

**Pull request merged**
