### PR TITLE
Make module generation

### PR DESCRIPTION
**Pull request by Veykril**
I've been looking into generating the make module from the [ungrammar](https://github.com/rust-analyzer/ungrammar/blob/eb7e474d641fdb5210318479696cb7b362190cfd/rust.ungram) tree for the past days similar to how the other stuff is generated and I figured I could put a draft request here for now with my current progress. I managed to generate constructor functions for most things with the exception of [gen_syntax.rs#L773-L798](https://github.com/Veykril/rust-analyzer/blob/25c64519058f60560c2f6961654eea559a17a266/xtask/src/codegen/gen_syntax.rs#L773-L798) as these are a bit more(partially also too) complex to auto-generate.

I basically create one function per alternating rule meaning for `AssocTypeArg = NameRef (':' TypeBoundList | '=' Type)` we get two functions as there is one alternation in that rule. The problem here is that we can't really auto-generate different names for these two functions so there has to be some mapping from generated names to proper names, otherwise the function will just have the rule's name. The output for that rule currently is [make.rs#L210-L230](https://github.com/Veykril/rust-analyzer/blob/25c64519058f60560c2f6961654eea559a17a266/crates/syntax/src/ast/generated/make.rs#L210-L230).

Duplicate parameters will also just get a number appended to discern them. It would probably be beneficial to add the corresponding rule above the function as a doc comment as well. Also currently attributes are considered for all rules so most of them have `attr` parameters, not sure if they will be relevant or not though removing those is a quick fix.

There are a few things I still have to do assuming what I have here right now is in the right direction:
- the aforementioned name mapping
- rules like `OrPat = (Pat ('|' Pat)* '|'?)` currently generate in such a way that it is possible to generate an empty or-pattern since it only takes an iterator
- `Module = Attr* Visibility? 'mod' Name (ItemList | ';')` and a few others currently generate as two rules, though ideally this could be a single one with an optional `ItemList` parameter
- Add more comments to the general generator stuff
- support a few more of the things that aren't supported, namely stuff that have optional keywords in them like `Static` or `Const` items, though I am unsure in what way to support their generation for now

### CODE REVIEW

**Comment by matklad** [comment]
Yeah, I think this moves in the excitingly proper direction!

WDYT about merging a minimal thing first? Ie, something which generates just a couple of really simple make functions, without special cases? Then, we can add more stuff on top. 

> The problem here is that we can't really auto-generate different names for these two functions so there has to be some mapping from generated name

There's several ways we can spin this:

* in the code-generate, add some kind of mapping like `"AssocTypeArg": ["_with_bound", "_with_type"]`
* ungrammar allows labeling rules, so we can use this instead: `(bound:(':' TypeBoundList) | type:('=' Type))`
* we can just guess the labels? if there's only one node in alternative, then `_with_node_name` could work? 
* we can tweak the grammar itself. IE, we can add `AssocTypeValue` or somth like that.

**Comment by flodiebold** [comment]
> There's several ways we can spin this:

 - we could generate builders for such nodes instead? `make_assoc_type_arg(name_ref).with_type_bound_list(type_bound_list)`

**Comment by Veykril** [comment]
I'll see if I can minify it a bit more for now, though I don't think any of the complex cases are left in now.

The builder idea seems quite nice, especially cause it would get rid of all the attribute parameters thats are rarely needed. Though we do need to add some more labels then due to rules like `ArrayExpr = Attr* '[' Attr* Expr ';' Expr ']'`[rust.ungram#L388-L392](https://github.com/rust-analyzer/ungrammar/blob/master/rust.ungram#L388-L392) which currently creates
```rust
pub fn array_expr1(
    attr: impl IntoIterator<Item = ast::Attr>,
    attr1: impl IntoIterator<Item = ast::Attr>,
    expr: ast::Expr,
    expr1: ast::Expr,
) -> ast::ArrayExpr {
```
which would mean we would get two builder methods for each of the attributes.

One thing I do wonder about though is, the syntax trees that are being generated by this do not contain any spaces, so should we move over to this from the current manual impls we will have a lot of tests changing due to changes to their spacing. Will this be something to worry about at this point?

**Comment by matklad** [comment]
>Will this be something to worry about at this point?

not to much -- I think we should insert basic spaces (a-la `compute_ws` function in `join_lines`), but it is ok to regress spacing somewhat. 

>The builder idea seems quite nice, especially cause it would get rid of all the attribute parameters thats are rarely needed.

Swift provides both `make` and builder style API IIRC.

**Comment by matklad** [comment]
Closing due to inactivity. Though, having some kind of auto-generated API based on ungrammar would be cool, yeah!

**Pull request closed without merging**
