### PR TITLE
Use env_logger instead of flexi_logger

### PR DESCRIPTION
**Pull request by AlexanderEkdahl**
This fixes https://github.com/rust-analyzer/rust-analyzer/issues/2335

- By default only `error` will be printed. From what I can tell this matches the current behaviour. Configured through `RUST_LOG`.
- I looked through the optional dependencies for `env_logger`and I have only enabled `human_time`. Without this feature no timestamp will be shown for log messages.
- `RA_LOG_DIR` feature is removed

This PR adds 2 new dependencies(`env_logger` and `human_time`) and removes 6 dependencies.

### CODE REVIEW

**Comment by lnicola** [comment]
Hmm, I've used the log to file feature before to debug RA not working in a vim LSP client.

**Comment by AlexanderEkdahl** [comment]
That is unfortunate. I assume there isn't any workaround? 

I don't feel strongly about switching from flexi_logger to env_logger. I just picked up this work as it was marked `good first issue` and I wanted to get contribute to rust-analyzer and better understand how it works.

**Comment by matklad** [comment]
@lnicola can vim be configured to show `stderr` in a dedicated buffer? I feel that client-side capturing of stderr is the better approach than logging to dir (because it also works with `eprintln`), but if that's not feasible for some clients, sticking with flexi logger is an option

**Comment by lnicola** [comment]
The workaround might be to write our own logging sink. We could also redirect stderr to a file with dup2, apparently that also works on Windows, but doesn't feel very nice.

No worries, your contribution is appreciated, I was just musing a little.

**Comment by lnicola** [comment]
@matklad no idea, but it might depend on how the client is starting the server. Maybe we should just expect clients to handle this some way.

**Comment by matklad** [comment]
Well, if we are to write our logging sink, it's better to just stick with flexi logger :)

I think I am ready to bite the bullet here and claim that it's client's responsibility to intercept stderr of a server and make it available for the developer. That way, ecosystem as a whole becomes simpler and more flexible, as each server doesn't invent its own logging conventions

bors r+

**Pull request merged**
