### PR TITLE
internal: Replace `mocha` with a custom test runner

### LINKED ISSUE #10723: Drop mocha as testing framework
We currently have a couple of client-side test, using `vscode-test` and `mocha`. The latter seems popular, but looking over its dependency tree made me quite [uncomfortable](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/RFC.3A.20dropping.20client-side.20tests).

Let's try to implement simple a replacement for it, if possible.

### PR DESCRIPTION
**Pull request by lnicola**
Closes #10723

r? @Aloso

### CODE REVIEW

**Comment by lnicola** [comment]
The output looks like this:

image

image

I'm not sure about those empty newlines, they seem to be produced by `console.log`.

**Comment by bjorn3** [comment]
For errors can you include a stacktrace?

**Comment by Aloso** [comment]
LGTM

> I'm not sure about those empty newlines, they seem to be produced by console.log.

`console.log` only adds 1 line break. Something else is going on here, but since this is only a minor inconvenience, it isn't necessary to investigate.

**Comment by lnicola** [comment]
bors r=Aloso

Fun fact: this yields a -1030 line diffstat on `package-lock.json`.

**Pull request merged**
