### PR TITLE
Cache cargo-audit on CI

### LINKED ISSUE #3399: Cache cargo-audit on CI
We spend five minutes of CPU time on each CI building `cargo audit`.

I think we should:

* enable caching so that we don't rebuild it each time
* install it with `--debug`, so that we don't spend as much time building it
* maybe somehow only trigger it when `Cargo.lock` changes? 

The current setup is here:

https://github.com/rust-analyzer/rust-analyzer/blob/02f761ba4bd356ef2aeae5ed8bdd750c57ade30d/.github/workflows/ci.yaml#L11-L19

### PR DESCRIPTION
**Pull request by matklad**
closes #3399

bors r+
🤖

### CODE REVIEW

**Comment by bjorn3** [comment]
You need to change the permissions of `~/.cargo` to make it possible to restore the cache: https://github.com/actions/cache/issues/133#issuecomment-599102035. Otherwise the cache restore will silently fail.

**Comment by matklad** [comment]
oh my, I would have never figured that out, thanks @bjorn3 !

In one of your other comments you've said that it's possible to use `~.cargo/.crate2.json` as a cache key. is this really possible though? Like, the file gets created only *after* cargo install, so it would be impossible to get a cache hit?

**Comment by bjorn3** [comment]
I can't remember in what comment I said it, but you are probably right that using `~/.cargo/.crate2.json` as cache key won't work.

**Comment by matklad** [comment]
This one: https://github.com/bytecodealliance/wasmtime/pull/1314#discussion_r392613844

**Pull request merged**
