### PR TITLE
cargo update

### PR DESCRIPTION
**Pull request by kjeremy**

### CODE REVIEW

**Comment by matklad** [comment]
`BSD-2-Clause` license is missing. I think 2-clause is not exactly MIT-level free, no?

**Comment by lnicola** [comment]
Well, that was confusing. `BSD-2-Clause` is now gone from the license set and needs to be removed from `tidy.rs`.

**Comment by lnicola** [comment]
@kjeremy maybe you can also bump `expect-test`.

**Comment by kjeremy** [comment]
That's what I get for not running `cargo test`!

**Comment by matklad** [comment]
bors has your back :D

**Comment by matklad** [comment]
(more seriously, it is 100% OK to r+ pull requests without running tests locally and without waiting for tests to finish on CI. It is a feature of bors to reduce PR waiting times)

**Comment by kjeremy** [comment]
I think it's okay: https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_(%22Simplified_BSD_License%22_or_%22FreeBSD_License%22)

**Pull request merged**
