### PR TITLE
Remove one of the two different algorithms for name resolution of macros :D

### PR DESCRIPTION
**Pull request by matklad**
r? @edwin0cheng

### CODE REVIEW

**Comment by edwin0cheng** [comment]
Look good to me, except one little thing I want to clarify: 

If I understand correctly, A non-exported macro can only be used in the same mod. If it is defined with `#[macro_use], its parent and the parent's children can be used too. But all other crate can not be used in all situation without `#[macro_use]` attribute. Is it correctly? 

I didn't write that part of code, but if i understand that correctly, The `local_macro` is used for that situation. I would agree it should be a map with ModuleID, but i don't know should we remove it ?

**Comment by matklad** [comment]
>If I understand correctly, A non-exported macro can only be used in the same mod.

**Comment by matklad** [comment]
>If I understand correctly, A non-exported macro can only be used in the same mod.

It can be used in the same module or in it's children, that's true. And this is exactly the place where the current implementation is wrong, because, if we just macro to module's macro map, it will be invisible in children. And we also don't handle `#[macro_use]`.

>The local_macro is used for that situation.

The local macro was just a hack to make goto definition work for macros. `global_macro_scope` is what is used for actual name resolution, and it is still there, only `local_macros` are removed.

**Comment by edwin0cheng** [comment]
> It can be used in the same module or in it's children, that's true. And this is exactly the place where the current implementation is wrong, because, if we just macro to module's macro map, it will be invisible in children. And we also don't handle #[macro_use].

This is exactly why we don't want to put the local macro in the name resolution, if it is put in module's macro map, it can be used by other crate which is wrong. We only want to put global macro in name resolution. Or do i miss something?

**Comment by matklad** [comment]
>This is exactly why we don't want to put the local macro in the name resolution, if it is put in module's macro map, it can be used by other crate which is wrong

That's true, yeah. However, if we *don't* put it there, than macros inside expressions won't be resolved. So, between wrongly resolving macro in external crate, and wrongly not resolving a macro in an expression of the local crate, the second error (not resolving) seems more sever :)

**Pull request merged**
