### PR TITLE
Use hir formatter for hover text

### LINKED ISSUE #2765: Macro-expansion of `*mut T` is missing a space
Expanding `*mut T` from macro results in `*mutT`.

Screenshot from 2020-01-08 21-15-10

### LINKED ISSUE #4665: RA inserts "&mutself" for trait method stub, and missing space after `:`
I am working on an implementation of the `mir::visit::Visitor` trait in rustc, and to add a new method I started typing `fn visit_termin<tab>`. That got auto-completed as follows:
```rust
    fn visit_terminator(&mutself, terminator: &Terminator< 'tcx>, location:Location) {
        
    }
```
Notice the missing space in `&mutself`, and the missing space before `Location`.

### PR DESCRIPTION
**Pull request by oxalica**
Fix #2765 , (should) fix #4665

### CODE REVIEW

**Comment by matklad** [comment]
Hm, I am debating whether this is the right approach at this stage... The problem is, most of the code shouldn't even touch the AST,  as, long term, not all the things will have AST (see https://github.com/rust-analyzer/rust-analyzer/pull/7900#issuecomment-796654409).

**Comment by matklad** [comment]
What would it take to move hover from AST to hir?

**Comment by oxalica** [comment]
@matklad 
> What would it take to move hover from AST to hir?

`add_function_impl` actually takes a `hir::Function` parameter. It should not be complicated. And we already has `HirDisplay`.
There are many changes after the last time I step into the code related. I'll look into it later.

**Comment by oxalica** [comment]
It seems `hir::Function` doesn't save enough data for the signature. Like the `extern` ABI, form or self parameter and parameter names/pats are all missing. There is also no generic arguments or where predicates in `FunctionData` but I believe they should be somewhere else I missed.

https://github.com/rust-analyzer/rust-analyzer/blob/b885e6bdeeb1023df53b3f292cfe301448eeaeef/crates/hir_def/src/data.rs#L20-L33

Also, `HirDisplay` is currently defined in `hir_ty`, as dependency of `hir`. I don't think that's the correct place for the trait.

**Comment by matklad** [comment]
>form or self parameter and parameter names/pats are all missing. 

Yeah, this is tricky. We have `hir::Param` and `hir::SelfParam`, and those should grow additional methods to get that info. Note that, while getting the type of param could not fail, getting the patter should return an optional `ast`. Parameter patterns are not a part of function ABI, so hover code should be prepared to handle the cases where they are not there. 

So, something like this: 

```rust
impl hir::Param {
    fn patteren_source(&self, db) -> Option<ast::Pattern> {
        let fn_source = self.func.source(db)?;
    }
}
```

Generics you can get as `let generics = hir::GenericDef::Function(fun).params(ctx.sema.db);`. Again, a particular form of where clauses is not something we are guaranteed to know. 

The extern ABI I think is currently missing altogether. It should be added to  `item_tree::Function`, `FunctionData` and `hir::Function`

**Comment by oxalica** [comment]
It almost works now.

Note that due to the de-sugar, generic predicates are split-ed and all go to `where` part.
It may not exactly the same as the original syntax, but should has equal semantic.

**Comment by matklad** [comment]
Yeah, this is good, thanks for working of this @oxalica, that's an important building block for many things!

**Comment by lnicola** [comment]
changelog feature add HIR formatter infra and use it for hover text:

**Comment by lnicola** [comment]
image

**Pull request merged**
