### PR TITLE
Make incremental sync opt-in

### PR DESCRIPTION
**Pull request by lnicola**
@matklad do you want to merge this? I'd make it opt-out, but it's fine to test it more.

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

Yeah, let's make this opt-in, and next week switch it to opt-out if we fail to find the issue ourselves.

**Comment by edwin0cheng** [comment]
bors retry

**Comment by lnicola** [comment]
@matklad you should probably retrigger the nightly build.

**Comment by matklad** [comment]
Hm, I haven't seen panics after the utf16 fix, and I now have a hypothesis that that might actually be a real fix:

* I've wrote that the code I worked on when I hit the panic didn't contain non-ascii characters
* I also wrote that the moment we hit a panic is not necessary the moment the error happens
* And I do sometimes type Rust code in Кирилица, by accident

So let's hope that everything is fine. We'll know for sure later today :D We need to enjoy the last opportunities to break things. 

Though, we still need to revert the opt-in, and we also need to implement "iterrate every char" test for line index.

**Comment by lnicola** [comment]
There might still be a bug in the tracking of line index validity range. I can't check right now, but I think we invalidate the lines below the edited range. The UTF-16 character list for the current line might also become invalid. I'll fix that when enabling it again.

> And I do sometimes type Rust code in Кирилица, by accident

XD. That's why I prefer per-window, not global, IME config.

**Comment by matklad** [comment]
>XD. That's why I prefer per-window, not global, IME config.

Hm, I think I should try this out -- originally I disliked it, because I was always confused about which language I am using right now, as the tray indication would just change when flipping the windows. However as of couple of years ago, I am using a [custom layout](https://github.com/matklad/config/blob/master/home-row.xkb), which just doesn't work with the tray indicator, so I got used to not knowing which layout is active at the moment :D

**Pull request merged**
