### PR TITLE
minor: Fix metrics.json path

### PR DESCRIPTION
**Pull request by lnicola**
CC https://github.com/rust-analyzer/rust-analyzer/pull/11724#issuecomment-1069047929

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Looks correct, let's test it

bors r+

**Comment by lnicola** [comment]
I'm testing it too, but the analysis takes a really long time on `diesel`.

**Comment by lnicola** [comment]
Right, it crashed because I didn't have the environment variable.

**Comment by lnicola** [comment]
bors retry

**Comment by lnicola** [comment]
bors retry

**Comment by lnicola** [comment]
@matklad how do you feel about adding `Shell::append_file` and/or `Shell::make_path` (returning the `Shell` CWD + the given path) to `xshell`?

**Comment by matklad** [comment]
:+1: to both `append_file` and `.to_abs_path()`

**Pull request merged**
