### PR TITLE
WIP: Module name resolution

### PR DESCRIPTION
**Pull request by matklad**
work towards #231

### CODE REVIEW

**Comment by aochagavia** [comment]
Nice work! I didn't have time to tackle this earlier this week, but I enjoyed reading the PR.

**Comment by aochagavia** [comment]
Nice work! Are you planning to add tests as well? This seems quite tricky to get right...

**Comment by matklad** [comment]
>Nice work! Are you planning to add tests as well? This seems quite tricky to get right...

Not in this PR: this is covered by the completion tests atm. 

But yeah, we definitely should have nameres specific unit-tests. There's one in this PR for the start. We also should add a test which checks that we don't recompute item_map if user types inside function body.

**Comment by matklad** [comment]
The main problem is that we've got an ICE...

**Pull request merged**
