### PR TITLE
fix: Update download instructions

### LINKED ISSUE #8966: 2021-05-24 release is missing binaries
Hi!

Tried to update to the latest version, but had to realize that the newest release is missing un-gzipped binaries from its assets.
As such, the command listed in the docs (https://rust-analyzer.github.io/manual.html#rust-analyzer-language-server-binary), `curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux -o ~/.local/bin/rust-analyzer` does not work for installation as the link is a 404.

I don't know if it's a CI regression or it was missed manually, but would be good to either add those binaries back or update the docs with a new installation method.

Cheers

### PR DESCRIPTION
**Pull request by lnicola**
Closes #8966

### CODE REVIEW

**Comment by lnicola** [comment]
Oops.

**Comment by cschmatzler** [comment]
Your update definitely is more detailed and also updates the Mac instructions, so we should probably go with this one.
@matklad

**Comment by lnicola** [comment]
Updated.

bors r=cschmatzler

**Pull request merged**
