### PR TITLE
Highlight punctuation as `HighlightTag::Operator`

### LINKED ISSUE #4620: Highlight punctuation
Currently, bits of punctuation such as `(`, `)`, `{`, `}`, `[` and `]` aren’t highlighted. Additionally, `.` isn’t highlighted, when it should arguably be highlighted as an operator.

### PR DESCRIPTION
**Pull request by ltentrup**
Fixes #4620

### CODE REVIEW

**Comment by arzg** [comment]
It would be ideal if `HighlightTag` had a `Punctuation` variant, because not all punctuation is an `Operator`. Is there any way this could be added?

**Comment by matklad** [comment]
Hm, yeah, I agree that we should introduce `HighlightTag::Punctuation` in the IDE layer. Not sure what's the best way to lower in to lsp though. I guess, we should introduce top-level `punctuation` token type as well -- re-using operator for this seems wrong, and adding `operator.punctuation` seems backwards.

**Comment by ltentrup** [comment]
I've added a new `Punctuation` highlight tag and a corresponding lowering to a semantic token.
I've also noticed that with this PR nearly every character gets a proper highlight tag (one exception are parameters for macro calls). So one could probably remove the `Generic` highlight tag at some point.

**Comment by matklad** [comment]
bors r+

yeah, generic should be removed, does anything break if you do it?

**Comment by ltentrup** [comment]
@matklad as far as I can tell this is the only (non-whitespace) place where generic is used 

https://github.com/rust-analyzer/rust-analyzer/blob/b63e23e98e7dfbe57de93ebe256254825512e148/crates/ra_ide/test_data/highlight_doctest.html#L70

(the `foo` and `bar` in `assert!(foo.bar())`). This, however, seems to be a bug.
The only reason for having the generic tag was that not every character was given a tag, which itself was needed for the addition of the injection modifier in doctests.

**Pull request merged**
