### PR TITLE
Resolve attributes during name resolution

### PR DESCRIPTION
**Pull request by jonas-schievink**
Another step required to support procedural attribute macros. This will emit diagnostics when attributes can't be resolved to either a built-in attribute, or to something in macro namespace.

Procedural attribute macros refuse to expand, because they aren't yet fully implemented. Instead, they always get the unresolved-proc-macro diagnostic to let the user know.

Note that we *don't* yet ignore items with unresolved attributes on them. That's the next step required to support attribute macros.

**Notes for users**: This will result in false positive diagnostics when attributes are used that are consumed by procedural macros. The diagnostic can be disabled by adding `"unresolved-attribute"` to the `rust-analyzer.diagnostics.disabled` setting.

### CODE REVIEW

**Comment by flodiebold** [comment]
We should make a note about this in the next changelog to prevent at least a few of the inevitable bug reports 😬

**Comment by jonas-schievink** [comment]
Yeah, good idea. I've added a note to the PR description too.

**Comment by matklad** [comment]
> Procedural attribute macros refuse to expand, because they aren't yet fully implemented. Instead, they always get the unresolved-proc-macro diagnostic to let the user know.

Hm, this feels less than ideal.... Perhaps we should make this sub-diagnostic experemental?

**Comment by matklad** [comment]
other than that,  lgtm! (maybe only add `.iter` method to Attrs?)

**Comment by jonas-schievink** [comment]
> Hm, this feels less than ideal.... Perhaps we should make this sub-diagnostic experemental?

Yeah I can do that. unresolved-proc-macro is already meant to be unintrusive and easy to ignore though, so that users are *aware* that the macro is being ignored, without having red lines all over the place.

**Comment by jonas-schievink** [comment]
And this seems to result in false positives for derive helpers like `#[serde(rename = "edition")]`, seems like we need to register those... somewhere?

**Pull request closed without merging**
