### PR TITLE
Add unwrap_type assist

### PR DESCRIPTION
**Pull request by bnjjj**
I found this assist pretty useful

### CODE REVIEW

**Comment by lnicola** [comment]
changelog feature add "unwrap type" assist

**Comment by bnjjj** [comment]
@lnicola I'm not sure to understand what you means sorry :/

**Comment by lnicola** [comment]
@bnjjj no worries, I ~~have~~ had until 5 minutes ago some code that scrapes the GitHub PR pages to extract these comments and put things in their right place in the changelog.

**Comment by matklad** [comment]
I think that this use-case is better served by the more general expand selection infrastructure: 

Peek 2021-03-22 15-57

I wonder though, how do we teach users that this is possible? It took me some time to realize that this "select, copy, select more, paste" workflow is possible.

**Comment by bnjjj** [comment]
Is it also available in other editors than vscode ?

**Comment by matklad** [comment]
It should be, that's a standard protocol feature now: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_selectionRange

**Comment by bnjjj** [comment]
Oh ok. I don't know then :/ to be honest when I'm looking for something to help me I just flood my quick fix shortcut haha

**Comment by matklad** [comment]
Closing based on https://github.com/rust-analyzer/rust-analyzer/pull/8070#issuecomment-804041892

**Pull request closed without merging**
