### PR TITLE
Don't re-read open files from disk when reloading a workspace

### LINKED ISSUE #4263: Incremental text sync panics
```
            0ms - infer:wait (319 calls)
            2ms - parse_macro_query (64 calls)
thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /home/matklad/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:34:9
stack backtrace:
   21ms - handle_inlay_hints
       20ms - inlay_hints
            6ms - Semantics::analyze2 (307 calls)
            0ms - crate_def_map:wait (42 calls)
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: alloc::string::String::replace_range
  15: rust_analyzer::main_loop::apply_document_changes
  16: ra_vfs::Vfs::change_file_overlay
```

cc @lnicola, not sure how to repro this, but I've seen this a couple of times.

### LINKED ISSUE #5742: thread 'main' panicked at `assertion failed: self.is_char_boundary(n)'
```
~                                         │  122 thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libcore/macros/mod
~                                         │    1 stack backtrace:
~                                         │    2    0: backtrace::backtrace::libunwind::trace
~                                         │    3              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
~                                         │    4    1: backtrace::backtrace::trace_unsynchronized
~                                         │    5              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
~                                         │    6    2: std::sys_common::backtrace::_print_fmt
~                                         │    7              at src/libstd/sys_common/backtrace.rs:78
~                                         │    8    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
~                                         │    9              at src/libstd/sys_common/backtrace.rs:59
~                                         │   10    4: core::fmt::write
~                                         │   11              at src/libcore/fmt/mod.rs:1076
~                                         │   12    5: std::io::Write::write_fmt
~                                         │   13              at src/libstd/io/mod.rs:1537
~                                         │   14    6: std::sys_common::backtrace::_print
~                                         │   15              at src/libstd/sys_common/backtrace.rs:62
~                                         │   16    7: std::sys_common::backtrace::print
~                                         │   17              at src/libstd/sys_common/backtrace.rs:49
~                                         │   18
~                                         │   19 8: std::panicking::default_hook::{{closure}}
~                                         │   20              at src/libstd/panicking.rs:198
~                                         │   21    9: std::panicking::default_hook
~                                         │   22              at src/libstd/panicking.rs:218
~                                         │   23   10: std::panicking::rust_panic_with_hook
~                                         │   24              at src/libstd/panicking.rs:486
~                                         │   25   11: rust_begin_unwind
~                                         │   26              at src/libstd/panicking.rs:388
~                                         │   27   12: core::panicking::panic_fmt
~                                         │   28              at src/libcore/panicking.rs:101
~                                         │   29   13: core::panicking::panic
~                                         │   30
~                                         │   31              at src/libcore/panicking.rs:56
~                                         │   32   14: alloc::string::String::replace_range
~                                         │   33   15: rust_analyzer::lsp_utils::apply_document_changes
~                                         │   34
~                                         │   35  16: core::ops::function::FnOnce::call_once
~                                         │   36   17: rust_analyzer::dispatch::NotificationDispatcher::on
~                                         │   37   18: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
~                                         │   38

```

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #5742
Fixes #4263

or so I hope.

### CODE REVIEW

**Comment by kjeremy** [comment]
I THINK this is correct. Is there anyway we can add a test?

**Comment by lnicola** [comment]
I might be wrong, but I think the main loop has fewer, if any, tests because the interaction with the outside world is too complex.

**Comment by kjeremy** [comment]
Okay this makes sense to me!

bors r+

**Comment by matklad** [comment]
Good catch!

**Pull request merged**
