### PR TITLE
feat: Add go to type definition for struct fields within struct

### PR DESCRIPTION
**Pull request by lf-**
Example:

```rust
struct A;

struct B {
    a/*<- cursor*/: A,
}
```

Go to type definition used to not work on this position. It now goes to
`A` as expected.

### CODE REVIEW

**Comment by lf-** [comment]
By the way, for some reason, rustfmt on save or in general was not working on crates/ide/src/goto_type_definition.rs while I was working in there. No idea what was going on there. May be an existing bug, who knows.

**Comment by jonas-schievink** [comment]
Were you typing in the `match_ast!` macro? rustfmt doesn't format inside macros

**Comment by lf-** [comment]
> Were you typing in the `match_ast!` macro? rustfmt doesn't format inside macros

Nailed it, yes. I think I didn't notice. Nevermind.

**Comment by flodiebold** [comment]
> rustfmt doesn't format inside macros

It does in some, doesn't it? I guess they are hardcoded? :grimacing:

**Comment by jonas-schievink** [comment]
I think so, yeah

**Pull request merged**
