### PR TITLE
vscode extension: use esbuild instead of rollup.

### PR DESCRIPTION
**Pull request by yaymukund**
This shaves a couple seconds off our build & trims npm dependencies. I tested it using VSCode's "Install [Extension] from VSIX" option and it seems to work. Note that it changes the root of the package from `out/src/main → out/main`.

Fell out of the discussion in #9179

### CODE REVIEW

**Comment by lnicola** [comment]
> ` +24 −373`

<3

Just for my curiosity, what's `-S` for `npm run`? I couldn't find anything in the documentation.

**Comment by lnicola** [comment]
Tested, I can confirm the faster build and that the extension still works (which isn't always the case after this kind of change).

**Comment by yaymukund** [comment]
> Just for my curiosity, what's `-S` for `npm run`? I couldn't find anything in the documentation.

Good question! It's [the save command](https://github.com/npm/cli/blob/1a2159d3cf2513e77e728e7feeaa04ad150d3812/tap-snapshots/test/lib/utils/config/index.js.test.cjs#L112-L114). It [appears to be unnecessary past Node 5][so], but I added it before I knew what it was since the ['Bundling Extensions' guide recommends it][guide].

[so]: https://stackoverflow.com/a/58475949
[guide]: https://code.visualstudio.com/api/working-with-extensions/bundling-extension#run-esbuild

**Comment by matklad** [comment]
Seems that `-S` is just a typo then in the docs: unless I am missing something, it makes no sense in the given context. Let's remove it here (and might be a good idea to send a PR to upstream docs/examples)

**Comment by lnicola** [comment]
Yeah, `--save` makes less sense for `npm run`, doesn't it?

**Comment by matklad** [comment]
bors r+

:tada:

**Comment by yaymukund** [comment]
> Seems that `-S` is just a typo then in the docs: unless I am missing something, it makes no sense in the given context. Let's remove it here (and might be a good idea to send a PR to upstream docs/examples)

I *think* `npm run -S ...` is actually doing `npm -S run ...`, so the flag technically works. I wonder if they support node <= 5, but [I have opend the PR](https://github.com/microsoft/vscode-docs/pull/4745) and we can see what they say. I've removed it here.

**Comment by lnicola** [comment]
changelog internal (first contribution) switch from `rollup` to `esbuild`.

**Pull request merged**
