### PR TITLE
add assist to surround with block

### PR DESCRIPTION
**Pull request by bnjjj**
After browsing the features for Intellij Rust I found this kind of feature. It could be interesting when you want to surround expressions inside if block or something similar.

Anyway I think it could be also interesting as a starting point to an assist to create a new function from a selection.

Here is a preview:
surround_with_block

### CODE REVIEW

**Comment by CryZe** [comment]
Is this all that useful? Selecting the code and pressing the opening curly brace key basically does the same thing (though rustfmt would have to do the formatting afterwards).

**Comment by bnjjj** [comment]
Yes you are right, but maybe it could be interesting to implement "move to a function" with the same kind of code. And then it could be interesting to already have a review about the code already written here. Just a proposal.

**Comment by vertexclique** [comment]
I really like this personally, which will pave the way for extracting methods outside the scope or in the scope.

**Comment by matklad** [comment]
Hm, yeah, I think this doesn't really bring any benefits over just using editor's bulid-in functionality of surrounding selection on typing `{`. It can be said that it is a component of "ExctractMethod" refactoring, but it's just the very tip of an iceberg, so I don't think we should merge this as is.

**Comment by bnjjj** [comment]
Yes, I will try in the next weeks to make some experiments to create a function from this. For now I'm a little bit busy so I haven't enough time. I prefer to close it and reopen later when I have something better and more useful. Thanks for your time @matklad

**Pull request closed without merging**
