### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by jethrogb**
See rust-lang/rust#57858

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

We should remove this once we remove the last image file from the repo

**Comment by lnicola** [comment]
Looks like the only image is `editors/code/icon.png`.

**Comment by jethrogb** [comment]
> once we remove the last image file from the repo

Actually this image file got added quite recently.

**Comment by lnicola** [comment]
For some reason, bors didn't like this.

**Pull request merged**
