### PR TITLE
Try serde_path_to_error for LSP InitializeParams

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by matklad** [comment]
what the error looks like? (the easiest way to test that would be writing a test)

**Comment by lnicola** [comment]
Something like:

```
Failed to deserialize InitializeParams: capabilities.workspace.workspaceEdit.changeAnnotationSupport: invalid type: boolean `true`, expected struct ChangeAnnotationWorkspaceEditClientCapabilities; {\"processId\":169421,\"clientInfo\":{\"name\":\"Visual Studio Code\",\"version\":\"1.52.1\"},\"locale\":\"en-gb\",\"rootPath\"
```

But I'd rather not include this test because it depends on the specific behavior of `serde_path_to_error`.

**Comment by matklad** [comment]
Perfect, I meant exactly this -- looking at a single error message

bors r+

not sure why I didn't do this before though...

**Comment by kjeremy** [comment]
I didn't know this existed. Awesome.

**Pull request merged**
