### PR TITLE
Implement StatusBar

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by kjeremy** [comment]
Could we use `window/showMessage` instead and capture it on the ts side for custom display?

**Comment by matklad** [comment]
I guess this would technically work, but that would mean that we will be spamming the user with notifications, and I'd rather avoid that.

**Comment by kjeremy** [comment]
Makes sense. I wonder if we should propose a "persistent notification".

**Comment by matklad** [comment]
There's some discussion about this over there: https://github.com/microsoft/language-server-protocol/issues/511#issuecomment-652549272

**Comment by matklad** [comment]
Hm?

bors r+

**Pull request merged**
