### PR TITLE
Automatically detect rust library source file map 

### LINKED ISSUE #8619: Detect Rust library source file map automatically according to the current toolchain
Currently, I need to configure `rust-analyzer.debug.sourceFileMap` manually in order to step into some of the Rust source files. Could rust analyzer detect the source file map automatically according to the current toolchain? For example, if the current toolchain is the stable version, detect and map `/rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0` to `${env:HOME}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust`.

### PR DESCRIPTION
**Pull request by vsrs**
This PR adds a new possible `rust-analyzer.debug.sourceFileMap` value:
```json
{
    "rust-analyzer.debug.sourceFileMap": "auto"
}
```

I did not make it the default because it uses two shell calls (`rustc --print sysroot` and `rustc -V -v`). First one can be slow (https://github.com/rust-lang/rustup/issues/783)

Fixes #8619

### CODE REVIEW

**Comment by EFanZh** [comment]
I also found that there paths start with `/cargo/`, Like `/cargo/registry/src/github.com-1ecc6299db9ec823/`. Is it a good idea to map it to the user .cargo cache? Like `~/.cargo/`?

**Comment by vsrs** [comment]
> I also found that there are paths start with `/cargo/`, Like `/cargo/registry/src/github.com-1ecc6299db9ec823/`. Is it a good idea to map it to the user .cargo cache? Like `~/.cargo/`?

I suppose, these are dependencies, and all the necessary information should be in the compiled executable (or pdb on windows).

> Also, the `"auto"` value prevents user from adding custom source mappings.

This is intentional. Conflicts are possible if you automatically add a value to the existing source map. And it's easy to forget and then spend a lot of time trying to figure out the reason. Trust me, I've done that before :)

**Comment by EFanZh** [comment]
The `/cargo` dependencies are likely to be dependencies used by standard libraries.

For example, this command on my PC:

```
nm -Cl ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libstd-b1047a2788193be4.so | grep /cargo
```

shows many symbols that have paths start with `/cargo/`. This library is distributed with the Rust toolchain.

**Comment by matklad** [comment]
bors d+

The code looks OK to me, but I don't really understand the debugging domain at all )

**Pull request merged**
