### PR TITLE
show values of constants in hover

### LINKED ISSUE #8497: Feature: show values of constants
I would find it really cool and useful if RA could tell me the values of numeric constants. I don't need a super fancy evaluation, even just an MVP that handles math operators would be absolutely rad.

The thing I would love to use this for is for double checking the hex value of bit hacks I've done to generate the right value, e.g. `const TOP: usize = !0 & !(!0 >> 1);`. Currently I either have to tab out of my editor to stuff it into another rust project or the playground, or just hope I got it right.

### PR DESCRIPTION
**Pull request by HKalbasi**
Fix #8497
cc #8655

### CODE REVIEW

**Comment by lnicola** [comment]
Needs a rebase, but it's pretty mechanical.

**Comment by HKalbasi** [comment]
Rebased.

**Comment by lnicola** [comment]
image

image

**Pull request merged**
