### PR TITLE
Bump psm, console, indicatif

### PR DESCRIPTION
**Pull request by kjeremy**

### CODE REVIEW

**Comment by lnicola** [comment]
Looks like our builds have gotten quite slow :sweat_smile:.

**Comment by bjorn3** [comment]
The slowest job is 11min. I think it was just waiting to get started for a long time.

**Comment by kjeremy** [comment]
The repo checks are fast but bors has gotten pretty slow.

**Comment by matklad** [comment]
Yeah, we need to check that our recent great split of hir didn't inflate CI. For from-scratch builds, cratification should be a net negative. 

Also, I think we should get rid of indicatiff altogether, and do a very simple progress rendering manually (the code can be stolen from Cargo).

**Comment by lnicola** [comment]
`indicatif` only brings in `number_prefix` and `unicode-width`, so it's probably not hugely expensive.

**Comment by matklad** [comment]
It's still 1.3k lines of code by itself, and I've also spend couple of
hours figuring out it's API

**Pull request merged**
