### PR TITLE
vscode refactoring: use more laconic export snytax, split huge string literal

### PR DESCRIPTION
**Pull request by Veetaha**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

Btw, if you are into typescript programming, one super-important task would be to implement downloading of binary github releases. Basically, porting this things: https://github.com/fwcd/vscode-kotlin-ide/blob/master/src/serverDownloader.ts

**Comment by Veetaha** [comment]
Hmm, thank you for the pointer! I'll take it once I study the VSCode api and our existing codebase more thoroughly.

**Comment by Veetaha** [comment]
But, speaking about binary releases, I suppose these releases are not cross-platform, this would need more investigation anyhow...

**Comment by matklad** [comment]
we provide separate artifacts for each plarform: https://github.com/rust-analyzer/rust-analyzer/releases

We now only need to download the right one and store it into `ExtensionContext.storagePath`

**Comment by Veetaha** [comment]
@matklad Okay, got it. Say I am not a systems programming pro, but I suppose even within one OS there might be differences in binary interfaces of different processor architectures, or do you think having 3 binary artifacts would be enough to cover all users?

**Comment by matklad** [comment]
>might be differences in binary interfaces of different processor architectures,

By default, rust targets a pretty old CPU, so this shouldn't be the problem. Like, there are folks with desktop linux on arm, and they'll have to compile from source, but for the overwhelming majority of users this should just work, modulo bugs.

**Pull request merged**
