### PR TITLE
(DO NOT MERGE) fix: proc_macro_srv: temporary abi fix (rust-lang/rust#84717)

### PR DESCRIPTION
**Pull request by lnicola**
bors r+

### CODE REVIEW

**Comment by lnicola** [comment]
I think we need to wait for the `rustc` PR to hit stable before merging this.

**Comment by cynecx** [comment]
We might need this too: https://github.com/rust-lang/rust/commit/92b2894d313b5d514d077bf65560df29cda35d13

**Comment by TheRawMeatball** [comment]
Does this PR solve the issue yet? I tried manually merging this PR to use it, but it still resulted in the proc macro server crashing. Is there anything to make this work, at least on my own machine?

**Comment by lnicola** [comment]
We also need at least https://github.com/rust-analyzer/rust-analyzer/pull/9047#issuecomment-852134592.

**Comment by TheRawMeatball** [comment]
But that seems to already be a part of latest nightly? I'm trying to use the latest nightly as of right now, and thought merging this PR into master on my PC would work but apparently it doesn't.

**Comment by lnicola** [comment]
It's in the latest nightly compiler, but needs to be ported to that rust-analyzer PR.

**Comment by yotamofek** [comment]
https://github.com/yotamofek/rust-analyzer/commit/aeb7b183a2302af968f1110fb3cbd00c76a34974

I made this commit on top of @lnicola 's adaptations to be able to use rust-analyzer with the latest nightly, so putting this here in case it may save anyone a bit of time.

**Comment by lnicola** [comment]
Superseded by #9550

**Pull request closed without merging**
