### PR TITLE
Semantic Highlight: Add Callable modifier for variables

### PR DESCRIPTION
**Pull request by GrayJack**
This PR added the `HighlightModifier::Callable` variant and assigned it to variables and parameters that are fn pointers, closures and implements FnOnce trait.

This allows to colorize these variables/parameters when used in call expression.

### CODE REVIEW

**Comment by lnicola** [comment]
We should also add the modifier to `package.json` so it shows up in autocomplete.

**Comment by matklad** [comment]
Let's add a test for this here: https://github.com/rust-analyzer/rust-analyzer/blob/20d369a826e8f333cba1988325480a49a730f00e/crates/ide/src/syntax_highlighting/tests.rs#L96-L135

This might require adding an Fn lang item as well (see Copy in the same test)

**Comment by GrayJack** [comment]
@matklad 

Done!

**Comment by matklad** [comment]
bors r+

Thanks!

**Pull request merged**
