### PR TITLE
Completion context remove exact match method in favor of fields

### PR DESCRIPTION
**Pull request by JoshMcguigan**
This is a minor cleanup PR following #8008. It removes the `expected_name_and_type` method on completion context in favor of using the fields. 

I thought this method was used in more places, or else it may have just made sense to make this change directly in #8008 :shrug:

### CODE REVIEW

**Comment by lnicola** [comment]
changelog fixup #8008

**Comment by matklad** [comment]
@JoshMcguigan could you try to r+ yourself to see if premissions  are setup proprely?

**Comment by JoshMcguigan** [comment]
> @JoshMcguigan could you try to r+ yourself to see if premissions are setup proprely?

Yep, I was going to give it a shot, but for some reason there was a weird CI test failure caused by a mark not registering as being hit. I'll ask a follow up question in zulip, but otherwise this should be g2g.

bors r+

**Comment by JoshMcguigan** [comment]
Discussion of the flakey fail in CI: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/test.20marks.20flakey.3F/near/230346699

**Pull request merged**
