### PR TITLE
Handle divergence in type inference for blocks

### LINKED ISSUE #1944: Wrong type inference in if and match with return statement
```rust
fn foo(x: Option<i32>) {
    let _x = if let Some(y) = x {
        y
    } else {
        return;
    };
}
```

Here, `_x` is inferred as `()` instead of `i32`. Also works with `if x.is_some() { 3 } else { return; }`.

CC #1505, #1680, @SomeoneToIgnore.

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #1944.

The `infer_basics` test is failing, not sure what to do about it.

### CODE REVIEW

**Comment by flodiebold** [comment]
I think we also need to consider cases like `some_function(return)` or `if some_condition { return; } else { return; }`, and check what rustc does with them -- I think it considers them diverging as well, though I don't know whether it gives them type `!`. (These may seem useless, but `some_function(unimplemented!())` or `if some_condition { panic!() } else { return; }` aren't...)

**Comment by flodiebold** [comment]
The `infer_basics` failure is probably fine, though as mentioned I'd still want to check what rustc does for this.

**Comment by lnicola** [comment]
I'm not sure how to check. `rustc` says that the function returns `()`, but that's the declared type, while our test shows the type of the block that makes up the function's body.

**Comment by lnicola** [comment]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=dfb2c41af9af50a8d6ba4c74bdfc9288

I think it's also `!` in `rustc`?

**Comment by flodiebold** [comment]
Yeah, but in a more roundabout way: If the block diverges, rustc [does not treat the missing tail expression as `()`](https://github.com/rust-lang/rust/blob/f2023ac599c38a59f86552089e6791c5a73412d3/src/librustc_typeck/check/mod.rs#L4049). And if there are no returns/breaks in the block and no provided type, that means it gets typed as `!`.

In general, I think we do need to track divergence separately from the type of the expression, similar to rustc, because e.g. for `let x = SomeStruct { field: unimplemented!() }` we wouldn't want to say `x: !`. None the less, I think this change goes in the right direction for that, so let's merge it :slightly_smiling_face: 

bors r+

**Comment by lnicola** [comment]
> e.g. for let x = SomeStruct { field: unimplemented!() } we wouldn't want to say x: !

That actually works because the code is only checking for `!` on statements, not bindings.

**Comment by flodiebold** [comment]
Well yeah, it still works, but we _should_ actually be checking for divergence inside expressions. For example [this type checks](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=de451556d053352e5385ceb3fab3c3ee):
```rust
fn test() -> i128 {
    foo(unimplemented!());
}

fn bar() -> i128 {
    Struct { field: unimplemented!() };
}
```
So we do need to recognize that `Struct { field: unimplemented!() }` diverges, but we _don't_ want to give it type `!`. So we need to track divergence separately from the type.

**Pull request merged**
