### PR TITLE
Add type to ParameterInformation label

### LINKED ISSUE #960: Signature Info parameter should be the entire range
When responding to the LSP's `SignatureHelp` request we only fill the `ParameterInformation` label for the name of the parameter. Most other language servers respond with everything between commas and parenthensis.

For instance with the following function:
```rust
fn foo(first: i32, second: i32) {}
```

We send back for the parameter labels: `first` and `second` when we should really be sending back `first: i32` and `second: i32` to match other language servers.

This is all handled in call_info.rs and would be a good first issue. It may be just as easy to implement #296 at the same time or as a follow on.

### PR DESCRIPTION
**Pull request by vipentti**
Fixes #960

### CODE REVIEW

**Comment by kjeremy** [comment]
The parameter label has to be a substring of the function signature. We should probably guarantee that with a test or something.

**Comment by matklad** [comment]
Ah, indeed, there's this weird quirk of the API... 

I am not too happy with the API LSP imposes on us here. VS Code works by highlighting a range for parameter in the complete function signature, but there are other possible implementations.

For example, IntelliJ just shows text/type/docstring of the parameter (which works better, because signatures might be huuge)

**Comment by vipentti** [comment]
If that's the case, then I guess implementing #296 together with this seems to be a good solution.

**Comment by matklad** [comment]
So, what about using strings for parametes in `CallInfo` and instead synthesizing a label in the `conv` layer, by concatinating parameter signatures?

**Comment by matklad** [comment]
>If that's the case, then I guess implementing #296 together with this seems to be a good solution.

I don't think we should use offsets internally: this looks like a strictly UI-concern, which probably shouldn't be exposed by the protocol at all.

**Comment by vipentti** [comment]
> The parameter label has to be a substring of the function signature. We should probably guarantee that with a test or something.

Does the parameter label have to be an *exact* substring of the signature ? With whitespace included ? 

Currently our function signatures are created using `completion::function_label` which, I believe, preserves all the original whitespace and formatting. Meaning if the original function had some strange formatting with regards to whitespace in the parameters list, the labels might not match exactly.

**Comment by vipentti** [comment]
Actually, is there a reason we couldn't just do 
```rust
res.extend(param_list.params().map(|param| { param.syntax().text().to_string() }))
```

**Comment by matklad** [comment]
I mean, "parameters must be a substring of a label" is a pretty arbitrary constrained, we should not try to maintain it in `Analysis`. Instead, we should enforce it at the `conv` layer, and the easiest thigs to do that is by just recreating label from the list of parameters, like in the ^^

**Comment by kjeremy** [comment]
@vipentti See https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp

**Comment by kjeremy** [comment]
Not only is the API a little weird but there are interactions between signature help and completions that have caused numerous bug reports for vscode and other servers. `completion::function_label` was a way of unifying the display between this feature and completion but maybe it does make more sense to do it in `conv` for the LSP. We already convert `Documentation` to `Documentation::MarkupContent` there for call info and completion.

**Comment by vipentti** [comment]
Doing it in `conv` would require us to implement some sort of `display` for functions ? Currently via `completion::function_label` we get the full signature including generic parameters and where clauses

**Comment by vipentti** [comment]
Closed in favor of #1110 which fixes this as well.

**Pull request closed without merging**
