### PR TITLE
Adding a snap yaml to rust-analyzer

### PR DESCRIPTION
**Pull request by lightyear15**
Is anyone interested in having a snap of it?

### CODE REVIEW

**Comment by bjorn3** [comment]
I am curious why using a snap would have any benefit. rust-analyzer is a single file executable, so it doesn't have the advantage of easier distribution. It also can't be isolated without making `cargo check` fail when any build script depends on a library not installed within the snap container and without preventing access to the project files if they are stored in a non-standard location.

**Comment by lightyear15** [comment]
> I am curious why using a snap would have any benefit. rust-analyzer is a single file executable, so it doesn't have the advantage of easier distribution. It also can't be isolated without making `cargo check` fail when any build script depends on a library not installed within the snap container and without preventing access to the project files if they are stored in a non-standard location.

The benefit is given by snap, continuously checking for new versions, building them for whatever platforms you tell to, and pushing them to proper release channel.
Regarding ``cargo``: it is true that the snap image will not be up-to-date with the last ``cargo`` version, as the ``cargo`` package is pulled using ubuntu package manager ``apt``, yet I'd say it won't create any problem for users. If ``rust-analyzer`` needs features from latest ``cargo`` and ``apt`` is falling behind, well rust-analyzer won't simply compile for a while, and we'll have to wait for ``apt`` guys to update their version of ``cargo``.
Regarding projects in non-standard location: true as well. Yet if we want a strictly confined snap, there is no other choice.

**Comment by killercup** [comment]
FYI: rust-analyzer is gonna be installable by the next version rustup, which is already available as a snap AFAIK.

**Comment by lightyear15** [comment]
> FYI: rust-analyzer is gonna be installable by the next version rustup, which is already available as a snap AFAIK.

Great, although, the rustup snap is experimental.

**Comment by matklad** [comment]
Our general approach is that we only ship GitHub & rustup releases, to keep maintenance burden as low as possible. Anyone is encouraged to package rust-analyzer for any distribution however.

**Pull request closed without merging**
