### PR TITLE
Fix retrieval of the Fn traits

### PR DESCRIPTION
**Pull request by flodiebold**
I used the wrong query, so it only used the lang items from the respective
crate...

### CODE REVIEW

**Comment by lnicola** [comment]
```
Expressions of unknown type: 9542 (11%)
Expressions of partially unknown type: 4169 (5%)
```

**Comment by flodiebold** [comment]
More importantly, `Some(foo).map(|x| x.)` now gives proper completions :slightly_smiling_face:

**Comment by matklad** [comment]
@flodiebold, you 🤘

**Comment by marcogroppo** [comment]
> I used the wrong query, so it only used the lang items from the respective
> crate...

ooops, naming could have been better from the start, sorry :) (super excited about the recent changes, the completions are getting better and better!)

**Pull request merged**
