### PR TITLE
Use a simple progress bar instead of indicatif

### PR DESCRIPTION
**Pull request by edwin0cheng**
pb

### CODE REVIEW

**Comment by matklad** [comment]
Let's make this even simpler and replace the actual progress bar and percentage with a true counter `n / total`?

**Comment by edwin0cheng** [comment]
without backspace ?

**Comment by edwin0cheng** [comment]
pr

**Comment by edwin0cheng** [comment]
Around 50 lines of code is handling cursor movement. Of course if we don't handle any cursor movement, it can be much simpler. I don't have any strong opinion about it.

**Comment by matklad** [comment]
Looks perfect now, thanks!

bors r+

**Comment by edwin0cheng** [comment]
bors retry

**Comment by edwin0cheng** [comment]
bors r=maklad

**Pull request merged**
