### PR TITLE
Move `smol_str` into `rust-analyzer`

### PR DESCRIPTION
**Pull request by Veykril**

### CODE REVIEW

**Comment by bjorn3** [comment]
It looks like fb8cf90cd5775bdea25bfc6e721beb6f02829e1c only deletes files and doesn't move them.

**Comment by Veykril** [comment]
Hmm

**Comment by Veykril** [comment]
Ah nvm I know what went wrong

**Comment by Veykril** [comment]
Closing this for now since we'll try to move the repo first and think about the other repos later.

**Pull request closed without merging**
