### PR TITLE
Drop larlpop-intern dependency

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by matklad** [comment]
yay!

bors r+

**Comment by lnicola** [comment]
Note that I'm not sure if this is doing the right thing -- is every identifier a type alias, and is that the right id to use? But `name` doesn't seem to be used yet, so it might not matter for now.

**Comment by matklad** [comment]
Yeah, I think this is fine for now. The important thing is to get rid of broken (due to wrong sync bound) interner

**Comment by flodiebold** [comment]
I think it might be wrong if it was still used, but I'm not sure that it actually *is* used in chalk anymore...

**Comment by matklad** [comment]
To be absolutely clear, the *real* reasoning I use is "does it pass the tests"  :D

**Comment by flodiebold** [comment]
Yeah, it's actually just used for debugging in the chalk integration tests... we could even just make it `()` :smile:

**Pull request merged**
