### PR TITLE
Add proc_macro crate for the 1.56 ABI

### LINKED ISSUE #9795: proc-macro panicked: called `Rust::unwrap()` on an `Err` value: ParseFloatError
Hello rust-analyzer team! First of all, thank you for the work that you do here. I don't wanna waste your time so I'll cut right to the chase. I am getting the error ``proc macro returned error: proc-macro panicked: called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Invalid }`` on the following code:

```rs
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
pub struct Config {
	pub name: String,
	pub school_level: String,
	pub school_type: String,
}
```

This error is highlighted on the whole struct as well as the attribute. Below is some more information:

Name of the file: `conf.rs`.
File link: [gleich/kiwi/src/conf.rs](https://github.com/gleich/kiwi/blob/main/src/conf.rs)
Repo link: https://github.com/gleich/kiwi
Rust version: rustc 1.54.0 (a178d0322 2021-07-26)
RA version: 950efff5c 2021-08-05 nightly (tried with RA stable)

Because this error is a rust-analyzer problem running `cargo check` or `cargo build` doesn't have this error.

### PR DESCRIPTION
**Pull request by alexjg**
I've copied the latest proc macro source from Rust nightly and modified it to compile on `stable`. This fixes #9795 . Almost everything here is uninteresting copy and paste, the interesting stuff is in `crates/proc_macro_srv/src/abis/mod.rs`. I've left the 1.55 ABI implementation in for now. We did discuss only supporting one nightly ABI so we may want to remove 1.55. That will break code which is pinned to older nightly releases but that seems acceptable to me, what do people think?

### CODE REVIEW

**Comment by lnicola** [comment]
You might need to run `cargo fmt` or something.

> We did discuss only supporting one nightly ABI so we may want to remove 1.55.

I think we can keep three versions (stable, beta, nightly). Technically, 1.55 is beta, right?

**Comment by alexjg** [comment]
Yup, forgot to run the `tidy` tests. Have force pushed.

Three versions sounds good, I'll leave 1.55 in then, this should be good to go.

**Comment by lnicola** [comment]
Thanks for taking care of this!

bors r+

**Comment by lnicola** [comment]
changelog feat add support for the 1.56 nightly proc macro ABI

**Pull request merged**
