### PR TITLE
Completely remove cargo audit

My current feeling is that the build maintenance friction it creates
is not proportional to the benefits it provides.

We are pretty frugal with the set of Rust dependencies, and our
security model is we

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by Veetaha** [comment]
What friction does it add? Bors doesn't gate by audit jobs, it can be `continue-on-error: true`

**Comment by matklad** [comment]
I think I've spend at least an hour of my time dealing with audit.

**Comment by flodiebold** [comment]
There's something weird happening with your PR titles by the way, in my email client it looks like:

> Completely remove cargo audit=0A=0AMy current feeling is that the build maintenance friction it creates=0Ais not proportional to the benefits it provides.=0A=0AWe are pretty frugal with the set of Rust dependencies, and our=0Asecurity model is we

**Comment by matklad** [comment]
Yup, fallout from switching to gh tool, should be fixed with https://github.com/matklad/config/commit/7afeb6696eea4f72d50886c90efd30e89ef4bec7

**Pull request merged**
