### PR TITLE
switch to rustc_lexer crate

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by est31** [comment]
Btw why did you publish a new crate instead of using https://crates.io/crates/rustc-ap-rustc_lexer ?

**Comment by matklad** [comment]
I actually haven't considered using ap crate... But, ideally, I'd prefer to have somewhat stableish API here with proper semver.

**Comment by est31** [comment]
@matklad let's talk over in #3843

**Pull request merged**
