### PR TITLE
fix: Don't load auxiliary crates outside the workspace

### PR DESCRIPTION
**Pull request by jonas-schievink**
I'm a bit unsure about this change since this might have unanticipated consequences, but this does fix https://github.com/rust-analyzer/rust-analyzer/issues/11300.

### CODE REVIEW

**Comment by lnicola** [comment]
This sounds quite reasonable. Since we're at the beginning of the week, we could merge it and see what breaks.

**Comment by huntc** [comment]
Sounds good to me.

**Comment by jonas-schievink** [comment]
Yeah, let's try it.

bors r+

**Comment by huntc** [comment]
Thank you!

**Comment by huntc** [comment]
This fix seems to have done the trick for me. RA appears to behaving optimally on my project now given today's nightly. Thanks so much for your efforts.

**Pull request merged**
