### PR TITLE
Add support for include_bytes!

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by lnicola** [comment]
Can you also tick these in https://github.com/rust-analyzer/rust-analyzer/issues/2212#issue-520906460?

**Comment by edwin0cheng** [comment]
Sure, I will update it tmr.

**Comment by lnicola** [comment]
Um, is it 3 AM there?

**Comment by edwin0cheng** [comment]
Yeah, And Im in Karaoke now lol

**Pull request merged**
