### PR TITLE
fix: Use objects instead of bools for markers in package.json

### PR DESCRIPTION
**Pull request by lnicola**
Addresses https://github.com/rust-analyzer/rust-analyzer/issues/9174#issue-913980665.

### CODE REVIEW

**Comment by lnicola** [comment]
bors retry

**Comment by matklad** [comment]
One thing to check here is whether code tries to auto-complete these in settings. I have vague recollection that I deliberately chose something wrong here...

**Comment by lnicola** [comment]
Do you mean when it's installed? They shouldn't be there, so does it matter?

**Comment by matklad** [comment]
Right, it does seem that I am talking nonsense! :-)

**Pull request merged**
