### PR TITLE
docs(README): improve installatin instructions

### PR DESCRIPTION
**Pull request by WofWca**
`git clone ...` -> ~~`git clone --depth 1 ...`~~ `git clone --single-branch -b master ...`

### CODE REVIEW

**Comment by lnicola** [comment]
I remember there were some downsides of shallow clones, like being heavier on the server when pushing. That might matter for users who are trying to contribute, but maybe not so much.

**Comment by matklad** [comment]
Yeah, I think a shallow clone will be net negative if you factor in upgrades. I wonder if 35 megabytes of history is reasonable though... have we accidentally committed blobs to the repo at some point? Might be interesting to check what are the largest git objects.

**Comment by lnicola** [comment]
A fresh bare clone is 44 MB for me, out of which `.git` is 38 MB. Running `git gc --aggressive` squeezes it down to 24/18 MB. As for the large objects:

```
All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file.
size   SHA                                       location
13232  5f6678e00ce83f25127900b3e094ae92e285e77e  search-index.js
3221   eb7b536895f69c18b387cf19d0b38bfdf1822970  search-index.js
1603   90ba7c4552db3d97aca6d27215cf4336ee8c07c7  search-index.js
1036   132ee1c4f11374c0ed8029b837e61cc82ce64371  search-index.js
669    0a7a70a6faa72ac32148a30377277914bc47f3fc  src/ra_syntax/ast/generated.rs.html
529    c6e91851bbaf888550b797d9477a67b3867fb356  search-index.js
414    3494537be9ed95c5dfad199f98dfbaf177db11fe  api-docs/search-index.js
335    ae85f03266ce1b61551fb5747f4c80f07bf5f1f6  search-index.js
297    88107e846f2a568c12cd696cdc3cf9597443ce26  api-docs/src/ra_hir/ty/infer.rs.html
240    b530891db97eccf9e9080e54c01b41e5b416d0b9  api-docs/ra_syntax/struct.SmolStr.html
218    33363048282d710315f8031916e08493b07f2278  api-docs/ra_syntax/ast/trait.AstNode.html
214    bc8714386b2e66bcf881814f6c83a6f3ca06005d  api-docs/ra_syntax/enum.TokenAtOffset.html
203    b9d03ce6204dde9eaba38249da1c858bb5b20981  api-docs/ra_syntax/ast/struct.AstChildren.html
201    6fcc1646e1b139f2cd64c0c8c655626474d6b396  api-docs/ra_syntax/ast/struct.CommentIter.html
182    7d742c5fb7d4597ae140f8418f52ffe03dc75343  api-docs/FiraSans-Medium.woff
178    d8e0363f4e1a000568d782653291e14c66ee3485  api-docs/FiraSans-Regular.woff
176    a54dfb1c09c896f3529fd7f5afdbae485129c8d7  search-index.js
153    aee89427b9f120800030e058f28d100389a87615  api-docs/src/ra_hir/ty.rs.html
144    7ab4b8d47d35c719ed7bb8a7493a2c255c0272a2  implementors/core/marker/trait.Unpin.js
141    deb4dea88bb6f513f957a49e333779b4c16718e3  crates/ra_syntax/src/ast/generated.rs
129    e72712e1337ca75153bf0fde33ff8b0907f3c937  search-index.js
123    c51b4caa4f19407deb919244c4f67470e00517c5  crates/ra_syntax/src/ast/generated.rs
121    3260cc58964400295b8497d65bb8bcc95c31cb9a  crates/ra_syntax/test_data/parser/ok/0035_weird_exprs.txt
118    1c9a815d89b6891f9e3290403d09c45c8af228df  code/package-lock.json
113    097b8d6ba4413e5c46523e21e5082c9bebed6583  api-docs/ra_hir/mock/struct.MockDatabase.html
106    35504da939116b9b00a88dc2de5484fa92c71e65  Cargo.lock
99     408449fd6f7e5b4fd2434980077d2bd49d88da99  crates/ra_syntax/src/ast/generated.rs
98     ee013bd6fe2327c27b5e625131529e4cbddcdc2e  search-index.js
94     2ce0039b10567368f35c077afcee9d4be0ededa4  crates/ra_hir/src/ty/tests.rs
92     38fba8d16801f3c93b4fcb19aa0886940a932359  api-docs/ra_parser/enum.SyntaxKind.html
```

**Comment by lnicola** [comment]
That's the `gh-pages` branch, could easy to get rid of.

**Comment by lnicola** [comment]
@WofWca Can you update this to specify `git clone --single-branch -b master git@github.com:rust-analyzer/rust-analyzer` instead? It's 12 MB.

```
127   bf056131efc4409ffc3880ba1e923f3b5caba1c3  crates/ra_syntax/src/ast/generated.rs
118   1c9a815d89b6891f9e3290403d09c45c8af228df  code/package-lock.json
106   20932a8378a03ce4190c15ade9b6c2330a743877  crates/ra_syntax/tests/data/parser/ok/0035_weird_exprs.txt
96    90480b6ca5f21db8dde64db80228ffffe416586c  crates/ra_syntax/src/ast/generated.rs
88    5e96ab1421ef0c0c8a89d39415b2736c0ca85de0  crates/ra_syntax/src/ast/generated.rs
84    1bd677cab755373512195f705bde498b8437384f  crates/ra_hir/src/ty/tests.rs
81    c4bddde85d00de59351bd24bd85ea35ae1dd8004  crates/ra_hir/src/ty/tests.rs
59    fcf8a1dbb091472caa429a48510d4a5bd671a507  crates/ra_hir/src/ty.rs
56    815c97483ff9c2017631f5c81ca9e10131eb7d9f  Cargo.lock
56    e51fd4a7aaddc3129f2d060e5bbac3862c51a2ab  Cargo.lock
55    a239f0630de4a9e8673badd1d8bba7152a8c6367  crates/libsyntax2/src/ast/generated.rs
50    7c7e825fdb891591ecf323a9fb7537b87795d9fa  crates/ra_hir/src/ty/.tests.rs.pending-snap
44    c7d409e6d67df123b2928ec3a0cd359f384c592a  crates/ra_hir/src/ty/tests.rs
43    13080b5aa6a5453b46a2940677c7d98bf946173c  crates/ra_hir/src/ty/infer.rs
40    c487bbbd482c1b029c560b9ee710adb4be377403  crates/ra_mbe/src/tests.rs
39    e4507c553ac78d9d0f2fde02cf33e259e3559929  crates/ra_syntax/tests/data/parser/ok/0035_weird_exprs.txt
35    d473478a9100daa7df7b4bc3675180f8ad91638c  crates/ra_syntax/src/ast/generated.rs
33    f77795d056c953b3c40fd22cb14619e94a6351a4  crates/ra_syntax/src/ast/generated.rs
32    07cc3e0dba3737b4b72684484210acb1f6e028b3  crates/ra_syntax/src/ast/generated.rs
32    2e4a489a0df23faa0a747e4f50aac2c9cc7e0178  crates/ra_hir/src/ty/infer.rs
32    db337735725d1efea691d44cd98b332b96ffff01  crates/ra_hir/src/ty/infer.rs
32    f3f1c25a9c5cfedb6a81b59e8fafb7c48bd95e1d  crates/ra_syntax/tests/data/parser/ok/0031_extern.txt
31    abbe4c154242305f3af19020d44757c81fc6987a  docs/dev/guide.md
31    4ebd44d271f429b8c5f514f5302681914d2b6cb5  crates/ra_hir/src/ty.rs
30    a3df0882783653533416c1fe0d0613c31599dd04  crates/ra_hir/src/ty.rs
29    420d9090c2f5e759f3c854e2c5a9b888c973e9c9  crates/ra_syntax/src/ast/generated.rs
29    8cf3222f76a740e9ec5b21298eb209509a107c7b  crates/ra_syntax/src/ast/generated.rs
29    9ba775e1c332f732574b3cb15baea0e2c4bf041d  crates/ra_syntax/src/ast/generated.rs
29    3878c99a86d9b5ce3f1e05c2f0e4952a213a572b  crates/ra_syntax/src/ast/generated.rs
29    4735256b4b7ffa3008ed010b943eb99e1c5f526f  crates/ra_hir/src/code_model.rs
```

**Comment by matklad** [comment]
Bingo @lnicola ! Yeah, looks like pushing pages docs to this repo is not a good idea. I wonder if we could/should move docs to the rust-analyzer.github.io repository?

**Comment by lnicola** [comment]
Having them in another repo sounds reasonable, I think.

**Comment by matklad** [comment]
I think https://github.com/rust-analyzer/rust-analyzer/pull/1956 should help quite a bit with the repo size

**Comment by WofWca** [comment]
> `git@github.com:rust-analyzer/rust-analyzer`

As far as I can tell, authorization is required for this, so I left it as `https`.

**Comment by matklad** [comment]
I wonder if this still makes sense after #1956, as the gh-pages branch is only one commit anyway now, and we don't have any significant other branches.

**Comment by matklad** [comment]
I believe that it should be OK now, and that we shouldn't microoptimize this further!

Thanks @WofWca for noticing that the repo is large and @lnicola for finding the root cause!

**Pull request closed without merging**
