### PR TITLE
Fix remaining references to `cargo xtask codegen`

### PR DESCRIPTION
**Pull request by Veykril**

### CODE REVIEW

**Comment by Veykril** [comment]
`cargo test -p xtask` replaced `cargo xtask codegen` now right? @matklad

**Comment by matklad** [comment]
Yup!

Ideally, we'd move codegen to respective crates, such that it's just `cargo t -p assists` for assits.  That, however, doesn't work for docs, which we generate, but don't commit to the repository.

**Comment by matklad** [comment]
Might be good idea to add "the file has been updated, simply re-run the tests" to the error message as well.

**Comment by matklad** [comment]
r=me

**Comment by Veykril** [comment]
I wonder if this works
bors r-
bors r=matklad

**Pull request merged**
