### PR TITLE
Specify working chalk revisions in manifest

### PR DESCRIPTION
**Pull request by lnicola**
CC #2067.

### CODE REVIEW

**Comment by matklad** [comment]
I'd rather stick with the current Cargo.lock forkflow. 

Chalk doesn't have a stable API yet, so we should optimize for using unstable API as conveniently as possible and updating early, rather than for pinning a specific version.

**Comment by lnicola** [comment]
But bumping the revision in `Cargo.toml` from time to time is less effort than answering issues like #2038, #2019 and #1962, especially as it often comes with code changes anyway?

**Comment by matklad** [comment]
Hm, there's truth to this, yeah!

bors r+ 

:)

**Comment by lnicola** [comment]
I think we have `--locked` exactly for this reason, and it wouldn't be needed otherwise.

**Comment by matklad** [comment]
`--locked` still is useful: we have many dependencies, and its quite probably that one of them accidentally publishes a non-semver compatible update.

**Pull request merged**
