### PR TITLE
Fix type equality for dyn Trait

### PR DESCRIPTION
**Pull request by flodiebold**
Fixes a lot of false type mismatches.

(And as always when touching the unification code, I have to say I'm looking forward to replacing it by Chalk's...)

### CODE REVIEW

**Comment by bjorn3** [comment]
> Fixes a lot of false type mismatches.

How much?

**Comment by edwin0cheng** [comment]
From:

Project Name |  Mismatches
-- | --
cargo  | 318
clap-rs| 236
cranelift-codegen| 651
futures| 20
helloworld|  0
html5ever|  65
hyper| 381
syn| 95

To:

Project Name |  Mismatches
-- | --
cargo| 296
clap-rs| 222
cranelift-codegen| 469
futures| 20
helloworld|  0
html5ever|  61
hyper| 381
syn| 95

**Comment by flodiebold** [comment]
In rust-analyzer itself the difference was even bigger, since we use trait objects a lot for the database.

**Comment by matklad** [comment]
Still seems like something is missing:

image

image

**Comment by flodiebold** [comment]
Chalk currently doesn't consider `dyn Trait` to implement the supertraits. Apparently there's some complicated soundness problems: https://github.com/rust-lang/chalk/issues/203 But maybe they're amenable to a simple implementation as a starting point :thinking:

**Pull request merged**
