### PR TITLE
Extract tests module to file in ide_db crate

### PR DESCRIPTION
**Pull request by sasurau4**
Helps with #6522 

- pass `cargo test`

### CODE REVIEW

**Comment by matklad** [comment]
though, at this scale, I think it makes sense to *first* implemet the assist to automate the thing, and then do the conversion.

**Comment by sasurau4** [comment]
I agree with @matklad . In today's master, targets of conversion is at most 123 files checking from `rg 'mod tests \{' crates/ -l | count`.
I try to implement if it needed. Could I communicate with you in https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frls-2.2E0?

**Comment by matklad** [comment]
Sure, feel free to start a topic in zullip (though I am a bit short on time today, might take a day to respond)

**Pull request merged**
