### PR TITLE
Add box postfix completion

### PR DESCRIPTION
**Pull request by kanru**

### CODE REVIEW

**Comment by matklad** [comment]
Good idea!

Can you update the test below as well?

**Comment by kanru** [comment]
Updated the test with `cargo insta review`. The tool is neat!

**Comment by lnicola** [comment]
So how does one use these completions? If I type „42.dbg„ I can complete it to `dbg!(42.)`, which is almost, but not quite what I imagined. And I can't trigger the completion without the dot.

**Comment by kanru** [comment]
> So how does one use these completions? If I type „42.dbg„ I can complete it to `dbg!(42.)`, which is almost, but not quite what I imagined. And I can't trigger the completion without the dot.

Yes, it's a completion triggered by the dot. It works pretty well for symbols or expressions. I think `42.` completed to `dbg!(42.)` is kind of a bug, probably due to `42.` being a valid number.

**Comment by matklad** [comment]
bors r+

> is kind of a bug, probably due to 42. being a valid number.

Filed https://github.com/rust-analyzer/rust-analyzer/issues/1435

**Pull request merged**
