### PR TITLE
Support .await syntax

### PR DESCRIPTION
**Pull request by unrealhoang**
- [x] Add `await` keyword to grammar, parser for await_expr
- [ ] Infer type for await_expr

### CODE REVIEW

**Comment by unrealhoang** [comment]
@matklad I'm not so familiar with syntax and parsing yet, so please help to commend if I'm doing things right.

**Comment by lnicola** [comment]
We'll also want highlighting support for await, I think. During the syntax discussions, the postfix form was criticized because some people feel it's hard to notice.

**Comment by matklad** [comment]
Yeah, this is the right first step!

I'll just bors r+ this, as it is self-contained and already useful.

bors r+

**Comment by matklad** [comment]
@lnicola I *think* highlighting should just work, because the kind is marked as a keyword

**Comment by lnicola** [comment]
I was thinking of making it similar to the `unsafe` highlighting :sweat_smile:. But it can be added in another PR, of course.

**Comment by matklad** [comment]
>During the syntax discussions, the postfix form was criticized for being harder to notice.

I am willing to  bet that it's an instance of Stroustrup rule :) Usual syntax highlighting will be enough for most people after a couple of releases with `.await`. I might be wrong of course, but it'll be easy to make more conspicuous highlighting if we deem that it is necessary, after the feature is stable for a couple of months.

**Comment by unrealhoang** [comment]
@matklad next we need to add `AwaitExpr` to `ast/Expr`?

**Comment by matklad** [comment]
Yep, this should be done in `ast` secion of grammar.ron, here: https://github.com/unrealhoang/rust-analyzer/blob/e18f8495d6569f4fc0b7457b65a1d199cf7b5974/crates/ra_syntax/src/grammar.ron#L487-L519.

We only need to get reciver out of `Await` expr, so `"AwaitExpr": (options: ["Expr"]),` should work.

It makes sense to update `hir::ExprCollector::collect_expr` and `hir::Expr` along the way as well. At this stage, typechecking can be just stubbed out to return Ty::Unknown

**Pull request merged**
