### PR TITLE
Move `GenericParams`'s handling of `impl Trait` into `fn_data_query`

### LINKED ISSUE #10286: `impl Trait` in macros: `subst.rs` "index out of bounds: the len is 1 but the index is 1"
#9639 has been closed, however a very similar issue is still happening to me. I encountered it the moment I added a `ctor!` macro call [at this line](https://github.com/SkiFire13/edile/blob/4fcda5941d995e9e02fb7042ff8a32b72d0c4faa/edile/src/own.rs#L47). (Note that the linked crate requires beta/nightly to compile, but only due to code unrelated to the issue; the minimal repro compiles fine on stable.) 
The macro call looks required for the crash to trigger, and manually expanding it solves the issue. This also happened in #9639 and the minimal repro posted there doesn't seem to address this.

Here's a minimal repro of my issue:

```rust
macro_rules! ty {
    () => {
        impl Sized
    }
}

fn foo(_: ty!()) {}

fn bar() {
    foo(());
}
```

It gives this error in vscode's output tab:

```
Panic context:
> 
version: 516eb40ba 2021-09-13 stable
request: rust-analyzer/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/g%3A/WorkSpace/repro/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\chalk-ir-0.71.0\src\fold\subst.rs:58:19
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 516eb40ba 2021-09-13 stable
request: rust-analyzer/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/g%3A/WorkSpace/repro/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\chalk-ir-0.71.0\src\fold\subst.rs:58:19
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 516eb40ba 2021-09-13 stable
request: rust-analyzer/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/g%3A/WorkSpace/repro/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\chalk-ir-0.71.0\src\fold\subst.rs:58:19
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I can't seem to get a full backtrace even when setting `RUST_BACKTRACE=full`.

### PR DESCRIPTION
**Pull request by SkiFire13**
Fixes #10286

### CODE REVIEW

**Comment by flodiebold** [comment]
Was it necessary to add `generic_params` to the function data? The fix I expected was to just make the `params` in the function data be fully expanded. (This requires walking the `TypeRef` and replacing macro invocations by the expanded version.) I'd then expect nothing else needing to change, but maybe I missed something?

**Comment by SkiFire13** [comment]
Adding `generic_params` to the `FunctionData` is not necessary, however it would mean having to create a new `GenericParams` inside `GenericParams::generic_params_query` since it used to just refer to the one in `Function` (and now I've changed it to refer to the one in `FunctionData`).

**Comment by flodiebold** [comment]
Now I see. This is kind of confusing, since apparently we mostly don't use `GenericParams::new` anymore and instead have a duplicate of that logic in `item_tree::lower::Ctx::lower_generic_params`. This would mean we have two slightly different generic_params. @jonas-schievink any ideas?

**Comment by jonas-schievink** [comment]
Yeah that code should probably be deduplicated. Might look into that in the next days if I find the time.

**Comment by flodiebold** [comment]
Yeah, I think this should be ok.

bors r+

**Comment by SkiFire13** [comment]
Oh, technically the title is wrong now, it has been moved into `GenericParams::generic_params_query`

**Pull request merged**
