### PR TITLE
[first contributation] fix: `add return type` assit works when there's missing whitespace

### PR DESCRIPTION
**Pull request by izik1**
I feel like the way I handled whitespace here isn't... Right? Maybe it should be folded into `InsertOrReplace::Insert`

Also, sorry about the commit name, I am _not_ good at writing user facing commit messages

Also sorry about the test names, could be clearer I feel

### CODE REVIEW

**Comment by izik1** [comment]
Fixes #10892, missed that part

**Comment by Veykril** [comment]
Ye the `needs_whitespace` bool can be added to the `InsertOrReplace::Insert` variant, that way there is no need to thread the bool separately through things.

**Review by Veykril — APPROVED** [review]
Thanks!
bors r+

**Comment by skylerqpq** [comment]
I just realized that I typoed `assist` in the PR title (and the first commit, but, that's probably less important)

**Pull request merged**
