### PR TITLE
Remove deny_c in CI

### PR DESCRIPTION
**Pull request by edwin0cheng**
https://github.com/rust-analyzer/rust-analyzer/pull/3800#issuecomment-607186153

r=@matklad

### CODE REVIEW

**Comment by matklad** [comment]
Let's comment it out for now, the upstream might get fixed: https://www.jetbrains.com/help/rider/Coding_Assistance__Complete_Statement.html#

r=me otherwise

**Comment by matklad** [comment]
actually relevant link: https://github.com/nagisa/rust_libloading/issues/61#issuecomment-607941377

**Comment by edwin0cheng** [comment]
But I think bor-s won't work on changing github-action, right? Anyway, let try it 

bors r=@matklad

**Comment by matklad** [comment]
Ah, right...

**Pull request merged**
