### PR TITLE
internal: Bump `xshell` and fix `dist`

### PR DESCRIPTION
**Pull request by lnicola**
bors r+

### CODE REVIEW

**Comment by lnicola** [comment]
Great, releases still fail on `rust-analyzer analysis-stats --with-deps $(rustc --print sysroot)/lib/rustlib/src/rust/library/std`:

```
9/24924 41% processing: array::try_collect_into_arraythread 'main' panicked at 'Mismatched kinds: {error}, [?15, {error}], [Type, Const(Uint(Usize))]', crates/hir_ty/src/builder.rs:138:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: hir_ty::builder::TyBuilder<chalk_ir::Binders<T>>::build
   3: hir_ty::infer::path::<impl hir_ty::infer::InferenceContext>::infer_path
   4: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
   6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
   8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  11: hir_ty::infer::infer_query
  12: salsa::runtime::Runtime::execute_query_implementation
  13: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  14: salsa::derived::slot::Slot<Q,MP>::read
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  17: hir_ty::db::infer_wait
  18: rust_analyzer::cli::analysis_stats::<impl rust_analyzer::cli::flags::AnalysisStats>::run_inference
  19: rust_analyzer::cli::analysis_stats::<impl rust_analyzer::cli::flags::AnalysisStats>::run
  20: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

CC @HKalbasi

**Comment by HKalbasi** [comment]
I can't reproduce it on my system, maybe due different rustc versions? I'm using beta 1.60. Will it panic on `array::try_collect_into_array` of your version as a standalone function?

**Comment by lnicola** [comment]
```
$ rust-analyzer analysis-stats $(rustc --print sysroot)/lib/rustlib/src/rust/library/core -o array::try_collect_into_array
Database loaded:     4.07s, 84minstr (metadata 383.76ms, 1361kinstr; build 3.65s, 8134kinstr)
  crates: 4, mods: 423, decls: 17129, fns: 12491
Item Collection:     2.25s, 22ginstr
0/12491 0% processing: array::try_collect_into_arraythread 'main' panicked at 'Mismatched kinds: {error}, [?15, {error}], [Type, Const(Uint(Usize))]', crates/hir_ty/src/builder.rs:138:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: hir_ty::builder::TyBuilder<chalk_ir::Binders<T>>::build
   3: hir_ty::infer::path::<impl hir_ty::infer::InferenceContext>::infer_path
   4: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
   6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
   8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  11: hir_ty::infer::infer_query
  12: salsa::runtime::Runtime::execute_query_implementation
  13: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  14: salsa::derived::slot::Slot<Q,MP>::read
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  17: hir_ty::db::infer_wait
  18: rust_analyzer::cli::analysis_stats::<impl rust_analyzer::cli::flags::AnalysisStats>::run_inference
  19: rust_analyzer::cli::analysis_stats::<impl rust_analyzer::cli::flags::AnalysisStats>::run
  20: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
$ rustc -V
rustc 1.60.0-beta.4 (99f967e7e 2022-03-14)
```

I didn't try to extract the function into a standalone project, I don't think that can work.

**Comment by lnicola** [comment]
For me, this is enough to trigger the crash:

```rust
#![feature(maybe_uninit_uninit_array)]
use std::mem::MaybeUninit;

fn main() {
    MaybeUninit::<i32>::uninit_array::<1>();
}
```

**Pull request merged**
