### PR TITLE
Give ‘unsafe’ semantic token modifier to unsafe traits

### PR DESCRIPTION
**Pull request by arzg**
Hi! This is my first pull request that touches rust-analyzer itself beyond a search-and-replace, so please tell me if I should change anything or do anything differently. :)

### CODE REVIEW

**Comment by Veykril** [comment]
Looks good to me, thanks!
bors r+

**Comment by matklad** [comment]
Hm, I am having second thoughts here, this doesn't look completly right to me:

image

I guess, the only case when unsafe trait is really unsafe is inside unsafe impl? Otherwise, the user shouldn't see the difference between safe and unsafe tratits?

Don't know what the right solution here, but it does feel that there's a problem here.

**Comment by Veykril** [comment]
Hm, ye that seems wrong now that you say(and show) it. The trait should only be highlighted as unsafe in unsafe impls(and maybe in the definition itself I'd say) as using it otherwise is perfectly fine.

**Comment by arzg** [comment]
Yeah, I think you’re right. Is it worth highlighting them differently if it’ll only happen in such limited circumstances? I think I would prefer no distinction at all to having them be highlighted inconsistently for no immediately obvious reason.

**Pull request merged**
