### PR TITLE
Generate the impl block via generate_trait_impl_text_from_impl

### PR DESCRIPTION
**Pull request by hi-rustin**
Try to close https://github.com/rust-analyzer/rust-analyzer/issues/8827

### CODE REVIEW

**Comment by hi-rustin** [comment]
@Veykril  Do you have any suggestions on how to get strukt right here?

**Comment by Veykril** [comment]
Right this is a bit more annoying to do here. I think what we actually want here is another function `generate_trait_impl_text_from_impl(impl_: &ast::Impl, trait_text: &str, code: &str) -> String` instead which copies the generics and all from another impl instead.

As for the following example:
```rust
struct Foo<T> { t: T }

impl<T: From<i32>> Foo<T> {
    fn new() -> Self {
        Foo { t: 0.into() }
    }
}
```
Here we want the `T: From<i32>` bounds of the impl, not just the `T` from the struct def. So we don't actually need the struct def here, only the impl node.

It's fine to copy the `generate_impl_text_inner` impl for that for now so that there is also a version working for an `ast::Impl`, or edit it so that it works for both if you can.

**Comment by hi-rustin** [comment]
@Veykril Added. Thanks for your help!

**Pull request merged**
