### PR TITLE
Fix test mark placement

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by lnicola** [comment]
So this was broken in #2337, but CI still passed?

**Comment by matklad** [comment]
Mark might be hit by a concurrent thread. I wonder if we should switch to thread-locals? I think this'll work for all cases for which we use marks

**Comment by lnicola** [comment]
Does `cargo test` tear down the thread after each test?

**Comment by matklad** [comment]
It shouldn't matter: we can clear the mark in drop

**Pull request merged**
