### PR TITLE
Fill deprecation for LSP

### PR DESCRIPTION
**Pull request by kjeremy**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

Thanks!

**Comment by kjeremy** [comment]
> We also probably want to find a better place for finding the deprecated attribute, but off the top of my head I don't know a strictly better place.

I was thinking of this too. We may want to do something similar to `Documentation` for built in attrs? For instance it would be nice to match on the deprecated attr's optional `note` or `since` field and add that to the `details` string. I'm not quite sure but I think we may need an abstraction for this sort of thing.

**Comment by DJMcNab** [comment]
I think `syn`'s abstraction works quite well (on mobile so can't link). Maybe we could look at what we can learn from that.

**Pull request merged**
