### PR TITLE
Expand column!()

### PR DESCRIPTION
**Pull request by kjeremy**

### CODE REVIEW

**Comment by bjorn3** [comment]
Can we also have `file!()`?

**Comment by kjeremy** [comment]
> 
> 
> Can we also have `file!()`?

I think that deserves a separate PR.

**Comment by matklad** [comment]
We also can't really have `file!()` at the moment, as rust-analyzer
(purposefully) lacks the knowledge about absolute file paths. I think, for
starters, we should expand file to just `""`.

**Comment by kjeremy** [comment]
I'll rebase this ones #2357 merges.

**Pull request merged**
