### PR TITLE
Try figure out correct workspace in vscode multi root workspace

### PR DESCRIPTION
**Pull request by urbandove**
the code to replace the root with the `${workspaceRoot}` arg breaks in multi root workspaces as it needs a qualifier `${workspaceRoot:workspaceName}`

This PR attempts to figure out the root workspace - and if it cant find it falls back to the first workspace

### CODE REVIEW

**Comment by matklad** [comment]
@vsrs you probably are more qualified to review this :)

**Comment by vsrs** [comment]
@urbandove 

The only reason why the simplification exists is to have better `launch.json` when someone saves a debug configuration (via `rust-analyzer.newDebugConfig` command for example).

With:
```jsonc
{
// ...
    "cwd": "${workspaceRoot}"
}
```

Without:
```
{
// ...
    "cwd": "E:\Projects\Rust\RA\test_projects\multiple_binaries\"
}
```
And it's not good to have the absolute path in the `launch.json`.

I've never worked with multi-root workspaces, but I think it should be possible to modify `simplifyPath` function and use `${workspaceRoot:workspaceName}` for a multi-root workspace.

**Comment by urbandove** [comment]
@vsrs Thanks for the clear explanation - I've included a link to that message in this updated PR so no-one tries deleting that function like i did

**Comment by bjorn3** [comment]
Will fix #5536

**Comment by urbandove** [comment]
I cant actually figure out why the typescript tests are failing - running locally works perfectly fine for me

**Comment by lnicola** [comment]
See https://github.com/rust-analyzer/rust-analyzer/pull/5528. I think it's a formatting difference.

**Comment by urbandove** [comment]
I had the linter successfuly before - but it still failed without noting the error in the github action.
removing an empty line seems to have worked.

**Comment by mburszley** [comment]
Just chiming in to make sure terminology is correct, the official docs [refer to the variable as `${workspaceFolder}`](https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder), not `${workspaceRoot}` (I think that has been deprecated or obsoleted).

**Comment by urbandove** [comment]
@mburszley I updated the var name in this PR - but there may be more places that will need to be updated

**Comment by urbandove** [comment]
@vsrs if you have a chance to review this again it would be lovely

**Comment by vsrs** [comment]
LGFM

**Comment by matklad** [comment]
bors r=vsrs

**Pull request merged**
