### PR TITLE
Fix compile failure on current stable rustc 1.39.0

### PR DESCRIPTION
**Pull request by oxalica**

### CODE REVIEW

**Comment by matklad** [comment]
Current stable is 1.40 :)

**Comment by matklad** [comment]
https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html

**Comment by flodiebold** [comment]
Someone was *very* fast at using newly stabilized features again :wink:

**Comment by oxalica** [comment]
Oops, okay. It updates. I'm using rustup mirror which is not sync-up yet.

**Comment by matklad** [comment]
@flodiebold I specifically resisted refactoring [this](https://github.com/rust-analyzer/rust-analyzer/blob/02f9e04ee926241389f8c9e41fec9281de1e0af9/crates/ra_hir_def/src/path.rs#L138) to use `as_deref()`, and only bumped requirement when the new code could benefit :)

**Pull request closed without merging**
