### PR TITLE
ItemTree: store a mapping from blocks to inner items

### PR DESCRIPTION
**Pull request by jonas-schievink**
To do name resolution within block expressions, we need to know which inner items are located inside each block expression. This adds such a mapping to `ItemTree`, replacing the previous one, which was seemingly unused other than to access all the inner items.

This also assigns `AstId`s to block expressions, which is needed to store the mapping in salsa.

### CODE REVIEW

**Comment by matklad** [comment]
Hm... I wonder if we should compute this in a more lazy way. Most of this info will be unused, as we won't be looking for inner items.

Hm, I think I want to say something slightly different. There are very few inner items, but a lot of blocks. I think we should do a bit of premature optimization here, and make sure we only record blocks which actually have items.

**Comment by jonas-schievink** [comment]
Yeah, sounds reasonable, though I'm not quite sure how that would look. Presumable we wouldn't want to use `AstIdMap` for this then? Would we still want to use a similar "bdfs" scheme to compute block ids?

**Comment by jonas-schievink** [comment]
Oh, and some numbers: This PR increases the memory usage of the `AstIdMapQuery` from 15 to 16 MB. I haven't measured the time overhead though.

**Comment by flodiebold** [comment]
> Hm... I wonder if we should compute this in a more lazy way. Most of this info will be unused, as we won't be looking for inner items.

Yeah, I would have imagined we only look for inner items once we're resolving names inside a block?

**Comment by matklad** [comment]
>Oh, and some numbers: This PR increases the memory usage of the AstIdMapQuery from 15 to 16 MB. I haven't measured the time overhead though.

wow, that's surprising, I'd expect a much larger impact naively. We also should already implement profiling infra to count things... Let me add an issue about this...

**Comment by matklad** [comment]
https://github.com/rust-analyzer/rust-analyzer/issues/7363

**Comment by matklad** [comment]
@jonas-schievink if this doesn't regress memory use that much, I'd merge this as is, but we should cross-check this once we have counters

**Comment by jonas-schievink** [comment]
Okay, sounds good.

bors r+

**Pull request merged**
