### PR TITLE
Add Vim and NeoVim setup section

### PR DESCRIPTION
**Pull request by oblitum**

### CODE REVIEW

**Comment by DJMcNab** [comment]
I'm not sure that we need to full paragraph about why this LSP client is good. It might be better just to say:

- Install coc.nvim by following the instructions at (...)
- Add rust analyser using: (from)(link to wiki page) 
```
Block from wiki
```

**Comment by oblitum** [comment]
Amended.

**Comment by DJMcNab** [comment]
Just a few nits:

- `json`/`jsonc` seem to be misspelt, but that might be the right specifier for jsonc.
- it's not entirely obvious where that block should go - maybe specifying 'by adding the following to `:CocConfig`'
- the json block could be surrounded by another set of braces, just so it is valid syntax. 
- the source (wiki link) could be a comment inside the code block. 

Otherwise, looks good to me!

bors delegate+

**Comment by oblitum** [comment]
coc.nvim configuration is in `jsonc`.

**Pull request merged**
