### PR TITLE
internal: Simplify `DefCollector::resolve_macros`

### PR DESCRIPTION
**Pull request by jonas-schievink**
bors r+

### CODE REVIEW

**Comment by jonas-schievink** [comment]
bors retry

**Comment by jonas-schievink** [comment]
bors retry

**Comment by jonas-schievink** [comment]
apparently there's a *major* outage https://www.githubstatus.com/

weirdly it's not affecting all repos though

**Comment by jonas-schievink** [comment]
bors retry

**Comment by lnicola** [comment]
bors retry

**Pull request merged**
