### PR TITLE
Remove CI badge

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by lnicola** [comment]
We could keep it. There is an URL for GitHub Actions badges.

**Comment by matklad** [comment]
We use bors, so that's not really required.

**Comment by matklad** [comment]
To expand on this:

* we don't need *status* aspect of the badge, as it is always green
* we already have a link to actions in the reapo header

**Comment by lnicola** [comment]
It's probably not that important, but I think the badges are not for the maintainers, but rather for portential users who can be moderately certain that the crate is still maintained. Since they're so popular, users expect to see the badge there.

**Comment by matklad** [comment]
Good point! Still, I think the fact that actions are built-in into GitHub UI, they will cover this use-case as well soon (but it might take some time for folks to adjust to looking at actions)

**Comment by lnicola** [comment]
Does the Actions link have an indication of passing or failed builds, or do you need to click on it?

For the record, the badge URL is https://github.com/rust-analyzer/rust-analyzer/workflows/CI/badge.svg.

**Pull request merged**
