### PR TITLE
Upgrade Chalk (without using its dyn/impl Trait support)

### PR DESCRIPTION
**Pull request by flodiebold**

### CODE REVIEW

**Comment by lnicola** [comment]
Can you please keep the commit numbers in `Cargo.toml`? See https://github.com/rust-analyzer/rust-analyzer/pull/2068#issuecomment-546304047.

**Comment by flodiebold** [comment]
Since we're working with current Chalk master after this, I wasn't sure whether that was necessary / worth it.

**Comment by lnicola** [comment]
It's the current `chalk` until it isn't anymore, and `rust-analyzer` will probably have more and more users running into issues like this.

**Comment by flodiebold** [comment]
Usually we update pretty quickly; we only didn't in this case because of the dyn/impl bugs, but it wasn't even actually necessary. I saw this more as a temporary measure.

**Comment by flodiebold** [comment]
I guess we can still decide to remove the `rev` again though, so I've added it back for now.

**Pull request merged**
