### PR TITLE
Improve parsing of type bounds

### PR DESCRIPTION
**Pull request by vipentti**
This adds new TYPE_BOUND_LIST and TYPE_BOUND syntax kinds. These are now used when parsing type bounds. In addition parsing paths inside a bound now does not recursively parse paths, rather they are treated as separate bounds, separated by +.

Basically now the generic params `struct S<T: 'a + ?Sized + (Copy)>;` in will be parsed as 

```
TYPE_PARAM_LIST@[8; 33)
  L_ANGLE@[8; 9)
  TYPE_PARAM@[9; 32)
    NAME@[9; 10)
      IDENT@[9; 10) "T"
    COLON@[10; 11)
    WHITESPACE@[11; 12)
    TYPE_BOUND_LIST@[12; 32)
      TYPE_BOUND@[12; 14)
        LIFETIME@[12; 14) "'a"
      WHITESPACE@[14; 15)
      PLUS@[15; 16)
      WHITESPACE@[16; 17)
      TYPE_BOUND@[17; 23)
        QUESTION@[17; 18)
        PATH_TYPE@[18; 23)
          PATH@[18; 23)
            PATH_SEGMENT@[18; 23)
              NAME_REF@[18; 23)
                IDENT@[18; 23) "Sized"
      WHITESPACE@[23; 24)
      PLUS@[24; 25)
      WHITESPACE@[25; 26)
      TYPE_BOUND@[26; 32)
        L_PAREN@[26; 27)
        PATH_TYPE@[27; 31)
          PATH@[27; 31)
            PATH_SEGMENT@[27; 31)
              NAME_REF@[27; 31)
                IDENT@[27; 31) "Copy"
        R_PAREN@[31; 32)
  R_ANGLE@[32; 33)
```

Previously it was parsed, with the paths nested:

```
TYPE_PARAM_LIST@[8; 33)
  L_ANGLE@[8; 9)
  TYPE_PARAM@[9; 32)
    NAME@[9; 10)
      IDENT@[9; 10) "T"
    COLON@[10; 11)
    WHITESPACE@[11; 12)
    LIFETIME@[12; 14) "'a"
    WHITESPACE@[14; 15)
    PLUS@[15; 16)
    WHITESPACE@[16; 17)
    QUESTION@[17; 18)
    PATH_TYPE@[18; 32)
      PATH@[18; 23)
        PATH_SEGMENT@[18; 23)
          NAME_REF@[18; 23)
            IDENT@[18; 23) "Sized"
      WHITESPACE@[23; 24)
      PLUS@[24; 25)
      WHITESPACE@[25; 26)
      L_PAREN@[26; 27)
      PATH_TYPE@[27; 31)
        PATH@[27; 31)
          PATH_SEGMENT@[27; 31)
            NAME_REF@[27; 31)
              IDENT@[27; 31) "Copy"
      R_PAREN@[31; 32)
  R_ANGLE@[32; 33)
```

Looking for feedback.

### CODE REVIEW

**Comment by vipentti** [comment]
Both `impl Trait` and `dyn Trait` do parse using `type_params::bounds_without_colon(p)` looking something like for `impl Iterator<Item=Foo<'a>> + 'a`

```
IMPL_TRAIT_TYPE@[9; 41)
  IMPL_KW@[9; 13)
  WHITESPACE@[13; 14)
  TYPE_BOUND_LIST@[14; 41)
    TYPE_BOUND@[14; 36)
      PATH_TYPE@[14; 36)
        PATH@[14; 36)
          PATH_SEGMENT@[14; 36)
            NAME_REF@[14; 22)
              IDENT@[14; 22) "Iterator"
            TYPE_ARG_LIST@[22; 36)
              L_ANGLE@[22; 23)
              ASSOC_TYPE_ARG@[23; 35)
                NAME_REF@[23; 27)
                  IDENT@[23; 27) "Item"
                EQ@[27; 28)
                PATH_TYPE@[28; 35)
                  PATH@[28; 35)
                    PATH_SEGMENT@[28; 35)
                      NAME_REF@[28; 31)
                        IDENT@[28; 31) "Foo"
                      TYPE_ARG_LIST@[31; 35)
                        L_ANGLE@[31; 32)
                        LIFETIME_ARG@[32; 34)
                          LIFETIME@[32; 34) "'a"
                        R_ANGLE@[34; 35)
              R_ANGLE@[35; 36)
    WHITESPACE@[36; 37)
    PLUS@[37; 38)
    WHITESPACE@[38; 39)
    TYPE_BOUND@[39; 41)
      LIFETIME@[39; 41) "'a"
```

**Comment by vipentti** [comment]
Bare syntax is the only one not properly parsed using `TYPE_BOUND_LIST`

**Comment by vipentti** [comment]
I'm not sure what would be the best approach for parsing `Box<T + 'f>` to be equivalent of `Box<dyn T + 'f>`

**Comment by matklad** [comment]
>I'm not sure what would be the best approach for parsing

Presumable, we could parse path, than, if we see +, we can use `precede` to make a `dyn trait`, otherwise we use precude to make a PathType?

**Comment by vipentti** [comment]
Updated the parsing of `Box<T + 'f>` in 98cff6e, now the end result of parsing it is much closer to parsing `Box<dyn T + 'f>`. Now the result looks something like

```
PATH_TYPE@[12; 23)
  PATH@[12; 23)
    PATH_SEGMENT@[12; 23)
      NAME_REF@[12; 15)
        IDENT@[12; 15) "Box"
      TYPE_ARG_LIST@[15; 23)
        L_ANGLE@[15; 16)
        TYPE_ARG@[16; 22)
          DYN_TRAIT_TYPE@[16; 22)
            TYPE_BOUND_LIST@[16; 22)
              TYPE_BOUND@[16; 17)
                PATH_TYPE@[16; 17)
                  PATH@[16; 17)
                    PATH_SEGMENT@[16; 17)
                      NAME_REF@[16; 17)
                        IDENT@[16; 17) "T"
              WHITESPACE@[17; 18)
              PLUS@[18; 19)
              WHITESPACE@[19; 20)
              TYPE_BOUND@[20; 22)
                LIFETIME@[20; 22) "'f"
        R_ANGLE@[22; 23)
```

**Comment by matklad** [comment]
bors r+

Nice, this makes so much more sense now!

**Pull request merged**
