### PR TITLE
Add server.extraArgs to the Code plugin

### PR DESCRIPTION
**Pull request by lf-**
This is nice for easily capturing log files to share.

### CODE REVIEW

**Comment by matklad** [comment]
Hm, I am not entirely convinced by the motivation here. Logs are captured by VS Code by default: 

image

`--log-file` is for (arguably, broken) environments where `stderr` is awkward to get.

**Comment by lf-** [comment]
> Hm, I am not entirely convinced by the motivation here. Logs are captured by VS Code by default:
> 
> image
> 
> `--log-file` is for (arguably, broken) environments where `stderr` is awkward to get.

Ah, I see. I partially was having issues getting LSan output from Code with the server logging, but it's possible that was just a misunderstanding of how the system works. The real reason I wrote this feature was because it was a lot more convenient for use with coc-rust-analyzer to be able to view the logs in an editor with live reload, such as Code, and that one is nearly the same codebase as the r-a Code extension so I wanted to have the settings be the same between the two implementations. It may have been a bit of programmer brain on my part as well, as I didn't deeply investigate the logging within Coc (I think CocOpenLog didn't give me what I wanted? I didn't trust it in any case) and instead wrote some hack code to get the logs. 

Feel free to close this PR if it doesn't seem useful outside the debugging session I wrote it for. 

~

One thing I do somewhat want to add is a feature for a wrapper script that's called with the integrated server path as its first argument, so I can stick the auto updated version of r-a into a systemd container to stop any future incidents with the OOM killer going after the editor or other things if there's leaks in r-a. It might be more broadly useful for handling exposing different C libraries via a nix-shell as well. Let me know if this would be something you'd be interested in taking.

**Comment by matklad** [comment]
>The real reason I wrote this feature was because it was a lot more convenient for use with coc-rust-analyzer to be able to view the logs in an editor with live reload

Hm, I think this is a bit problem, which should be fixed on coc side (to benefit all servers, and not just rust-analyzer) -- viewing logs should be easy and discoverable. It seems like this is a common problem:

* https://users.rust-lang.org/t/how-to-compare-logs-from-coc-nvim-and-nvim-lspconfig/57539
* https://github.com/rust-analyzer/rust-analyzer/issues/8233

If you are feeling like it, I encourage you to look into fixing this on coc's side -- it seems one of those things  that don't sound glamorous, but can actually improve experience for many people.

**Comment by matklad** [comment]
cc @fannheyward from the coc-side

**Comment by fannheyward** [comment]
@lf- what logs do you want in coc? requests logs between coc and r-a? coc/coc-rust-analyzer has the same configuration as VSCode , set `rust-analyzer.trace.server": "verbose"` in your coc-settings.json, then you can get the logs from `:CocCommand workspace.showOutput` - `rust-analyzer`.

**Comment by matklad** [comment]
@fannheyward there are also logs from stderr. VS Code makes both moderately discoverable: 

image

**Comment by matklad** [comment]
Huh, good that I've opened logs, didn't expect that panic in there :rofl:

**Comment by fannheyward** [comment]
@matklad the `Rust Analyzer Language Server Trace` logs is controlled by `rust-analyzer.trace.server`, right?

What's the `Rust Analyzer Language Server` logs? I can't get it from VSCode.

**Comment by matklad** [comment]
@fannheyward yup, the `Trace` is controlled by the settings. The other thing is shown only if rust-analyzer actually logs anything to stderr. To get some log output, set `RA_LOG`  to `rust_analyzer=info`

**Comment by fannheyward** [comment]
@matklad got it with `RA_LOG=rust_analyzer=info`.

@lf- You can also get this logs from `:CocCommand workspace.showOutput` - `rust-analyzer`, without `rust-analyzer.trace.server` settings.

`RA_LOG=rust_analyzer=info vi src/main.rs`

截屏2021-04-06 19 34 56

**Pull request closed without merging**
