### PR TITLE
Update

### PR DESCRIPTION
**Pull request by kjeremy**

### CODE REVIEW

**Comment by Veetaha** [comment]
@kjeremy might I ask you on which command do you run to update the dependencies?

**Comment by kjeremy** [comment]
@Veetaha In the case above I used `cargo outdated` (use `cargo install cargo-outdated` to install). That will show you what can be updated. Then I use `cargo update` (sometimes with `-p` to specify a specific crate if for example you do not want to update the git rev of chalk) to update the lock file.

Obviously it's more complicated if you need to bump major/minor versions. As always do a `cargo test` and a simple run to make sure things do not regress.

**Comment by Veetaha** [comment]
t h x !

**Pull request merged**
