### PR TITLE
Goto definition works for `S { a: }` case

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by matklad** [comment]
cc @JoshMcguigan this might fix the issue you are seeing in completion.

**Comment by lnicola** [comment]
changelog fix fix resolution of incomplete fields

**Comment by matklad** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/8026 cleans the stuff up

**Comment by JoshMcguigan** [comment]
> cc @JoshMcguigan this might fix the issue you are seeing in completion.

Indeed this fixes the issue I was seeing on #8008 :tada:

**Pull request merged**
