### PR TITLE
fix: Code: use `Uri.toString()` for URLs

### LINKED ISSUE #9280: Bootstrap error [TypeError: Only absolute URLs are supported
In VSCode, using the latest version of Rust-Analyzer nightly, I get this error:

```
ERROR [6/15/2021, 3:02:45 AM]: Bootstrap error [TypeError: Only absolute URLs are supported
	at getNodeRequestOptions (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:20682:9)
	at /Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:20787:19
	at new Promise (<anonymous>)
	at Object.fetch (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:20784:9)
	at /Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22713:36
	at downloadFile (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22714:7)
	at /Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22693:15
	at C._withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:44110)
	at C.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:43864)
	at Object.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:30045)
	at Object.download (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22687:45)
	at /Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:23057:19
	at downloadWithRetryDialog (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:23095:26)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async getServer (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:23056:5)
	at async bootstrapServer (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22957:18)
	at async bootstrap (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22893:18)
	at async tryActivate (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22778:24)
	at async activate (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22769:5)]
```

This is a serious regression in nightly and it's important to fix it before the next release.
@matklad, please take a look.

### PR DESCRIPTION
**Pull request by wxb1ank**
I believe this should fix #9280. Testing is needed but I wanted to quickly push a hotfix.

### CODE REVIEW

**Comment by lnicola** [comment]
This can't hurt, right?

bors r+

**Comment by matklad** [comment]
We probably want to kick a nightly release

**Comment by matklad** [comment]
Did a release, also opened https://github.com/rust-analyzer/rust-analyzer/issues/9283.

Thanks @wxb1ank for lightning-fast fix by the way!

**Comment by wxb1ank** [comment]
> 
> 
> Did a release, also opened #9283.
> 
> Thanks @wxb1ank for lightning-fast fix by the way!

No problem, sorry for the regression in the first place. I should've tested update functionality in #8951. Oh well :)

**Comment by SomeoneToIgnore** [comment]
@wxb1ank , maybe that helps you:

When changing the client, I was able to manually debug the functionality with the "Run Installed Extension" (see the screenshot).

To fully emulate various cases (weekly release tries to bootstrap, nightly release tries to bootstrap) you'll have to amend the `package.json` and put the proper `version`, `releaseTag` values and remove `$generated-start`, `$generated-end` ones.

Simplest way to "properly" adjust the `package.json` would be to download the corresponding `rust-analyzer.vsix` plugin from the [r-a releases page](https://github.com/rust-analyzer/rust-analyzer/releases/), open it with any unarchiver, find the `package.json` there and copy-paste the contents over the one in the repo.
Then you start the debug and the plugin will pick up the amended `package.json` automatically, considering itself a weekly/nightly released plugin.

That should be enough to debug the bootstrap functionality on _one_ platform of yours. I suggest testing at least two: Windows and Linux/Mac since the path handling is different in those which can lead to subtle bugs.

image

**Comment by wxb1ank** [comment]
@SomeoneToIgnore Thank you!! That makes testing much easier :)

**Pull request merged**
