### PR TITLE
internal: Remove a few snippet completions, replace them with user snippets definitions in VSCode

### PR DESCRIPTION
**Pull request by Veykril**
Closes https://github.com/rust-analyzer/rust-analyzer/issues/9636
cc https://github.com/rust-analyzer/rust-analyzer/issues/7033#issuecomment-939959905

### CODE REVIEW

**Comment by Veykril** [comment]
No it wouldn't, any other client would have to ship this default setting as well.

**Comment by Veykril** [comment]
I am going to go ahead merging this now in spirit of the issue it closes, other clients will have to follow up with the same default set of snippets if they wish to retain the current ones.
bors r+

**Comment by Veykril** [comment]
or not

**Comment by shanesveller** [comment]
> No it wouldn't, any other client would have to ship this default setting as well.

This is extremely unfortunate and disappointing, considering how non-standardized snippet configuration/support is among other compatible editors. We now have a strictly worse OOTB experience than VSC users where previously it was equivalent in this regard.

Any chance of a partial revert or (much less preferably) an intentional documentation push around that?

I can pin my version of RA for now.

**Comment by Veykril** [comment]
For users that do not like these default snippets it would be a worse experience for them if we forcibly continued shipping these as builtins though as well. So you could argue keeping it is a worse experience for some r-a users in general.
Instead of us reverting it the other clients should instead allow configuring the custom user snippets, a feature that has been implemented on the server side of things for a fair bit now.

**Comment by flodiebold** [comment]
> I can pin my version of RA for now.

Wouldn't it be easier to just configure the snippets? It's just an LSP setting, every client should support setting those somehow.

**Comment by LikeLakers2** [comment]
I'm just curious why this change has to affect non-VSCode editors. Why couldn't it have been a VSCode-only change?

**Comment by Veykril** [comment]
We removed functionality from the server implementation as there is no reason for the server to ship these, as they are user customizable and as such they shouldn't be hardcoded in the server.

Hence this change affects all clients, its just that since we also developt the VSCode extension, we implemented the removed snippets as a default client config. We could've very well just not reimplemented them as VSCode defaults either.

**Comment by shanesveller** [comment]
> We removed functionality from the server implementation as there is no reason for the server to ship these

This is the piece that is unclear for me - it had existing demonstrable utility for me, and I missed the context for why it should've been/was removed from the backend. Can you point me to that discussion?

> Wouldn't it be easier to just configure the snippets?
Does it seem jarring to you to say "we should move these defaults from one central definition to a broader list of editor-specific definitions that need to be readily discoverable and/or upstreamed into the per-editor tooling instead"? Because that's how I perceive this change with the information I have so far.

**Comment by LikeLakers2** [comment]
@Veykril Thank you for explaining, but I'm still confused.

Rust-analyzer publicly supports more than VSCode, with https://rust-analyzer.github.io/ naming Emacs and Vim. But from the sound of things, this only adds the snippets back to VSCode. Doesn't that mean that Emacs and Vim now have degraded experiences with this change?

**Comment by shanesveller** [comment]
Also, having this change documented as an "internal improvement" with no remark on it disabling existing functionality (however temporarily based on follow-up or user actions) feels like an inaccurate characterization that will fly under the radar.

**Comment by Veykril** [comment]
> This is the piece that is unclear for me - it had existing demonstrable utility for me, and I missed the context for why it should've been/was removed from the backend. Can you point me to that discussion?

Sure, here is one example of where someone finds these snippets not useful, rather annoying https://github.com/rust-analyzer/rust-analyzer/issues/9636. With how things were before, people weren't able to opt-out of these. With the removal people can now opt-in into all the snippets they want. We could've very well not re-added them to VSCode either and have no default snippets in the config. Note that `default` snippets here is a very vague thing anyways, picking a default set is very specific to the programmer. Some people use certain snippets a lot, while others don't, so are those snippets a good default?

> Rust-analyzer publicly supports more than VSCode, with rust-analyzer.github.io naming Emacs and Vim (but implying that it's compatible with others). But from the sound of things, this only adds the snippets back to VSCode. Doesn't that mean that Emacs and Vim now have degraded experiences with this change?

This is not a client specific change, we removed these defaults for *all* clients by removing the from the hardcoded list in the server itself. We merely decided that we want to ship these as default for the VSCode client for the time being.

**Comment by Veykril** [comment]
> Also, having this change documented as an "internal improvement" with no remark on it disabling existing functionality (however temporarily based on follow-up or user actions) feels like an inaccurate characterization that will fly under the radar.

This you are completely right on, I apologize for that. This should've been marked more clearly by me.

**Comment by flodiebold** [comment]
> Does it seem jarring to you to say "we should move these defaults from one central definition to a broader list of editor-specific definitions that need to be readily discoverable and/or upstreamed into the per-editor tooling instead"? Because that's how I perceive this change with the information I have so far.

I didn't express an opinion about whether we should have done this change or not. I'm just saying, wouldn't it be easier for you to just configure the snippet, instead of pinning the RA version?

**Comment by shanesveller** [comment]
> I'm just saying, wouldn't it be easier for you to just configure the snippet, instead of pinning the RA version?

Most likely, yes. I've not needed to apply this level of customization to my LSP usage in the past and will need some time to read and digest the documentation around that to attempt to fix it for myself. I've tried to make this post not about me and not about a specific editor, that's the only reason for leaving this vague. Pinning a version instead is very straightforward in my environment/workflow (Nix-based).

**Comment by LikeLakers2** [comment]
> > Rust-analyzer publicly supports more than VSCode, with rust-analyzer.github.io naming Emacs and Vim (but implying that it's compatible with others). But from the sound of things, this only adds the snippets back to VSCode. Doesn't that mean that Emacs and Vim now have degraded experiences with this change?
>
> This is not a client specific change, we removed these defaults for all clients by removing the from the hardcoded list in the server itself. We merely decided that we want to ship these as default for the VSCode client for the time being.

You're missing the point. Rust-analyzer, on its website, claims to support Emacs and Vim. This implies that Emacs and Vim will not be unfairly disadvantaged compared to VSCode by the Rust-Analyzer developers.

But by making this change, suddenly VSCode has an advantage that Emacs and Vim do not. That means Emacs and Vim have degraded user experiences.

I get it if the Rust-Analyzer developers aren't maintaining a Emacs or Vim extension (or whatever you might use in those ecosystems), and thus can't implement custom code snippets in those editors. But it just sounds to me like we're preferring VSCode over other editors here -- and if that's the case, then I would really prefer that the Rust-Analyzer website not fool me into thinking I'd get the same exact Rust-Analyzer experience with Emacs or Vim as I would on VSCode.

**Comment by flodiebold** [comment]
> Rust-analyzer, on its website, claims to support Emacs and Vim. This implies that Emacs and Vim will not be unfairly disadvantaged compared to VSCode by the Rust-Analyzer developers.

It doesn't imply that; the manual actually clearly states "[VS Code] is the best supported editor at the moment." But also, this isn't Emacs and Vim being "unfairly disadvantaged". Emacs and Vim users can configure these snippets for themselves right now, and the respective integrations can add them to the default settings. I am an Emacs user and wrote the lsp-mode integration, I could make a PR to add the setting; I just personally don't think these snippets are particularly useful, so I probably won't.

**Comment by matklad** [comment]
Hm, I am confused here. The way it is implemented, it seems that the default lives on the server side:

https://github.com/rust-analyzer/rust-analyzer/blob/8dc3a270f6a893a592db1a5fe3cf8752521987e1/crates/rust-analyzer/src/config.rs#L120-L161

This default gets used here: 

https://github.com/rust-analyzer/rust-analyzer/blob/8dc3a270f6a893a592db1a5fe3cf8752521987e1/crates/rust-analyzer/src/config.rs#L1165

The reason why VS Code needs the same default on the client-side **in addition to server-side default** is that VS Code just **always** sends it's default config, even if the user didn't specify anything. That is, VS Code itself overwrites server-side defaults, and we work-around that. 

So, this should "just work" in any editor, unless it mirrors VS Code's "helpfully stomp over defaults" behavior. For the latter case, client-side defaults *should* then mirror whatever we have serever side, which  is available via `rust-analyzer --print-config-schema`. 

So, @Veykril, unless I am missing something, we probably should remove mentions of VS Code?

**Comment by Veykril** [comment]
Ye I just realized that as well that defaults should work for all, so I am confused that they apparently don't. So ye the title is just misleading.

**Comment by matklad** [comment]
How to investigate:

* run with logging enabled (eg `RA_LOG=rust_analyzer=info code .`)
* look for the first `[INFO rust_analyzer::config] updating config from JSON:` in the output

If it says something like

```
[INFO rust_analyzer::config] updating config from JSON: {}
```

Then the client sends empty config and server-side config should work.

If, in contrast, it says something like

```
[INFO rust_analyzer::config] updating config from JSON: {
  "cargoRunner": null,
  "completion": {
    "snippets": {}
  }
```

then the client forcefully overrides the default to nothing.

**Comment by flodiebold** [comment]
Yes, I can actually confirm the snippets still exist in Emacs.

**Pull request merged**
