### PR TITLE
cargo update

### PR DESCRIPTION
**Pull request by kjeremy**

### CODE REVIEW

**Comment by lnicola** [comment]
We should also update `pico-args`, but it has some breaking changes.

**Comment by kjeremy** [comment]
Agreed. That deserves a separate PR.

**Comment by matklad** [comment]
>We should also update pico-args, but it has some breaking changes.

btw, I've recently realise that immediate mode command-line parsing is possible, to provide automated help messages

```
let mut args = imargo::from_env();
if args.subcommand("install", "installs rust-analyzer") {
    let mimalloc = args.has("--mimalloc", "enable mimalloc allocator");
    let client: String = args.value("--client");
    args.finish()?;
    install(mimalloc, client);
}
if args.subcommand("release", "kicks the release process") {

}
args.finish()?;
```

`args` records all of the errors and emits them (and a help message) on `.finish`. I am unlikely to have time to finish the impl though :)

**Pull request merged**
