### PR TITLE
Upgrade Chalk

### PR DESCRIPTION
**Pull request by flodiebold**

### CODE REVIEW

**Comment by matklad** [comment]
@flodiebold do we want to get this into today's release?

**Comment by flodiebold** [comment]
I don't think there's any upside, so let's wait until after.

**Comment by flodiebold** [comment]
Upgraded again. This one required some more changes because of https://github.com/rust-lang/chalk/pull/360.

**Comment by matklad** [comment]
Hm, let's try to get this into today's release at least (unless you strongly object) :) 

I think that, by updating chalk frequently, we should be able to find regressions quicker.

bors r+

**Comment by flodiebold** [comment]
Yeah, also I wouldn't want to leave this lying around for long because of merge conflicts :grimacing:

**Pull request merged**
