### PR TITLE
add let and letm postfix to turn expressions into variables

### LINKED ISSUE #6426: Introduce postfixes to turn expressions into variables (like IntelliJ's .var).
Create two new postfixes: `let` and `letm`.

`let`:
```rust
"Hello, World!".let
let $0 = "Hello, World!";
```

and `letm`
```rust
"Hello, World!".letm
let mut $0 = "Hello, World!";
```

If possible, creating variables for expressions being called would be awesome:
```rust
vec![1, 2, 3].into_iter().map(|foo| foo * 2);
```
calling `.let` after `vec![1, 2, 3]` would turn into: 
```rust
let $0 = vec![1, 2, 3];
$0.into_iter().map(|foo| foo * 2);
```

### PR DESCRIPTION
**Pull request by bnjjj**
Partially resolve #6426

### CODE REVIEW

**Comment by lnicola** [comment]
Can you also add them to the [docs](https://rust-analyzer.github.io/manual.html#magic-completions)?

**Comment by matklad** [comment]
Let's additionally check that the parent node here is block. That is, we don't want to suggest let for something like `foo(92.<|>)`. Or rather, we *should*, but that should result in a more complex refactor which calls into "introduce variable".

**Comment by bnjjj** [comment]
Thanks for your review, it's updated

**Pull request merged**
