### PR TITLE
Webpack support

### PR DESCRIPTION
**Pull request by kjeremy**
Adds webpack support to the extension. I THINK I got everything and it seems to work locally though I'm not sure about the travis config or removing `terminateProcess.sh` (which I didn't see used anywhere?). I left the file just in case.

### CODE REVIEW

**Comment by kjeremy** [comment]
Note that whether we want this or not is a different question. The dart extension recently moved to it to improve startup times but we may not care as much.

**Comment by kwonoj** [comment]
I do strongly recommend bundle: fyi (https://code.visualstudio.com/api/working-with-extensions/bundling-extension), when it comes to increased numbers of modules (files), loading time will be significantly different. cjs's `require` is an expensive operation.

**Comment by kjeremy** [comment]
@fannheyward @kwonoj if one of you wants to pick up this PR and run with it go for it!

**Comment by fannheyward** [comment]
#1900 is works.

**Comment by matklad** [comment]
closed in favor of https://github.com/rust-analyzer/rust-analyzer/pull/1900

**Comment by matklad** [comment]
Historically, bundling caused a number of issues for us. Given that we don't have many runtime deps, and that the extension is archived into vsix anyway, I wonder if we really should use bundling?

Like, how much faster do we load because of it?

**Pull request closed without merging**
