### PR TITLE
Work around crlf in syntax tree

### LINKED ISSUE #4067: Show Syntax Tree's highlighting gets confused on CRLF files
Example:

image

Here I'm hovering `ATTR@[47; 63)` and it tells me that the text is

```rust
]
#[derive(Logo
```

instead of the correct

```rust
#[derive(Logos)]
```

due to the fact it's using offsets into an LF view of the file, but the file is actually using CRLF.

### PR DESCRIPTION
**Pull request by Veetaha**
Workarounds fixes #4067

### CODE REVIEW

**Comment by Diggsey** [comment]
You're right, this is a bit of a horrible workaround. It would also still fail for documents with mixed LF/CRLF line endings. How hard would it be to make RA use a view of the file that uses raw code-points?

**Comment by matklad** [comment]
Please edit PR title and commit message to avoid profanity (and euphemisms).

**Comment by Veetaha** [comment]
Sorry, the nerve...

**Comment by matklad** [comment]
>Sorry, the nerve...

The nerve is OK, but it's a good idea to try to express it somewhat more discretely: people's emotions tend to be pretty contagious unfortunately. 

As an aside, I actually find Russian language a much more expressive tool for these situations :laughing: 

bors r+

**Comment by lnicola** [comment]
By the way, why do we normalize the line endings?

**Comment by matklad** [comment]
>By the way, why do we normalize the line endings?

Mainly because, when implementing refactorings, you don't want to think what kind of line ending to generate, and you also don't want to deal with it when implementing line-ending depending features (like join lines). 

More generally, from a langauge spec point of view it's a good idea to do normalization early, to make sure that line endings don't accidently leak out. 

IIRC, rust raw string literals used to preserve line endings (or were it doc comments?) accidentally.

**Comment by CAD97** [comment]
> It would also still fail for documents with mixed LF/CRLF line endings.

FWIW, most editors (including vscode, IIRC) will by default normalize line endings to either LF or CRLF when encountering mixed line endings. Thankfully, this means that mixed line endings aren't really something that needs to be worried about in normal usage.

(The normalization direction varies; I've seen both "prefer more prevalent" and "prefer first" for the normalized line ending target. There's usually a setting for "preserve mixed line endings," but the use cases for explicitly _trying_ to have mixed line endings extend to about singly the task of testing handling of mixed line endings.)

**Pull request merged**
