### PR TITLE
Add custom cargo runners support.

### PR DESCRIPTION
**Pull request by vsrs**
This PR adds an option to delegate actual cargo commands building to another extension. For example, to use a different manager like [cross](https://github.com/rust-embedded/cross).

https://github.com/vsrs/cross-rust-analyzer is an example of such extension. I'll publish it after the rust-analyzer release with this functionality.

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/4902

### CODE REVIEW

**Comment by vsrs** [comment]
I decided to dwell on a command approach for the moment, for
1) looks like it works perfectly
2) unfortunately, I don't have enough time :(

**Comment by vsrs** [comment]
@matklad looks like there is a floating error in the tests. I did not change the code but the first run [failed](https://github.com/rust-analyzer/rust-analyzer/runs/802661597?check_suite_focus=true#step:10:1854 ) while the second [succeeded](https://github.com/rust-analyzer/rust-analyzer/runs/802795048?check_suite_focus=true).

**Comment by matklad** [comment]
Yup, that's due to https://github.com/rust-analyzer/rust-analyzer/pull/5008. We can just revert it, but ti would be cool to debug this, as this shouldn't be happening, as far as my understanding goes. 

For heavy tests, we create files in the tmp directory on disk, then crate analyzer instance. The analyzer reads files from disk and reports when it is done. After that, we proceed with a test. 

Apparantly, there are some additional vfs events happening *after* we report project as loaded. But those events should *not* affect the state of rust-analyzer, and should not cancel in-flight requests.

We used to "open" all the documents, exactly to prevent file system events from affecting the state, but this should no longer be necessary.

**Comment by vsrs** [comment]
I tried several times to run heavy tests locally on mac, no "luck" they work. Perhaps it makes sense to rollback #5008 to keep CI working.

**Comment by matklad** [comment]
Ok, I assume this is fine to experiment, but, long term, the dependency between extensions is clearly going into the wrong direction here, we need to introduce something akin IntelliJ's extension points.

bors r+

**Pull request merged**
