### PR TITLE
fix block parse problem

### PR DESCRIPTION
**Pull request by bravomikekilo**
try to fix [issue-1598](https://github.com/rust-analyzer/rust-analyzer/issues/1598).

### CODE REVIEW

**Comment by kjeremy** [comment]
Tests?

**Comment by matklad** [comment]
Sorry for letting this slip!

Yeah, this looks roghtly like it should be: basically, there's a logic to not treat `{ foo} & bar` as a binary expr, and instead treat it as two statements. Apparently, field access (and probably method calls as well?) should cancel that out.

The best way to test this would probably be to add 

```
// test name_of_the_test
// short example
```

test comments to the relevant bits of the parser

**Comment by bravomikekilo** [comment]
Ok, I will add test in comment

**Comment by bravomikekilo** [comment]
test added @matklad

**Comment by matklad** [comment]
bors r+

Thanks!

**Pull request merged**
