### PR TITLE
Use mmap for proc macro libs

### LINKED ISSUE #4002: Proc macro support is loading the dylib in memory
We could `mmap` it instead, unless someone objects.

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #4002.

### CODE REVIEW

**Comment by matklad** [comment]
What's the motivation here? Better perf? My understanding is that mmap only improves perf drastically if there's random access involved, and, for seqeuential access, it's not that different from read.

**Comment by lnicola** [comment]
Not loading a couple of MBs in memory when they might not be needed. E.g. if the symbol is found among the first ones, we won't load the rest of the library.

**Comment by bjorn3** [comment]
`object` needs a slice for the whole file, while the symbol table is only a small part of the file. By using mmap, the rest of the file doesn't get loaded.

**Comment by lnicola** [comment]
Hold on a bit, I think I've messed up the rebase.

**Comment by matklad** [comment]
Can goblin just work with `Read`? The docs seem to indicate that it can, though I haven't found anything with Read: https://docs.rs/goblin/0.2.1/goblin/

**Comment by bjorn3** [comment]
1. `goblin` requires you to individually handle every object file format separately, while `object` provides a uniform interface.
2. `goblin::Object::parse` requires a slice. If you only want to do partial reads of the object file, you will need to manually call methods like `goblin::elf::header::header64::Header::from_bytes` and traverse to the symbol table.

**Comment by matklad** [comment]
Ok, let's see if rumors about mmap blowing up in various corner cases are true :)

bors r+

**Comment by lnicola** [comment]
It looks like `Object::parse` [builds a `Cursor`](https://github.com/m4b/goblin/blob/master/src/lib.rs#L303) from the passed byte slice, so it might work with `Read`, but doesn't support it yet?

**Comment by lnicola** [comment]
Rebased.

**Pull request merged**
