### PR TITLE
show current function in analysis-stats progress bar

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by flodiebold** [comment]
The problem with this, and the reason why I didn't do this, is that the progress bar is not updated every time, so if it crashes, the function in the progress message is usually not the one where it crashed :(

**Comment by edwin0cheng** [comment]
Can we use [`enable_steady_tick`](https://docs.rs/indicatif/0.11.0/indicatif/struct.ProgressBar.html#method.enable_steady_tick) here ?

**Comment by edwin0cheng** [comment]
May i miss something, why the progress bar is not updated every time when `set_message` is called ?

**Comment by matklad** [comment]
Argh, indicatiff API are really confusing... Should be fixed in https://github.com/rust-analyzer/rust-analyzer/pull/1288

**Pull request merged**
