### PR TITLE
Implement import-granularity guessing 

### PR DESCRIPTION
**Pull request by Veykril**
This renames our `MergeBehavior` to `ImportGranularity` as rustfmt has it as the purpose of them are basically the same. `ImportGranularity::Preserve` currently has no specific purpose for us as we don't have an organize imports assist yet, so it currently acts the same as `ImportGranularity::Item`.

We now try to guess the import style on a per file basis and fall back to the user granularity setting if the file has no specific style yet or where it is ambiguous. This can be turned off by setting `import.enforceGranularity` to `true`.

Closes https://github.com/rust-analyzer/rust-analyzer/issues/8870

### CODE REVIEW

**Comment by matklad** [comment]
Hm, yeah, I think it’s somewhat tricky to define what we actually want here...

I think generally I want to strongly follow defaults (so merging). But if I open someone else’s project, and add import to some existing file, I want it to be consistent.

So perhaps the correct behavior here is “don’t create inconsistent file”? Ie, even if setting day “full”, but the current file uses “none”, we should honor the file rather than the setting?

And then maybe separately have “force” setting to disable the guessing logic?

**Comment by Veykril** [comment]
> So perhaps the correct behavior here is “don’t create inconsistent file”? Ie, even if setting day “full”, but the current file uses “none”, we should honor the file rather than the setting?

The problem with this then is that you won't ever get the full/crate logic in new files until you manually merge imports such that the file has a nested import. The other way around would at least work, that is user setting is none/item but the file has full/crate style.

**Comment by matklad** [comment]
Why? It seems like if there’s only one import, it’s not inconsistent with
any strategy, so any strategy works?

**Comment by Veykril** [comment]
Oh I guess I misunderstood you, since you said in that case we should honor the file I thought you meant it as we should fall back to one import per item like the file is using. Forget what I said then that seems like a good approach.

**Comment by Veykril** [comment]
Ah ye now I see my misunderstanding, my mindest was locked into the simple heuristic I got going here which wouldn't always work with that approach. 👍

**Comment by Veykril** [comment]
Turns out getting this right can be quite tricky. Got a basic implementation now but haven't gotten to creating tests yet(nor checked whether this actually works yet).

**Comment by Veykril** [comment]
Alright, the heuristic should be implemented now with some tests, kept `crate` as the default behavior instead as well now. Happy to take up some more test cases, couldn't come up with more myself currently.

**Comment by matklad** [comment]
Looks good to me!

Might be a good idea to manually check a couple of crates in the wild, to see if we miss something obvious.

For non obvious, I like the test harness here, and I suspect it’s one of those cases where we’ll be ironing out special cases for a long time :)

r=me

**Comment by Veykril** [comment]
> For non obvious, I like the test harness here, and I suspect it’s one of those cases where we’ll be ironing out special cases for a long time :)

That's what I suspect as well

bors r=matklad

**Pull request merged**
