### PR TITLE
fix: Properly unify receivers during method resolution

### PR DESCRIPTION
**Pull request by flodiebold**
This fixes our type inference problems with `DynMap`; the problem there were the projection types in
```rust
impl<P: Policy> KeyMap<Key<P::K, P::V, P>>
```
which messed up the naive type equality check we did. It also actually simplifies the logic though, IMO. I also added a fix for associated const resolution that I noticed (visibility not being taken into account).

### CODE REVIEW

**Comment by flodiebold** [comment]
(CC #8961)

**Comment by lnicola** [comment]
Did this also fix the annoying `is_unknown was called on a non-concrete constant value!` errors?

**Comment by flodiebold** [comment]
Yeah, though I didn't do it intentionally :sweat_smile:

**Comment by lnicola** [comment]
Now if only https://github.com/rust-lang/chalk/pull/754 got merged...

**Comment by lnicola** [comment]
image

**Pull request merged**
