### PR TITLE
Make `find_path_inner` a query

### PR DESCRIPTION
**Pull request by jonas-schievink**
This eliminates the remaining performance problems in the "Implement default members" assist (at least those that I've found).

Closes https://github.com/rust-analyzer/rust-analyzer/issues/4498

### CODE REVIEW

**Comment by flodiebold** [comment]
I'm not sure that's the best function to querify -- because of the `max_len` parameter, we would have many copies of basically the same query. OTOH the parameter is necessary to prevent infinite loops. I assume you tried to querify `find_path`? Maybe there's some other way to improve this though, i.e. some internal caching we could do :thinking:

**Comment by jonas-schievink** [comment]
Yeah, with `find_path` querified it still takes around 2 seconds to compute.

**Comment by flodiebold** [comment]
Maybe it's fine, `find_path_inner` will usually probably not be called with many different values for `max_len`... I don't know, @matklad what do you think?

**Comment by matklad** [comment]
Haven't looked into this yet, my gut feeling is that maybe this should be handled outside of queries at all? 

Like, this is some kind of searching bottom-up behavior, it seems somehow inappropriate to put it inside the query (just like the `find_path`). 

So, naively I'd expect that, rathar than queriefing `find_path` itself, we:

* queriefy some kind of an index which makes find_path just fast
* add some local per-AssistCtx caching

Again, this all is written without looking at the actual code, take with a pinch of salt :)

**Comment by matklad** [comment]
Yeah, I think the problem is that our current `find_path` is sort-of wrong, I've written https://github.com/rust-analyzer/rust-analyzer/issues/4515 for the "proper" way to do this.

**Comment by matklad** [comment]
Note that I am also not against merging this as is, but we really should do #4515 -- the more I think about it, the more it seems to be a part of a core infrastructure of an IDE.

**Comment by jonas-schievink** [comment]
Rebased just in case you do want to merge this

**Pull request merged**
