### PR TITLE
Extend convert_tuple_struct_to_named_struct to also apply to enum tuple variants

### PR DESCRIPTION
**Pull request by joshuawarner32**
This is largely copied and adapted from the existing `convert_tuple_struct_to_named_struct` code.

Not sure if maybe some of this code can/should be shared between those two assists - but the differences are significant enough to make it at least seem like a non-trivial refactor.

### CODE REVIEW

**Comment by matklad** [comment]
I think that both cases should probably be covered by the same assist. There’s little benefit in distinguishing between structs and enum variants — the user-visible operation is the same.

**Comment by joshuawarner32** [comment]
> I think that both cases should probably be covered by the same assist. 

Ok, that makes sense. I'll go ahead and attempt that refactor.

**Comment by matklad** [comment]
bors r+

Thanks!

**Comment by lnicola** [comment]
changelog feature (first contribution) extend "Convert tuple struct to named struct" assist to work for enum variants.

**Pull request merged**
