### PR TITLE
WIP: Enable parsing of attributes inside a match block

### LINKED ISSUE #845: Syntax error with match cfgs
rust-analyzer gives errors in valid rust code:

```
match thing {
    #[cfg(feature = "whatever")]
//  ^ expected pattern          ^ expected COMMA
    Thing::Banana(...) => (),
}

### PR DESCRIPTION
**Pull request by vipentti**
We allow invalid inner attributes to be parsed, e.g. inner attributes that are
not directly after the opening brace of the match block.

Instead we run validation on `MatchArmList` to allow better reporting of errors.

This fixes #845 and works towards #759

### CODE REVIEW

**Comment by matklad** [comment]
I think I agree that we should just parse inner and outer attributes in all contexts and make error reporting a job of a validator.

However, I am not sure that we should simultaneously expand the set of places where we allow attributes at all **and** switch to all attributes parsing. 

Let's start with just adding parsing of outer attributes to match arms :)

**Comment by vipentti** [comment]
Changed to using `outer_attributes` for the match arms. Now we should properly parse `inner_attributes` at the beginning of a match block and then `outer_attributes` for each match arm.

**Comment by matklad** [comment]
Let's remove the validators from the PR to keep it strictly about syntax?

**Comment by matklad** [comment]
bors r+

thanks!

**Comment by matklad** [comment]
@vipentti just to be clear, I like the validators thing, and I think we probably should come back to it some time soon! It's just that it is not 100% clear to me if they are indeed a better fit than just handling attributes directly in the parser, and I am not ready to dive into validators design right now :)

**Comment by vipentti** [comment]
Sounds good! Actually thinking about it, it would probably be simpler to handle attributes and errors related to them in the parser at least on some level.

**Pull request merged**
