### PR TITLE
Ignore cancelled inlay hints responses

### LINKED ISSUE #1607: Inlay hints update too fast
It's a very good feature but currently, it changes too fast with every keystroke backing to {unknown}. If it can stay as where they are and update when ready, that would be much nicer to use.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Fixes #1607

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
What do I do wrong?

image

**Comment by matklad** [comment]
>What do I do wrong?

I wish I knew! Doing investigation right now

**Comment by lnicola** [comment]
Have you summoned me?

```diff
-            return editor.setDecorations(typeHintDecorationType, newDecorations);
+            return editor.setDecorations(
+                typeHintDecorationType,
+                newDecorations
+            );
```

**Comment by matklad** [comment]
>Prettier is also up-to-date:

CI is using 1.17 though, for *some* reason

**Comment by matklad** [comment]
https://travis-ci.org/rust-analyzer/rust-analyzer/jobs/564863471#L246

**Comment by SomeoneToIgnore** [comment]
> CI is using 1.17 though, for some reason

It's a lockfile that causes it to be used.
I've checked with that version also — same result.

**Comment by lnicola** [comment]
I use Arch BTW.

**Comment by SomeoneToIgnore** [comment]
I use macOS, this might be the reason.
I can try out how it works on my linux desktop in the evening.

**Comment by matklad** [comment]
I've upgraded prettier on CI to 1.18. 

bors r+

**Comment by lnicola** [comment]
@matklad does Travis have a clone of the repository or just the source code? Can we run `git diff` for cases like these? And also for contributors who submit a drive-by PR and would rather not bother with `npm` tools.

**Comment by matklad** [comment]
I guess, it should be the job of prettier to print the diff, but yeah, we can probably just use `git diff`...

So, `npm run prettier && git diff` should work, right?

**Comment by SomeoneToIgnore** [comment]
Or maybe use `--fix` as in https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/package.json#L24 ?

**Comment by bjorn3** [comment]
> @matklad does Travis have a clone of the repository or just the source code?

A shallow clone (eg only the last ... comment):

```bash
$ git clone --depth=50 https://github.com/rust-analyzer/rust-analyzer.git rust-analyzer/rust-analyzer
```

**Comment by lnicola** [comment]
> So, `npm run prettier && git diff` should work, right?

I think that would always return success. Maybe `npm run prettier; ret=$?; ret || git diff; exit $ret` or something like that?

**Comment by matklad** [comment]
>I think that would always return success.

TIL about `git diff --exit-code`

**Comment by SomeoneToIgnore** [comment]
JFYI everything works on my Linux machine.

**Pull request merged**
