### PR TITLE
Make ty and ty::primitives public.

### PR DESCRIPTION
**Pull request by eonil**
Expose some HIR types to fix https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Accessing.20ra_hir.3A.3Aty.3A.3Aprimitive.3A.3A*.20.3F

### CODE REVIEW

**Comment by matklad** [comment]
Hm, but these types are reexported via https://github.com/rust-analyzer/rust-analyzer/pull/2204/files? Have I missed something?

**Comment by eonil** [comment]
I'll check up again.

**Comment by eonil** [comment]
I think your patch should make it to work, but it doesn't work for me with this error. I'm not expert on Rust syntax and I don't know why. Maybe I am doing something wrong?

```rust
error[E0603]: module `ty` is private
 --> src/main.rs:3:17
  |
3 |     use ra_hir::ty::primitive::UncertainIntTy;
  |                 ^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0603`.
error: could not compile `using_ra_hir_prim_1`.
```

Here's how I reference `ra_hir` crate in `Cargo.toml`.

```rust
[dependencies.ra_hir]
git = "https://github.com/rust-analyzer/rust-analyzer"
rev = "3dff405443e23a551429d224b6a676361cc6574d"
```

Here's test project to reproduce the issue: https://github.com/eonil/tmp-using_ra_hir_prim_1

I am using stable `rustc 1.39.0 (4560ea788 2019-11-04)` installed with `rustup update`.

**Comment by matklad** [comment]
you should

```
use ra_hir::UncertainIntTy;
```

The types are re-exported at the root of the hri crate

**Comment by eonil** [comment]
It was my fault. Thanks and sorry.

**Pull request closed without merging**
