### PR TITLE
Add <> when completing generics

### PR DESCRIPTION
**Pull request by matklad**
@flodiebold wdyt? Is it correct that we always need to add `<>` in generic types?

### CODE REVIEW

**Comment by matklad** [comment]
Yeah, there's a test that checks that if all params have defaults we don't add `<>`

**Comment by flodiebold** [comment]
Maybe I'm missing something, but won't this insert angle brackets when I write
```rust
let x = Vec
```
which are not just unnecessary, but also a syntax error?

**Comment by matklad** [comment]
Nope, as we check that path is in the type context: https://github.com/rust-analyzer/rust-analyzer/pull/1970/files#diff-3426e56c8c2815f5242454e3159a019cR183

**Pull request merged**
