### PR TITLE
Fix memory usage metrics

### PR DESCRIPTION
**Pull request by jonas-schievink**
Let's see if this fixes https://github.com/rust-analyzer/rust-analyzer/issues/6808

bors r+

### CODE REVIEW

**Comment by lnicola** [comment]
Nope, it's still not there: https://raw.githubusercontent.com/rust-analyzer/metrics/master/metrics.json

**Comment by jonas-schievink** [comment]
Metrics for this PR are still being computed: https://github.com/rust-analyzer/rust-analyzer/runs/1537884275

**Comment by lnicola** [comment]
Maybe it's a PR vs. bors thing? JSON already has:

```json
{"host":{"os":"Ubuntu 18.04.5 LTS","cpu":"Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz","mem":"7121292 kB"},"timestamp":1607696116,"revision":"f304ce329f5c40f52572be7dbe29224033516c10","metrics":{"analysis-stats/ripgrep/total time":[7445,"ms"],"analysis-stats/ripgrep/type mismatches":[5,"#"],"analysis-stats/ripgrep/unknown type":[151,"#"],"analysis-stats/self/total time":[32484,"ms"],"analysis-stats/self/type mismatches":[583,"#"],"analysis-stats/self/unknown type":[1602,"#"],"analysis-stats/webrender/total time":[14633,"ms"],"analysis-stats/webrender/type mismatches":[216,"#"],"analysis-stats/webrender/unknown type":[1520,"#"],"build":[449229,"ms"]}}
```

**Comment by jonas-schievink** [comment]
That's for a different PR: https://github.com/rust-analyzer/rust-analyzer/commit/f304ce329f5c40f52572be7dbe29224033516c10

**Comment by lnicola** [comment]
D'oh, right, sorry.

**Comment by jonas-schievink** [comment]
Metrics are only computed when something is pushed to master

**Comment by jonas-schievink** [comment]
```
Measuring analysis-stats/self
Error: command `./target/release/rust-analyzer analysis-stats --quiet --memory-usage .` failed, exit code: 101
```

:thinking:

**Comment by jonas-schievink** [comment]
That command works fine locally

**Pull request merged**
