### PR TITLE
Remove TextMate grammar

### LINKED ISSUE #6267: Latest nightly seems to ignore semantic highlighting settings
I have semantic highlight disabled via the configuration below. The latest nightly seems to ignore it now and always applies semantic highlighting. I've also tried to disable it via the global `Editor -> Semantic Highlighting: Enabled` setting.

Disabling of semantic highlighting worked as expected prior to `rust-analyzer version: nightly (f0412da)`.

```json
   "editor.semanticTokenColorCustomizations": {
        "[Atom One Dark]": {
            "enabled": false,
        }
    },
```

EDIT: Per conversation below, the highlighting differences are attributed to a newly introduced grammar.

### PR DESCRIPTION
**Pull request by lnicola**
Closes #6267

This is now included upstream in VS Code.

### CODE REVIEW

**Comment by dustypomerleau** [comment]
bors r+

Thanks for all the feedback on this. I agree it's time to remove  - will simplify maintenance and give users more control.

**Comment by dustypomerleau** [comment]
Ah - appears I don't have the permissions to merge, @lnicola.

**Comment by lnicola** [comment]
bors r=dustypomerleau

**Pull request merged**
