### PR TITLE
syntax: return owned string instead of leaking string

### PR DESCRIPTION
**Pull request by cynecx**
Quick hack? to alleviate https://github.com/rust-analyzer/rust-analyzer/issues/8181#issuecomment-806019126. I haven't run any tests but this should affect performance since we are deallocating more.

r? @matklad

### CODE REVIEW

**Comment by iDawer** [comment]
I wonder if this can be made with closures:

```rust
impl ast::Name {
    pub fn process_text<T, F: FnOnce(&str) -> T>(&self, f: F) -> T {
        let green = self.syntax().green();
        let text = text_of_first_token(&green);
        f(text)
    }
}
```

Does it make sense? I'm playing with it right now

**Comment by matklad** [comment]
I think that'd make API complicated I think. The perfect soulution is to clone the green token (arc bump), and return that, viewed as a string.

I wonder if just `-> impl Deref<str>` would work?

**Comment by matklad** [comment]
@matklad shakes fist at Gmail for not delivering an email reply :zap: :zap: :zap: 

LGTM, but let's use SmolStr rather than String. Or, if that works out, you can try the impl Deref trick. 

bors d+

**Comment by cynecx** [comment]
@matklad

> Or, if that works out

You mean when when it doesn't work out?

**Comment by cynecx** [comment]
> The perfect soulution is to clone the green token (arc bump), and return that, viewed as a string.

I think that would require some (non-trivial?) changes to rowan because we would need some kind of Wrapper that combines an Arc and offset to the children, no?

Either way, I think that can be done in a future revision :)

bors r+

**Comment by lnicola** [comment]
image

This almost got us back to the pre-clone-for-update memory usage.

**Pull request merged**
