### PR TITLE
vscode: fix the default value for withSysroot

### PR DESCRIPTION
**Pull request by Veetaha**
See [zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/withSysroot.20is.20false.20.3F)
cc @edwin0cheng

### CODE REVIEW

**Comment by edwin0cheng** [comment]
Checked out in m machine and it works. Thanks a lot. 
But I wonder whether there are some configs options have same problem. 
E.g `useClientWatching` ?

**Comment by Veetaha** [comment]
I don't think so. `withSysroot` is the only special config value that is not registered in `package.json`. All other properties do have default values specified in `package.json`

**Comment by SomeoneToIgnore** [comment]
There was at least `maxInlayHintLength` setting that turned off the shortening when `null` was set there.
Is it the way it works still?

**Comment by Veetaha** [comment]
Hmm, I did @SomeoneToIgnore , but the default value for maxInlayHintLength was and is 20

**Comment by SomeoneToIgnore** [comment]
True, I've just thought about other places where nulls could be lost after the refactoring.
I cannot check it myself now whether it works or now, hence saying that there's another obscure place worth checking.

**Comment by Veetaha** [comment]
@SomeoneToIgnore we actually declared `maxInlayHintLength` as non-nullable [in json schema](https://github.com/rust-analyzer/rust-analyzer/blob/d9767727168c68b4ecf930c9dab5a950c0be8e7b/editors/code/package.json#L248-L253), but in config we [declared it nullable](https://github.com/rust-analyzer/rust-analyzer/blob/34241b9af966208d73f37f1cdf7f862f2590d846/editors/code/src/config.ts#L28) for some reason. I remember @matklad saying
> [if something looks like it doesn't make sense  it probably indeed doesn't make sense](https://github.com/rust-analyzer/rust-analyzer/pull/2911#discussion_r371176578)

And I said that we should always doubt that and double-check with the team, so I was right...
Do we need to change `maxInlayHintlength` to accept `null` values and/or make `null` the default?

**Comment by SomeoneToIgnore** [comment]
Thanks for checking it, so there's a mistake after all :(

Feature-wise, I'd appreciate some way to disable inlay hints shortening.
How to implement it is a more difficult question, looks like `null`'s confuse everybody, so maybe we should refactor the settings again somehow.

**Comment by SomeoneToIgnore** [comment]
And yes, the `null` value was used to disable that shortening initially, so maybe that's the reason for having it this way in the config.

**Comment by Veetaha** [comment]
@SomeoneToIgnore, you can explicitly set `null` to `rust-analyzer.maxInlayHintsLength`, though vscode will yell at you, but do what you wanted:
image.

We don't validate our config at runtime and I wrote a comment on that here:
https://github.com/rust-analyzer/rust-analyzer/blob/a15c8739b9a6da223e1f3a6ff6aa868913c0dbf4/editors/code/src/config.ts#L141-L142

So, yes, you can pass `null`, but this way our static cast `null as number` will be unsound (though the extension doesn't actually read this specific config value and just passes it to `ra_lsp_server` so it won't crash)
https://github.com/rust-analyzer/rust-analyzer/blob/a15c8739b9a6da223e1f3a6ff6aa868913c0dbf4/editors/code/src/config.ts#L148

And we will end up with deceiving our type system. Though I think in this particular situation we have a right to **blame the user**, since he was warned by vscode that he is passing an invalid value.

**Comment by Veetaha** [comment]
Instead of `null` the user may pass a string `"maxInlayHintLength": "inf"`, though `null` lgtm.

**Pull request merged**
