### PR TITLE
internal: move diagnostics to hir

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by flodiebold** [comment]
Hmm yes it goes in the direction, but I wouldn't have expected the diagnostics to just move to `hir`, rather than all the way to `ide`? I think my vision is basically how the field shorthand diagnostic is already implemented, actually. But there would have to be an interface for the various kinds of diagnostics in `hir`, of course :thinking:

**Comment by matklad** [comment]
Argh, I think I shifted one time to much. This moves diagnostic infra to hir_ty. I want to move it to hir as the end state, not to the ide. The fixes will leave in the ide though.

Not sure where most of diagnostic tests should live: I kinda want all tests to belong to crates actually emitting the specific diagnostics, but it certainly is easier to test at the level where you have generic infra.

**Comment by flodiebold** [comment]
I thought I wrote that badly :sweat_smile: I'd have expected diagnostics infra to move to `ide` in the end. I'd see testing for when diagnostics are emitted in the respective crates, and testing diagnostic descriptions and quickfixes in `ide`.

**Comment by matklad** [comment]
So what I think we want in the end is 

* `hir_xxx` emit raw diagnostics, something like `DefDiagnostic` which has local id in it as a public filed.
* in `hir`, we re-formulate that it terms of hir-types. We go from (potentially local) ids to global unique ids. This step doesn't involve traits -- just translating one struct into another
* in `ide_diagnostics`, we have have traits like `DiagnosticWithFix` and `Diagnostic`, which we implement for `hir` types. We might even end-up not using traits there, as there's no real need (and definitelly no dynamic dispatch)
* `ide_diagnostics` also implements a bunch of lints which do not need privileged access to compiler data structures 

In terms of diff with this PR, the type definitions in `hir::diagnostic` stay, while `impl Diagnostic for` go away.

**Comment by flodiebold** [comment]
Agree, I think we probably don't need the traits.

**Pull request merged**
