### PR TITLE
Fix array element attribute position

### PR DESCRIPTION
**Pull request by edwin0cheng**
This PR fixed a bug which an ATTR node insert in the wrong place in array element. ~~And introduce `precede_next` for allow outer attributes to insert into a parsed `expr`.~~  

related #2783

### CODE REVIEW

**Comment by matklad** [comment]
I think it should be possible to achieve this without `precede_next`. We already handle this in some cases:

```rust
const _: &str = { #[attr] "Hello" };
```

```
CONST_DEF@[33; 69)
  CONST_KW@[33; 38) "const"
  WHITESPACE@[38; 39) " "
  UNDERSCORE@[39; 40) "_"
  COLON@[40; 41) ":"
  WHITESPACE@[41; 42) " "
  REFERENCE_TYPE@[42; 46)
    AMP@[42; 43) "&"
    PATH_TYPE@[43; 46)
      PATH@[43; 46)
        PATH_SEGMENT@[43; 46)
          NAME_REF@[43; 46)
            IDENT@[43; 46) "str"
  WHITESPACE@[46; 47) " "
  EQ@[47; 48) "="
  WHITESPACE@[48; 49) " "
  BLOCK_EXPR@[49; 68)
    BLOCK@[49; 68)
      L_CURLY@[49; 50) "{"
      WHITESPACE@[50; 51) " "
      LITERAL@[51; 66)
        ATTR@[51; 58)
          POUND@[51; 52) "#"
          L_BRACK@[52; 53) "["
          PATH@[53; 57)
            PATH_SEGMENT@[53; 57)
              NAME_REF@[53; 57)
                IDENT@[53; 57) "attr"
          R_BRACK@[57; 58) "]"
        WHITESPACE@[58; 59) " "
        STRING@[59; 66) "\"Hello\""
      WHITESPACE@[66; 67) " "
      R_CURLY@[67; 68) "}"
  SEMI@[68; 69) ";"
```

Seems like this can be extended to arguments as well.

The case above is handled by `stmt` function, it works roughly like this:

```rust
let m = p.start();
let has_attrs = p.at(T![#]);
attributes::outer_attributes(p);

let (cm, _) = expr_stmt(p);

if let Some(cm) = cm {
    let kind = cm.kind();
    cm.undo_completion(p).abandon(p);
    m.complete(p, kind);
}
```

**Comment by edwin0cheng** [comment]
Fixed. 👍

**Comment by edwin0cheng** [comment]
bors retry

**Pull request merged**
