### PR TITLE
Remove old syntax highlighting

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by Geobert** [comment]
What happen to guys like me that doesn't run VSCode insider?

**Comment by matklad** [comment]
You need to wait until this feature stabilizes in VS code. 

Maintaining our own ad-hock hacky workarounds is costly, with our resources, the more prudent approach is to spend efforts test-driving the proposed official API.

**Comment by Geobert** [comment]
Sorry I was not clear enough in my question: do we still have syntax highlighting with VSCode stable? :)

I understand why you're doing this and I think it's the correct move.

**Comment by matklad** [comment]
you still have the old text-mate based syntax highlighting, only the semantic bits (like underlining the mut variables) are gone.

**Pull request merged**
