### PR TITLE
Fix thread priority problems on windows

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors try

**Comment by matklad** [comment]
bors try

**Comment by matklad** [comment]
bors try

**Comment by lnicola** [comment]
Would it make sense to reduce the priority of the thread pool threads instead? This way it would work on other platforms, too.

**Comment by matklad** [comment]
bors try

I would have lowered  thread pool priority, but there’s no easy api to customize thread creation. But it seems to be orthogonal to being cross platform? 


Ideally, I’d prefer to not tweak propiorities at all and just rely on fairness, but on windows we specifically hit an unfair case.

**Comment by lnicola** [comment]
> I would have lowered thread pool priority, but there’s no easy api to customize thread creation.

Ah, I missed that. I know that some crates like `rayon` have a thread creation callback, but `threadpool` doesn't. I was under the impression that you've recently switched to a different thread pool implementation, but no, it's the same one.

> But it seems to be orthogonal to being cross platform?

On Linux you can decrease a thread's priority (_nice_), but not increase it unless you have `CAP_SYS_NICE`.

In general, I wouldn't expect schedulers to be fair. They're a mess of heuristics (like the priority boosting that Windows does in some cases) that either improve responsiveness or throughput. In the recent discussion about user-space spinlocks, Torvalds [pointed out](https://www.realworldtech.com/forum/?threadid=189711&curpostid=189723) that fairness is bad for throughput, on smaller systems, but:

> Pretty much every time we picked an unfair - but fast - locking model in the kernel, we ended up regretting it eventually, and had to add fairness.

**Pull request merged**
