### PR TITLE
feat: Add very simplistic ident completion for format_args! macro input

### PR DESCRIPTION
**Pull request by Veykril**

### CODE REVIEW

**Comment by lnicola** [comment]
This doesn't seem to work for me:

```rust
fn main() {
    let world = "world";
    println!("Hello, {w}")
}
```

panics with "thread '<unnamed>' panicked at 'byte index 16 is out of bounds of `"Hello, {w}"`'", with or without the closing brace.

**Comment by Veykril** [comment]
lets revert this PR for now then I guess?

**Comment by lnicola** [comment]
https://user-images.githubusercontent.com/308347/152745371-f6b9a801-ddf1-41ae-afc1-c148f7bfddef.mp4

**Pull request merged**
