### PR TITLE
reformant to use small heuristics

### PR DESCRIPTION
**Pull request by matklad**
What do folks think about enabling this rustfmt option?

cc https://internals.rust-lang.org/t/running-rustfmt-on-rust-lang-rust-and-other-rust-lang-repositories/8732/81

### CODE REVIEW

**Comment by matklad** [comment]
image

**Comment by killercup** [comment]
I personally like this style better but it is at the cost of having the next diffs be slightly larger, when rustfmt eventually has to switch to the taller style when lines get longer.

**Comment by kjeremy** [comment]
I like this

**Comment by DJMcNab** [comment]
I'm in favour of this, even though I have a PR open.

**Comment by kjeremy** [comment]
I think we should do this.

**Comment by matklad** [comment]
reformatted!

**Pull request closed without merging**
