### PR TITLE
Add assist to sort members alphabetically.

### PR DESCRIPTION
**Pull request by vsrs**
Supports traits, impls, structs, unions and enums (including inner struct variants). Does not support modules yet.

```rust
en┃um Animal {
  Dog(String, f64),
  Cat { weight: f64, name: String },
}
```
->
```rust
enum Animal {
  Cat { weight: f64, name: String },
  Dog(String, f64),
}
```
---
```rust
enum Animal {
  Dog(String, f64),
  Cat {┃ weight: f64, name: String },
}
```
->
```rust
enum Animal {
  Dog(String, f64),
  Cat { name: String, weight: f64 },
}
```
---
More samples in docs https://github.com/vsrs/rust-analyzer/blob/0b7835619a3ec7fdc5c11e6ab001ad452314a3f2/crates/ide_assists/src/handlers/sort_items.rs#L12-L83.

Relates #6110

### CODE REVIEW

**Comment by matklad** [comment]
I am of two minds here. 

On the one hand, some people do want to sort stuff alphabetically, and this assist would be sometimes useful to them. 

On the other hand, many (most?) people don't sort alphabetically (I always go for semantic, "suggested reading order" sorting), and for them such an assist would be a sizable negative.

We clearly need to support the need of the first category of Rust programmers, but we also clearly don't want to tax the second category. 

Is there some way to handle both? Perhaps the time has come to introduce config for assists?

**Comment by Lokathor** [comment]
I'm most interested in the module sorting, and I would also like it to be configurable what the sorting of a module is. Eg, which group of item goes first.

But yeah, this should only happen precisely when the user commands it, not just all the time. In vs code this could be a new action that the user can do from the command menu or from a keybind. I'm not sure if that works well with other editors or not.

**Comment by vsrs** [comment]
@matklad 

Well, actually I don't think anyone would use sorting for impl, not even myself :) But it's very convenient for enums (and sometimes trait methods), I'm working now on big rust codebase with tons of algebraic data and such sorting really helps. I've supported impls and struct just to be complete.

> and for them such an assist would be a sizable negative.

Did you mean that it's a distraction (annoying bulb\quick fix suggestion) and/or a waste of resources (takes time to analyze if the assist is applicable)? If so, we can make this assist very lightweight - enable it only when an item is selected. I believe something like this at the beginning should work:
```
    if ctx.frange.range.is_empty() {
        return None;
    }
```
Separate configuration option seems like a overkill to me.

As for sorting modules, this is not that easy. Pure alphabetical sorting is not suitable, of course. And all developers have their own style and preferences, so we need some templates. But I have never seen good implementations\analogues. For C# there are VS native templates and Resharper templates, but both are extremely inconvenient.

And one more interesting question: where should these templates be? In rust-analyzer or rustfmt?

**Comment by matklad** [comment]
>Did you mean that it's a distraction (annoying bulb\quick fix suggestion) and/or a waste of resources (takes time to analyze if the assist is applicable)?

Exactly! 

> enable it only when an item is selected

That's absolutely brilliant! 

One day, we should also add tutorials for such assists -- like in moden games, when you first are in a context where an action is applicable, there's a popup showing a shortcut. 

Ideally, we should do this for all new assists -- you should get a :star: or something instead of :bulb: if there's an assist you haven't tried before. Out of scope for the PR obviously.

**Comment by matklad** [comment]
>As for sorting modules,

Yeah, I think that's sufficently different from project-to-project that anything pre-configured wouldn't work. Long term, I hope we expose a programming API such that each project can implement their own "macro styling rule" by writing a rust program on top of those API.

**Comment by Lokathor** [comment]
The configuration for sorting modules does not have to be complex. You could have a config option that's a list of item types (eg: struct, enum, const, etc) and they're sorted according to the priority in the list, with unlisted items getting some default sort order at the end.

**Comment by vsrs** [comment]
@matklad,

> > enable it only when an item is selected

> That's absolutely brilliant!

 I've changed the behavior

**Comment by vsrs** [comment]
@Lokathor

> The configuration for sorting modules does not have to be complex. 

Let's assume this code:

```rust
trait Foo {}

struct A {}
impl A{}
impl Drop for A{...}
impl Foo for A {}

struct B {}
impl B{}
impl Foo for B {}
```
For example, I want to have all struct's impls right after the struct. How can this be configured?

**Comment by Lokathor** [comment]
sort_order: ["trait", "struct"],

**Comment by matklad** [comment]
>t, I did not even imagine that it would be configurable to separate a struct's impls from a struct. That would be so completely foreign to my bra

FWIW, this is exactly what rust-analyzer is doing :-) [Example](https://github.com/rust-analyzer/rust-analyzer/blob/5664a2b0b31403024ce5ab927760d630d5ddc9a4/crates/text_edit/src/lib.rs#L8-L184), and [style guide rule](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/style.md#order-of-items). The TL;DR of the rationale is that data is more important than algorithms, so it helps when *all* struct&enums are declared at the start of the file. 

bors r+

**Comment by matklad** [comment]
Sorry for not r+ing this last week, sad to see that it slipped the release :(

**Comment by lnicola** [comment]
sort-fields

(note the slight inconsistency here: to sort the variants of `Animal` I have to select the enum name, but to sort the fields of `Cat` I have to select the fields themselves)

**Comment by vsrs** [comment]
> (note the slight inconsistency here: to sort the variants of `Animal` I have to select the enum name, but to sort the fields of `Cat` I have to select the fields themselves)

Indeed. I processed only RECORD_FIELD_LIST and forgot about VARIANT itself. Thanks, I'll fix this.

**Pull request merged**
