### PR TITLE
Move README so the root directory has less files

### PR DESCRIPTION
**Pull request by ice1000**
As title.

### CODE REVIEW

**Comment by matklad** [comment]
I feel like `README.md` is something that is valuable to keep at root, as it's the first thing a new user/contributor should take a look at.

**Comment by ice1000** [comment]
But GitHub will still display `.github/README` on the frontpage of the repo.

**Comment by ice1000** [comment]
Like this: https://github.com/ocornut/imgui

**Comment by matklad** [comment]
Github does, but `git clone git@github.com:rust-analyzer/rust-analyzer.git && cat rust-analyzer/README.md` doesn't. Not everyone knows that readme can also be found in `.github`. I certainly didn't before this PR :)

**Comment by ice1000** [comment]
Ok.

**Comment by ice1000** [comment]
Psst: I @you in zulip, can you take a look at the question?

**Pull request closed without merging**
