### PR TITLE
README: Add some instructions for running typescript tests and linter.

### PR DESCRIPTION
**Pull request by davidlattimore**

### CODE REVIEW

**Comment by davidlattimore** [comment]
I created a PR yesterday and had a tslint error when CI ran so went looking for instructions on how to run the linter but couldn't find any. I don't know if what I've written here is necessarily the best way, but it's what I found that worked.

**Comment by lnicola** [comment]
I've also used `npm run vscode:prepublish` to see the errors, but it might be covered by `npm run ci`.

**Comment by matklad** [comment]
bors r+

Note that we are moving the frontend code to https://github.com/rust-lang/vscode-rust

**Pull request merged**
