### PR TITLE
Upgrade Chalk

### PR DESCRIPTION
**Pull request by flodiebold**
Also make overflow depth and max type size configurable through env variables. This can be helpful at least for debugging.

Tests currently fail because of rust-lang/chalk#656, so we'll need to wait for the next update to merge this.

### CODE REVIEW

**Comment by jackh726** [comment]
@flodiebold that PR is merged; feel free to do a release for Chalk if you want to merge this before the release next weekend

**Comment by kjeremy** [comment]
@flodiebold Chalk 41 has been released which contains your fix.

**Comment by flodiebold** [comment]
@kjeremy Yeah, but it also causes #6628, so I think we have to wait a bit longer...

**Comment by kjeremy** [comment]
😢

**Comment by cynecx** [comment]
https://github.com/rust-lang/chalk/issues/658 has been closed, so https://github.com/rust-analyzer/rust-analyzer/issues/6628 should work now?

**Comment by flodiebold** [comment]
It should, but there's no new Chalk release yet.

**Comment by jackh726** [comment]
@flodiebold 0.43 has been released.

**Comment by lnicola** [comment]
Looks like this brought a nice perf improvement, cc @jackh726:

image

image

**Comment by jackh726** [comment]
@lnicola wow! That's impressive. I didn't even think about it, but that's probably the fold by value change. I'm actually really shocked, because when the same thing was implemented in rustc, IIRC there wasn't a huge perf win.

**Comment by matklad** [comment]
While we are at this exciting topic, has anyone by any chance looked at enabling instruction counts on github actions?

**Comment by lnicola** [comment]
Last time we tried, it didn't seem to work, probably because of security limitations. And on the topic of metrics, we're no longer reporting memory usage since https://github.com/rust-analyzer/rust-analyzer/pull/5581.

**Comment by flodiebold** [comment]
I think rust-lang/chalk#638 might also have played a role; I think/hope it's preventing us from enumerating all impls for a trait in a lot of cases where we previously would.

**Comment by jackh726** [comment]
> I think [rust-lang/chalk#638](https://github.com/rust-lang/chalk/pull/638) might also have played a role; I think/hope it's preventing us from enumerating all impls for a trait in a lot of cases where we previously would.

Ah. That seems a bit more likely to me.

**Pull request merged**
