### PR TITLE
Update crates

### PR DESCRIPTION
**Pull request by kjeremy**
Removes duplicate crossbeam crates.

### CODE REVIEW

**Comment by lnicola** [comment]
@matklad not sure since when, but one of the tests is now failing:

`thread 'body::scope::tests::infer_resolve_while_let' panicked at 'mark was not hit', crates/test_utils/src/marks.rs:79:9`

**Comment by kjeremy** [comment]
@lnicola Hm... I ran a `cargo test` before submitting this and it passed on my windows 10 machine.

**Comment by matklad** [comment]
Should be fixed by https://github.com/rust-analyzer/rust-analyzer/pull/2340

**Pull request merged**
