### PR TITLE
Freshen docs for prebuilt binaries and raLspServer setting

### PR DESCRIPTION
**Pull request by Veetaha**
Better documented breaking changes as per an incident in #2988
Follow up for #3053

### CODE REVIEW

**Comment by Veetaha** [comment]
Wait

**Comment by Veetaha** [comment]
Can you cancel please? @matklad

**Comment by Veetaha** [comment]
Added more docs, now we are ready to merge!

**Comment by Veetaha** [comment]
This also closes #3007

**Comment by Veetaha** [comment]
Also **BREAKING CHANGE** I increased the requirements for nodejs to from `v10` to `v12` if I have such a luxury anyway...

**Comment by Veetaha** [comment]
One more little fix, now we are 100% ready! :sweat_smile:

**Comment by Veetaha** [comment]
@matklad

**Comment by alvinhochun** [comment]
Think the top-level `README.md` also needs updating? It still suggests building from source for "quick start". It doesn't mention the VSCode extension being available on the marketplace.

**Pull request merged**
