### PR TITLE
internal: clarify who a rls-2.0 wg

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by edwin0cheng** [comment]
I have to login to see these links, so maybe not a good idea to put in the doc ?

**Comment by matklad** [comment]
@edwin0cheng logging in I think is OK, but needing to be on the team is a bummer... Added a clarification about that. 

We need to think how to make this more transparent. There's def a bunch of issues here:

* you can't see the team if you are not on the team already
* we don't have transparent rules for how people go on and off the team (I think I've added every one of you personally? That's definitely a bug)
* we are not using rust-lang teams infra...

Note, however, that there are some advantages to the current setup I'd rather not loose:

* convenient single source of truth, which is synced with bors
* adding people is easy -- roughly, everyone who sticks around for some time gets r+ without a special process/extra coordination.

**Comment by edwin0cheng** [comment]
Maybe we could add some CI step to fetch that list from bors-ng and rewrite it to our doc in the future ?

Anyway, 

bors r+

**Pull request merged**
