### PR TITLE
Add benchmark tests for mbe

### PR DESCRIPTION
**Pull request by edwin0cheng**
This PR add more real world tests dumped from `rust-analyzer analysis-stats .` to benchmark its performance.

cc #7513

r? @matklad

### CODE REVIEW

**Comment by edwin0cheng** [comment]
CI had passed. I forgot I have to ignore some tidy tests in test fixtures :)

**Comment by matklad** [comment]
Hm, 6mb file seems a bit excessive to keep in git repo :rofl: 

It was generated by some code, right? Lets' maybe ignore this file via .gitignore, but commit the code to create it. So that benchmargks look like this:

```
#[test]
fn benchmark_foo() {
    if skip_slow_tests() { return; }
    // Uses Once to create `target/bench_data/lotsofrust.rs`
    let bf = BenchmarkFixtures::new();
    let file: String = bf.get("many-macros.rs").
}
```

I think it does make sense to write to disk, so that benchmark generation doesn't affect profiles

**Comment by edwin0cheng** [comment]
Its generated by some hacky awk scripts and adhoc dbg output... but well, I agree that it is too large :)

Let me try to write a proper generation code and see how’s it is.

**Comment by edwin0cheng** [comment]
Instead of a large file for macro invocation fixtures, I am able to generate invocations from `MacroRules`. The generate code itself is quite fast (and dirty) so I decided no need to write it back to disk.

It is ready to review again :)

**Comment by matklad** [comment]
bors r+


Nice!

**Pull request merged**
