### PR TITLE
cargo-watcher: Resolve macro call site in more cases

### PR DESCRIPTION
**Pull request by kiljacken**
This resolves the actual macro call site in a few more cases, f.x. when a macro invokes `compile_error!` (I'm looking at you `ra_hir_def::path::__path`).

### CODE REVIEW

**Comment by kiljacken** [comment]
Also adds a related information item to the error pointing to the actual source of the error:
image

**Comment by lnicola** [comment]
Some tests need to be updated, I think.

**Comment by kiljacken** [comment]
That's what I get for not running insta review last. Should be fixed.

**Pull request merged**
