### PR TITLE
In `RootConfig::contains`, check against canonicalized version of root path

### PR DESCRIPTION
**Pull request by pnkfelix**
In `RootConfig::contains`, check against canonicalized version of root path since OS may hand us data that uses the canonical form rather than the root as specified by the user.

This is a step towards a resolution of issue #734 but does not completely fix the problem there.

### CODE REVIEW

**Comment by matklad** [comment]
Looks like code formatting check has failed. You might want to run `cargo format-hook` in the root of the repository once to install a pre-commit hook to do `rustfmt`.

**Comment by matklad** [comment]
r=me with formatting fixed

**Comment by vipentti** [comment]
NOTE: `canonicalize` may cause some problems on Windows. This may not be an issue in this case.

see #821

**Pull request merged**
