### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by kjeremy**

### CODE REVIEW

**Comment by pnkfelix** [comment]
Did the update to `insta = 0.7.0` here cause the JSON output to change? I'm seeing a bunch of insta snapshot mismatches that all appear to be due to newly injected trailing commas in the generated JSON output.

**Comment by matklad** [comment]
Are you building rust-analyzer with nightly? The Debug format changed in nightly, that’s why the tests could fail

**Comment by pnkfelix** [comment]
What rust channel am I supposed to build iwth?

When I use stable, I get an error like this:

```
     Running target/debug/deps/ra_batch-1c83502d4551a596

running 1 test
test tests::test_loading_rust_analyzer ... FAILED

failures:

---- tests::test_loading_rust_analyzer stdout ----
thread 'tests::test_loading_rust_analyzer' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "can\'t l\
oad standard library from sysroot\n\"/home/pnkfelix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src\"\\
ntry running `rustup component add rust-src`" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by matklad** [comment]
The CI (and I personally) use stable.

Have you tried

```rustup component add rust-src```

?

**Comment by pnkfelix** [comment]
Yes, I did that in the past.

Doing it again says:

```
% rustup component add rust-src
info: component 'rust-src' is up to date
%
```

**Comment by pnkfelix** [comment]
(Let me trying changing my default to `stable` and seeing if that changes the behavior of `rustup component add`)

**Comment by matklad** [comment]
opened https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/building.20with.20stable for more real-time troubleshooting

**Comment by pnkfelix** [comment]
Okay that was the problem: `rustup component` is sensitive to the current channel, and I didn't realize that.

**Pull request merged**
