### PR TITLE
Bump default CHALK_SOLVER_MAX_SIZE to 150

### LINKED ISSUE #10673: `Itertools::max` is misdetected as `Ord::max`, resulting in `expected 1 argument, found 0` error
## Steps to reproduce

Create a new bin crate, and replace `src/main.rs` with the following code.

`src/main.rs`
```rust
fn main() {
    let _ = vec![vec![1, 2, 3]]
        .iter()
        .flat_map(|x| x.iter().flat_map(|x| Some(x)))
        .max()
        .unwrap();
}
```

When `edition = "2021"`, nothing is wrong.
When `edition = "2018"`, `rust-analyzer` points out that there is an error on the fifth line (`.max()`): `[rust-analyzer mismatched-arg-count] [E] expected 1 argument, found 0`.
Hovering on the `max` shows `core::cmp::Ord`, not `std::iter::Iterator`.

In both case, `cargo check` shows no errors or warnings.

Probably there is an issue in resolving traits in prelude.

## Version info
`rustup show`
```
active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.56.0 (09c42c458 2021-10-18)
```
`:CocInfo`
```
## versions

vim version: NVIM v0.6.0-dev+nightly-756-g8c74c895b
node version: v14.18.1
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/username/.vim/dein/.cache/init.vim/.dein
term: tmux
platform: darwin
```

### LINKED ISSUE #11072: RA unable to deduce the type of hashmap collected from iterator chain
**rust-analyzer version**: 2021-12-13

**rustc version**: 1.56.1

In this code example RA seems unable to figure out the type of the HashMap.
This gets resolved either by removing the second map, or by making the tuple something simpler, like `((0, 0), 0)`.
```
use std::collections::HashMap;

let _conversions = (0..1)
    .map(|_| (0, ((0, 0, 0), 0)))
    .map(|c| c)
    .collect::<HashMap<_, _>>();
```

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #11072
Fixes #10673

### CODE REVIEW

**Comment by lnicola** [comment]
```
# 30
Database loaded:     1.18s, 284minstr (metadata 979.53ms, 23minstr; build 103.92ms, 8754kinstr)
  crates: 39, mods: 834, decls: 18887, fns: 14088
Item Collection:     9.76s, 79ginstr
  exprs: 387133, ??ty: 395 (0%), ?ty: 288 (0%), !ty: 146                                                                                                             
Inference:           48.36s, 373ginstr
Total:               58.12s, 453ginstr

# 40
Database loaded:     629.35ms, 284minstr (metadata 421.20ms, 23minstr; build 107.17ms, 8736kinstr)
  crates: 39, mods: 834, decls: 18887, fns: 14088
Item Collection:     9.96s, 79ginstr
  exprs: 387133, ??ty: 369 (0%), ?ty: 223 (0%), !ty: 146                                                                                                             
Inference:           47.67s, 375ginstr
Total:               57.62s, 455ginstr

# 100
Database loaded:     650.64ms, 284minstr (metadata 431.63ms, 23minstr; build 101.20ms, 8742kinstr)
  crates: 39, mods: 834, decls: 18887, fns: 14088
Item Collection:     9.59s, 79ginstr
  exprs: 387133, ??ty: 350 (0%), ?ty: 174 (0%), !ty: 147                                                                                                             
Inference:           46.05s, 360ginstr
Total:               55.63s, 439ginstr

# 150
Database loaded:     622.19ms, 284minstr (metadata 422.41ms, 23minstr; build 104.36ms, 8760kinstr)
  crates: 39, mods: 834, decls: 18887, fns: 14088
Item Collection:     9.72s, 79ginstr
  exprs: 387133, ??ty: 350 (0%), ?ty: 173 (0%), !ty: 147                                                                                                             
Inference:           45.91s, 361ginstr
Total:               55.63s, 440ginstr

# 200
Database loaded:     650.20ms, 284minstr (metadata 444.47ms, 23minstr; build 100.37ms, 8760kinstr)
  crates: 39, mods: 834, decls: 18887, fns: 14088
Item Collection:     9.64s, 79ginstr
  exprs: 387133, ??ty: 350 (0%), ?ty: 173 (0%), !ty: 147                                                                                                             
Inference:           48.24s, 378ginstr
Total:               57.88s, 458ginstr
```

Thanks to @flodiebold for figuring this out!

**Comment by lnicola** [comment]
image

**Comment by TonalidadeHidrica** [comment]
Thanks for the fix!

**Pull request merged**
