### PR TITLE
Add snippet for derive

### PR DESCRIPTION
**Pull request by bnjjj**
A snippet I used a lot with RLS.

### CODE REVIEW

**Comment by matklad** [comment]
This is covered by add derive assist: https://twitter.com/rust_analyzer/status/1251175570643259392

**Comment by bnjjj** [comment]
Why not supporting both ? I feel more productive using only my keyboard and writing directly derive instead of writing my struct and then go back looking for an assist.

**Comment by kiljacken** [comment]
You should be able to invoke the assist from your keyboard. The shortcut might depend on your editor, but in VSCode fx. the default is ctrl+.

**Comment by SomeoneToIgnore** [comment]
As a side note, I think what would be cool is to provide a basic completion (with some hardcoded options) for the whole `#[derive(Debug, PartialEq, Eq)]` line, as Intellij does.

**Comment by flodiebold** [comment]
Yeah, I think completing `#[derive($0)]` before a struct declaration, and completing the built-in derives (and any in-scope proc-macro derives!), would be desirable, and a better solution than a simple snippet :slightly_smiling_face:

**Comment by matklad** [comment]
In general, we should complete attributes:

* https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt
* https://github.com/intellij-rust/intellij-rust/blob/master/src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt

**Comment by Ten0** [comment]
The question "why not support both?" seems to me like it still stands. I believe I'd be more comfortable starting to type derive than finding the corresponding assist.

**Comment by flodiebold** [comment]
That would be covered by the completion. (Really this is mostly a question of terminology, especially if we offer the completion even if you don't type the `#[`...)

**Comment by matklad** [comment]
>The question "why not support both?" seems to me like it still stands.

That's a good question. The general answer is that adding a new feature slightly decreases the benefit of all other features. The right solution to this problem is to suggest features depending on the context. 

That's why assists system is the most brilliant invention in the IDE space. In theory, Emacs' <kbd>M-x</kbd> can do anything a :bulb: can do. In practice, a :bulb: provides way more benefit to the users who see only a handful of options that make sense in this particular surrounding context. 

In this particular case, I feel like providing completion for attributes in general "top-level" context would be a net negative. I think Kotlin does the right thing here:

image

image

only after `@` is typed we are in a context where annotations are suggested.

**Pull request closed without merging**
