### PR TITLE
Remove VARIATION SELECTOR-16 in Run arrow

### PR DESCRIPTION
**Pull request by lnicola**
Closes #4446, cc @Veetaha.

### CODE REVIEW

**Comment by lnicola** [comment]
I feel there should be a space between "▶" and "Run Test", WDYT?

**Comment by kjeremy** [comment]
I like this one better... but can we use whatever vscode uses in it's debugger? Or if any of their bundled extensions uses one... we should at least be consistent.

**Comment by Veetaha** [comment]
Sure, but what has changed? I don't see any changes in the diff

**Comment by kjeremy** [comment]
@Veetaha 
image

**Comment by Veetaha** [comment]
Bruh, text rendering is so hard...

**Comment by Veetaha** [comment]
See https://microsoft.github.io/vscode-codicons/dist/codicon.html

**Comment by lnicola** [comment]
@Veetaha There was a (invisible) U+fe0f after the arrow, which asks for it to be rendered as an emoji. So we had U+25b6 U+fe0f U+fe0e, and the latter probably had no effect.

**Comment by Veetaha** [comment]
It does work @kjeremy

**Comment by kjeremy** [comment]
Wait... there was a PR related to this symbol and emojis and this may have been intentional. I actually thought that @Veetaha was the one who submitted it.

**Comment by kjeremy** [comment]
I had the person wrong :) #3091

**Comment by lnicola** [comment]
@kjeremy do you mean #4446 or an older one?

**Comment by lnicola** [comment]
Yeah, #3126 was incomplete because the emoji was already in there.

**Comment by lnicola** [comment]
I guess we could also use "⏵ Run Test" instead of "▶ Run Test".

**Comment by Veetaha** [comment]
??
image

**Comment by bjorn3** [comment]
image

**Comment by lnicola** [comment]
Okay, that's too thin. I think we shouldn't use the Code-specific solution.

**Comment by Veetaha** [comment]
Don't you think my PR works?

**Comment by lnicola** [comment]
This one is better.

**Comment by hhiraba** [comment]
It looks fine also in my environment, which is gnome-terminal + neovim + coc.nvim.
Screenshot from 2020-05-14 00-11-10

(my env interpret U+25b6's width as half, but It ’s okay because they don’t overlap...)

**Comment by Veetaha** [comment]
Btw, white themed ide???
image

**Comment by edwin0cheng** [comment]
I like this one more too. 

My 5 cent: 

how about we use an env variable like : `RA_PLAY_SYM` to let user overwrite the symbol ?

**Comment by kjeremy** [comment]
An environment variable seems a little heavy handed.

**Comment by lnicola** [comment]
I guess we can configure it from the LSP settings but something about feature creep? :-).

**Comment by matklad** [comment]
Yeah, I feel liks we should just have non-emoji play button. For anything more fancy I think we should just upstream context-dependent running. 

bors r+

**Pull request merged**
