### PR TITLE
Highlight mutable variables differently

### PR DESCRIPTION
**Pull request by viorina**
Screenshot from 2019-07-18 19-04-57

### CODE REVIEW

**Comment by matklad** [comment]
Cool!

To bad we can't just underline the identifier like IntelliJ does. That would certainly work better with rainbow highlighting. 

bors r+

**Comment by lnicola** [comment]
> To bad we can't just underline the identifier like IntelliJ does.

Just wondering, why can't we?

**Comment by matklad** [comment]
That's VS Code restriction: themes can only specify colors, and not decorations, like bold or underline

**Comment by lnicola** [comment]
But the extension uses Code text decorations when highlighting is enabled, and they [seem](https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions) to support `text-decoration`?

**Comment by matklad** [comment]
Hm, hopefully I am wrong then :) I am thinking about `colorCustomization` https://github.com/matklad/config/blob/ed588057545276e05ea4979ea7086addc3724a4e/vscode/settings.json#L145-L159.

Looks like we definitely should create a separate decoration for mutable things

**Comment by matklad** [comment]
Yeah, seems like this should do the trick. Does it compose well with rainbow highlighting? Could you send a PR? ^^

**Comment by matklad** [comment]
@lnicola ok, I'll do this myself because I want this sooo much! Thanks for pointing out that this is possible!

**Pull request merged**
