### PR TITLE
Consider trait to be in scope for trait-impls

### LINKED ISSUE #8912: Trait in a trait impl not automatically considered in-scope
screenshot-2021-05-21-19:03:48

Here, the method call to `fmt` is unresolved, but it should resolve to `<Subtree as Display>::fmt`. The implemented trait is normally considered to be in scope while in the impl block, maybe that logic is missing from rust-analyzer?

### PR DESCRIPTION
**Pull request by Veykril**
Fixes #8912
bors r+

### CODE REVIEW

**Comment by Veykril** [comment]
bors retry

**Comment by Veykril** [comment]
bors retry

**Comment by Veykril** [comment]
bors retry

**Comment by matklad** [comment]
bors retry

**Pull request merged**
