### PR TITLE
Simplify unwrapping of blocks

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by matklad** [comment]
cc @bnjjj, turns out it's possible to make this substantionally simpler!

**Comment by bnjjj** [comment]
Oh yes ! Thanks for the cc. FYI I'm not really available for now and I know I have some pending PRs. I will come back ASAP to update these PRs. :)

**Comment by matklad** [comment]
> I will come back ASAP to update these PRs

Please make sure that you only do this because you want to, and not because you somehow feel obliged to :) It's totally OK to let PRs linger or slip from the radar altogether.

**Comment by bnjjj** [comment]
Don't worry I really want haha :)

**Pull request merged**
