### PR TITLE
feat: Render documentation for derive completion

### PR DESCRIPTION
**Pull request by Veykril**
eEzGiq2wNa

Nothing fancy as all the std derives aren't really documented though maybe some 3rd party crates document them equally to their trait counterparts.

### CODE REVIEW

**Comment by Veykril** [comment]
Is there a way to define empty/no-op proc-macros/derives for test fixtures? The changes here currently make `derive` completion untestable otherwise as there is nothing to complete now since the hardcoded derive list is kind of gone.

**Comment by lnicola** [comment]
For some reason, this had a funky effect on the type mismatches and unknown types numbers.

**Comment by lnicola** [comment]
image

**Comment by Veykril** [comment]
I think you misclicked there, I get to https://github.com/rust-analyzer/rust-analyzer/commit/5092d8c when clicking that on that drop which would make more sense to me

**Comment by lnicola** [comment]
Look at the green (`webrender`) line.

**Comment by Veykril** [comment]
Huh this seems odd. Do we always check the same version of webrender and ripgrep? If not I assume something big changed there?

**Comment by lnicola** [comment]
Yes, we use a specific commit from `rustc-perf` (and those don't get updated anyway). And it bounces back a couple commits later.

**Comment by lnicola** [comment]
Looks like it might be non-deterministic: 

image

**Comment by jonas-schievink** [comment]
Yeah, that's uuuh, not what should happen :sweat_smile:

**Comment by lnicola** [comment]
The memory chart also shows differences, but only for webrender. I would expect some slight variation in memory usage from run to run, but maybe they do something funny.

**Comment by jonas-schievink** [comment]
I think the way we load proc macros is racy, https://github.com/rust-analyzer/rust-analyzer/pull/9083 also introduced some weird test failures on Windows

**Pull request merged**
