### PR TITLE
Dont unnecessarily unnest imports

### LINKED ISSUE #6071: Don't needlessly unnnest imports
If we auto-import `File`  in this code

```rust
use std::{fs::{self}};

fn main()  {
    let _: File = todo!();
}
```
we get

```rust
use std::{fs::{self}};
use fs::File;
```

Instead, we should get `use std::{fs::{self, File}};`

I think the bug is in this function:

https://github.com/rust-analyzer/rust-analyzer/blob/4ddb8124b01a04adcc7d42444f7ca8d377bb60ae/crates/hir_def/src/find_path.rs#L19-L23

It returns (but this needs to be double checked) `fs::File` for the above example, rather than `std::fs::File`

### PR DESCRIPTION
**Pull request by Veykril**
Fixes #6071

This has the side effect that paths that refer to items inside of the current module get prefixed with `self`. Changing this behavior is unfortunately not straightforward should it be unwanted, though I don't see a problem with this as prefixing imports like this with `self` is what I do personally anyways 😅. You can see what I mean with this in one of the tests which had to be changed in `crates/ssr/src/tests.rs`.

There is one test that i still have to look at though, ~~which I by accident pushed with `#[ignore]` on it~~, which is `different_crate_renamed`, for some reason this now doesn't use the crate alias. This also makes me believe that aliases in general will break with this. So maybe this is not as straight forwards as I'd hoped for, but I don't really know how aliases work here.

Edit: The failing test should work now

### CODE REVIEW

**Comment by matklad** [comment]
Yeah, this is tricky... Here's the case that @flodiebold was talking about in #6071 which will fail under this PR:

```diff
diff --git a/crates/assists/src/handlers/add_missing_impl_members.rs b/crates/assists/src/handlers/add_missing_impl_members.rs
index 8df1d786b..1ac5fefd6 100644
--- a/crates/assists/src/handlers/add_missing_impl_members.rs
+++ b/crates/assists/src/handlers/add_missing_impl_members.rs
@@ -414,6 +414,41 @@ impl foo::Foo for S {
         );
     }
 
+    #[test]
+    fn test_qualify_path_2() {
+        check_assist(
+            add_missing_impl_members,
+            r#"
+mod foo {
+    pub mod bar {
+        pub struct Bar;
+        pub trait Foo { fn foo(&self, bar: Bar); }
+    }
+}
+
+use foo::bar;
+
+struct S;
+impl bar::Foo for S { <|> }"#,
+            r#"
+mod foo {
+    pub mod bar {
+        pub struct Bar;
+        pub trait Foo { fn foo(&self, bar: Bar); }
+    }
+}
+
+use foo::bar;
+
+struct S;
+impl bar::Foo for S {
+    fn foo(&self, bar: bar::Bar) {
+        ${0:todo!()}
+    }
+}"#,
+        );
+    }
+
     #[test]
     fn test_qualify_path_generic() {
         check_assist(
```

I guess maybe we should have two versions of `find_path`

* `find_path_for_use` which returns a path which you can just use (for things like path-qualifing when inserting missing memebers)
* `find_path_for_use` (naming is horrible) which returns a path you can insert as a use-statement. 

Alternatively, maybe the original idea of fixing the import insertion to work with short paths is worhtwhile? Although I am encouranged by the size of the diff here.

**Comment by Veykril** [comment]
Ye I saw your discussion afterwards as well, having two different `find_path` functions seems like a good idea as I imagine fixing the short paths in import insertion itself will be quite tricky

**Comment by Veykril** [comment]
Alright, here is another try, instead of fully splitting the functions up I split up their logic according to an enum, as both functions require a lot of similar functionality. This should properly do the trick if I'm not mistaken. The name can still be bikeshed I just picked `prefixed` as that was something I could come up with fast that somewhat fits I believe.

There is also the option in there to prefix paths with `self` if they refer to something local to module(which is a style I personally like, hence I added it given it was so simple). I figured that could be a potential configuration which is why I am bringing that up here as well now.

Let me know if this was the idea that was targeted or not.

**Comment by matklad** [comment]
>Alright, here is another try, instead of fully splitting the functions up I split up their logic according to an enum, as both functions require a lot of similar functionality. This should properly do the trick if I'm not mistaken.

Yeah, that's the right thing to do: private impl is parametrized by enum/boolean, public API is two separately named functions. This is a special case of a general phenomenon when user and implementer would prefer different APIs. 

>which is a style I personally like, hence I added it given it was so simple

LGTM! I guess we should just see if folks complain about this. I personally stick to `use crate::full::path` syntax  even when `use self::path` would work :-) 

bors r+

**Pull request merged**
