### PR TITLE
Micro-optimize type hints to avoid allocations

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by kiljacken** [comment]
I wish we had stable generators already :(

**Comment by matklad** [comment]
FWIW, in IntelliJ Rust I've once explicitly removed lazy sequence based processesing to an accamulator one -- the stack traces are so much nicer that way.

**Comment by kiljacken** [comment]
@matklad I could see that being the case, but it seems like it could be solved tecnically :) I grew up with Python, so generator pipelines will always be near to my heart.
Nice change anyways, eliminating wasteful allocations is always nice!

**Pull request merged**
