### PR TITLE
fix: Watch for Cargo.toml and .lock changes

### LINKED ISSUE #5333: Auto reload isn't working when Cargo.toml or Cargo.lock are changed outside of editor
When switching between `master` and `kjeremy:mark-fixes-as-preferred` things are not reloaded (it is enabled in the settings). There are changes to `Cargo.toml` and `Cargo.lock` so I would expect it to reload. The status bar does not change from "Ready".

### PR DESCRIPTION
**Pull request by lnicola**
Maybe closes #5333

### CODE REVIEW

**Comment by kjeremy** [comment]
I could have sworn we already did this. On that note we should really have a test.

**Comment by lnicola** [comment]
This seems pretty hard to test.

**Comment by lnicola** [comment]
> I could have sworn we already did this.

We do it in.. a couple of other places? :disappointed:

**Comment by matklad** [comment]
bors r+

Sadly, it’s that part of code which is pretty difficult to test in a good way…

**Pull request merged**
