### PR TITLE
Macro queries

### PR DESCRIPTION
**Pull request by matklad**
In https://github.com/rust-analyzer/rust-analyzer/pull/1231, I've added aggressive clean up of `ast_id_to_node` query. 

The result of this query is a `SyntaxTree`, and we don't want to retain syntax trees in memory unless absolutely necessary.

Moreover, `SyntaxTree` has identity equality semantics, meaning that we'll get a diffferent syntax tree for a file after every reparse. That means that `ast_id_to_node` query should not genereally be used in HIR, unless it is behind some kind of salsa firewall, like the `raw` module of name resoulution.

However, that PR resulted in the abysmal performance: turns out we were using  ast_id_to_node quite heavily in hir when expanding macros! 

So this PR  installs the more incremental-friendly query structure:

* converting source to token tree is now a query; changing source without affecting token-trees will now preserve macro expansions
* expand macro (tt -> tt) is now a query as well, so we cache macro expansions *before* parsing them into item lists or expressions, which is nice: we can cache expansion without knowing the calling context!

r? @edwin0cheng

### CODE REVIEW

**Comment by edwin0cheng** [comment]
LGTM, except i have one silly question, do macro hygiene affect the query ?

**Comment by edwin0cheng** [comment]
r+

**Comment by matklad** [comment]
Good question!

That depends on how we handle hygiene (we currently don't handle it at all) :-)

The idea (which I am not sure is workable) is that macro expansion doesn't know about hygiene directly, it only knows about abstract token identities and preserves it during expansion. So, when we run this tt -> tt query, ids of tokens on the left could be correlated with ids of tokens on the right, and I hope that will be enough to make hygienic expansions.

Because we always assign ids locally to expansion, that means that caching should just work

**Pull request merged**
