### PR TITLE
Allow semantic tokens for strings to be disabled

### PR DESCRIPTION
**Pull request by djrenren**
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7111

Pretty straightforward change, but open to any suggestions if there's a more recommended testing strategy than what I went with.

### CODE REVIEW

**Comment by djrenren** [comment]
Whoops forgot to run all the doc generating stuff. Should be all set now. Also any suggestions for alternate docstrings and/or names for the new config option would be very welcome.

**Comment by matklad** [comment]
bors r+

Thanks! I'll adjust config name in a follow-up PR

**Comment by lnicola** [comment]
It feels like this is a weird layer to implement and test it, but..

**Comment by matklad** [comment]
The layer I think is OK -- this is a work-around for the client impl, so it belongs to the lsp layer, and not to the ide. 

Agree that it doesn't make sense to spend an integration test here, I'll adjust that as well (don't want to make the PR enter a round of reviers, it's been waiting way too long already)

**Pull request merged**
