### PR TITLE
Add assist to replace filter_map(..).next() with find_map(..)

### PR DESCRIPTION
**Pull request by theotherphil**
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/1725

### CODE REVIEW

**Comment by lnicola** [comment]
Should we also check that the method of the right one (from the Iterator trait)?

**Comment by Veykril** [comment]
I think the issue was intending for this to be a warning/hint diagnostic with a quickfix, not an assist.

**Comment by theotherphil** [comment]
Ah, I misunderstood the terminology. I’ll rewrite as a diagnostic.

**Comment by theotherphil** [comment]
I'm implementing the diagnostic version on https://github.com/rust-analyzer/rust-analyzer/pull/7062.

**Pull request closed without merging**
