### PR TITLE
fix: Don't descend MacroCall TokenTree delimiters

### LINKED ISSUE #9190: First token from macro_rules invocation bleeds token type into the macro braces
This is an issue with token colorization & semantic token type (purely visual). I am using rust-analyzer in Visual Studio Code.

The braces of a `macro_rules!` macro invocation (e.g. the parentheses/brackets/braces in `foo!()`/`foo![]`/`foo!{}`) can sometimes gain the semantic token type of the first token in the body block of a `macro_rules!` macro. This can result in the braces being colored incorrectly.

Example code: 

```rust
macro_rules! foo {
    () => {
        ""
    };
}

pub fn test() {
    foo!();
}
```

The `()` in the `foo!()` macro are colored green. You can see the token type is reported as a string.

image

Some other examples demonstrating different tokens and different braces:

```rust
macro_rules! bar {
    () => {
        0
    };
}

macro_rules! baz {
    () => {
        &0
    };
}

pub fn test() {
    bar![];
    baz!{};
}
```

image

image

### PR DESCRIPTION
**Pull request by Veykril**
Fixes #9190

### CODE REVIEW

**Comment by jonas-schievink** [comment]
I think there's another.. bug? oddness? here: `map_token_down` does

```rs
let range = token.value.text_range().checked_sub(self.arg.value.text_range().start())?;
```

The `checked_sub` seems wrong, or at least questionable

**Comment by Veykril** [comment]
`self.arg.value` is the macro input token tree right? In that case we would subtract the left delimiters range start from its own range which would result in 0 no?

**Comment by jonas-schievink** [comment]
Hmm, right. I guess that means we "waste" space in the `TokenMap` for them, but that isn't too bad.

**Pull request merged**
