### PR TITLE
Benchmarking infrastructure

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
cc @edwin0cheng

**Comment by matklad** [comment]
also cc @jonas-schievink -- I think its about time we start writing benchmarks for name resolution & item tree. I am not sure if this approach with synthetic generation is viable though, but feels like it's worth at least a try!.

bors r+-

**Comment by jonas-schievink** [comment]
Hmm, why make these `#[test]`s instead of Cargo benchmark binaries?

**Comment by matklad** [comment]
I do want to make sure they don't bitrot, and treating them as tests (which are run during `cargo test`) seems the easiest way to do that. With benchmark, I think we'd need `harness=false` and our own `main` anyway?

**Pull request merged**
