### PR TITLE
Fix cargo registry caching for builds

### PR DESCRIPTION
**Pull request by bjorn3**
https://github.com/rust-analyzer/rust-analyzer/pull/3612#issuecomment-599668535

### CODE REVIEW

**Comment by bjorn3** [comment]
Windows still has the caching issue. There is some work being done over at https://github.com/openethereum/openethereum/pull/11568 to fix this, but it doesn't work yet.

**Comment by matklad** [comment]
Hm, do we really need this?

Looking at https://github.com/rust-analyzer/rust-analyzer/runs/510919657?check_suite_focus=true#step:8:1, it seems like caching works as expected?

**Comment by bjorn3** [comment]
https://github.com/rust-analyzer/rust-analyzer/runs/510919657?check_suite_focus=true#step:5:13 shows errors though.

**Comment by matklad** [comment]
Yeah... That probably means that we don't need to cache the registry at all? We cache compiled libraries anyway.

**Comment by bjorn3** [comment]
Maybe

**Comment by bjorn3** [comment]
It is useful when updating rustc, as in that case all crates need to be recompiled.

**Comment by matklad** [comment]
I think if we are recompiling the world, saving on network doesn't really make sense. I'd just remove this from caching then!

**Comment by matklad** [comment]
bors r+

Thanks!

Let's see how it works out...

**Comment by bjorn3** [comment]
I think I should have kept the `Cache cargo index` step.

**Comment by matklad** [comment]
yeah, r+ doesn't mean anything anyway, this has to be merged manually...

**Comment by bjorn3** [comment]
Forgot that gh apps can't merge workflow changes.

**Comment by bjorn3** [comment]
Seems that the cargo registry cache is actually necessary: https://github.com/rust-analyzer/rust-analyzer/pull/3613/checks?check_run_id=511843473#step:7:12

**Pull request merged**
