### PR TITLE
Always put a space after dyn in macro pretty-printing

### LINKED ISSUE #11100: Implement missing members on an #[async_trait] generates invalid code
I just used `Implement missing members` on the `#[async_trait]` `axum::extract::FromRequest` (which isn't all too helpful, but I hadn't thought about the async'ness), and noticed that the return type of `from_request` was written out as

```rust
core::pin::Pin<
    Box<
        dyncore::future::Future<Output = Result<Self, Self::Rejection>>
            + core::marker::Send
            + 'async_trait,
    >,
>
```

It looks like some printing logic inside RA missed the required space between `dyn` and `core`.

### PR DESCRIPTION
**Pull request by jplatte**
Fixes #11100.

### CODE REVIEW

**Comment by Veykril** [comment]
Thanks!
bors r+

**Comment by lnicola** [comment]
bors retry

**Comment by lnicola** [comment]
Does this insert an extra space on `dyn Trait`?

**Comment by Veykril** [comment]
`dyn Trait` is being hit in the first arm already, so is `impl Trait`. This mainly fixes `dyn::Trait` being `dyn ::Trait` now, `impl` is not affected so we should add that as well ye

**Pull request merged**
