### PR TITLE
vscode: added feature flags for better short-term ux

### PR DESCRIPTION
**Pull request by Veetaha**
See [this zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Feature.20flags) for more details.

### CODE REVIEW

**Comment by Veetaha** [comment]
@lnicola @matklad 
I somehow can't add reviewers here:
image

**Comment by lnicola** [comment]
Does this actually work? I'm impressed :+1:.

**Comment by Veetaha** [comment]
@matklad  I get the following error:
image

**Comment by Veetaha** [comment]
@lnicola 
ra_feature_flags

**Comment by Veetaha** [comment]
Also I am not 100% sure that the description for `lsp.diagnostics` feature flag is correct...

**Pull request merged**
