### PR TITLE
Feature-gate some dependencies

### PR DESCRIPTION
**Pull request by HKalbasi**
This is needed for wasi build. I can imagine other usages (for example vscode bundled binaries does not need most of cli features, and can save a bit of binary size?) but it doesn't work with this PR, due some flags are entangled. If `xflags` support cfgs for individual commands it can be fixed.

### CODE REVIEW

**Comment by flodiebold** [comment]
Having a bunch of cfgs all over the place does not seem very maintainable, even with the added CI check. Could we refactor to separate those parts out a bit more, or alternatively make them work with wasi? If we can't run processes with wasi, how would we get a project setup anyway :grimacing: 

Maybe @matklad has an opinion here?

**Comment by matklad** [comment]
Yeah, in general, we are rather resource-constraint, so we ruthlessly prioritise maintainability over everything else. The general guideline is that any non-core feature should add zero maintenance burden. See, eg, push-back against non-trivial publishing here: https://github.com/rust-analyzer/rust-analyzer/pull/4776

Adding feature flags, making dependencies optional, and adding extra CI jobs are things which increase maintenance very substantially. 

I *think* we can make a soft-promise that the `ide` crate is compatible with WASM, but the `rust-analyzer` crate is explicitly non re-usable, and any consumer which wants to, eg, compile it to wasi would need to put the relevant work on the consumer's side, even if that means order of magnitude more work in total.

**Comment by HKalbasi** [comment]
I see. WASI build is even worse than a library build for normal usages, because of bigger size. The only point is that wasi is a no-brainer interface for an official wasm build, and it would work with existing code in vscode web extension, vim wasm and similar (in a probably sub optimal way)

> I think we can make a soft-promise that the ide crate is compatible with WASM

Can we upgrade that promise, and provide actual, official wasm builds of it, with some interface, in releases? Or an npm package, or at least a check in ci that some wasm interface is build-able with latest version? Currently rust-analyzer-wasm upgrading needs manual, non-trivial work.

We can continue in #11244

**Comment by flodiebold** [comment]
We [do](https://github.com/rust-analyzer/rust-analyzer/blob/54782428a621b996f1bbcc133e3d6a008db762b5/.github/workflows/ci.yaml#L73) check in CI that the ide crate builds in WASM.

**Pull request closed without merging**
