### PR TITLE
fix: Return absolute paths in find_path if crate start is ambiguous

### LINKED ISSUE #6941: Auto-import imports the wrong thing when module clashes with extern crate
Assuming an extern crate named `c`, the following code inserts the wrong use item:

```rust
mod c {}

c::module<|>::thing_in_crate!();
```

Results in this import:
```rust
use c::module;
```

This resolves to the module, not the crate. Instead the import should look like this:

```rust
use ::c::module;
```

### PR DESCRIPTION
**Pull request by Veykril**
Fixes #6941

### CODE REVIEW

**Comment by Veykril** [comment]
bors retry

**Comment by bjorn3** [comment]
The bors dashboard doesn't show this PR: https://app.bors.tech/repositories/4610

Let's try closing and re-opening.

**Comment by bjorn3** [comment]
It showed up after I pressed sync pull requests.

bors r+

**Comment by bjorn3** [comment]
Bors still doesn't respond.

**Comment by Veykril** [comment]
Guess I'll open it as a new PR then? Wonder what happened here...

**Comment by Veykril** [comment]
oh nvm I just realized this isn't a problem with this PR, but with bors in general

**Comment by SomeoneToIgnore** [comment]
Maybe we can restore and merge the PR, since failures were due to bors misbehaving?

I've tried fixing the same issue recently and also used `cov_mark::check!`, but noted, that `check_found_path_` function in `find_path.rs` does not really resolve paths starting with `::` for some reason?
Anyway, you did not use the marks in your approach, so should not matter much 🙂

**Comment by Veykril** [comment]
It did get merged, I opened a new P before noticing it was bors acting up https://github.com/rust-analyzer/rust-analyzer/pull/8820

**Pull request closed without merging**
