### PR TITLE
Use log::info in trait_solve_query instead of eprintln

### PR DESCRIPTION
**Pull request by edwin0cheng**
cc @flodiebold

### CODE REVIEW

**Comment by flodiebold** [comment]
Oops :sweat_smile: I thought I reverted that...

**Comment by flodiebold** [comment]
@matklad that should probably go in the release...

**Comment by matklad** [comment]
Yep, it will go into the next release, in a week :D

**Comment by matklad** [comment]
Though I can try to re-publish the release later today... Or we can just test everyone's log rotation :D

**Pull request merged**
