### PR TITLE
DO NOT MERGE experimental port to rowan#32

### PR DESCRIPTION
**Pull request by CAD97**
cc https://github.com/rust-analyzer/rowan/pull/32

This is an update of ra to use the rowan branch where I've implemented the "`llvm::trailing_objects` trick" for `GreenNode`. This means `GreenNode` always lives behind an `Arc`.

This branch is for perf testing of the rowan change. I expect it to be neutral or negative and as thus be discarded (until `GreenToken` is shrunk?) but it's worth testing at least!

r? @matklad (though this is low priority of course)
I'm not sure how to run any perf tests, otherwise I'd try to do so myself.

### CODE REVIEW

**Comment by lnicola** [comment]
>  I'm not sure how to run any perf tests, otherwise I'd try to do so myself.

`cargo run --bin ra_cli --release -- analysis-stats /path/to/some/larger/project`

Note that there is some caching involved and the parser is slow (#1643), so you might want to play with the `RA_LRU_CAP` environment variable. Setting it to `0` caches everything, while leaving it unchanged or at a lower value will exercise the parser much more.

**Comment by lnicola** [comment]
The CI error is only a formatting change:

```
-fn to_green_element(element: SyntaxElement) -> NodeOrToken<Arc<rowan::GreenNode>, rowan::GreenToken> {
+fn to_green_element(
+    element: SyntaxElement,
+) -> NodeOrToken<Arc<rowan::GreenNode>, rowan::GreenToken> {
```

**Comment by matklad** [comment]
I think 

```
cargo run --bin ra_cli --release -- symbols large_file.rs
```

or 


```
cargo run --bin ra_cli --release -- parse --no-dump large_file.rs
```

might be a good metric here as well, in addition to the overall ansysis_stats.

**Comment by CAD97** [comment]
Dumb dump of measurements:

<details><summary>trailing-objects</summary>

```powershell
PS D:\usr\Documents\Code\Rust\rust-analyzer> Measure-Command { cargo run --bin ra_cli --release -- analysis-stats . | Out-Default }
    Finished release [optimized + debuginfo] target(s) in 0.47s
     Running `target\release\ra_cli.exe analysis-stats .`
Database loaded, 216 roots, 1.0347024s
Crates in this dir: 25
Total modules found: 323
Total expressions: 88402
Expressions of unknown type: 6738 (7%)
Expressions of partially unknown type: 3182 (3%)
Type mismatches: 4097
Inference: 40.2337923s, 0b allocated 0b resident
Total: 51.7559952s, 0b allocated 0b resident


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 54
Milliseconds      : 319
Ticks             : 543199001
TotalDays         : 0.000628702547453704
TotalHours        : 0.0150888611388889
TotalMinutes      : 0.905331668333333
TotalSeconds      : 54.3199001



PS D:\usr\Documents\Code\Rust\rust-analyzer> Measure-Command { type "D:\rust-lang\src\libcore\unicode\tables.rs" | cargo run --bin ra_cli --release -- symbols }         
    Finished release [optimized + debuginfo] target(s) in 0.43s
     Running `target\release\ra_cli.exe symbols`


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 664
Ticks             : 6640937
TotalDays         : 7.68626967592593E-06
TotalHours        : 0.000184470472222222
TotalMinutes      : 0.0110682283333333
TotalSeconds      : 0.6640937
TotalMilliseconds : 664.0937



PS D:\usr\Documents\Code\Rust\rust-analyzer> Measure-Command { type "D:\rust-lang\src\libcore\unicode\tables.rs" | cargo run --bin ra_cli --release -- parse --no-dump } 
    Finished release [optimized + debuginfo] target(s) in 0.43s
     Running `target\release\ra_cli.exe parse --no-dump`


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 569
Ticks             : 5695037
TotalDays         : 6.59147800925926E-06
TotalHours        : 0.000158195472222222
TotalMinutes      : 0.00949172833333333
TotalSeconds      : 0.5695037
TotalMilliseconds : 569.5037



```
</details>

<details><summary>trailing-objects~2</summary>

```powershell
PS D:\usr\Documents\Code\Rust\rust-analyzer> git checkout HEAD~2
Note: switching to 'HEAD~2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at bbd0fbd9 Merge #2101
PS D:\usr\Documents\Code\Rust\rust-analyzer> Measure-Command { cargo run --bin ra_cli --release -- analysis-stats . | Out-Default }
    Finished release [optimized + debuginfo] target(s) in 0.51s
     Running `target\release\ra_cli.exe analysis-stats .`
Database loaded, 216 roots, 979.2838ms
Crates in this dir: 25
Total modules found: 323
Total declarations: 10952
Total expressions: 88402
Expressions of unknown type: 6737 (7%)
Expressions of partially unknown type: 3182 (3%)
Type mismatches: 4098
Inference: 33.7676716s, 0b allocated 0b resident
Total: 44.3966774s, 0b allocated 0b resident


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 47
Milliseconds      : 14
Ticks             : 470147946
TotalDays         : 0.000544152715277778
TotalHours        : 0.0130596651666667
TotalMinutes      : 0.78357991
TotalSeconds      : 47.0147946
TotalMilliseconds : 47014.7946



PS D:\usr\Documents\Code\Rust\rust-analyzer> Measure-Command { type "D:\rust-lang\src\libcore\unicode\tables.rs" | cargo run --bin ra_cli --release -- symbols }         
    Finished release [optimized + debuginfo] target(s) in 0.51s
     Running `target\release\ra_cli.exe symbols`


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 749
Ticks             : 7493724
TotalDays         : 8.67329166666667E-06
TotalHours        : 0.000208159
TotalMinutes      : 0.01248954
TotalSeconds      : 0.7493724
TotalMilliseconds : 749.3724



PS D:\usr\Documents\Code\Rust\rust-analyzer> Measure-Command { type "D:\rust-lang\src\libcore\unicode\tables.rs" | cargo run --bin ra_cli --release -- parse --no-dump } 
    Finished release [optimized + debuginfo] target(s) in 0.42s
     Running `target\release\ra_cli.exe parse --no-dump`


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 566
Ticks             : 5665552
TotalDays         : 6.55735185185185E-06
TotalHours        : 0.000157376444444444
TotalMinutes      : 0.00944258666666667
TotalSeconds      : 0.5665552
TotalMilliseconds : 566.5552



```
</details>

**Comment by bjorn3** [comment]
And what are the results of master?

**Comment by lnicola** [comment]
So the `analysis-stats` run gets slower:

```
Inference: 40.2337923s, 0b allocated 0b resident
Total: 51.7559952s, 0b allocated 0b resident

Inference: 33.7676716s, 0b allocated 0b resident
Total: 44.3966774s, 0b allocated 0b resident
```

But the single-file parse times look better than before. The database load times are close, so I'm guessing this was on a warm disk cache.

**Comment by CAD97** [comment]
I ran the command twice in a row (to avoid measuring build time in the overall timing) and took the second result, so I assume the disk cache would be somewhat warm. trailing-objects~2 is bbd0fbd9, which is the commit from master that this branch forked from for the fairest comparison possible.

**Comment by bjorn3** [comment]
> trailing-objects~2 is bbd0fbd, which is the commit from master that this branch forked from for the fairest comparison possible.

I thought the `~` was a `-`, so I thought the second one was a different version of this PR.

**Comment by lnicola** [comment]
Something is fishy here. Your base is from two days ago, however:

```
Database loaded, 216 roots, 1.0347024s
Crates in this dir: 25
Total modules found: 323
Total expressions: 88402
Expressions of unknown type: 6738 (7%)
Expressions of partially unknown type: 3182 (3%)
Type mismatches: 4097
Inference: 40.2337923s, 0b allocated 0b resident
Total: 51.7559952s, 0b allocated 0b resident
```

While I get:

```
Database loaded, 216 roots, 229.880234ms
Crates in this dir: 25
Total modules found: 323
Total declarations: 10953
Total functions: 3814
Item Collection: 7.84425208s, 0b allocated 0b resident
Total expressions: 88495
Expressions of unknown type: 6744 (7%)
Expressions of partially unknown type: 3182 (3%)
Type mismatches: 4110
Inference: 15.909583615s, 0b allocated 0b resident
Total: 23.753841793s, 0b allocated 0b resident
```

The expression counts are close, but you're missing the "Item Collection" line which was added in f1cfd5ec3d in August. How is this possible?

**Comment by CAD97** [comment]
`Measure-Command` messed up the progress bar, so it's possible it ate some of the output or even that I accidentally removed it when removing the progress bar that didn't get deleted.

I'll rerun this without Measure-Command when I get back to my machine (had to run to an appointment) to make sure if it is or isn't that. Could it potentially be a Windows/*nix issue?

**Comment by lnicola** [comment]
They're simple `println!`s, so I don't think it's platform-related. But indeed, they're the two lines above the progress bar.

Off-topic, but is your PC really slow, or is RA much slower on Windows?

**Comment by CAD97** [comment]
Anything touching the filesystem is going to be slower on Windows. Also, my `D:\` drive is a 5400 RPM 8MB Cache SATA 6.0Gb/s HDD. My processor is an i7-4810MQ @ 2.8GHz 4c8t in a laptop. I'm running on `beta-x86_64-pc-windows-gnu (default) rustc 1.39.0-beta.5 (fa5c2f3e5 2019-10-02)` currently. I'm also not doing anything special to try and isolate the measurement, I'm just running it in a normal shell.

analysis-stats without `Measure-Command`:

<details><summary>trailing-objects</summary>

```powershell
PS D:\usr\Documents\Code\Rust\rust-analyzer> cargo run --bin ra_cli --release -- analysis-stats .
    Finished release [optimized + debuginfo] target(s) in 0.53s
     Running `target\release\ra_cli.exe analysis-stats .`
Database loaded, 216 roots, 1.0041756s
Crates in this dir: 25
Total modules found: 323
Total declarations: 10952
Total functions: 3813
Item Collection: 10.7575698s, 0b allocated 0b resident
Total expressions: 88402                                                                                                                                                 
Expressions of unknown type: 6736 (7%)
Expressions of partially unknown type: 3180 (3%)
Type mismatches: 4097
Inference: 34.3966963s, 0b allocated 0b resident
Total: 45.154878s, 0b allocated 0b resident
```
</details>

<details><summary>trailing-objects~2</summary>
```powershell
PS D:\usr\Documents\Code\Rust\rust-analyzer> cargo run --bin ra_cli --release -- analysis-stats .
    Finished release [optimized + debuginfo] target(s) in 0.53s
     Running `target\release\ra_cli.exe analysis-stats .`
Database loaded, 216 roots, 958.3043ms
Crates in this dir: 25
Total modules found: 323
Total declarations: 10952
Total functions: 3813
Item Collection: 10.7996937s, 0b allocated 0b resident
Total expressions: 88402                                                                                                                                                 
Expressions of unknown type: 6735 (7%)
Expressions of partially unknown type: 3180 (3%)
Type mismatches: 4098
Inference: 34.538116s, 0b allocated 0b resident
Total: 45.3385228s, 0b allocated 0b resident
```
</details>

Current master, along with an unedited `Measure-Command`-wrapped invocation:

<details><summary>542bc182</summary>

```powershell
PS D:\usr\Documents\Code\Rust\rust-analyzer> cargo run --bin ra_cli --release -- analysis-stats .
    Finished release [optimized + debuginfo] target(s) in 0.44s
     Running `target\release\ra_cli.exe analysis-stats .`
Database loaded, 218 roots, 1.0139522s
Crates in this dir: 26
Total modules found: 325
Total declarations: 11000
Total functions: 3825
Item Collection: 10.6624567s, 0b allocated 0b resident
Total expressions: 89059
Expressions of unknown type: 6952 (7%)
Expressions of partially unknown type: 3540 (3%)
Type mismatches: 3613
Inference: 34.6395351s, 0b allocated 0b resident
Total: 45.3130805s, 0b allocated 0b resident
PS D:\usr\Documents\Code\Rust\rust-analyzer> Measure-Command { cargo run --bin ra_cli --release -- analysis-stats . | Out-Default }
    Finished release [optimized + debuginfo] target(s) in 0.42s
     Running `target\release\ra_cli.exe analysis-stats .`
Database loaded, 218 roots, 982.8775ms
Crates in this dir: 26
Total modules found: 325
Total declarations: 11000░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/3825

Total expressions: 89059
Expressions of unknown type: 6947 (7%)
Expressions of partially unknown type: 3537 (3%)
Type mismatches: 3608
Inference: 32.4578312s, 0b allocated 0b resident
Total: 43.3185391s, 0b allocated 0b resident


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 45
Milliseconds      : 730
Ticks             : 457307657
TotalDays         : 0.000529291269675926
TotalHours        : 0.0127029904722222
TotalMinutes      : 0.762179428333333
TotalSeconds      : 45.7307657
TotalMilliseconds : 45730.7657



```
</details>

Conclusion: `Measure-Command` messes with rewriting stdout commands.

**Comment by lnicola** [comment]
This run you got the same times on both commits, so maybe it doesn't regress performance?

```
Item Collection: 10.7575698s, 0b allocated 0b resident
Inference: 34.3966963s, 0b allocated 0b resident
Total: 45.154878s, 0b allocated 0b resident

Item Collection: 10.7996937s, 0b allocated 0b resident
Inference: 34.538116s, 0b allocated 0b resident
Total: 45.3385228s, 0b allocated 0b resident
```

**Comment by CAD97** [comment]
Best conclusion I can draw is it's within noise, which is really what I expected.

> Realistically, this removes one pointer chase in NodeData to get to the green node's children and adds a pointer chase in GreenElement to get to a GreenNode's kind or len, at the cost of some tricky unsafe allocation.

**Comment by bjorn3** [comment]
Maybe use [hyperfine](https://github.com/sharkdp/hyperfine). It runs the program multiple times and gives an average, 95% confidence bounds and min and max. Using --warmup, you can specify how much warmup rounds you want. (default is 0) It will warn when it thinks the variance is to high on the actual bench runs. You can also specify multiple commands to be benchmarked after each other.

**Comment by lnicola** [comment]
`hyperfine` might be overkill. I can confirm that it seems mostly within noise on my Linux laptop, too.

**Comment by CAD97** [comment]
Closing this as it's added complexity for no gain. Will probably end up with a new experiment for https://github.com/rust-analyzer/rowan/pull/33.

**Pull request closed without merging**
