### PR TITLE
Use multiple marked strings for hover content

### LINKED ISSUE #3813: Module name on hover should have another newline after it
So that the module and item have a blank line between them.

### LINKED ISSUE #4594: Module path in on-hover message is no-longer monospace
Non-monospace code makes my eyes unhappy...
cc #4559
image

rust-analyzer version: nightly (f4f5fca)

### PR DESCRIPTION
**Pull request by aloucks**
Also moved them module name below function signatures.

Fixes #4594
Fixes #3813

cc #3813
cc #4559

image

image

image

image

Dark+ Theme

image

### CODE REVIEW

**Comment by aloucks** [comment]
@Veetaha @kjeremy I think this resolves the issues with the hover tooltip. The migration to multiple marked strings also allows greater flexibility for adding additional content without messing around with string concatenation. VSCode automatically renders a thin line between the content sections, adding a natural separation.

**Comment by kjeremy** [comment]
I don't think this is quite the right change. Only the rust-analyzer crate should know about LSP types. Also MarkedString is deprecated in the LSP and MarkupContent should be returned instead. See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_hover

**Comment by aloucks** [comment]
https://github.com/microsoft/language-server-protocol/issues/518

**Comment by kjeremy** [comment]
Thanks for that link. If the horizontal rule doesn't work maybe we should
file a bug with vscode-languageclient.

I'll look into this in more detail tomorrow when I'm off mobile.

**Comment by aloucks** [comment]
The "---" or "___" trick doesn't work well when there is a code block below it. It doesn't set the vertical spacing correctly and the regions are jammed together. The only way to have the spacing look right is with the multiple marked strings, as far as I can tell. 

In any case, after messing around with this, I definitely don't think there should be a double newline between the sections even if the line separator doesn't work out in the near term. The double newline looked really weird in most cases. 

If this PR isn't satisfactory, can we revert the original one that caused the issue? The non-monospaced module path is quite unsightly.

**Comment by matklad** [comment]
Yeah, kjeremy  is right, we must keep `ra_ide` free of `lsp` types. Though, something we might want to do is to add a `struct Markdown(String)` type to get more type clarity. I also agree that `MarkupContent` is a way to go, and, if it doesn't work as we want it to, we should pester upstream until they fix it :D

I've merged the alternative PR

**Pull request closed without merging**
