### PR TITLE
support remainder assignment operator

### PR DESCRIPTION
**Pull request by JeanMertz**
`%=` was returning errors for me, turns out it wasn't added as a valid assignment operation.

I'm not sure what the best location would be to add a test for this. Please let me know and I'll add one.

### CODE REVIEW

**Comment by matklad** [comment]
looks like we don't have a test for `op=` at all. Adding a one to `data/parser/ok/0048_compound_assignment.rs` should work.

**Comment by JeanMertz** [comment]
Done.

**Comment by JeanMertz** [comment]
By the way, I ran into this while using rust-analyzer during [my first open-source contribution video](https://www.youtube.com/watch?v=1e53UNn8Y_k). Rust Analyzer is really working nicely, it helps me tremendously.

Perhaps in the future I can find a nice issue that I can tackle in an upcoming video 👍

Thanks again for creating this project.

**Comment by matklad** [comment]
bors r+

Thanks for the contribution and the kind words!

**Pull request merged**
