### PR TITLE
Use more Rustic highlighting specifiers

### PR DESCRIPTION
**Pull request by matklad**
bors r+
🤖

### CODE REVIEW

**Comment by matklad** [comment]
cc @lnicola

**Comment by lnicola** [comment]
But why? Inherent functions are now no longer marked as methods, which is probably not what users would expect.

**Comment by matklad** [comment]
Hm, they should be marked as such:
https://github.com/rust-analyzer/rust-analyzer/pull/6947/files#diff-5432b98d7968fe0154258257763520ecf07ecc2769c9e2a55db02389f183c906R386

The goal here is to preserve the same lsp-level behavior, but have more
rust-specific insides.

**Comment by lnicola** [comment]
I'm looking at the test changes: https://github.com/rust-analyzer/rust-analyzer/pull/6947/files#diff-8104eb9eebc09900dd0ffcf4965ba5e33ac1775c21dcc6cb40db7009eadc08e7R49.

(And indeed, even associated/static methods are now functions, there's a couple of them in the same file.)

**Comment by matklad** [comment]
Hm, good question. Seems like a bug *somewhere*? Those should get an
`.associated` class now...

**Comment by matklad** [comment]
Excellent catch, fixed by https://github.com/rust-analyzer/rust-analyzer/pull/6951

**Pull request merged**
