### PR TITLE
vscode: a couple of more intuitive names and shortening languageServer to langServer

### PR DESCRIPTION
**Pull request by Veetaha**
God, naming is so hard. I'd like to extract this change from upcomming "Download latest language server" command PR.

### CODE REVIEW

**Comment by matklad** [comment]
WDYT about removing the `lang` as well? We have only one server, and we already call the language client a client.

**Comment by Veetaha** [comment]
Hmmm, I hope this invariant will never be invalidated

**Comment by Veetaha** [comment]
LGTM

**Comment by Veetaha** [comment]
done

**Pull request merged**
