### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by lnicola** [comment]
Hmm why does this rebuild the deps?

**Comment by matklad** [comment]
looks like the cache is fetched from master, and it is not ready:

https://travis-ci.org/rust-analyzer/rust-analyzer/jobs/561414039#L168

bors r-

**Comment by lnicola** [comment]
It's finished now. Compared to https://travis-ci.org/rust-analyzer/rust-analyzer/jobs/561378497, running the tests 116s as opposed to 282s.

**Comment by matklad** [comment]
ok, looks like it doesn't rebuild the deps, which is cool! Now we need only to make sure that the cache is not busted after the rebuild...

**Comment by lnicola** [comment]
And also that the build time increase doesn't offset the faster run time.

**Comment by lnicola** [comment]
454s for the build vs 281s. 454+116=570, 281+282=563. So we didn't get anything out of it?

**Comment by matklad** [comment]
yeah, but, at least, we don't have debuginfo anymore

**Pull request merged**
