### PR TITLE
try to warn about old rust

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by lnicola** [comment]
Maybe get this from the release page or test some specific version on Travis?

**Comment by bjorn3** [comment]
Why are you getting the version from cargo instead of rustc? It is possible to mix different versions of cargo and rustc. (Though rarely done I believe)

**Comment by matklad** [comment]
@lnicola  I've contemplated this, but I've decided against:

* I want to avoid network access (so, no release page)
* syncing number in `.travis.yml` and `main.rs` seems to be strictly more work than using a single number. Though, I might fix this once we again hit a problem with travis getting stuck on the old rust version due to caches :) 

@bjorn3 mostly because we need only `cargo` to be in path, and adding `rustc` to the mix might fail if it is setup via `CARGO_RUSTC`. That is obviously wrong

**Comment by matklad** [comment]
... but as this is a workning, being right in 90% of cases is good enough!

**Comment by lnicola** [comment]
Well, I meant parsing it from `travis.yml` instead of keeping that constant, but it's fine either way.

**Comment by matklad** [comment]
bors, why have you canceled the PR?

bors r+

**Pull request merged**
