### PR TITLE
support Self in match pattern 

### LINKED ISSUE #4650: `Fill match arms` assist ignores existing variants prefixed with `Self::`
Right now if you have an enum that has some match arms and a match like this:

```rust
match x {
    Self::V1 => todo!(),
    Self::V2 => todo!(),
}
```

and you add a new variant and then run the fill match arms assist it will insert additional copies of `V1` and `V2` in the match arms that are prefixed with the types own name rather than Self.

### PR DESCRIPTION
**Pull request by bnjjj**
close #4650

### CODE REVIEW

**Comment by matklad** [comment]
Hm, I think the bug here is not that we don't use self in the edit we suggest, but that we fail to see that we already have required enum variants.

Seems like we don't resolve Self for some reason:

image

I think we should have it fixed already? 

https://github.com/rust-analyzer/rust-analyzer/pull/4470

**Comment by flodiebold** [comment]
Hmm but that seems to be pretty much the same as what the `enum_variant_through_self_in_pattern` test tests for :thinking: I guess it's possible that the `Self::C` in the test only gets inferred through the expected type, but I don't know :thinking:

**Comment by matklad** [comment]
Hm, yeah, it might be  that we resolve this correctly, but:

* there's a bug in highlihgting
* there's a bug in exhaustivness check.

**Comment by bnjjj** [comment]
It seems it's a deeper issue than I thought. As I have some restricted time for now I prefer close this PR and come back to this issue later if not already fixed. I hope you'll understand. My point here is to not let a PR stay too long inactive.

**Pull request closed without merging**
