### PR TITLE
don't poison mutex around chalk

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by matklad** [comment]
cc @flodiebold

**Comment by flodiebold** [comment]
Ah :smile: TBH I don't have a good mental model for in what situations poisoning makes sense... Why did it panic at all?

**Comment by matklad** [comment]
>Why did it panic at all?

We implement cancellation via panicking, so some dependent query got cancelled. 

> I don't have a good mental model for in what situations poisoning makes sense

Neither do I :)

**Comment by bjorn3** [comment]
Poisoning makes sense when an operation temporarily brings data in an inconsistent state. It also helps propagating failure from one thread to another, so that when one thread fails other threads dont accidentially keep running when doing so is pointless.

**Pull request merged**
