### PR TITLE
Prevent child cargo process from messing with our stdin

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by kiljacken** [comment]
Wow, that's subtle, good job

**Comment by matklad** [comment]
Uhu. I've actually thought about this yesterday, scrutinized this bit of code for exactly this issue, even filed [this](https://github.com/rust-analyzer/rust-analyzer/commit/9d5a5211a4ab83fb891c6eb32f6ed6d63b6b027f) to make it more clear in the other case, and still missed the fact that `stdin` is also a thing

**Comment by kjeremy** [comment]
Wow. Can we test for this?

**Comment by matklad** [comment]
we can, but I don't believe it is worthwhile. We can only test that this
specific instance work, we can't write a test which works for all future
instances of process spawning.

**Pull request merged**
