### PR TITLE
1.52.0

### PR DESCRIPTION
**Pull request by matklad**
A lot of APIs we use in this release!

### CODE REVIEW

**Comment by lnicola** [comment]
bors try

**Comment by SomeoneToIgnore** [comment]
I've resolved the handlers.rs conflict by accepting my changes from https://github.com/rust-analyzer/rust-analyzer/pull/8711/files#diff-13acc206c18467a7dbe2876d204fee460c728232fbb677a4d769641e76dd9fe5 and discarding the 1.52 ones, since the parsing function had been changed entirely.

Yet I've done it via the GitHub UI and that apparently introduced the merge commit instead of the rebase: if that's unwanted, we need a proper rebase.

**Comment by Veykril** [comment]
Merge commits will be rejected by CI, so ye we want a proper rebase here instead

**Comment by SomeoneToIgnore** [comment]
Well, I'll take it over since started to mess with it, hope it's fine.

**Comment by SomeoneToIgnore** [comment]
bors try

**Comment by matklad** [comment]
>Well, I'll take it over since started to mess with it

Thanks!

**Pull request merged**
