### PR TITLE
Update actions

### PR DESCRIPTION
**Pull request by brianbarnatt7**

### CODE REVIEW

**Comment by matklad** [comment]
Reported to GitHub as CI abuse.

**Comment by lnicola** [comment]
Ah, sorry, I've already done that and cancelled the workflow.

**Comment by matklad** [comment]
Thanks! I've also enabled "forbid user accounts younger than 24 hours to interract with the repo" for a couple of days.

**Comment by lnicola** [comment]
I'm not sure how much that helps. They can just spam other 200 repos instead.

**Pull request closed without merging**
