### PR TITLE
Fix a small typo

### PR DESCRIPTION
**Pull request by killercup**
Truly an A+, errrr, +a commit

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

Reminds me that we need to implement syntax aware spell checker, which checks comments and declarations, but does not check references...

**Comment by matklad** [comment]
bors r+

Reminds me that we need to implement syntax aware spell checker, which checks comments and declarations, but does not check references...

**Comment by matklad** [comment]
bors r+

Reminds me that we need to implement syntax aware spell checker, which checks comments and declarations, but does not check references...

**Comment by CAD97** [comment]
[GitHub acting up is likely the reason for the duplicated comments and bors oddity.](https://blog.github.com/2018-10-21-october21-incident-report/)

But hey, at least they're folded by default!

**Pull request merged**
