### PR TITLE
Switch from jemalloc to tikv-jemalloc

### PR DESCRIPTION
**Pull request by djrenren**
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8252.

No idea if we're still interested in this but it was a simple change so here's the PR.

### CODE REVIEW

**Comment by lnicola** [comment]
I think the benchmark linked in that issue used a sized deallocation variant, but I'm not sure how to set it up.

**Comment by lnicola** [comment]
bors r-

Don't we also have to change this? https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/rust-analyzer/src/bin/main.rs#L27

**Comment by Veykril** [comment]
Oh ye, we do

**Comment by lnicola** [comment]
bors d+

**Comment by djrenren** [comment]
Okay fix is pushed. I did it by overriding the package name for `jemallocator` and `jemalloc-ctl` rather than changing the source to reference `tikv_jemalloc`. If that goes against any style rules or whatever, I can change it but since the two are supposed to be compatible (and presumably someday the main `jemalloc` crate may get updated) it seemed like a decent call. Happy to do whatever you all think is best.

**Comment by matklad** [comment]
I like the renaming!

bors r+

**Comment by lnicola** [comment]
No, it's fine, I actually wanted to suggest doing that.

bors r+

**Comment by djrenren** [comment]
> I think the benchmark linked in that issue used a sized deallocation variant, but I'm not sure how to set it up.

As far as I can tell, t`ikv_jemalloc` just uses sized deallocation whereas the old `jemalloc` does not. The original rustc PR doesn't include any configuration to turn it on and just links to the [`lib.rs`](https://docs.rs/tikv-jemallocator/0.4.1/src/tikv_jemallocator/lib.rs.html#121-126) file in `tikv_jemalloctor`

**Comment by lnicola** [comment]
Ah, that's nice. I remember seeing some linker magic, but hopefully it's not needed.

**Comment by matklad** [comment]
For posterity, some ra benches:

```
Old

Database loaded:     349.36ms, 268minstr
  crates: 34, mods: 659, decls: 12785, fns: 10090
Item Collection:     6.27s, 73ginstr
  exprs: 276279, ??ty: 6712 (2%), ?ty: 3169 (1%), !ty: 1062
Inference:           14.28s, 114ginstr
Total:               20.55s, 188ginstr

New 

Database loaded:     346.65ms, 261minstr
  crates: 34, mods: 659, decls: 12785, fns: 10090
Item Collection:     6.07s, 66ginstr
  exprs: 276279, ??ty: 6712 (2%), ?ty: 3169 (1%), !ty: 1062
Inference:           14.11s, 107ginstr
Total:               20.17s, 174ginstr

```

**Pull request merged**
